In [1]:
import pandas as pd
import missingno

enc = 'utf-8'

In [2]:
NUTS0 = 'GR'
NUTS2 = 'Thessaly'

In [3]:
timeline = pd.read_csv(f'../../data/{NUTS2}/{NUTS0}_{NUTS2}_Timeline_NUTS3_2010-2022.csv', encoding=enc)
timeline_filled_mean = pd.read_csv(f'../../data/{NUTS2}/{NUTS0}_{NUTS2}_Timeline_NUTS3_2010-2022_filled_meantemps.csv', encoding=enc)

In [4]:
timeline

,NUTS2_ID,NUTS2_NAME,NUTS3_ID,NUTS3_NAME,x,y,dt_placement
0,EL61,θεσσαλια,EL611,"καρδιτσα, τρικαλα",21.19021,39.65516,2010-01-01
1,EL61,θεσσαλια,EL611,"καρδιτσα, τρικαλα",21.19021,39.65516,2010-01-02
2,EL61,θεσσαλια,EL611,"καρδιτσα, τρικαλα",21.19021,39.65516,2010-01-03
3,EL61,θεσσαλια,EL611,"καρδιτσα, τρικαλα",21.19021,39.65516,2010-01-04
4,EL61,θεσσαλια,EL611,"καρδιτσα, τρικαλα",21.19021,39.65516,2010-01-05
...,...,...,...,...,...,...,...
3295107,EL61,θεσσαλια,EL613,"μαγνησια, σποραδες",23.30086,39.20331,2022-12-27
3295108,EL61,θεσσαλια,EL613,"μαγνησια, σποραδες",23.30086,39.20331,2022-12-28
3295109,EL61,θεσσαλια,EL613,"μαγνησια, σποραδες",23.30086,39.20331,2022-12-29
3295110,EL61,θεσσαλια,EL613,"μαγνησια, σποραδες",23.30086,39.20331,2022-12-30
3295111,EL61,θεσσαλια,EL613,"μαγνησια, σποραδες",23.30086,39.20331,2022-12-31

In [5]:
timeline_filled_mean

,nuts3,nuts2,x,y,dt_placement,day,month,year,ndvi,ndmi,...,lst_night,lst_day_jan_mean,lst_day_feb_mean,lst_day_mar_mean,lst_day_apr_mean,lst_night_jan_mean,lst_night_feb_mean,lst_night_mar_mean,lst_night_apr_mean,rainfall
0,καρδιτσας,θεσσαλιας,21.74256,39.29376,2010-01-01,1,1,2010,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,60.374623
1,καρδιτσας,θεσσαλιας,21.74256,39.29376,2010-01-02,2,1,2010,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,28.121427
2,καρδιτσας,θεσσαλιας,21.74256,39.29376,2010-01-03,3,1,2010,NaN,NaN,...,13895.0,NaN,NaN,NaN,NaN,13895.000000,NaN,NaN,NaN,0.081799
3,καρδιτσας,θεσσαλιας,21.74256,39.29376,2010-01-04,4,1,2010,NaN,NaN,...,13895.0,NaN,NaN,NaN,NaN,13895.000000,NaN,NaN,NaN,1.822118
4,καρδιτσας,θεσσαλιας,21.74256,39.29376,2010-01-05,5,1,2010,NaN,NaN,...,13895.0,NaN,NaN,NaN,NaN,13895.000000,NaN,NaN,NaN,0.011088
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3143171,τρικαλων,θεσσαλιας,22.11958,39.62555,2022-12-27,27,12,2022,0.192832,0.041302,...,13975.0,14225.483871,14431.214286,14457.548387,14457.548387,13753.419355,13812.821429,13782.645161,13782.645161,0.000000
3143172,τρικαλων,θεσσαλιας,22.11958,39.62555,2022-12-28,28,12,2022,NaN,NaN,...,13975.0,14225.483871,14431.214286,14457.548387,14457.548387,13753.419355,13812.821429,13782.645161,13782.645161,0.000000
3143173,τρικαλων,θεσσαλιας,22.11958,39.62555,2022-12-29,29,12,2022,0.192832,0.041302,...,13956.0,14225.483871,14431.214286,14457.548387,14457.548387,13753.419355,13812.821429,13782.645161,13782.645161,0.000000
3143174,τρικαλων,θεσσαλιας,22.11958,39.62555,2022-12-30,30,12,2022,0.192832,0.041302,...,13905.0,14225.483871,14431.214286,14457.548387,14457.548387,13753.419355,13812.821429,13782.645161,13782.645161,0.000000
3143175,τρικαλων,θεσσαλιας,22.11958,39.62555,2022-12-31,31,12,2022,0.192832,0.041302,...,13881.0,14225.483871,14431.214286,14457.548387,14457.548387,13753.419355,13812.821429,13782.645161,13782.645161,0.000000

In [6]:
timeline_filled_mean.drop(columns=['nuts2'], inplace = True)
timeline_filled_mean.rename(columns={"nuts3": "NUTS3_NAME"}, inplace=True)

In [7]:
timeline.NUTS2_NAME.unique()

array(['θεσσαλια'], dtype=object)

In [8]:
timeline.NUTS3_NAME.unique()

array(['καρδιτσα, τρικαλα', 'λαρισα', 'μαγνησια, σποραδες'], dtype=object)

In [9]:
timeline_filled_mean.NUTS3_NAME.unique()

array(['καρδιτσας', 'λαρισας', 'μαγνησιας', 'τρικαλων'], dtype=object)

In [10]:
timeline_filled_mean['NUTS3_NAME'] = timeline_filled_mean['NUTS3_NAME'].apply(lambda x : x.replace('καρδιτσας','καρδιτσα, τρικαλα'))
timeline_filled_mean['NUTS3_NAME'] = timeline_filled_mean['NUTS3_NAME'].apply(lambda x : x.replace('λαρισας','λαρισα'))
timeline_filled_mean['NUTS3_NAME'] = timeline_filled_mean['NUTS3_NAME'].apply(lambda x : x.replace('μαγνησιας','μαγνησια, σποραδες'))
timeline_filled_mean['NUTS3_NAME'] = timeline_filled_mean['NUTS3_NAME'].apply(lambda x : x.replace('τρικαλων','καρδιτσα, τρικαλα'))

In [11]:
timeline_filled_mean

,NUTS3_NAME,x,y,dt_placement,day,month,year,ndvi,ndmi,ndwi,...,lst_night,lst_day_jan_mean,lst_day_feb_mean,lst_day_mar_mean,lst_day_apr_mean,lst_night_jan_mean,lst_night_feb_mean,lst_night_mar_mean,lst_night_apr_mean,rainfall
0,"καρδιτσα, τρικαλα",21.74256,39.29376,2010-01-01,1,1,2010,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,60.374623
1,"καρδιτσα, τρικαλα",21.74256,39.29376,2010-01-02,2,1,2010,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,28.121427
2,"καρδιτσα, τρικαλα",21.74256,39.29376,2010-01-03,3,1,2010,NaN,NaN,NaN,...,13895.0,NaN,NaN,NaN,NaN,13895.000000,NaN,NaN,NaN,0.081799
3,"καρδιτσα, τρικαλα",21.74256,39.29376,2010-01-04,4,1,2010,NaN,NaN,NaN,...,13895.0,NaN,NaN,NaN,NaN,13895.000000,NaN,NaN,NaN,1.822118
4,"καρδιτσα, τρικαλα",21.74256,39.29376,2010-01-05,5,1,2010,NaN,NaN,NaN,...,13895.0,NaN,NaN,NaN,NaN,13895.000000,NaN,NaN,NaN,0.011088
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3143171,"καρδιτσα, τρικαλα",22.11958,39.62555,2022-12-27,27,12,2022,0.192832,0.041302,-0.046541,...,13975.0,14225.483871,14431.214286,14457.548387,14457.548387,13753.419355,13812.821429,13782.645161,13782.645161,0.000000
3143172,"καρδιτσα, τρικαλα",22.11958,39.62555,2022-12-28,28,12,2022,NaN,NaN,NaN,...,13975.0,14225.483871,14431.214286,14457.548387,14457.548387,13753.419355,13812.821429,13782.645161,13782.645161,0.000000
3143173,"καρδιτσα, τρικαλα",22.11958,39.62555,2022-12-29,29,12,2022,0.192832,0.041302,-0.046541,...,13956.0,14225.483871,14431.214286,14457.548387,14457.548387,13753.419355,13812.821429,13782.645161,13782.645161,0.000000
3143174,"καρδιτσα, τρικαλα",22.11958,39.62555,2022-12-30,30,12,2022,0.192832,0.041302,-0.046541,...,13905.0,14225.483871,14431.214286,14457.548387,14457.548387,13753.419355,13812.821429,13782.645161,13782.645161,0.000000
3143175,"καρδιτσα, τρικαλα",22.11958,39.62555,2022-12-31,31,12,2022,0.192832,0.041302,-0.046541,...,13881.0,14225.483871,14431.214286,14457.548387,14457.548387,13753.419355,13812.821429,13782.645161,13782.645161,0.000000

In [12]:
nuts3_id = {'καρδιτσα, τρικαλα': 'EL611', 
            'λαρισα': 'EL612', 
            'μαγνησια, σποραδες': 'EL613' 
        }

In [13]:
timeline_filled_mean['NUTS3_ID'] = timeline_filled_mean['NUTS3_NAME'].map(nuts3_id)
timeline_filled_mean['NUTS2_ID'] = 'EL61'
timeline_filled_mean['NUTS2_NAME'] = 'θεσσαλια'

In [14]:
cols = timeline_filled_mean.columns

cols

Index(['NUTS3_NAME', 'x', 'y', 'dt_placement', 'day', 'month', 'year', 'ndvi',
       'ndmi', 'ndwi', 'ndbi', 'ndvi_mean', 'ndmi_mean', 'ndwi_mean',
       'ndbi_mean', 'ndvi_std', 'ndmi_std', 'ndwi_std', 'ndbi_std', 'lst_day',
       'lst_night', 'lst_day_jan_mean', 'lst_day_feb_mean', 'lst_day_mar_mean',
       'lst_day_apr_mean', 'lst_night_jan_mean', 'lst_night_feb_mean',
       'lst_night_mar_mean', 'lst_night_apr_mean', 'rainfall', 'NUTS3_ID',
       'NUTS2_ID', 'NUTS2_NAME'],
      dtype='object')

In [15]:
print(len(cols))

33

In [16]:
new_cols = ['NUTS2_ID', 'NUTS2_NAME', 'NUTS3_ID', 'NUTS3_NAME',
            'x', 'y', 'dt_placement', 'day', 'month', 'year', 'ndvi',
       'ndmi', 'ndwi', 'ndbi', 'ndvi_mean', 'ndmi_mean', 'ndwi_mean',
       'ndbi_mean', 'ndvi_std', 'ndmi_std', 'ndwi_std', 'ndbi_std', 'lst_day',
       'lst_night', 'lst_day_jan_mean', 'lst_day_feb_mean', 'lst_day_mar_mean',
       'lst_day_apr_mean', 'lst_night_jan_mean', 'lst_night_feb_mean',
       'lst_night_mar_mean', 'lst_night_apr_mean', 'rainfall', ]

In [17]:
print(len(new_cols))

33

In [18]:
timeline_filled_mean = timeline_filled_mean[new_cols]

In [19]:
timeline_filled_mean

,NUTS2_ID,NUTS2_NAME,NUTS3_ID,NUTS3_NAME,x,y,dt_placement,day,month,year,...,lst_night,lst_day_jan_mean,lst_day_feb_mean,lst_day_mar_mean,lst_day_apr_mean,lst_night_jan_mean,lst_night_feb_mean,lst_night_mar_mean,lst_night_apr_mean,rainfall
0,EL61,θεσσαλια,EL611,"καρδιτσα, τρικαλα",21.74256,39.29376,2010-01-01,1,1,2010,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,60.374623
1,EL61,θεσσαλια,EL611,"καρδιτσα, τρικαλα",21.74256,39.29376,2010-01-02,2,1,2010,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,28.121427
2,EL61,θεσσαλια,EL611,"καρδιτσα, τρικαλα",21.74256,39.29376,2010-01-03,3,1,2010,...,13895.0,NaN,NaN,NaN,NaN,13895.000000,NaN,NaN,NaN,0.081799
3,EL61,θεσσαλια,EL611,"καρδιτσα, τρικαλα",21.74256,39.29376,2010-01-04,4,1,2010,...,13895.0,NaN,NaN,NaN,NaN,13895.000000,NaN,NaN,NaN,1.822118
4,EL61,θεσσαλια,EL611,"καρδιτσα, τρικαλα",21.74256,39.29376,2010-01-05,5,1,2010,...,13895.0,NaN,NaN,NaN,NaN,13895.000000,NaN,NaN,NaN,0.011088
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3143171,EL61,θεσσαλια,EL611,"καρδιτσα, τρικαλα",22.11958,39.62555,2022-12-27,27,12,2022,...,13975.0,14225.483871,14431.214286,14457.548387,14457.548387,13753.419355,13812.821429,13782.645161,13782.645161,0.000000
3143172,EL61,θεσσαλια,EL611,"καρδιτσα, τρικαλα",22.11958,39.62555,2022-12-28,28,12,2022,...,13975.0,14225.483871,14431.214286,14457.548387,14457.548387,13753.419355,13812.821429,13782.645161,13782.645161,0.000000
3143173,EL61,θεσσαλια,EL611,"καρδιτσα, τρικαλα",22.11958,39.62555,2022-12-29,29,12,2022,...,13956.0,14225.483871,14431.214286,14457.548387,14457.548387,13753.419355,13812.821429,13782.645161,13782.645161,0.000000
3143174,EL61,θεσσαλια,EL611,"καρδιτσα, τρικαλα",22.11958,39.62555,2022-12-30,30,12,2022,...,13905.0,14225.483871,14431.214286,14457.548387,14457.548387,13753.419355,13812.821429,13782.645161,13782.645161,0.000000
3143175,EL61,θεσσαλια,EL611,"καρδιτσα, τρικαλα",22.11958,39.62555,2022-12-31,31,12,2022,...,13881.0,14225.483871,14431.214286,14457.548387,14457.548387,13753.419355,13812.821429,13782.645161,13782.645161,0.000000

In [20]:
timeline_filled_mean.to_csv(f'../../data/{NUTS2}/{NUTS0}_{NUTS2}_Timeline_NUTS3_2010-2022_filled_meantemps.csv', encoding = enc, index = False)