In [1]:
import pandas as pd
import sys

sys.path.insert(0, "../../Modules")

from preprocessing_utils import process_italic

enc = 'utf-8'

In [2]:
df_demograpchics = pd.read_csv('../data/IT_WEB_Demographics_Raw.csv', encoding=enc)
df_demograpchics

                lau1    nuts3   nuts2 population
0        Abano Terme   Padova  Veneto     19,349
1              Adria   Rovigo  Veneto     20,233
2               Affi   Verona  Veneto      2,297
3               Agna   Padova  Veneto      3,400
4             Agordo  Belluno  Veneto      4,249
..               ...      ...     ...        ...
576          Zimella   Verona  Veneto      4,834
577       Zoldo Alto  Belluno  Veneto        999
578  Zoppè di Cadore  Belluno  Veneto        265
579        Zovencedo  Vicenza  Veneto        796
580         Zugliano  Vicenza  Veneto      6,690

[581 rows x 4 columns]

In [3]:
df_demograpchics.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 581 entries, 0 to 580
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   lau1        581 non-null    object
 1   nuts3       581 non-null    object
 2   nuts2       581 non-null    object
 3   population  581 non-null    object
dtypes: object(4)
memory usage: 18.3+ KB

In [4]:
process_italic(df_demograpchics, 'lau1')
process_italic(df_demograpchics, 'nuts2')
process_italic(df_demograpchics, 'nuts3')

In [5]:
df_demograpchics

                lau1    nuts3   nuts2 population
0        abano terme   padova  veneto     19,349
1              adria   rovigo  veneto     20,233
2               affi   verona  veneto      2,297
3               agna   padova  veneto      3,400
4             agordo  belluno  veneto      4,249
..               ...      ...     ...        ...
576          zimella   verona  veneto      4,834
577       zoldo alto  belluno  veneto        999
578  zoppe da cadore  belluno  veneto        265
579        zovencedo  vicenza  veneto        796
580         zugliano  vicenza  veneto      6,690

[581 rows x 4 columns]

In [6]:
demographics_lau1 = df_demograpchics['lau1'].unique().tolist()
demographics_lau1.sort()

demographics_nuts2 = df_demograpchics['nuts2'].unique().tolist()
demographics_nuts2.sort()

demographics_nuts3 = df_demograpchics['nuts3'].unique().tolist()
demographics_nuts3.sort()

with open('../data/IT_WEB_demographics_lau1_processed.txt', 'w', encoding=enc) as f:
    for item in demographics_lau1:
        f.write("%s\n" % item)

with open('../data/IT_WEB_demographics_nuts2_processed.txt', 'w', encoding=enc) as f:
    for item in demographics_nuts2:
        f.write("%s\n" % item)

with open('../data/IT_WEB_demographics_nuts3_processed.txt', 'w', encoding=enc) as f:
    for item in demographics_nuts3:
        f.write("%s\n" % item)

print(f"Number of LAU1 Units in Italy, Veneto (from demographics file): {len(demographics_lau1)}")

Number of LAU1 Units in Italy, Veneto (from demographics file): 581

In [7]:
df_demograpchics.to_csv('../data/IT_WEB_Demographics_Processed.csv', index=False)