In [1]:
import numpy as np
import pandas as pd
pd.set_option('display.max_columns', None)

In [2]:
data = pd.read_csv(r'E:\Drive\NOA\MBD-Prediction\Grid Level\data\CMacedonia\GR_CMacedonia_Timeline_GRID_2016-2018_filled.csv', encoding='utf-8')

In [3]:
try:
    data.drop(columns=['Unnamed: 0'], inplace=True)
except Exception:
    print("No column named \'Unnamed: 0\'")

In [4]:
data['dt_placement'] = pd.to_datetime(data['dt_placement'])

# Extract year, month, and day from the 'date' column
data['year'] = data['dt_placement'].dt.year
data['month'] = data['dt_placement'].dt.month
data['day'] = data['dt_placement'].dt.day

In [5]:
data

,x,y,cell_number,dt_placement,NUTS2_ID,year,month,ndvi,ndmi,ndwi,ndbi,ndvi_mean,ndmi_mean,ndwi_mean,ndbi_mean,ndvi_std,ndmi_std,ndwi_std,ndbi_std,lst_day,lst_night,rainfall,day
0,21.76334,40.79806,0,2016-01-01,EL52,2016,1,0.322417,-0.083739,-0.311678,0.083739,0.317002,-0.081787,-0.306300,0.081787,0.012348,0.031579,0.012786,0.031579,14237.0,13758.0,0.304373,1
1,21.76334,40.79806,0,2016-01-02,EL52,2016,1,0.322417,-0.083739,-0.311678,0.083739,0.317002,-0.081787,-0.306300,0.081787,0.012348,0.031579,0.012786,0.031579,13840.0,13758.0,0.069506,2
2,21.76334,40.79806,0,2016-01-03,EL52,2016,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13840.0,13758.0,16.788566,3
3,21.76334,40.79806,0,2016-01-04,EL52,2016,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13840.0,13758.0,6.750442,4
4,21.76334,40.79806,0,2016-01-05,EL52,2016,1,0.322417,-0.083739,-0.311678,0.083739,0.317002,-0.081787,-0.306300,0.081787,0.012348,0.031579,0.012786,0.031579,13840.0,13388.0,0.590280,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4839931,24.08217,40.99570,4415,2018-12-27,EL52,2018,12,0.198149,-0.130382,-0.197142,0.130382,0.203739,-0.105573,-0.197259,0.105573,0.101297,0.112771,0.064730,0.112771,13921.0,13492.0,0.000000,27
4839932,24.08217,40.99570,4415,2018-12-28,EL52,2018,12,0.198149,-0.130382,-0.197142,0.130382,0.203739,-0.105573,-0.197259,0.105573,0.101297,0.112771,0.064730,0.112771,13953.0,13492.0,0.250176,28
4839933,24.08217,40.99570,4415,2018-12-29,EL52,2018,12,0.198149,-0.130382,-0.197142,0.130382,0.203739,-0.105573,-0.197259,0.105573,0.101297,0.112771,0.064730,0.112771,13919.0,13492.0,6.513221,29
4839934,24.08217,40.99570,4415,2018-12-30,EL52,2018,12,0.198149,-0.130382,-0.197142,0.130382,0.203739,-0.105573,-0.197259,0.105573,0.101297,0.112771,0.064730,0.112771,13919.0,13492.0,0.000000,30
4839935,24.08217,40.99570,4415,2018-12-31,EL52,2018,12,0.198149,-0.130382,-0.197142,0.130382,0.203739,-0.105573,-0.197259,0.105573,0.101297,0.112771,0.064730,0.112771,13919.0,13520.0,0.000000,31

In [6]:
data_jan = data.loc[data['month'] == 1]
data_fed = data.loc[data['month'] == 2]
data_mar = data.loc[data['month'] == 3]
data_apr = data.loc[data['month'] == 4]

In [8]:
df_mean_jan = data_jan.groupby(['cell_number', 'year', 'month'], as_index=False)[['lst_day', 'lst_night']].mean()
df_mean_feb = data_fed.groupby(['cell_number', 'year', 'month'], as_index=False)[['lst_day', 'lst_night']].mean()
df_mean_mar = data_mar.groupby(['cell_number', 'year', 'month'], as_index=False)[['lst_day', 'lst_night']].mean()
df_mean_apr = data_apr.groupby(['cell_number', 'year', 'month'], as_index=False)[['lst_day', 'lst_night']].mean()

In [9]:
df_mean_jan.rename(columns={'lst_day': 'lst_day_jan_mean', 'lst_night': 'lst_night_jan_mean'}, inplace=True)
df_mean_feb.rename(columns={'lst_day': 'lst_day_feb_mean', 'lst_night': 'lst_night_feb_mean'}, inplace=True)
df_mean_mar.rename(columns={'lst_day': 'lst_day_mar_mean', 'lst_night': 'lst_night_mar_mean'}, inplace=True)
df_mean_apr.rename(columns={'lst_day': 'lst_day_apr_mean', 'lst_night': 'lst_night_apr_mean'}, inplace=True)

In [10]:
df_mean_jan.drop(columns=['month'], inplace = True)
df_mean_feb.drop(columns=['month'], inplace = True)
df_mean_mar.drop(columns=['month'], inplace = True)
df_mean_apr.drop(columns=['month'], inplace = True)

In [11]:
df_mean = pd.merge(df_mean_jan, df_mean_feb, on=['cell_number', 'year']).merge(df_mean_mar, on=['cell_number', 'year']).merge(df_mean_apr, on=['cell_number', 'year'])

In [15]:
df_mean.loc[(df_mean['cell_number'] == 0) & (df_mean['year'] == 2016)]

,cell_number,year,lst_day_jan_mean,lst_night_jan_mean,lst_day_feb_mean,lst_night_feb_mean,lst_day_mar_mean,lst_night_mar_mean,lst_day_apr_mean,lst_night_apr_mean
0,0,2016,13979.0,13652.16129,14312.047619,13841.952381,14394.032258,13811.645161,14815.133333,14107.866667

In [13]:
data_mean = pd.merge(data, df_mean, on=['cell_number', 'year'])

In [14]:
data_mean

,x,y,cell_number,dt_placement,NUTS2_ID,year,month,ndvi,ndmi,ndwi,ndbi,ndvi_mean,ndmi_mean,ndwi_mean,ndbi_mean,ndvi_std,ndmi_std,ndwi_std,ndbi_std,lst_day,lst_night,rainfall,day,lst_day_jan_mean,lst_night_jan_mean,lst_day_feb_mean,lst_night_feb_mean,lst_day_mar_mean,lst_night_mar_mean,lst_day_apr_mean,lst_night_apr_mean
0,21.76334,40.79806,0,2016-01-01,EL52,2016,1,0.322417,-0.083739,-0.311678,0.083739,0.317002,-0.081787,-0.306300,0.081787,0.012348,0.031579,0.012786,0.031579,14237.0,13758.0,0.304373,1,13979.000000,13652.161290,14312.047619,13841.952381,14394.032258,13811.645161,14815.133333,14107.866667
1,21.76334,40.79806,0,2016-01-02,EL52,2016,1,0.322417,-0.083739,-0.311678,0.083739,0.317002,-0.081787,-0.306300,0.081787,0.012348,0.031579,0.012786,0.031579,13840.0,13758.0,0.069506,2,13979.000000,13652.161290,14312.047619,13841.952381,14394.032258,13811.645161,14815.133333,14107.866667
2,21.76334,40.79806,0,2016-01-03,EL52,2016,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13840.0,13758.0,16.788566,3,13979.000000,13652.161290,14312.047619,13841.952381,14394.032258,13811.645161,14815.133333,14107.866667
3,21.76334,40.79806,0,2016-01-04,EL52,2016,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13840.0,13758.0,6.750442,4,13979.000000,13652.161290,14312.047619,13841.952381,14394.032258,13811.645161,14815.133333,14107.866667
4,21.76334,40.79806,0,2016-01-05,EL52,2016,1,0.322417,-0.083739,-0.311678,0.083739,0.317002,-0.081787,-0.306300,0.081787,0.012348,0.031579,0.012786,0.031579,13840.0,13388.0,0.590280,5,13979.000000,13652.161290,14312.047619,13841.952381,14394.032258,13811.645161,14815.133333,14107.866667
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4839931,24.08217,40.99570,4415,2018-12-27,EL52,2018,12,0.198149,-0.130382,-0.197142,0.130382,0.203739,-0.105573,-0.197259,0.105573,0.101297,0.112771,0.064730,0.112771,13921.0,13492.0,0.000000,27,14135.322581,13648.483871,14345.500000,13768.035714,14556.548387,13920.612903,15015.566667,14174.466667
4839932,24.08217,40.99570,4415,2018-12-28,EL52,2018,12,0.198149,-0.130382,-0.197142,0.130382,0.203739,-0.105573,-0.197259,0.105573,0.101297,0.112771,0.064730,0.112771,13953.0,13492.0,0.250176,28,14135.322581,13648.483871,14345.500000,13768.035714,14556.548387,13920.612903,15015.566667,14174.466667
4839933,24.08217,40.99570,4415,2018-12-29,EL52,2018,12,0.198149,-0.130382,-0.197142,0.130382,0.203739,-0.105573,-0.197259,0.105573,0.101297,0.112771,0.064730,0.112771,13919.0,13492.0,6.513221,29,14135.322581,13648.483871,14345.500000,13768.035714,14556.548387,13920.612903,15015.566667,14174.466667
4839934,24.08217,40.99570,4415,2018-12-30,EL52,2018,12,0.198149,-0.130382,-0.197142,0.130382,0.203739,-0.105573,-0.197259,0.105573,0.101297,0.112771,0.064730,0.112771,13919.0,13492.0,0.000000,30,14135.322581,13648.483871,14345.500000,13768.035714,14556.548387,13920.612903,15015.566667,14174.466667
4839935,24.08217,40.99570,4415,2018-12-31,EL52,2018,12,0.198149,-0.130382,-0.197142,0.130382,0.203739,-0.105573,-0.197259,0.105573,0.101297,0.112771,0.064730,0.112771,13919.0,13520.0,0.000000,31,14135.322581,13648.483871,14345.500000,13768.035714,14556.548387,13920.612903,15015.566667,14174.466667

In [16]:
data_mean.to_csv(r'E:\Drive\NOA\MBD-Prediction\Grid Level\data\CMacedonia\GR_CMacedonia_Timeline_GRID_2016-2018_filled_mean.csv', encoding='utf-8')