In [12]:
import numpy as np
import pandas as pd
pd.set_option('display.max_columns', None)

In [13]:
data = pd.read_csv(r'E:\Drive\NOA\MBD-Prediction\Grid Level\data\Thrace\GR_Thrace_Timeline_GRID_2018-2020_filled_mean.csv', encoding='utf-8')

In [14]:
try:
    data.drop(columns=['Unnamed: 0'], inplace=True)
except Exception:
    print("No column named \'Unnamed: 0\'")

In [15]:
data['dt_placement'] = pd.to_datetime(data['dt_placement'])

# Extract year, month, and day from the 'date' column
data['year'] = data['dt_placement'].dt.year
data['month'] = data['dt_placement'].dt.month
data['day'] = data['dt_placement'].dt.day

In [16]:
data

,x,y,cell_number,dt_placement,NUTS2_ID,year,month,ndvi,ndmi,ndwi,ndbi,ndvi_mean,ndmi_mean,ndwi_mean,ndbi_mean,ndvi_std,ndmi_std,ndwi_std,ndbi_std,lst_day,lst_night,rainfall,day,lst_day_jan_mean,lst_night_jan_mean,lst_day_feb_mean,lst_night_feb_mean,lst_day_mar_mean,lst_night_mar_mean,lst_day_apr_mean,lst_night_apr_mean
0,23.65882,41.33542,0,2018-01-01,EL51,2018,1,0.075421,0.163148,0.062645,-0.163148,0.146046,0.072780,-0.063395,-0.072780,0.097993,0.055410,0.113606,0.055410,14093.0,13642.000000,0.000000,1,13877.354839,13637.354839,13989.714286,13643.392857,14153.612903,13769.354839,14733.700000,14052.000000
1,23.65882,41.33542,0,2018-01-02,EL51,2018,1,0.075421,0.163148,0.062645,-0.163148,0.146046,0.072780,-0.063395,-0.072780,0.097993,0.055410,0.113606,0.055410,13931.0,13642.000000,2.953801,2,13877.354839,13637.354839,13989.714286,13643.392857,14153.612903,13769.354839,14733.700000,14052.000000
2,23.65882,41.33542,0,2018-01-03,EL51,2018,1,0.075421,0.163148,0.062645,-0.163148,0.146046,0.072780,-0.063395,-0.072780,0.097993,0.055410,0.113606,0.055410,13783.0,13488.000000,0.000000,3,13877.354839,13637.354839,13989.714286,13643.392857,14153.612903,13769.354839,14733.700000,14052.000000
3,23.65882,41.33542,0,2018-01-04,EL51,2018,1,0.075421,0.163148,0.062645,-0.163148,0.146046,0.072780,-0.063395,-0.072780,0.097993,0.055410,0.113606,0.055410,13783.0,13515.000000,3.852192,4,13877.354839,13637.354839,13989.714286,13643.392857,14153.612903,13769.354839,14733.700000,14052.000000
4,23.65882,41.33542,0,2018-01-05,EL51,2018,1,0.075421,0.163148,0.062645,-0.163148,0.146046,0.072780,-0.063395,-0.072780,0.097993,0.055410,0.113606,0.055410,13783.0,13515.000000,0.000000,5,13877.354839,13637.354839,13989.714286,13643.392857,14153.612903,13769.354839,14733.700000,14052.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3579531,26.60756,41.40729,3265,2020-12-27,EL51,2020,12,0.450774,0.156466,-0.351211,-0.156466,0.200367,-0.010449,-0.132835,0.010449,0.117562,0.077335,0.106493,0.077335,NaN,41.405597,40.110161,27,14099.225806,13492.870968,14269.241379,13800.586207,14750.290323,13907.612903,14912.933333,13992.366667
3579532,26.60756,41.40729,3265,2020-12-28,EL51,2020,12,0.450774,0.156466,-0.351211,-0.156466,0.200367,-0.010449,-0.132835,0.010449,0.117562,0.077335,0.106493,0.077335,NaN,41.405597,10.648291,28,14099.225806,13492.870968,14269.241379,13800.586207,14750.290323,13907.612903,14912.933333,13992.366667
3579533,26.60756,41.40729,3265,2020-12-29,EL51,2020,12,0.450774,0.156466,-0.351211,-0.156466,0.200367,-0.010449,-0.132835,0.010449,0.117562,0.077335,0.106493,0.077335,NaN,41.405597,1.150095,29,14099.225806,13492.870968,14269.241379,13800.586207,14750.290323,13907.612903,14912.933333,13992.366667
3579534,26.60756,41.40729,3265,2020-12-30,EL51,2020,12,0.450774,0.156466,-0.351211,-0.156466,0.200367,-0.010449,-0.132835,0.010449,0.117562,0.077335,0.106493,0.077335,NaN,41.405597,0.027165,30,14099.225806,13492.870968,14269.241379,13800.586207,14750.290323,13907.612903,14912.933333,13992.366667
3579535,26.60756,41.40729,3265,2020-12-31,EL51,2020,12,0.450774,0.156466,-0.351211,-0.156466,0.200367,-0.010449,-0.132835,0.010449,0.117562,0.077335,0.106493,0.077335,NaN,41.405597,0.257085,31,14099.225806,13492.870968,14269.241379,13800.586207,14750.290323,13907.612903,14912.933333,13992.366667

In [17]:
dataset_list = []
groups = data.groupby(['x', 'y', 'year'])

In [18]:
num_of_groups = len(groups)

In [19]:
c = 0

for group, frame in groups:
    print(f"Iteration: {c}/{num_of_groups}", end='\r')
    temp_df = frame.copy()
    temp_df.reset_index(drop=True, inplace=True)
    temp_df['acc_rainfall_1week'] = temp_df['rainfall'].rolling(window=7, min_periods=0).sum()
    temp_df['acc_rainfall_2week'] = temp_df['rainfall'].rolling(window=14, min_periods=0).sum()
    temp_df['acc_rainfall_month'] = temp_df['rainfall'].rolling(window=30, min_periods=0).sum()
    temp_df['acc_rainfall_jan'] = temp_df['dt_placement'].apply(lambda x: temp_df.loc[temp_df['dt_placement'] <= x, 'rainfall'].sum())
    dataset_list.append(temp_df)
    c = c + 1

In [20]:
dataset = pd.concat(dataset_list, ignore_index=True)
dataset.reset_index(drop=True, inplace=True)

In [21]:
dataset

,x,y,cell_number,dt_placement,NUTS2_ID,year,month,ndvi,ndmi,ndwi,ndbi,ndvi_mean,ndmi_mean,ndwi_mean,ndbi_mean,ndvi_std,ndmi_std,ndwi_std,ndbi_std,lst_day,lst_night,rainfall,day,lst_day_jan_mean,lst_night_jan_mean,lst_day_feb_mean,lst_night_feb_mean,lst_day_mar_mean,lst_night_mar_mean,lst_day_apr_mean,lst_night_apr_mean,acc_rainfall_1week,acc_rainfall_2week,acc_rainfall_month,acc_rainfall_jan
0,23.65882,41.33542,0,2018-01-01,EL51,2018,1,0.075421,0.163148,0.062645,-0.163148,0.146046,0.072780,-0.063395,-0.072780,0.097993,0.055410,0.113606,0.055410,14093.0,13642.000000,0.000000,1,13877.354839,13637.354839,13989.714286,13643.392857,14153.612903,13769.354839,14733.700000,14052.000000,0.000000,0.000000,0.000000,0.000000
1,23.65882,41.33542,0,2018-01-02,EL51,2018,1,0.075421,0.163148,0.062645,-0.163148,0.146046,0.072780,-0.063395,-0.072780,0.097993,0.055410,0.113606,0.055410,13931.0,13642.000000,2.953801,2,13877.354839,13637.354839,13989.714286,13643.392857,14153.612903,13769.354839,14733.700000,14052.000000,2.953801,2.953801,2.953801,2.953801
2,23.65882,41.33542,0,2018-01-03,EL51,2018,1,0.075421,0.163148,0.062645,-0.163148,0.146046,0.072780,-0.063395,-0.072780,0.097993,0.055410,0.113606,0.055410,13783.0,13488.000000,0.000000,3,13877.354839,13637.354839,13989.714286,13643.392857,14153.612903,13769.354839,14733.700000,14052.000000,2.953801,2.953801,2.953801,2.953801
3,23.65882,41.33542,0,2018-01-04,EL51,2018,1,0.075421,0.163148,0.062645,-0.163148,0.146046,0.072780,-0.063395,-0.072780,0.097993,0.055410,0.113606,0.055410,13783.0,13515.000000,3.852192,4,13877.354839,13637.354839,13989.714286,13643.392857,14153.612903,13769.354839,14733.700000,14052.000000,6.805993,6.805993,6.805993,6.805993
4,23.65882,41.33542,0,2018-01-05,EL51,2018,1,0.075421,0.163148,0.062645,-0.163148,0.146046,0.072780,-0.063395,-0.072780,0.097993,0.055410,0.113606,0.055410,13783.0,13515.000000,0.000000,5,13877.354839,13637.354839,13989.714286,13643.392857,14153.612903,13769.354839,14733.700000,14052.000000,6.805993,6.805993,6.805993,6.805993
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3579531,26.60756,41.40729,3265,2020-12-27,EL51,2020,12,0.450774,0.156466,-0.351211,-0.156466,0.200367,-0.010449,-0.132835,0.010449,0.117562,0.077335,0.106493,0.077335,NaN,41.405597,40.110161,27,14099.225806,13492.870968,14269.241379,13800.586207,14750.290323,13907.612903,14912.933333,13992.366667,41.386282,66.425832,178.760248,945.448095
3579532,26.60756,41.40729,3265,2020-12-28,EL51,2020,12,0.450774,0.156466,-0.351211,-0.156466,0.200367,-0.010449,-0.132835,0.010449,0.117562,0.077335,0.106493,0.077335,NaN,41.405597,10.648291,28,14099.225806,13492.870968,14269.241379,13800.586207,14750.290323,13907.612903,14912.933333,13992.366667,51.427257,55.530515,189.246326,956.096386
3579533,26.60756,41.40729,3265,2020-12-29,EL51,2020,12,0.450774,0.156466,-0.351211,-0.156466,0.200367,-0.010449,-0.132835,0.010449,0.117562,0.077335,0.106493,0.077335,NaN,41.405597,1.150095,29,14099.225806,13492.870968,14269.241379,13800.586207,14750.290323,13907.612903,14912.933333,13992.366667,52.577352,53.184668,190.396420,957.246481
3579534,26.60756,41.40729,3265,2020-12-30,EL51,2020,12,0.450774,0.156466,-0.351211,-0.156466,0.200367,-0.010449,-0.132835,0.010449,0.117562,0.077335,0.106493,0.077335,NaN,41.405597,0.027165,30,14099.225806,13492.870968,14269.241379,13800.586207,14750.290323,13907.612903,14912.933333,13992.366667,52.604516,53.211832,187.858429,957.273646
3579535,26.60756,41.40729,3265,2020-12-31,EL51,2020,12,0.450774,0.156466,-0.351211,-0.156466,0.200367,-0.010449,-0.132835,0.010449,0.117562,0.077335,0.106493,0.077335,NaN,41.405597,0.257085,31,14099.225806,13492.870968,14269.241379,13800.586207,14750.290323,13907.612903,14912.933333,13992.366667,52.859634,53.468917,188.115514,957.530731

In [22]:
dataset.to_csv(r'E:\Drive\NOA\MBD-Prediction\Grid Level\data\Thrace\GR_Thrace_Timeline_GRID_2018-2020_filled_mean_rain.csv', encoding='utf-8')