In [23]:
import numpy as np
import pandas as pd
pd.set_option('display.max_columns', None)

In [24]:
data = pd.read_csv(r'E:\Drive\NOA\MBD-Prediction\Grid Level\data\Attica\GR_Attica_Timeline_GRID_2011_filled_mean.csv', encoding='utf-8')

In [25]:
try:
    data.drop(columns=['Unnamed: 0'], inplace=True)
except Exception:
    print("No column named \'Unnamed: 0\'")

In [26]:
data['dt_placement'] = pd.to_datetime(data['dt_placement'])

# Extract year, month, and day from the 'date' column
data['year'] = data['dt_placement'].dt.year
data['month'] = data['dt_placement'].dt.month
data['day'] = data['dt_placement'].dt.day

In [27]:
data

,x,y,cell_number,dt_placement,NUTS2_ID,year,month,ndvi,ndmi,ndwi,ndbi,ndvi_mean,ndmi_mean,ndwi_mean,ndbi_mean,ndvi_std,ndmi_std,ndwi_std,ndbi_std,lst_day,lst_night,rainfall,day,lst_day_jan_mean,lst_night_jan_mean,lst_day_feb_mean,lst_night_feb_mean,lst_day_mar_mean,lst_night_mar_mean,lst_day_apr_mean,lst_night_apr_mean
0,22.92536,36.22923,0,2011-01-01,EL30,2011,1,NaN,NaN,NaN,NaN,0.298096,0.192858,-0.030036,-0.192858,0.115468,0.076475,0.207660,0.076475,14115.0,14006.0,0.103795,1,14201.483871,14011.612903,14331.821429,13982.714286,14356.774194,14027.677419,14585.166667,14110.800000
1,22.92536,36.22923,0,2011-01-02,EL30,2011,1,NaN,NaN,NaN,NaN,0.298096,0.192858,-0.030036,-0.192858,0.115468,0.076475,0.207660,0.076475,14115.0,14109.0,132.058654,2,14201.483871,14011.612903,14331.821429,13982.714286,14356.774194,14027.677419,14585.166667,14110.800000
2,22.92536,36.22923,0,2011-01-03,EL30,2011,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,14115.0,14109.0,0.219865,3,14201.483871,14011.612903,14331.821429,13982.714286,14356.774194,14027.677419,14585.166667,14110.800000
3,22.92536,36.22923,0,2011-01-04,EL30,2011,1,NaN,NaN,NaN,NaN,0.298096,0.192858,-0.030036,-0.192858,0.115468,0.076475,0.207660,0.076475,14257.0,13988.0,0.312082,4,14201.483871,14011.612903,14331.821429,13982.714286,14356.774194,14027.677419,14585.166667,14110.800000
4,22.92536,36.22923,0,2011-01-05,EL30,2011,1,NaN,NaN,NaN,NaN,0.298096,0.192858,-0.030036,-0.192858,0.115468,0.076475,0.207660,0.076475,14257.0,13988.0,1.513182,5,14201.483871,14011.612903,14331.821429,13982.714286,14356.774194,14027.677419,14585.166667,14110.800000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
269000,24.05547,37.79233,736,2011-12-27,EL30,2011,12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,14031.0,13918.0,0.000000,27,14271.483871,13981.193548,14340.250000,13896.678571,14544.193548,13975.516129,14610.900000,14179.966667
269001,24.05547,37.79233,736,2011-12-28,EL30,2011,12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,14186.0,14053.0,0.000000,28,14271.483871,13981.193548,14340.250000,13896.678571,14544.193548,13975.516129,14610.900000,14179.966667
269002,24.05547,37.79233,736,2011-12-29,EL30,2011,12,0.181882,-0.028344,-0.219983,0.028344,0.182326,-0.024150,-0.214190,0.024150,0.014287,0.019814,0.036058,0.019814,14255.0,14053.0,1.019003,29,14271.483871,13981.193548,14340.250000,13896.678571,14544.193548,13975.516129,14610.900000,14179.966667
269003,24.05547,37.79233,736,2011-12-30,EL30,2011,12,0.181882,-0.028344,-0.219983,0.028344,0.182326,-0.024150,-0.214190,0.024150,0.014287,0.019814,0.036058,0.019814,14255.0,14053.0,0.813852,30,14271.483871,13981.193548,14340.250000,13896.678571,14544.193548,13975.516129,14610.900000,14179.966667
269004,24.05547,37.79233,736,2011-12-31,EL30,2011,12,0.181882,-0.028344,-0.219983,0.028344,0.182326,-0.024150,-0.214190,0.024150,0.014287,0.019814,0.036058,0.019814,14062.0,13969.0,0.295510,31,14271.483871,13981.193548,14340.250000,13896.678571,14544.193548,13975.516129,14610.900000,14179.966667

In [28]:
dataset_list = []
groups = data.groupby(['x', 'y', 'year'])

In [29]:
num_of_groups = len(groups)

In [30]:
c = 0

for group, frame in groups:
    print(f"Iteration: {c}/{num_of_groups}", end='\r')
    temp_df = frame.copy()
    temp_df.reset_index(drop=True, inplace=True)
    temp_df['acc_rainfall_1week'] = temp_df['rainfall'].rolling(window=7, min_periods=0).sum()
    temp_df['acc_rainfall_2week'] = temp_df['rainfall'].rolling(window=14, min_periods=0).sum()
    temp_df['acc_rainfall_month'] = temp_df['rainfall'].rolling(window=30, min_periods=0).sum()
    temp_df['acc_rainfall_jan'] = temp_df['dt_placement'].apply(lambda x: temp_df.loc[temp_df['dt_placement'] <= x, 'rainfall'].sum())
    dataset_list.append(temp_df)
    c = c + 1

In [31]:
dataset = pd.concat(dataset_list, ignore_index=True)
dataset.reset_index(drop=True, inplace=True)

In [32]:
dataset

,x,y,cell_number,dt_placement,NUTS2_ID,year,month,ndvi,ndmi,ndwi,ndbi,ndvi_mean,ndmi_mean,ndwi_mean,ndbi_mean,ndvi_std,ndmi_std,ndwi_std,ndbi_std,lst_day,lst_night,rainfall,day,lst_day_jan_mean,lst_night_jan_mean,lst_day_feb_mean,lst_night_feb_mean,lst_day_mar_mean,lst_night_mar_mean,lst_day_apr_mean,lst_night_apr_mean,acc_rainfall_1week,acc_rainfall_2week,acc_rainfall_month,acc_rainfall_jan
0,22.92536,36.22923,0,2011-01-01,EL30,2011,1,NaN,NaN,NaN,NaN,0.298096,0.192858,-0.030036,-0.192858,0.115468,0.076475,0.207660,0.076475,14115.0,14006.0,0.103795,1,14201.483871,14011.612903,14331.821429,13982.714286,14356.774194,14027.677419,14585.166667,14110.800000,0.103795,0.103795,0.103795,0.103795
1,22.92536,36.22923,0,2011-01-02,EL30,2011,1,NaN,NaN,NaN,NaN,0.298096,0.192858,-0.030036,-0.192858,0.115468,0.076475,0.207660,0.076475,14115.0,14109.0,132.058654,2,14201.483871,14011.612903,14331.821429,13982.714286,14356.774194,14027.677419,14585.166667,14110.800000,132.162450,132.162450,132.162450,132.162450
2,22.92536,36.22923,0,2011-01-03,EL30,2011,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,14115.0,14109.0,0.219865,3,14201.483871,14011.612903,14331.821429,13982.714286,14356.774194,14027.677419,14585.166667,14110.800000,132.382314,132.382314,132.382314,132.382314
3,22.92536,36.22923,0,2011-01-04,EL30,2011,1,NaN,NaN,NaN,NaN,0.298096,0.192858,-0.030036,-0.192858,0.115468,0.076475,0.207660,0.076475,14257.0,13988.0,0.312082,4,14201.483871,14011.612903,14331.821429,13982.714286,14356.774194,14027.677419,14585.166667,14110.800000,132.694397,132.694397,132.694397,132.694397
4,22.92536,36.22923,0,2011-01-05,EL30,2011,1,NaN,NaN,NaN,NaN,0.298096,0.192858,-0.030036,-0.192858,0.115468,0.076475,0.207660,0.076475,14257.0,13988.0,1.513182,5,14201.483871,14011.612903,14331.821429,13982.714286,14356.774194,14027.677419,14585.166667,14110.800000,134.207578,134.207578,134.207578,134.207578
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
269000,24.05547,37.79233,736,2011-12-27,EL30,2011,12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,14031.0,13918.0,0.000000,27,14271.483871,13981.193548,14340.250000,13896.678571,14544.193548,13975.516129,14610.900000,14179.966667,58.581730,111.698848,131.004068,1212.057612
269001,24.05547,37.79233,736,2011-12-28,EL30,2011,12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,14186.0,14053.0,0.000000,28,14271.483871,13981.193548,14340.250000,13896.678571,14544.193548,13975.516129,14610.900000,14179.966667,49.972854,111.698848,130.819427,1212.057612
269002,24.05547,37.79233,736,2011-12-29,EL30,2011,12,0.181882,-0.028344,-0.219983,0.028344,0.182326,-0.024150,-0.214190,0.024150,0.014287,0.019814,0.036058,0.019814,14255.0,14053.0,1.019003,29,14271.483871,13981.193548,14340.250000,13896.678571,14544.193548,13975.516129,14610.900000,14179.966667,14.498666,110.433525,130.710955,1213.076615
269003,24.05547,37.79233,736,2011-12-30,EL30,2011,12,0.181882,-0.028344,-0.219983,0.028344,0.182326,-0.024150,-0.214190,0.024150,0.014287,0.019814,0.036058,0.019814,14255.0,14053.0,0.813852,30,14271.483871,13981.193548,14340.250000,13896.678571,14544.193548,13975.516129,14610.900000,14179.966667,1.832855,110.007446,131.374415,1213.890468
269004,24.05547,37.79233,736,2011-12-31,EL30,2011,12,0.181882,-0.028344,-0.219983,0.028344,0.182326,-0.024150,-0.214190,0.024150,0.014287,0.019814,0.036058,0.019814,14062.0,13969.0,0.295510,31,14271.483871,13981.193548,14340.250000,13896.678571,14544.193548,13975.516129,14610.900000,14179.966667,2.128365,106.279571,131.669925,1214.185978

In [33]:
dataset.to_csv(r'E:\Drive\NOA\MBD-Prediction\Grid Level\data\Attica\GR_Attica_Timeline_GRID_2011_filled_mean_rain.csv', encoding='utf-8')