In [1]:
import numpy as np
import pandas as pd
pd.set_option('display.max_columns', None)

In [2]:
data = pd.read_csv(r'E:\Drive\NOA\MBD-Prediction\Grid Level\data\CMacedonia\GR_CMacedonia_Timeline_GRID_2016-2018_filled_mean.csv', encoding='utf-8')

In [3]:
try:
    data.drop(columns=['Unnamed: 0'], inplace=True)
except Exception:
    print("No column named \'Unnamed: 0\'")

In [4]:
data['dt_placement'] = pd.to_datetime(data['dt_placement'])

# Extract year, month, and day from the 'date' column
data['year'] = data['dt_placement'].dt.year
data['month'] = data['dt_placement'].dt.month
data['day'] = data['dt_placement'].dt.day

In [5]:
data

,x,y,cell_number,dt_placement,NUTS2_ID,year,month,ndvi,ndmi,ndwi,ndbi,ndvi_mean,ndmi_mean,ndwi_mean,ndbi_mean,ndvi_std,ndmi_std,ndwi_std,ndbi_std,lst_day,lst_night,rainfall,day,lst_day_jan_mean,lst_night_jan_mean,lst_day_feb_mean,lst_night_feb_mean,lst_day_mar_mean,lst_night_mar_mean,lst_day_apr_mean,lst_night_apr_mean
0,21.76334,40.79806,0,2016-01-01,EL52,2016,1,0.322417,-0.083739,-0.311678,0.083739,0.317002,-0.081787,-0.306300,0.081787,0.012348,0.031579,0.012786,0.031579,14237.0,13758.0,0.304373,1,13979.000000,13652.161290,14312.047619,13841.952381,14394.032258,13811.645161,14815.133333,14107.866667
1,21.76334,40.79806,0,2016-01-02,EL52,2016,1,0.322417,-0.083739,-0.311678,0.083739,0.317002,-0.081787,-0.306300,0.081787,0.012348,0.031579,0.012786,0.031579,13840.0,13758.0,0.069506,2,13979.000000,13652.161290,14312.047619,13841.952381,14394.032258,13811.645161,14815.133333,14107.866667
2,21.76334,40.79806,0,2016-01-03,EL52,2016,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13840.0,13758.0,16.788566,3,13979.000000,13652.161290,14312.047619,13841.952381,14394.032258,13811.645161,14815.133333,14107.866667
3,21.76334,40.79806,0,2016-01-04,EL52,2016,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13840.0,13758.0,6.750442,4,13979.000000,13652.161290,14312.047619,13841.952381,14394.032258,13811.645161,14815.133333,14107.866667
4,21.76334,40.79806,0,2016-01-05,EL52,2016,1,0.322417,-0.083739,-0.311678,0.083739,0.317002,-0.081787,-0.306300,0.081787,0.012348,0.031579,0.012786,0.031579,13840.0,13388.0,0.590280,5,13979.000000,13652.161290,14312.047619,13841.952381,14394.032258,13811.645161,14815.133333,14107.866667
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4839931,24.08217,40.99570,4415,2018-12-27,EL52,2018,12,0.198149,-0.130382,-0.197142,0.130382,0.203739,-0.105573,-0.197259,0.105573,0.101297,0.112771,0.064730,0.112771,13921.0,13492.0,0.000000,27,14135.322581,13648.483871,14345.500000,13768.035714,14556.548387,13920.612903,15015.566667,14174.466667
4839932,24.08217,40.99570,4415,2018-12-28,EL52,2018,12,0.198149,-0.130382,-0.197142,0.130382,0.203739,-0.105573,-0.197259,0.105573,0.101297,0.112771,0.064730,0.112771,13953.0,13492.0,0.250176,28,14135.322581,13648.483871,14345.500000,13768.035714,14556.548387,13920.612903,15015.566667,14174.466667
4839933,24.08217,40.99570,4415,2018-12-29,EL52,2018,12,0.198149,-0.130382,-0.197142,0.130382,0.203739,-0.105573,-0.197259,0.105573,0.101297,0.112771,0.064730,0.112771,13919.0,13492.0,6.513221,29,14135.322581,13648.483871,14345.500000,13768.035714,14556.548387,13920.612903,15015.566667,14174.466667
4839934,24.08217,40.99570,4415,2018-12-30,EL52,2018,12,0.198149,-0.130382,-0.197142,0.130382,0.203739,-0.105573,-0.197259,0.105573,0.101297,0.112771,0.064730,0.112771,13919.0,13492.0,0.000000,30,14135.322581,13648.483871,14345.500000,13768.035714,14556.548387,13920.612903,15015.566667,14174.466667
4839935,24.08217,40.99570,4415,2018-12-31,EL52,2018,12,0.198149,-0.130382,-0.197142,0.130382,0.203739,-0.105573,-0.197259,0.105573,0.101297,0.112771,0.064730,0.112771,13919.0,13520.0,0.000000,31,14135.322581,13648.483871,14345.500000,13768.035714,14556.548387,13920.612903,15015.566667,14174.466667

In [6]:
dataset_list = []
groups = data.groupby(['x', 'y', 'year'])

In [7]:
num_of_groups = len(groups)

In [8]:
c = 0

for group, frame in groups:
    print(f"Iteration: {c}/{num_of_groups}", end='\r')
    temp_df = frame.copy()
    temp_df.reset_index(drop=True, inplace=True)
    temp_df['acc_rainfall_1week'] = temp_df['rainfall'].rolling(window=7, min_periods=0).sum()
    temp_df['acc_rainfall_2week'] = temp_df['rainfall'].rolling(window=14, min_periods=0).sum()
    temp_df['acc_rainfall_month'] = temp_df['rainfall'].rolling(window=30, min_periods=0).sum()
    temp_df['acc_rainfall_jan'] = temp_df['dt_placement'].apply(lambda x: temp_df.loc[temp_df['dt_placement'] <= x, 'rainfall'].sum())
    dataset_list.append(temp_df)
    c = c + 1

In [9]:
dataset = pd.concat(dataset_list, ignore_index=True)
dataset.reset_index(drop=True, inplace=True)

In [10]:
dataset

,x,y,cell_number,dt_placement,NUTS2_ID,year,month,ndvi,ndmi,ndwi,ndbi,ndvi_mean,ndmi_mean,ndwi_mean,ndbi_mean,ndvi_std,ndmi_std,ndwi_std,ndbi_std,lst_day,lst_night,rainfall,day,lst_day_jan_mean,lst_night_jan_mean,lst_day_feb_mean,lst_night_feb_mean,lst_day_mar_mean,lst_night_mar_mean,lst_day_apr_mean,lst_night_apr_mean,acc_rainfall_1week,acc_rainfall_2week,acc_rainfall_month,acc_rainfall_jan
0,21.76334,40.79806,0,2016-01-01,EL52,2016,1,0.322417,-0.083739,-0.311678,0.083739,0.317002,-0.081787,-0.306300,0.081787,0.012348,0.031579,0.012786,0.031579,14237.0,13758.0,0.304373,1,13979.000000,13652.161290,14312.047619,13841.952381,14394.032258,13811.645161,14815.133333,14107.866667,0.304373,0.304373,0.304373,0.304373
1,21.76334,40.79806,0,2016-01-02,EL52,2016,1,0.322417,-0.083739,-0.311678,0.083739,0.317002,-0.081787,-0.306300,0.081787,0.012348,0.031579,0.012786,0.031579,13840.0,13758.0,0.069506,2,13979.000000,13652.161290,14312.047619,13841.952381,14394.032258,13811.645161,14815.133333,14107.866667,0.373879,0.373879,0.373879,0.373879
2,21.76334,40.79806,0,2016-01-03,EL52,2016,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13840.0,13758.0,16.788566,3,13979.000000,13652.161290,14312.047619,13841.952381,14394.032258,13811.645161,14815.133333,14107.866667,17.162446,17.162446,17.162446,17.162446
3,21.76334,40.79806,0,2016-01-04,EL52,2016,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13840.0,13758.0,6.750442,4,13979.000000,13652.161290,14312.047619,13841.952381,14394.032258,13811.645161,14815.133333,14107.866667,23.912887,23.912887,23.912887,23.912887
4,21.76334,40.79806,0,2016-01-05,EL52,2016,1,0.322417,-0.083739,-0.311678,0.083739,0.317002,-0.081787,-0.306300,0.081787,0.012348,0.031579,0.012786,0.031579,13840.0,13388.0,0.590280,5,13979.000000,13652.161290,14312.047619,13841.952381,14394.032258,13811.645161,14815.133333,14107.866667,24.503167,24.503167,24.503167,24.503167
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4839931,24.08217,40.99570,4415,2018-12-27,EL52,2018,12,0.198149,-0.130382,-0.197142,0.130382,0.203739,-0.105573,-0.197259,0.105573,0.101297,0.112771,0.064730,0.112771,13921.0,13492.0,0.000000,27,14135.322581,13648.483871,14345.500000,13768.035714,14556.548387,13920.612903,15015.566667,14174.466667,17.174665,112.207197,144.389915,1325.149331
4839932,24.08217,40.99570,4415,2018-12-28,EL52,2018,12,0.198149,-0.130382,-0.197142,0.130382,0.203739,-0.105573,-0.197259,0.105573,0.101297,0.112771,0.064730,0.112771,13953.0,13492.0,0.250176,28,14135.322581,13648.483871,14345.500000,13768.035714,14556.548387,13920.612903,15015.566667,14174.466667,17.424841,112.435998,118.765849,1325.399507
4839933,24.08217,40.99570,4415,2018-12-29,EL52,2018,12,0.198149,-0.130382,-0.197142,0.130382,0.203739,-0.105573,-0.197259,0.105573,0.101297,0.112771,0.064730,0.112771,13919.0,13492.0,6.513221,29,14135.322581,13648.483871,14345.500000,13768.035714,14556.548387,13920.612903,15015.566667,14174.466667,23.794933,67.850121,125.227832,1331.912727
4839934,24.08217,40.99570,4415,2018-12-30,EL52,2018,12,0.198149,-0.130382,-0.197142,0.130382,0.203739,-0.105573,-0.197259,0.105573,0.101297,0.112771,0.064730,0.112771,13919.0,13492.0,0.000000,30,14135.322581,13648.483871,14345.500000,13768.035714,14556.548387,13920.612903,15015.566667,14174.466667,23.794933,63.919255,125.227832,1331.912727
4839935,24.08217,40.99570,4415,2018-12-31,EL52,2018,12,0.198149,-0.130382,-0.197142,0.130382,0.203739,-0.105573,-0.197259,0.105573,0.101297,0.112771,0.064730,0.112771,13919.0,13520.0,0.000000,31,14135.322581,13648.483871,14345.500000,13768.035714,14556.548387,13920.612903,15015.566667,14174.466667,18.397721,53.292003,125.159885,1331.912727

In [11]:
dataset.to_csv(r'E:\Drive\NOA\MBD-Prediction\Grid Level\data\CMacedonia\GR_CMacedonia_Timeline_GRID_2016-2018_filled_mean_rain.csv', encoding='utf-8')