In [32]:
import numpy as np
import pandas as pd
import geopandas as gpd
import sys

sys.path.insert(0, r"E:\Drive\NOA\MBD-Prediction\Modules")

from utils import describe_dataframe, process_greek

enc = 'utf-8'

folder_path = "C:/Users/dimit/Documents/noa hoard/Greece Shapefiles"

pd.set_option('display.max_columns', None)

In [2]:
data = pd.read_csv(r'E:\Drive\NOA\MBD-Prediction\Grid Level\data\CMacedonia\GR_CMacedonia_Timeline_GRID_2016-2018_filled.csv', encoding=enc)
greece_nuts3 = gpd.read_file(r"E:\Drive\NOA\MBD-Prediction\Europe NUTS - LAU Shapefiles\Greece\data\EL_Whole.shp",  encoding=enc)
greece_lau1 = gpd.read_file(f"{folder_path}/el_lau1.shp",  encoding=enc)

In [3]:
try:
    data.drop(columns=['Unnamed: 0'], inplace=True)
except Exception:
    print("No column named \'Unnamed: 0\'")

In [4]:
data

,x,y,cell_number,dt_placement,NUTS2_ID,year,month,ndvi,ndmi,ndwi,ndbi,ndvi_mean,ndmi_mean,ndwi_mean,ndbi_mean,ndvi_std,ndmi_std,ndwi_std,ndbi_std,lst_day,lst_night,rainfall,day,lst_day_jan_mean,lst_night_jan_mean,lst_day_feb_mean,lst_night_feb_mean,lst_day_mar_mean,lst_night_mar_mean,lst_day_apr_mean,lst_night_apr_mean,acc_rainfall_1week,acc_rainfall_2week,acc_rainfall_month,acc_rainfall_jan
0,21.76334,40.79806,0,2016-01-01,EL52,2016,1,0.322417,-0.083739,-0.311678,0.083739,0.317002,-0.081787,-0.306300,0.081787,0.012348,0.031579,0.012786,0.031579,14237.0,13758.0,0.304373,1,13979.000000,13652.161290,14312.047619,13841.952381,14394.032258,13811.645161,14815.133333,14107.866667,0.304373,0.304373,0.304373,0.304373
1,21.76334,40.79806,0,2016-01-02,EL52,2016,1,0.322417,-0.083739,-0.311678,0.083739,0.317002,-0.081787,-0.306300,0.081787,0.012348,0.031579,0.012786,0.031579,13840.0,13758.0,0.069506,2,13979.000000,13652.161290,14312.047619,13841.952381,14394.032258,13811.645161,14815.133333,14107.866667,0.373879,0.373879,0.373879,0.373879
2,21.76334,40.79806,0,2016-01-03,EL52,2016,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13840.0,13758.0,16.788566,3,13979.000000,13652.161290,14312.047619,13841.952381,14394.032258,13811.645161,14815.133333,14107.866667,17.162446,17.162446,17.162446,17.162446
3,21.76334,40.79806,0,2016-01-04,EL52,2016,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13840.0,13758.0,6.750442,4,13979.000000,13652.161290,14312.047619,13841.952381,14394.032258,13811.645161,14815.133333,14107.866667,23.912887,23.912887,23.912887,23.912887
4,21.76334,40.79806,0,2016-01-05,EL52,2016,1,0.322417,-0.083739,-0.311678,0.083739,0.317002,-0.081787,-0.306300,0.081787,0.012348,0.031579,0.012786,0.031579,13840.0,13388.0,0.590280,5,13979.000000,13652.161290,14312.047619,13841.952381,14394.032258,13811.645161,14815.133333,14107.866667,24.503167,24.503167,24.503167,24.503167
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4839931,24.08217,40.99570,4415,2018-12-27,EL52,2018,12,0.198149,-0.130382,-0.197142,0.130382,0.203739,-0.105573,-0.197259,0.105573,0.101297,0.112771,0.064730,0.112771,13921.0,13492.0,0.000000,27,14135.322581,13648.483871,14345.500000,13768.035714,14556.548387,13920.612903,15015.566667,14174.466667,17.174665,112.207197,144.389915,1325.149331
4839932,24.08217,40.99570,4415,2018-12-28,EL52,2018,12,0.198149,-0.130382,-0.197142,0.130382,0.203739,-0.105573,-0.197259,0.105573,0.101297,0.112771,0.064730,0.112771,13953.0,13492.0,0.250176,28,14135.322581,13648.483871,14345.500000,13768.035714,14556.548387,13920.612903,15015.566667,14174.466667,17.424841,112.435998,118.765849,1325.399507
4839933,24.08217,40.99570,4415,2018-12-29,EL52,2018,12,0.198149,-0.130382,-0.197142,0.130382,0.203739,-0.105573,-0.197259,0.105573,0.101297,0.112771,0.064730,0.112771,13919.0,13492.0,6.513221,29,14135.322581,13648.483871,14345.500000,13768.035714,14556.548387,13920.612903,15015.566667,14174.466667,23.794933,67.850121,125.227832,1331.912727
4839934,24.08217,40.99570,4415,2018-12-30,EL52,2018,12,0.198149,-0.130382,-0.197142,0.130382,0.203739,-0.105573,-0.197259,0.105573,0.101297,0.112771,0.064730,0.112771,13919.0,13492.0,0.000000,30,14135.322581,13648.483871,14345.500000,13768.035714,14556.548387,13920.612903,15015.566667,14174.466667,23.794933,63.919255,125.227832,1331.912727
4839935,24.08217,40.99570,4415,2018-12-31,EL52,2018,12,0.198149,-0.130382,-0.197142,0.130382,0.203739,-0.105573,-0.197259,0.105573,0.101297,0.112771,0.064730,0.112771,13919.0,13520.0,0.000000,31,14135.322581,13648.483871,14345.500000,13768.035714,14556.548387,13920.612903,15015.566667,14174.466667,18.397721,53.292003,125.159885,1331.912727

In [5]:
greece_grid = gpd.GeoDataFrame(data, geometry=gpd.points_from_xy(data.x, data.y), crs='EPSG:4326')

greece_grid.head()

,x,y,cell_number,dt_placement,NUTS2_ID,year,month,ndvi,ndmi,ndwi,ndbi,ndvi_mean,ndmi_mean,ndwi_mean,ndbi_mean,ndvi_std,ndmi_std,ndwi_std,ndbi_std,lst_day,lst_night,rainfall,day,lst_day_jan_mean,lst_night_jan_mean,lst_day_feb_mean,lst_night_feb_mean,lst_day_mar_mean,lst_night_mar_mean,lst_day_apr_mean,lst_night_apr_mean,acc_rainfall_1week,acc_rainfall_2week,acc_rainfall_month,acc_rainfall_jan,geometry
0,21.76334,40.79806,0,2016-01-01,EL52,2016,1,0.322417,-0.083739,-0.311678,0.083739,0.317002,-0.081787,-0.3063,0.081787,0.012348,0.031579,0.012786,0.031579,14237.0,13758.0,0.304373,1,13979.0,13652.16129,14312.047619,13841.952381,14394.032258,13811.645161,14815.133333,14107.866667,0.304373,0.304373,0.304373,0.304373,POINT (21.76334 40.79806)
1,21.76334,40.79806,0,2016-01-02,EL52,2016,1,0.322417,-0.083739,-0.311678,0.083739,0.317002,-0.081787,-0.3063,0.081787,0.012348,0.031579,0.012786,0.031579,13840.0,13758.0,0.069506,2,13979.0,13652.16129,14312.047619,13841.952381,14394.032258,13811.645161,14815.133333,14107.866667,0.373879,0.373879,0.373879,0.373879,POINT (21.76334 40.79806)
2,21.76334,40.79806,0,2016-01-03,EL52,2016,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13840.0,13758.0,16.788566,3,13979.0,13652.16129,14312.047619,13841.952381,14394.032258,13811.645161,14815.133333,14107.866667,17.162446,17.162446,17.162446,17.162446,POINT (21.76334 40.79806)
3,21.76334,40.79806,0,2016-01-04,EL52,2016,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13840.0,13758.0,6.750442,4,13979.0,13652.16129,14312.047619,13841.952381,14394.032258,13811.645161,14815.133333,14107.866667,23.912887,23.912887,23.912887,23.912887,POINT (21.76334 40.79806)
4,21.76334,40.79806,0,2016-01-05,EL52,2016,1,0.322417,-0.083739,-0.311678,0.083739,0.317002,-0.081787,-0.3063,0.081787,0.012348,0.031579,0.012786,0.031579,13840.0,13388.0,0.590280,5,13979.0,13652.16129,14312.047619,13841.952381,14394.032258,13811.645161,14815.133333,14107.866667,24.503167,24.503167,24.503167,24.503167,POINT (21.76334 40.79806)

In [6]:
greece_nuts3 = greece_nuts3.to_crs(epsg=4326)
greece_lau1 = greece_lau1.to_crs(epsg=4326)
greece_grid = greece_grid.to_crs(epsg=4326)

In [7]:
greece_lau1.drop(columns=['KWD_YPES'], inplace = True)
greece_lau1.drop(greece_lau1[greece_lau1['NAME'] == 'Άθως'].index, inplace = True)
greece_lau1.rename(columns={"NAME": "LAU1_NAME", "geometry": "lau1_geom"}, inplace = True)
greece_lau1.set_geometry("lau1_geom", inplace = True)
greece_lau1['lau1_centroid'] = greece_lau1['lau1_geom'].centroid
greece_lau1['lau1_rpoint'] = greece_lau1['lau1_geom'].representative_point()
greece_lau1.reset_index(drop=True, inplace=True)

greece_nuts3.rename(columns={"geometry": "nuts3_geom"}, inplace = True)
greece_nuts3.set_geometry("nuts3_geom", inplace = True)

C:\Users\dimit\AppData\Local\Temp\ipykernel_14216\2894926608.py:5: UserWarning: Geometry is in a geographic CRS. Results from 'centroid' are likely incorrect. Use 'GeoSeries.to_crs()' to re-project geometries to a projected CRS before this operation.

  greece_lau1['lau1_centroid'] = greece_lau1['lau1_geom'].centroid

In [8]:
print(f'greece_nuts3 CRS: {greece_nuts3.crs}')
print(f'greece_lau1 CRS: {greece_lau1.crs}')
print(f'greece_grid CRS: {greece_grid.crs}')

greece_nuts3 CRS: EPSG:4326
greece_lau1 CRS: EPSG:4326
greece_grid CRS: EPSG:4326

In [9]:
greece_lau1.set_geometry("lau1_rpoint", inplace = True)
greece_nuts3 = greece_nuts3.to_crs(epsg=4326)
greece_lau1 = greece_lau1.to_crs(epsg=4326)

greece_gdf = greece_lau1.sjoin(greece_nuts3, predicate="within", how = "left")
greece_gdf.head()

,LAU1_NAME,lau1_geom,lau1_centroid,lau1_rpoint,index_right,CNTR_CODE,CNTR_NAME,NUTS1_ID,NUTS1_LATN,NUTS1_NAME,NUTS2_ID,NUTS2_LATN,NUTS2_NAME,NUTS3_ID,NUTS3_LATN,NUTS3_NAME,MOUNT_TYPE,URBN_TYPE,COAST_TYPE
0,Αμυνταίου,"POLYGON ((21.70746 40.85172, 21.70955 40.85119...",POINT (21.63479 40.67528),POINT (21.67171 40.68676),30,EL,Greece,EL5,Voreia Elláda,Βόρεια Ελλάδα,EL53,Dytiki Makedonia,Δυτική Μακεδονία,EL533,Florina,Φλώρινα,3.0,3,3
1,Άκτιου - Βόνιτσας,"MULTIPOLYGON (((20.79456 38.75371, 20.79456 38...",POINT (20.95158 38.82289),POINT (20.93655 38.81891),41,EL,Greece,EL6,Kentriki Elláda,Κεντρική Ελλάδα,EL63,Dytiki Elláda,Δυτική Ελλάδα,EL631,Aitoloakarnania,Αιτωλοακαρνανία,2.0,3,1
2,Άνδρου,"MULTIPOLYGON (((24.95917 37.69039, 24.95897 37...",POINT (24.84814 37.85801),POINT (24.86216 37.84094),11,EL,Greece,EL4,"Nisia Aigaiou, Kriti","Νησιά Αιγαίου, Κρήτη",EL42,Notio Aigaio,Νότιο Αιγαίο,EL422,"Andros, Thira, Kea, Milos, Mykonos, Naxos, Par...","Άνδρος, Θήρα, Κέα, Μήλος, Μύκονος, Νάξος, Πάρο...",2.0,3,1
3,Άργους - Μυκηνών,"POLYGON ((22.52084 37.83857, 22.52111 37.83829...",POINT (22.62532 37.66339),POINT (22.62833 37.65584),49,EL,Greece,EL6,Kentriki Elláda,Κεντρική Ελλάδα,EL65,Peloponnisos,Πελοπόννησος,EL651,"Argolida, Arkadia","Αργολίδα, Αρκαδία",3.0,3,1
4,Έδεσσας,"POLYGON ((21.99535 40.90380, 21.99562 40.90344...",POINT (21.92931 40.79799),POINT (21.93215 40.79303),24,EL,Greece,EL5,Voreia Elláda,Βόρεια Ελλάδα,EL52,Kentriki Makedonia,Κεντρική Μακεδονία,EL524,Pella,Πέλλα,2.0,3,2

In [10]:
greece_gdf.drop(columns = ['lau1_centroid',	'lau1_rpoint', 'index_right', 'CNTR_CODE', 'CNTR_NAME', 'NUTS1_LATN', 'NUTS2_LATN', 'NUTS3_LATN'], inplace = True)

In [11]:
greece_gdf.set_geometry('lau1_geom', inplace = True)
greece_grid.set_geometry('geometry', inplace = True)

In [12]:
greece_gdf = greece_gdf.to_crs(epsg=4326)
greece_grid = greece_grid.to_crs(epsg=4326)

In [13]:
greece_gdf_sub = greece_gdf[greece_gdf['NUTS2_ID'] == 'EL52'].copy()
greece_gdf_sub.reset_index(drop=True, inplace=True)

In [14]:
greece_grid.head()

,x,y,cell_number,dt_placement,NUTS2_ID,year,month,ndvi,ndmi,ndwi,ndbi,ndvi_mean,ndmi_mean,ndwi_mean,ndbi_mean,ndvi_std,ndmi_std,ndwi_std,ndbi_std,lst_day,lst_night,rainfall,day,lst_day_jan_mean,lst_night_jan_mean,lst_day_feb_mean,lst_night_feb_mean,lst_day_mar_mean,lst_night_mar_mean,lst_day_apr_mean,lst_night_apr_mean,acc_rainfall_1week,acc_rainfall_2week,acc_rainfall_month,acc_rainfall_jan,geometry
0,21.76334,40.79806,0,2016-01-01,EL52,2016,1,0.322417,-0.083739,-0.311678,0.083739,0.317002,-0.081787,-0.3063,0.081787,0.012348,0.031579,0.012786,0.031579,14237.0,13758.0,0.304373,1,13979.0,13652.16129,14312.047619,13841.952381,14394.032258,13811.645161,14815.133333,14107.866667,0.304373,0.304373,0.304373,0.304373,POINT (21.76334 40.79806)
1,21.76334,40.79806,0,2016-01-02,EL52,2016,1,0.322417,-0.083739,-0.311678,0.083739,0.317002,-0.081787,-0.3063,0.081787,0.012348,0.031579,0.012786,0.031579,13840.0,13758.0,0.069506,2,13979.0,13652.16129,14312.047619,13841.952381,14394.032258,13811.645161,14815.133333,14107.866667,0.373879,0.373879,0.373879,0.373879,POINT (21.76334 40.79806)
2,21.76334,40.79806,0,2016-01-03,EL52,2016,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13840.0,13758.0,16.788566,3,13979.0,13652.16129,14312.047619,13841.952381,14394.032258,13811.645161,14815.133333,14107.866667,17.162446,17.162446,17.162446,17.162446,POINT (21.76334 40.79806)
3,21.76334,40.79806,0,2016-01-04,EL52,2016,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13840.0,13758.0,6.750442,4,13979.0,13652.16129,14312.047619,13841.952381,14394.032258,13811.645161,14815.133333,14107.866667,23.912887,23.912887,23.912887,23.912887,POINT (21.76334 40.79806)
4,21.76334,40.79806,0,2016-01-05,EL52,2016,1,0.322417,-0.083739,-0.311678,0.083739,0.317002,-0.081787,-0.3063,0.081787,0.012348,0.031579,0.012786,0.031579,13840.0,13388.0,0.590280,5,13979.0,13652.16129,14312.047619,13841.952381,14394.032258,13811.645161,14815.133333,14107.866667,24.503167,24.503167,24.503167,24.503167,POINT (21.76334 40.79806)

In [15]:
greece_gdf_sub.head()

,LAU1_NAME,lau1_geom,NUTS1_ID,NUTS1_NAME,NUTS2_ID,NUTS2_NAME,NUTS3_ID,NUTS3_NAME,MOUNT_TYPE,URBN_TYPE,COAST_TYPE
0,Έδεσσας,"POLYGON ((21.99535 40.90380, 21.99562 40.90344...",EL5,Βόρεια Ελλάδα,EL52,Κεντρική Μακεδονία,EL524,Πέλλα,2.0,3,2
1,Αλεξάνδρειας,"MULTIPOLYGON (((22.66199 40.52431, 22.66194 40...",EL5,Βόρεια Ελλάδα,EL52,Κεντρική Μακεδονία,EL521,Ημαθία,2.0,2,1
2,Αλμωπίας,"POLYGON ((22.22498 41.16444, 22.22529 41.16444...",EL5,Βόρεια Ελλάδα,EL52,Κεντρική Μακεδονία,EL524,Πέλλα,2.0,3,2
3,Αμπελοκήπων - Μενεμένης,"POLYGON ((22.87764 40.66601, 22.87775 40.66573...",EL5,Βόρεια Ελλάδα,EL52,Κεντρική Μακεδονία,EL522,Θεσσαλονίκη,2.0,1,1
4,Αμφίπολης,"POLYGON ((24.04143 41.04942, 24.04322 41.04930...",EL5,Βόρεια Ελλάδα,EL52,Κεντρική Μακεδονία,EL526,Σέρρες,2.0,3,1

In [16]:
cm_grid = greece_grid.sjoin_nearest(greece_gdf, how='left', max_distance=0.01, distance_col='dist')

c:\Users\dimit\Python Virtual Environments\noa_eywa\Lib\site-packages\geopandas\array.py:365: UserWarning: Geometry is in a geographic CRS. Results from 'sjoin_nearest' are likely incorrect. Use 'GeoSeries.to_crs()' to re-project geometries to a projected CRS before this operation.

  warnings.warn(

In [17]:
cm_grid.head()

,x,y,cell_number,dt_placement,NUTS2_ID_left,year,month,ndvi,ndmi,ndwi,ndbi,ndvi_mean,ndmi_mean,ndwi_mean,ndbi_mean,ndvi_std,ndmi_std,ndwi_std,ndbi_std,lst_day,lst_night,rainfall,day,lst_day_jan_mean,lst_night_jan_mean,lst_day_feb_mean,lst_night_feb_mean,lst_day_mar_mean,lst_night_mar_mean,lst_day_apr_mean,lst_night_apr_mean,acc_rainfall_1week,acc_rainfall_2week,acc_rainfall_month,acc_rainfall_jan,geometry,index_right,LAU1_NAME,NUTS1_ID,NUTS1_NAME,NUTS2_ID_right,NUTS2_NAME,NUTS3_ID,NUTS3_NAME,MOUNT_TYPE,URBN_TYPE,COAST_TYPE,dist
0,21.76334,40.79806,0,2016-01-01,EL52,2016,1,0.322417,-0.083739,-0.311678,0.083739,0.317002,-0.081787,-0.3063,0.081787,0.012348,0.031579,0.012786,0.031579,14237.0,13758.0,0.304373,1,13979.0,13652.16129,14312.047619,13841.952381,14394.032258,13811.645161,14815.133333,14107.866667,0.304373,0.304373,0.304373,0.304373,POINT (21.76334 40.79806),4,Έδεσσας,EL5,Βόρεια Ελλάδα,EL52,Κεντρική Μακεδονία,EL524,Πέλλα,2.0,3,2,0.0
1,21.76334,40.79806,0,2016-01-02,EL52,2016,1,0.322417,-0.083739,-0.311678,0.083739,0.317002,-0.081787,-0.3063,0.081787,0.012348,0.031579,0.012786,0.031579,13840.0,13758.0,0.069506,2,13979.0,13652.16129,14312.047619,13841.952381,14394.032258,13811.645161,14815.133333,14107.866667,0.373879,0.373879,0.373879,0.373879,POINT (21.76334 40.79806),4,Έδεσσας,EL5,Βόρεια Ελλάδα,EL52,Κεντρική Μακεδονία,EL524,Πέλλα,2.0,3,2,0.0
2,21.76334,40.79806,0,2016-01-03,EL52,2016,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13840.0,13758.0,16.788566,3,13979.0,13652.16129,14312.047619,13841.952381,14394.032258,13811.645161,14815.133333,14107.866667,17.162446,17.162446,17.162446,17.162446,POINT (21.76334 40.79806),4,Έδεσσας,EL5,Βόρεια Ελλάδα,EL52,Κεντρική Μακεδονία,EL524,Πέλλα,2.0,3,2,0.0
3,21.76334,40.79806,0,2016-01-04,EL52,2016,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13840.0,13758.0,6.750442,4,13979.0,13652.16129,14312.047619,13841.952381,14394.032258,13811.645161,14815.133333,14107.866667,23.912887,23.912887,23.912887,23.912887,POINT (21.76334 40.79806),4,Έδεσσας,EL5,Βόρεια Ελλάδα,EL52,Κεντρική Μακεδονία,EL524,Πέλλα,2.0,3,2,0.0
4,21.76334,40.79806,0,2016-01-05,EL52,2016,1,0.322417,-0.083739,-0.311678,0.083739,0.317002,-0.081787,-0.3063,0.081787,0.012348,0.031579,0.012786,0.031579,13840.0,13388.0,0.590280,5,13979.0,13652.16129,14312.047619,13841.952381,14394.032258,13811.645161,14815.133333,14107.866667,24.503167,24.503167,24.503167,24.503167,POINT (21.76334 40.79806),4,Έδεσσας,EL5,Βόρεια Ελλάδα,EL52,Κεντρική Μακεδονία,EL524,Πέλλα,2.0,3,2,0.0

In [22]:
describe_dataframe(cm_grid, remove_zeros=True)

                Column  Missing
7                 ndvi  12.0233
8                 ndmi  12.0233
9                 ndwi  12.0233
10                ndbi  12.0233
11           ndvi_mean  11.3085
12           ndmi_mean  11.3093
13           ndwi_mean  11.3085
14           ndbi_mean  11.3117
15            ndvi_std  11.3085
16            ndmi_std  11.3093
17            ndwi_std  11.3085
18            ndbi_std  11.3117
19             lst_day   0.7779
20           lst_night   0.8634
21            rainfall   0.1422
26  lst_night_feb_mean   0.0151

In [25]:
cm_grid.columns

Index(['x', 'y', 'cell_number', 'dt_placement', 'NUTS2_ID_left', 'year',
       'month', 'ndvi', 'ndmi', 'ndwi', 'ndbi', 'ndvi_mean', 'ndmi_mean',
       'ndwi_mean', 'ndbi_mean', 'ndvi_std', 'ndmi_std', 'ndwi_std',
       'ndbi_std', 'lst_day', 'lst_night', 'rainfall', 'day',
       'lst_day_jan_mean', 'lst_night_jan_mean', 'lst_day_feb_mean',
       'lst_night_feb_mean', 'lst_day_mar_mean', 'lst_night_mar_mean',
       'lst_day_apr_mean', 'lst_night_apr_mean', 'acc_rainfall_1week',
       'acc_rainfall_2week', 'acc_rainfall_month', 'acc_rainfall_jan',
       'geometry', 'index_right', 'LAU1_NAME', 'NUTS1_ID', 'NUTS1_NAME',
       'NUTS2_ID_right', 'NUTS2_NAME', 'NUTS3_ID', 'NUTS3_NAME', 'MOUNT_TYPE',
       'URBN_TYPE', 'COAST_TYPE', 'dist'],
      dtype='object')

In [26]:
cm_grid.rename(columns={'NUTS2_ID_left': 'NUTS2_ID'}, inplace=True)

In [27]:
new_order = ['x', 'y', 'cell_number', 'dt_placement','NUTS1_ID', 'NUTS1_NAME', 'NUTS2_ID', 'NUTS2_NAME', 'NUTS3_ID', 'NUTS3_NAME', 'LAU1_NAME', 'year', 'month',
             'ndvi', 'ndmi', 'ndwi', 'ndbi', 'ndvi_mean', 'ndmi_mean',
             'ndwi_mean', 'ndbi_mean', 'ndvi_std', 'ndmi_std', 'ndwi_std',
             'ndbi_std', 'lst_day', 'lst_night', 'rainfall', 'day',
             'lst_day_jan_mean', 'lst_night_jan_mean', 'lst_day_feb_mean',
             'lst_night_feb_mean', 'lst_day_mar_mean', 'lst_night_mar_mean',
             'lst_day_apr_mean', 'lst_night_apr_mean', 'acc_rainfall_1week',
             'acc_rainfall_2week', 'acc_rainfall_month', 'acc_rainfall_jan',
             'MOUNT_TYPE','URBN_TYPE', 'COAST_TYPE']

In [28]:
cm_grid = cm_grid[new_order]

In [30]:
cm_grid.head()

,x,y,cell_number,dt_placement,NUTS1_ID,NUTS1_NAME,NUTS2_ID,NUTS2_NAME,NUTS3_ID,NUTS3_NAME,LAU1_NAME,year,month,ndvi,ndmi,ndwi,ndbi,ndvi_mean,ndmi_mean,ndwi_mean,ndbi_mean,ndvi_std,ndmi_std,ndwi_std,ndbi_std,lst_day,lst_night,rainfall,day,lst_day_jan_mean,lst_night_jan_mean,lst_day_feb_mean,lst_night_feb_mean,lst_day_mar_mean,lst_night_mar_mean,lst_day_apr_mean,lst_night_apr_mean,acc_rainfall_1week,acc_rainfall_2week,acc_rainfall_month,acc_rainfall_jan,MOUNT_TYPE,URBN_TYPE,COAST_TYPE
0,21.76334,40.79806,0,2016-01-01,EL5,Βόρεια Ελλάδα,EL52,Κεντρική Μακεδονία,EL524,Πέλλα,Έδεσσας,2016,1,0.322417,-0.083739,-0.311678,0.083739,0.317002,-0.081787,-0.3063,0.081787,0.012348,0.031579,0.012786,0.031579,14237.0,13758.0,0.304373,1,13979.0,13652.16129,14312.047619,13841.952381,14394.032258,13811.645161,14815.133333,14107.866667,0.304373,0.304373,0.304373,0.304373,2.0,3,2
1,21.76334,40.79806,0,2016-01-02,EL5,Βόρεια Ελλάδα,EL52,Κεντρική Μακεδονία,EL524,Πέλλα,Έδεσσας,2016,1,0.322417,-0.083739,-0.311678,0.083739,0.317002,-0.081787,-0.3063,0.081787,0.012348,0.031579,0.012786,0.031579,13840.0,13758.0,0.069506,2,13979.0,13652.16129,14312.047619,13841.952381,14394.032258,13811.645161,14815.133333,14107.866667,0.373879,0.373879,0.373879,0.373879,2.0,3,2
2,21.76334,40.79806,0,2016-01-03,EL5,Βόρεια Ελλάδα,EL52,Κεντρική Μακεδονία,EL524,Πέλλα,Έδεσσας,2016,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13840.0,13758.0,16.788566,3,13979.0,13652.16129,14312.047619,13841.952381,14394.032258,13811.645161,14815.133333,14107.866667,17.162446,17.162446,17.162446,17.162446,2.0,3,2
3,21.76334,40.79806,0,2016-01-04,EL5,Βόρεια Ελλάδα,EL52,Κεντρική Μακεδονία,EL524,Πέλλα,Έδεσσας,2016,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13840.0,13758.0,6.750442,4,13979.0,13652.16129,14312.047619,13841.952381,14394.032258,13811.645161,14815.133333,14107.866667,23.912887,23.912887,23.912887,23.912887,2.0,3,2
4,21.76334,40.79806,0,2016-01-05,EL5,Βόρεια Ελλάδα,EL52,Κεντρική Μακεδονία,EL524,Πέλλα,Έδεσσας,2016,1,0.322417,-0.083739,-0.311678,0.083739,0.317002,-0.081787,-0.3063,0.081787,0.012348,0.031579,0.012786,0.031579,13840.0,13388.0,0.590280,5,13979.0,13652.16129,14312.047619,13841.952381,14394.032258,13811.645161,14815.133333,14107.866667,24.503167,24.503167,24.503167,24.503167,2.0,3,2

In [36]:
process_greek(cm_grid, 'NUTS1_NAME')
process_greek(cm_grid, 'NUTS2_NAME')
process_greek(cm_grid, 'NUTS3_NAME')
process_greek(cm_grid, 'LAU1_NAME')

In [37]:
cm_grid.head()

,x,y,cell_number,dt_placement,NUTS1_ID,NUTS1_NAME,NUTS2_ID,NUTS2_NAME,NUTS3_ID,NUTS3_NAME,LAU1_NAME,year,month,ndvi,ndmi,ndwi,ndbi,ndvi_mean,ndmi_mean,ndwi_mean,ndbi_mean,ndvi_std,ndmi_std,ndwi_std,ndbi_std,lst_day,lst_night,rainfall,day,lst_day_jan_mean,lst_night_jan_mean,lst_day_feb_mean,lst_night_feb_mean,lst_day_mar_mean,lst_night_mar_mean,lst_day_apr_mean,lst_night_apr_mean,acc_rainfall_1week,acc_rainfall_2week,acc_rainfall_month,acc_rainfall_jan,MOUNT_TYPE,URBN_TYPE,COAST_TYPE
0,21.76334,40.79806,0,2016-01-01,EL5,βορεια ελλαδα,EL52,κεντρικη μακεδονια,EL524,πελλα,εδεσσας,2016,1,0.322417,-0.083739,-0.311678,0.083739,0.317002,-0.081787,-0.3063,0.081787,0.012348,0.031579,0.012786,0.031579,14237.0,13758.0,0.304373,1,13979.0,13652.16129,14312.047619,13841.952381,14394.032258,13811.645161,14815.133333,14107.866667,0.304373,0.304373,0.304373,0.304373,2.0,3,2
1,21.76334,40.79806,0,2016-01-02,EL5,βορεια ελλαδα,EL52,κεντρικη μακεδονια,EL524,πελλα,εδεσσας,2016,1,0.322417,-0.083739,-0.311678,0.083739,0.317002,-0.081787,-0.3063,0.081787,0.012348,0.031579,0.012786,0.031579,13840.0,13758.0,0.069506,2,13979.0,13652.16129,14312.047619,13841.952381,14394.032258,13811.645161,14815.133333,14107.866667,0.373879,0.373879,0.373879,0.373879,2.0,3,2
2,21.76334,40.79806,0,2016-01-03,EL5,βορεια ελλαδα,EL52,κεντρικη μακεδονια,EL524,πελλα,εδεσσας,2016,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13840.0,13758.0,16.788566,3,13979.0,13652.16129,14312.047619,13841.952381,14394.032258,13811.645161,14815.133333,14107.866667,17.162446,17.162446,17.162446,17.162446,2.0,3,2
3,21.76334,40.79806,0,2016-01-04,EL5,βορεια ελλαδα,EL52,κεντρικη μακεδονια,EL524,πελλα,εδεσσας,2016,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13840.0,13758.0,6.750442,4,13979.0,13652.16129,14312.047619,13841.952381,14394.032258,13811.645161,14815.133333,14107.866667,23.912887,23.912887,23.912887,23.912887,2.0,3,2
4,21.76334,40.79806,0,2016-01-05,EL5,βορεια ελλαδα,EL52,κεντρικη μακεδονια,EL524,πελλα,εδεσσας,2016,1,0.322417,-0.083739,-0.311678,0.083739,0.317002,-0.081787,-0.3063,0.081787,0.012348,0.031579,0.012786,0.031579,13840.0,13388.0,0.590280,5,13979.0,13652.16129,14312.047619,13841.952381,14394.032258,13811.645161,14815.133333,14107.866667,24.503167,24.503167,24.503167,24.503167,2.0,3,2

In [38]:
cm_grid.to_csv(r'E:\Drive\NOA\MBD-Prediction\Grid Level\data\CMacedonia\GR_CMacedonia_Timeline_GRID_2016-2018_filled.csv', encoding=enc, index = False)