In [204]:
import numpy as np
import pandas as pd
import geopandas as gpd
import sys

sys.path.insert(0, r"E:\Drive\NOA\MBD-Prediction\Modules")

from utils import describe_dataframe, process_greek

enc = 'utf-8'

pd.set_option('display.max_columns', None)

In [205]:
base_folder = 'E:/Drive/NOA/MBD-Prediction/Grid Level/data'

In [206]:
NUTS2 = 'Thrace'
NUTS2_ID = 'EL51'
YEAR = 2025

In [207]:
data = pd.read_csv(f'{base_folder}/{NUTS2}/GR_{NUTS2}_Timeline_GRID_{YEAR}_filled_mean_rain.csv', encoding=enc)
greece_nuts3 = gpd.read_file(r"E:\Drive\NOA\MBD-Prediction\Europe Shapefiles\Greece\data\EL_Whole.shp",  encoding=enc)
greece_lau1 = gpd.read_file(r"E:\Drive\NOA\MBD-Prediction\Shapefiles\Greece Shapefiles\el_lau1.shp",  encoding=enc)

In [208]:
try:
    data.drop(columns=['Unnamed: 0'], inplace=True)
except Exception:
    print("No column named \'Unnamed: 0\'")

In [209]:
try:
    data.drop(columns=['rainfall.1'], inplace=True)
except Exception:
    print("No column named \'rainfall.1\'")

No column named 'rainfall.1'

In [210]:
data

,x,y,cell_number,dt_placement,NUTS2_ID,year,month,ndvi,ndmi,ndwi,ndbi,ndvi_mean,ndmi_mean,ndwi_mean,ndbi_mean,ndvi_std,ndmi_std,ndwi_std,ndbi_std,lst_day,lst_night,rainfall,day,lst_day_jan_mean,lst_night_jan_mean,lst_day_feb_mean,lst_night_feb_mean,lst_day_mar_mean,lst_night_mar_mean,lst_day_apr_mean,lst_night_apr_mean,acc_rainfall_1week,acc_rainfall_2week,acc_rainfall_month,acc_rainfall_jan
0,23.65882,41.33542,0,2025-01-01,EL51,2025,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13893.0,13684.0,0.00,1,13864.935484,13732.064516,13718.714286,13448.535714,14232.535714,13851.206897,14335.652174,13977.26087,0.000000,0.000000,0.000000,0.000000
1,23.65882,41.33542,0,2025-01-02,EL51,2025,1,0.078916,0.146433,0.098425,-0.146433,0.183488,0.070950,-0.082637,-0.070950,0.087655,0.112251,0.138840,0.112251,13803.0,13667.0,0.00,2,13864.935484,13732.064516,13718.714286,13448.535714,14232.535714,13851.206897,14335.652174,13977.26087,0.000000,0.000000,0.000000,0.000000
2,23.65882,41.33542,0,2025-01-03,EL51,2025,1,0.078916,0.146433,0.098425,-0.146433,0.183488,0.070950,-0.082637,-0.070950,0.087655,0.112251,0.138840,0.112251,13803.0,13667.0,6.45,3,13864.935484,13732.064516,13718.714286,13448.535714,14232.535714,13851.206897,14335.652174,13977.26087,6.450000,6.450000,6.450000,6.450000
3,23.65882,41.33542,0,2025-01-04,EL51,2025,1,0.078916,0.146433,0.098425,-0.146433,0.183488,0.070950,-0.082637,-0.070950,0.087655,0.112251,0.138840,0.112251,13803.0,13546.0,4.76,4,13864.935484,13732.064516,13718.714286,13448.535714,14232.535714,13851.206897,14335.652174,13977.26087,11.210000,11.210000,11.210000,11.210000
4,23.65882,41.33542,0,2025-01-05,EL51,2025,1,0.078916,0.146433,0.098425,-0.146433,0.183488,0.070950,-0.082637,-0.070950,0.087655,0.112251,0.138840,0.112251,13803.0,13649.0,2.02,5,13864.935484,13732.064516,13718.714286,13448.535714,14232.535714,13851.206897,14335.652174,13977.26087,13.230000,13.230000,13.230000,13.230000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
395181,26.60756,41.40729,3265,2025-04-27,EL51,2025,4,0.673457,0.405805,-0.278192,-0.405805,0.581224,0.303862,-0.286841,-0.303862,0.083491,0.094515,0.021567,0.094515,15026.0,14163.0,0.00,27,14100.551724,13825.290323,13973.440000,13530.678571,14492.000000,13844.551724,14692.666667,14029.26087,0.313529,0.602941,41.940587,192.024701
395182,26.60756,41.40729,3265,2025-04-28,EL51,2025,4,0.673457,0.405805,-0.278192,-0.405805,0.581224,0.303862,-0.286841,-0.303862,0.083491,0.094515,0.021567,0.094515,NaN,NaN,0.00,28,14100.551724,13825.290323,13973.440000,13530.678571,14492.000000,13844.551724,14692.666667,14029.26087,0.313529,0.602941,41.940587,192.024701
395183,26.60756,41.40729,3265,2025-04-29,EL51,2025,4,0.673457,0.405805,-0.278192,-0.405805,0.581224,0.303862,-0.286841,-0.303862,0.083491,0.094515,0.021567,0.094515,NaN,NaN,0.00,29,14100.551724,13825.290323,13973.440000,13530.678571,14492.000000,13844.551724,14692.666667,14029.26087,0.313529,0.602941,41.940587,192.024701
395184,26.60756,41.40729,3265,2025-04-30,EL51,2025,4,0.673457,0.405805,-0.278192,-0.405805,0.581224,0.303862,-0.286841,-0.303862,0.083491,0.094515,0.021567,0.094515,NaN,NaN,0.00,30,14100.551724,13825.290323,13973.440000,13530.678571,14492.000000,13844.551724,14692.666667,14029.26087,0.313529,0.313529,41.940587,192.024701
395185,26.60756,41.40729,3265,2025-05-01,EL51,2025,5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,14100.551724,13825.290323,13973.440000,13530.678571,14492.000000,13844.551724,14692.666667,14029.26087,0.313529,0.313529,34.198823,192.024701

In [211]:
greece_grid = gpd.GeoDataFrame(data, geometry=gpd.points_from_xy(data.x, data.y), crs='EPSG:4326')

greece_grid.head()

,x,y,cell_number,dt_placement,NUTS2_ID,year,month,ndvi,ndmi,ndwi,ndbi,ndvi_mean,ndmi_mean,ndwi_mean,ndbi_mean,ndvi_std,ndmi_std,ndwi_std,ndbi_std,lst_day,lst_night,rainfall,day,lst_day_jan_mean,lst_night_jan_mean,lst_day_feb_mean,lst_night_feb_mean,lst_day_mar_mean,lst_night_mar_mean,lst_day_apr_mean,lst_night_apr_mean,acc_rainfall_1week,acc_rainfall_2week,acc_rainfall_month,acc_rainfall_jan,geometry
0,23.65882,41.33542,0,2025-01-01,EL51,2025,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13893.0,13684.0,0.00,1,13864.935484,13732.064516,13718.714286,13448.535714,14232.535714,13851.206897,14335.652174,13977.26087,0.00,0.00,0.00,0.00,POINT (23.65882 41.33542)
1,23.65882,41.33542,0,2025-01-02,EL51,2025,1,0.078916,0.146433,0.098425,-0.146433,0.183488,0.07095,-0.082637,-0.07095,0.087655,0.112251,0.13884,0.112251,13803.0,13667.0,0.00,2,13864.935484,13732.064516,13718.714286,13448.535714,14232.535714,13851.206897,14335.652174,13977.26087,0.00,0.00,0.00,0.00,POINT (23.65882 41.33542)
2,23.65882,41.33542,0,2025-01-03,EL51,2025,1,0.078916,0.146433,0.098425,-0.146433,0.183488,0.07095,-0.082637,-0.07095,0.087655,0.112251,0.13884,0.112251,13803.0,13667.0,6.45,3,13864.935484,13732.064516,13718.714286,13448.535714,14232.535714,13851.206897,14335.652174,13977.26087,6.45,6.45,6.45,6.45,POINT (23.65882 41.33542)
3,23.65882,41.33542,0,2025-01-04,EL51,2025,1,0.078916,0.146433,0.098425,-0.146433,0.183488,0.07095,-0.082637,-0.07095,0.087655,0.112251,0.13884,0.112251,13803.0,13546.0,4.76,4,13864.935484,13732.064516,13718.714286,13448.535714,14232.535714,13851.206897,14335.652174,13977.26087,11.21,11.21,11.21,11.21,POINT (23.65882 41.33542)
4,23.65882,41.33542,0,2025-01-05,EL51,2025,1,0.078916,0.146433,0.098425,-0.146433,0.183488,0.07095,-0.082637,-0.07095,0.087655,0.112251,0.13884,0.112251,13803.0,13649.0,2.02,5,13864.935484,13732.064516,13718.714286,13448.535714,14232.535714,13851.206897,14335.652174,13977.26087,13.23,13.23,13.23,13.23,POINT (23.65882 41.33542)

In [212]:
greece_nuts3 = greece_nuts3.to_crs(epsg=4326)
greece_lau1 = greece_lau1.to_crs(epsg=4326)
greece_grid = greece_grid.to_crs(epsg=4326)

In [213]:
greece_lau1.drop(columns=['KWD_YPES'], inplace = True)
greece_lau1.drop(greece_lau1[greece_lau1['NAME'] == 'Άθως'].index, inplace = True)
greece_lau1.rename(columns={"NAME": "LAU1_NAME", "geometry": "lau1_geom"}, inplace = True)
greece_lau1.set_geometry("lau1_geom", inplace = True)
greece_lau1['lau1_centroid'] = greece_lau1['lau1_geom'].centroid
greece_lau1['lau1_rpoint'] = greece_lau1['lau1_geom'].representative_point()
greece_lau1.reset_index(drop=True, inplace=True)

greece_nuts3.rename(columns={"geometry": "nuts3_geom"}, inplace = True)
greece_nuts3.set_geometry("nuts3_geom", inplace = True)

C:\Users\dimit\AppData\Local\Temp\ipykernel_154136\2894926608.py:5: UserWarning: Geometry is in a geographic CRS. Results from 'centroid' are likely incorrect. Use 'GeoSeries.to_crs()' to re-project geometries to a projected CRS before this operation.

  greece_lau1['lau1_centroid'] = greece_lau1['lau1_geom'].centroid

In [214]:
print(f'greece_nuts3 CRS: {greece_nuts3.crs}')
print(f'greece_lau1 CRS: {greece_lau1.crs}')
print(f'greece_grid CRS: {greece_grid.crs}')

greece_nuts3 CRS: EPSG:4326
greece_lau1 CRS: EPSG:4326
greece_grid CRS: EPSG:4326

In [215]:
greece_lau1.set_geometry("lau1_rpoint", inplace = True)
greece_nuts3 = greece_nuts3.to_crs(epsg=4326)
greece_lau1 = greece_lau1.to_crs(epsg=4326)

greece_gdf = greece_lau1.sjoin(greece_nuts3, predicate="within", how = "left")
greece_gdf.head()

,LAU1_NAME,lau1_geom,lau1_centroid,lau1_rpoint,index_right,CNTR_CODE,CNTR_NAME,NUTS1_ID,NUTS1_LATN,NUTS1_NAME,NUTS2_ID,NUTS2_LATN,NUTS2_NAME,NUTS3_ID,NUTS3_LATN,NUTS3_NAME,MOUNT_TYPE,URBN_TYPE,COAST_TYPE
0,Αμυνταίου,"POLYGON ((21.70746 40.85172, 21.70955 40.85119...",POINT (21.63479 40.67528),POINT (21.67171 40.68676),30,EL,Greece,EL5,Voreia Elláda,Βόρεια Ελλάδα,EL53,Dytiki Makedonia,Δυτική Μακεδονία,EL533,Florina,Φλώρινα,3.0,3,3
1,Άκτιου - Βόνιτσας,"MULTIPOLYGON (((20.79456 38.75371, 20.79456 38...",POINT (20.95158 38.82289),POINT (20.93655 38.81891),41,EL,Greece,EL6,Kentriki Elláda,Κεντρική Ελλάδα,EL63,Dytiki Elláda,Δυτική Ελλάδα,EL631,Aitoloakarnania,Αιτωλοακαρνανία,2.0,3,1
2,Άνδρου,"MULTIPOLYGON (((24.95917 37.69039, 24.95897 37...",POINT (24.84814 37.85801),POINT (24.86216 37.84094),11,EL,Greece,EL4,"Nisia Aigaiou, Kriti","Νησιά Αιγαίου, Κρήτη",EL42,Notio Aigaio,Νότιο Αιγαίο,EL422,"Andros, Thira, Kea, Milos, Mykonos, Naxos, Par...","Άνδρος, Θήρα, Κέα, Μήλος, Μύκονος, Νάξος, Πάρο...",2.0,3,1
3,Άργους - Μυκηνών,"POLYGON ((22.52084 37.83857, 22.52111 37.83829...",POINT (22.62532 37.66339),POINT (22.62833 37.65584),49,EL,Greece,EL6,Kentriki Elláda,Κεντρική Ελλάδα,EL65,Peloponnisos,Πελοπόννησος,EL651,"Argolida, Arkadia","Αργολίδα, Αρκαδία",3.0,3,1
4,Έδεσσας,"POLYGON ((21.99535 40.90380, 21.99562 40.90344...",POINT (21.92931 40.79799),POINT (21.93215 40.79303),24,EL,Greece,EL5,Voreia Elláda,Βόρεια Ελλάδα,EL52,Kentriki Makedonia,Κεντρική Μακεδονία,EL524,Pella,Πέλλα,2.0,3,2

In [216]:
greece_gdf.drop(columns = ['lau1_centroid',	'lau1_rpoint', 'index_right', 'CNTR_CODE', 'CNTR_NAME', 'NUTS1_LATN', 'NUTS2_LATN', 'NUTS3_LATN'], inplace = True)

In [217]:
greece_gdf.set_geometry('lau1_geom', inplace = True)
greece_grid.set_geometry('geometry', inplace = True)

In [218]:
greece_gdf = greece_gdf.to_crs(epsg=4326)
greece_grid = greece_grid.to_crs(epsg=4326)

In [219]:
greece_gdf_sub = greece_gdf[greece_gdf['NUTS2_ID'] == NUTS2_ID].copy()
greece_gdf_sub.reset_index(drop=True, inplace=True)

In [220]:
greece_grid.head()

,x,y,cell_number,dt_placement,NUTS2_ID,year,month,ndvi,ndmi,ndwi,ndbi,ndvi_mean,ndmi_mean,ndwi_mean,ndbi_mean,ndvi_std,ndmi_std,ndwi_std,ndbi_std,lst_day,lst_night,rainfall,day,lst_day_jan_mean,lst_night_jan_mean,lst_day_feb_mean,lst_night_feb_mean,lst_day_mar_mean,lst_night_mar_mean,lst_day_apr_mean,lst_night_apr_mean,acc_rainfall_1week,acc_rainfall_2week,acc_rainfall_month,acc_rainfall_jan,geometry
0,23.65882,41.33542,0,2025-01-01,EL51,2025,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13893.0,13684.0,0.00,1,13864.935484,13732.064516,13718.714286,13448.535714,14232.535714,13851.206897,14335.652174,13977.26087,0.00,0.00,0.00,0.00,POINT (23.65882 41.33542)
1,23.65882,41.33542,0,2025-01-02,EL51,2025,1,0.078916,0.146433,0.098425,-0.146433,0.183488,0.07095,-0.082637,-0.07095,0.087655,0.112251,0.13884,0.112251,13803.0,13667.0,0.00,2,13864.935484,13732.064516,13718.714286,13448.535714,14232.535714,13851.206897,14335.652174,13977.26087,0.00,0.00,0.00,0.00,POINT (23.65882 41.33542)
2,23.65882,41.33542,0,2025-01-03,EL51,2025,1,0.078916,0.146433,0.098425,-0.146433,0.183488,0.07095,-0.082637,-0.07095,0.087655,0.112251,0.13884,0.112251,13803.0,13667.0,6.45,3,13864.935484,13732.064516,13718.714286,13448.535714,14232.535714,13851.206897,14335.652174,13977.26087,6.45,6.45,6.45,6.45,POINT (23.65882 41.33542)
3,23.65882,41.33542,0,2025-01-04,EL51,2025,1,0.078916,0.146433,0.098425,-0.146433,0.183488,0.07095,-0.082637,-0.07095,0.087655,0.112251,0.13884,0.112251,13803.0,13546.0,4.76,4,13864.935484,13732.064516,13718.714286,13448.535714,14232.535714,13851.206897,14335.652174,13977.26087,11.21,11.21,11.21,11.21,POINT (23.65882 41.33542)
4,23.65882,41.33542,0,2025-01-05,EL51,2025,1,0.078916,0.146433,0.098425,-0.146433,0.183488,0.07095,-0.082637,-0.07095,0.087655,0.112251,0.13884,0.112251,13803.0,13649.0,2.02,5,13864.935484,13732.064516,13718.714286,13448.535714,14232.535714,13851.206897,14335.652174,13977.26087,13.23,13.23,13.23,13.23,POINT (23.65882 41.33542)

In [221]:
greece_gdf_sub.head()

,LAU1_NAME,lau1_geom,NUTS1_ID,NUTS1_NAME,NUTS2_ID,NUTS2_NAME,NUTS3_ID,NUTS3_NAME,MOUNT_TYPE,URBN_TYPE,COAST_TYPE
0,Αβδήρων,"MULTIPOLYGON (((25.11115 41.00509, 25.11129 41...",EL5,Βόρεια Ελλάδα,EL51,"Aνατολική Μακεδονία, Θράκη",EL512,Ξάνθη,2.0,2,1
1,Αλεξανδρούπολης,"MULTIPOLYGON (((26.02534 40.77036, 26.02556 40...",EL5,Βόρεια Ελλάδα,EL51,"Aνατολική Μακεδονία, Θράκη",EL511,Έβρος,4.0,2,1
2,Αρριανών,"POLYGON ((25.84128 41.33854, 25.84157 41.33852...",EL5,Βόρεια Ελλάδα,EL51,"Aνατολική Μακεδονία, Θράκη",EL513,Ροδόπη,2.0,3,1
3,Διδυμοτείχου,"POLYGON ((26.33233 41.51492, 26.33276 41.51469...",EL5,Βόρεια Ελλάδα,EL51,"Aνατολική Μακεδονία, Θράκη",EL511,Έβρος,4.0,2,1
4,Δοξάτου,"POLYGON ((24.33347 41.14739, 24.33534 41.14657...",EL5,Βόρεια Ελλάδα,EL51,"Aνατολική Μακεδονία, Θράκη",EL514,Δράμα,2.0,2,2

In [222]:
cm_grid = greece_grid.sjoin_nearest(greece_gdf, how='left', max_distance=0.01, distance_col='dist')

c:\Users\dimit\Python Virtual Environments\noa_eywa\Lib\site-packages\geopandas\array.py:365: UserWarning: Geometry is in a geographic CRS. Results from 'sjoin_nearest' are likely incorrect. Use 'GeoSeries.to_crs()' to re-project geometries to a projected CRS before this operation.

  warnings.warn(

In [223]:
cm_grid.head()

,x,y,cell_number,dt_placement,NUTS2_ID_left,year,month,ndvi,ndmi,ndwi,ndbi,ndvi_mean,ndmi_mean,ndwi_mean,ndbi_mean,ndvi_std,ndmi_std,ndwi_std,ndbi_std,lst_day,lst_night,rainfall,day,lst_day_jan_mean,lst_night_jan_mean,lst_day_feb_mean,lst_night_feb_mean,lst_day_mar_mean,lst_night_mar_mean,lst_day_apr_mean,lst_night_apr_mean,acc_rainfall_1week,acc_rainfall_2week,acc_rainfall_month,acc_rainfall_jan,geometry,index_right,LAU1_NAME,NUTS1_ID,NUTS1_NAME,NUTS2_ID_right,NUTS2_NAME,NUTS3_ID,NUTS3_NAME,MOUNT_TYPE,URBN_TYPE,COAST_TYPE,dist
0,23.65882,41.33542,0,2025-01-01,EL51,2025,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13893.0,13684.0,0.00,1,13864.935484,13732.064516,13718.714286,13448.535714,14232.535714,13851.206897,14335.652174,13977.26087,0.00,0.00,0.00,0.00,POINT (23.65882 41.33542),129,Κάτω Νευροκοπίου,EL5,Βόρεια Ελλάδα,EL51,"Aνατολική Μακεδονία, Θράκη",EL514,Δράμα,2.0,2,2,0.0
1,23.65882,41.33542,0,2025-01-02,EL51,2025,1,0.078916,0.146433,0.098425,-0.146433,0.183488,0.07095,-0.082637,-0.07095,0.087655,0.112251,0.13884,0.112251,13803.0,13667.0,0.00,2,13864.935484,13732.064516,13718.714286,13448.535714,14232.535714,13851.206897,14335.652174,13977.26087,0.00,0.00,0.00,0.00,POINT (23.65882 41.33542),129,Κάτω Νευροκοπίου,EL5,Βόρεια Ελλάδα,EL51,"Aνατολική Μακεδονία, Θράκη",EL514,Δράμα,2.0,2,2,0.0
2,23.65882,41.33542,0,2025-01-03,EL51,2025,1,0.078916,0.146433,0.098425,-0.146433,0.183488,0.07095,-0.082637,-0.07095,0.087655,0.112251,0.13884,0.112251,13803.0,13667.0,6.45,3,13864.935484,13732.064516,13718.714286,13448.535714,14232.535714,13851.206897,14335.652174,13977.26087,6.45,6.45,6.45,6.45,POINT (23.65882 41.33542),129,Κάτω Νευροκοπίου,EL5,Βόρεια Ελλάδα,EL51,"Aνατολική Μακεδονία, Θράκη",EL514,Δράμα,2.0,2,2,0.0
3,23.65882,41.33542,0,2025-01-04,EL51,2025,1,0.078916,0.146433,0.098425,-0.146433,0.183488,0.07095,-0.082637,-0.07095,0.087655,0.112251,0.13884,0.112251,13803.0,13546.0,4.76,4,13864.935484,13732.064516,13718.714286,13448.535714,14232.535714,13851.206897,14335.652174,13977.26087,11.21,11.21,11.21,11.21,POINT (23.65882 41.33542),129,Κάτω Νευροκοπίου,EL5,Βόρεια Ελλάδα,EL51,"Aνατολική Μακεδονία, Θράκη",EL514,Δράμα,2.0,2,2,0.0
4,23.65882,41.33542,0,2025-01-05,EL51,2025,1,0.078916,0.146433,0.098425,-0.146433,0.183488,0.07095,-0.082637,-0.07095,0.087655,0.112251,0.13884,0.112251,13803.0,13649.0,2.02,5,13864.935484,13732.064516,13718.714286,13448.535714,14232.535714,13851.206897,14335.652174,13977.26087,13.23,13.23,13.23,13.23,POINT (23.65882 41.33542),129,Κάτω Νευροκοπίου,EL5,Βόρεια Ελλάδα,EL51,"Aνατολική Μακεδονία, Θράκη",EL514,Δράμα,2.0,2,2,0.0

In [224]:
describe_dataframe(cm_grid, remove_zeros=True)

                Column  Missing
7                 ndvi  39.5895
8                 ndmi  39.5895
9                 ndwi  39.5895
10                ndbi  39.5895
11           ndvi_mean  34.9200
12           ndmi_mean  34.9200
13           ndwi_mean  34.9200
14           ndbi_mean  34.9200
15            ndvi_std  34.9200
16            ndmi_std  34.9200
17            ndwi_std  34.9200
18            ndbi_std  34.9200
19             lst_day  13.3400
20           lst_night  13.3884
21            rainfall   0.8264
23    lst_day_jan_mean   3.9192
24  lst_night_jan_mean   3.9498
25    lst_day_feb_mean   3.9192
26  lst_night_feb_mean   3.9498
27    lst_day_mar_mean   3.9192
28  lst_night_mar_mean   3.9192
29    lst_day_apr_mean   3.9192
30  lst_night_apr_mean   3.9192

In [225]:
cm_grid.columns

Index(['x', 'y', 'cell_number', 'dt_placement', 'NUTS2_ID_left', 'year',
       'month', 'ndvi', 'ndmi', 'ndwi', 'ndbi', 'ndvi_mean', 'ndmi_mean',
       'ndwi_mean', 'ndbi_mean', 'ndvi_std', 'ndmi_std', 'ndwi_std',
       'ndbi_std', 'lst_day', 'lst_night', 'rainfall', 'day',
       'lst_day_jan_mean', 'lst_night_jan_mean', 'lst_day_feb_mean',
       'lst_night_feb_mean', 'lst_day_mar_mean', 'lst_night_mar_mean',
       'lst_day_apr_mean', 'lst_night_apr_mean', 'acc_rainfall_1week',
       'acc_rainfall_2week', 'acc_rainfall_month', 'acc_rainfall_jan',
       'geometry', 'index_right', 'LAU1_NAME', 'NUTS1_ID', 'NUTS1_NAME',
       'NUTS2_ID_right', 'NUTS2_NAME', 'NUTS3_ID', 'NUTS3_NAME', 'MOUNT_TYPE',
       'URBN_TYPE', 'COAST_TYPE', 'dist'],
      dtype='object')

In [226]:
cm_grid.rename(columns={'NUTS2_ID_left': 'NUTS2_ID'}, inplace=True)

In [227]:
new_order = ['x', 'y', 'cell_number', 'dt_placement','NUTS1_ID', 'NUTS1_NAME', 'NUTS2_ID', 'NUTS2_NAME', 'NUTS3_ID', 'NUTS3_NAME', 'LAU1_NAME', 'year', 'month',
             'ndvi', 'ndmi', 'ndwi', 'ndbi', 'ndvi_mean', 'ndmi_mean',
             'ndwi_mean', 'ndbi_mean', 'ndvi_std', 'ndmi_std', 'ndwi_std',
             'ndbi_std', 'lst_day', 'lst_night', 'rainfall', 'day',
             'lst_day_jan_mean', 'lst_night_jan_mean', 'lst_day_feb_mean',
             'lst_night_feb_mean', 'lst_day_mar_mean', 'lst_night_mar_mean',
             'lst_day_apr_mean', 'lst_night_apr_mean', 'acc_rainfall_1week',
             'acc_rainfall_2week', 'acc_rainfall_month', 'acc_rainfall_jan',
             'MOUNT_TYPE','URBN_TYPE', 'COAST_TYPE']

In [228]:
cm_grid = cm_grid[new_order]

In [229]:
cm_grid.head()

,x,y,cell_number,dt_placement,NUTS1_ID,NUTS1_NAME,NUTS2_ID,NUTS2_NAME,NUTS3_ID,NUTS3_NAME,LAU1_NAME,year,month,ndvi,ndmi,ndwi,ndbi,ndvi_mean,ndmi_mean,ndwi_mean,ndbi_mean,ndvi_std,ndmi_std,ndwi_std,ndbi_std,lst_day,lst_night,rainfall,day,lst_day_jan_mean,lst_night_jan_mean,lst_day_feb_mean,lst_night_feb_mean,lst_day_mar_mean,lst_night_mar_mean,lst_day_apr_mean,lst_night_apr_mean,acc_rainfall_1week,acc_rainfall_2week,acc_rainfall_month,acc_rainfall_jan,MOUNT_TYPE,URBN_TYPE,COAST_TYPE
0,23.65882,41.33542,0,2025-01-01,EL5,Βόρεια Ελλάδα,EL51,"Aνατολική Μακεδονία, Θράκη",EL514,Δράμα,Κάτω Νευροκοπίου,2025,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13893.0,13684.0,0.00,1,13864.935484,13732.064516,13718.714286,13448.535714,14232.535714,13851.206897,14335.652174,13977.26087,0.00,0.00,0.00,0.00,2.0,2,2
1,23.65882,41.33542,0,2025-01-02,EL5,Βόρεια Ελλάδα,EL51,"Aνατολική Μακεδονία, Θράκη",EL514,Δράμα,Κάτω Νευροκοπίου,2025,1,0.078916,0.146433,0.098425,-0.146433,0.183488,0.07095,-0.082637,-0.07095,0.087655,0.112251,0.13884,0.112251,13803.0,13667.0,0.00,2,13864.935484,13732.064516,13718.714286,13448.535714,14232.535714,13851.206897,14335.652174,13977.26087,0.00,0.00,0.00,0.00,2.0,2,2
2,23.65882,41.33542,0,2025-01-03,EL5,Βόρεια Ελλάδα,EL51,"Aνατολική Μακεδονία, Θράκη",EL514,Δράμα,Κάτω Νευροκοπίου,2025,1,0.078916,0.146433,0.098425,-0.146433,0.183488,0.07095,-0.082637,-0.07095,0.087655,0.112251,0.13884,0.112251,13803.0,13667.0,6.45,3,13864.935484,13732.064516,13718.714286,13448.535714,14232.535714,13851.206897,14335.652174,13977.26087,6.45,6.45,6.45,6.45,2.0,2,2
3,23.65882,41.33542,0,2025-01-04,EL5,Βόρεια Ελλάδα,EL51,"Aνατολική Μακεδονία, Θράκη",EL514,Δράμα,Κάτω Νευροκοπίου,2025,1,0.078916,0.146433,0.098425,-0.146433,0.183488,0.07095,-0.082637,-0.07095,0.087655,0.112251,0.13884,0.112251,13803.0,13546.0,4.76,4,13864.935484,13732.064516,13718.714286,13448.535714,14232.535714,13851.206897,14335.652174,13977.26087,11.21,11.21,11.21,11.21,2.0,2,2
4,23.65882,41.33542,0,2025-01-05,EL5,Βόρεια Ελλάδα,EL51,"Aνατολική Μακεδονία, Θράκη",EL514,Δράμα,Κάτω Νευροκοπίου,2025,1,0.078916,0.146433,0.098425,-0.146433,0.183488,0.07095,-0.082637,-0.07095,0.087655,0.112251,0.13884,0.112251,13803.0,13649.0,2.02,5,13864.935484,13732.064516,13718.714286,13448.535714,14232.535714,13851.206897,14335.652174,13977.26087,13.23,13.23,13.23,13.23,2.0,2,2

In [230]:
process_greek(cm_grid, 'NUTS1_NAME')
process_greek(cm_grid, 'NUTS2_NAME')
process_greek(cm_grid, 'NUTS3_NAME')
process_greek(cm_grid, 'LAU1_NAME')

In [231]:
cm_grid.head()

,x,y,cell_number,dt_placement,NUTS1_ID,NUTS1_NAME,NUTS2_ID,NUTS2_NAME,NUTS3_ID,NUTS3_NAME,LAU1_NAME,year,month,ndvi,ndmi,ndwi,ndbi,ndvi_mean,ndmi_mean,ndwi_mean,ndbi_mean,ndvi_std,ndmi_std,ndwi_std,ndbi_std,lst_day,lst_night,rainfall,day,lst_day_jan_mean,lst_night_jan_mean,lst_day_feb_mean,lst_night_feb_mean,lst_day_mar_mean,lst_night_mar_mean,lst_day_apr_mean,lst_night_apr_mean,acc_rainfall_1week,acc_rainfall_2week,acc_rainfall_month,acc_rainfall_jan,MOUNT_TYPE,URBN_TYPE,COAST_TYPE
0,23.65882,41.33542,0,2025-01-01,EL5,βορεια ελλαδα,EL51,"ανατολικη μακεδονια, θρακη",EL514,δραμα,κατω νευροκοπιου,2025,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13893.0,13684.0,0.00,1,13864.935484,13732.064516,13718.714286,13448.535714,14232.535714,13851.206897,14335.652174,13977.26087,0.00,0.00,0.00,0.00,2.0,2,2
1,23.65882,41.33542,0,2025-01-02,EL5,βορεια ελλαδα,EL51,"ανατολικη μακεδονια, θρακη",EL514,δραμα,κατω νευροκοπιου,2025,1,0.078916,0.146433,0.098425,-0.146433,0.183488,0.07095,-0.082637,-0.07095,0.087655,0.112251,0.13884,0.112251,13803.0,13667.0,0.00,2,13864.935484,13732.064516,13718.714286,13448.535714,14232.535714,13851.206897,14335.652174,13977.26087,0.00,0.00,0.00,0.00,2.0,2,2
2,23.65882,41.33542,0,2025-01-03,EL5,βορεια ελλαδα,EL51,"ανατολικη μακεδονια, θρακη",EL514,δραμα,κατω νευροκοπιου,2025,1,0.078916,0.146433,0.098425,-0.146433,0.183488,0.07095,-0.082637,-0.07095,0.087655,0.112251,0.13884,0.112251,13803.0,13667.0,6.45,3,13864.935484,13732.064516,13718.714286,13448.535714,14232.535714,13851.206897,14335.652174,13977.26087,6.45,6.45,6.45,6.45,2.0,2,2
3,23.65882,41.33542,0,2025-01-04,EL5,βορεια ελλαδα,EL51,"ανατολικη μακεδονια, θρακη",EL514,δραμα,κατω νευροκοπιου,2025,1,0.078916,0.146433,0.098425,-0.146433,0.183488,0.07095,-0.082637,-0.07095,0.087655,0.112251,0.13884,0.112251,13803.0,13546.0,4.76,4,13864.935484,13732.064516,13718.714286,13448.535714,14232.535714,13851.206897,14335.652174,13977.26087,11.21,11.21,11.21,11.21,2.0,2,2
4,23.65882,41.33542,0,2025-01-05,EL5,βορεια ελλαδα,EL51,"ανατολικη μακεδονια, θρακη",EL514,δραμα,κατω νευροκοπιου,2025,1,0.078916,0.146433,0.098425,-0.146433,0.183488,0.07095,-0.082637,-0.07095,0.087655,0.112251,0.13884,0.112251,13803.0,13649.0,2.02,5,13864.935484,13732.064516,13718.714286,13448.535714,14232.535714,13851.206897,14335.652174,13977.26087,13.23,13.23,13.23,13.23,2.0,2,2

In [232]:
cm_grid.to_csv(f'{base_folder}/{NUTS2}/GR_{NUTS2}_Timeline_GRID_{YEAR}_filled_mean_rain_shp.csv', encoding=enc, index = False)