In [59]:
import numpy as np
import pandas as pd
import geopandas as gpd
import sys

sys.path.insert(0, r"E:\Drive\NOA\MBD-Prediction\Modules")

from utils import describe_dataframe, process_greek

enc = 'utf-8'

pd.set_option('display.max_columns', None)

In [60]:
base_folder = 'E:/Drive/NOA/MBD-Prediction/Grid Level/data'

In [61]:
NUTS2 = 'Thessaly'
NUTS2_ID = 'EL61'
YEAR = 2024

In [62]:
data = pd.read_csv(f'{base_folder}/{NUTS2}/GR_{NUTS2}_Timeline_GRID_{YEAR}_filled_mean_rain.csv', encoding=enc)
greece_nuts3 = gpd.read_file(r"E:\Drive\NOA\MBD-Prediction\Europe Shapefiles\Greece\data\EL_Whole.shp",  encoding=enc)
greece_lau1 = gpd.read_file(r"E:\Drive\NOA\MBD-Prediction\Shapefiles\Greece Shapefiles\el_lau1.shp",  encoding=enc)

In [63]:
try:
    data.drop(columns=['Unnamed: 0'], inplace=True)
except Exception:
    print("No column named \'Unnamed: 0\'")

In [64]:
try:
    data.drop(columns=['rainfall.1'], inplace=True)
except Exception:
    print("No column named \'rainfall.1\'")

No column named 'rainfall.1'

In [65]:
data

,x,y,cell_number,dt_placement,NUTS2_ID,year,month,ndvi,ndmi,ndwi,ndbi,ndvi_mean,ndmi_mean,ndwi_mean,ndbi_mean,ndvi_std,ndmi_std,ndwi_std,ndbi_std,lst_day,lst_night,rainfall,day,lst_day_jan_mean,lst_night_jan_mean,lst_day_feb_mean,lst_night_feb_mean,lst_day_mar_mean,lst_night_mar_mean,lst_day_apr_mean,lst_night_apr_mean,acc_rainfall_1week,acc_rainfall_2week,acc_rainfall_month,acc_rainfall_jan
0,21.15549,39.67943,0,2024-01-01,EL61,2024,1,0.511748,0.258288,-0.470457,-0.258288,0.428874,0.342719,-0.366368,-0.342719,0.146795,0.096576,0.108932,0.096576,13844.0,13651.0,1.164514,1,13607.903226,13633.967742,13652.862069,13682.965517,13892.00000,13649.096774,14751.60,13889.96,1.164514,1.164514,1.164514,1.164514
1,21.15549,39.67943,0,2024-01-02,EL61,2024,1,0.511748,0.258288,-0.470457,-0.258288,0.428874,0.342719,-0.366368,-0.342719,0.146795,0.096576,0.108932,0.096576,13844.0,13651.0,11.846938,2,13607.903226,13633.967742,13652.862069,13682.965517,13892.00000,13649.096774,14751.60,13889.96,13.011452,13.011452,13.011452,13.011452
2,21.15549,39.67943,0,2024-01-03,EL61,2024,1,0.511748,0.258288,-0.470457,-0.258288,0.428874,0.342719,-0.366368,-0.342719,0.146795,0.096576,0.108932,0.096576,13844.0,13651.0,0.714449,3,13607.903226,13633.967742,13652.862069,13682.965517,13892.00000,13649.096774,14751.60,13889.96,13.725901,13.725901,13.725901,13.725901
3,21.15549,39.67943,0,2024-01-04,EL61,2024,1,0.511748,0.258288,-0.470457,-0.258288,0.428874,0.342719,-0.366368,-0.342719,0.146795,0.096576,0.108932,0.096576,13844.0,13724.0,0.000000,4,13607.903226,13633.967742,13652.862069,13682.965517,13892.00000,13649.096774,14751.60,13889.96,13.725901,13.725901,13.725901,13.725901
4,21.15549,39.67943,0,2024-01-05,EL61,2024,1,0.511748,0.258288,-0.470457,-0.258288,0.428874,0.342719,-0.366368,-0.342719,0.146795,0.096576,0.108932,0.096576,13863.0,13643.0,0.250432,5,13607.903226,13633.967742,13652.862069,13682.965517,13892.00000,13649.096774,14751.60,13889.96,13.976333,13.976333,13.976333,13.976333
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495409,24.06721,39.33807,3237,2024-05-28,EL61,2024,5,0.436893,0.030013,-0.412045,-0.030013,0.363871,0.042370,-0.291696,-0.042370,0.148894,0.086673,0.207093,0.086673,15049.0,14578.0,0.000000,28,14348.516129,14093.677419,14380.137931,14210.344828,14438.16129,14177.741935,14678.76,14356.84,0.471549,27.405561,90.684940,746.164222
495410,24.06721,39.33807,3237,2024-05-29,EL61,2024,5,0.286225,0.060863,-0.228535,-0.060863,0.226291,0.081376,-0.121595,-0.081376,0.105870,0.065469,0.154644,0.065469,15049.0,14578.0,0.000000,29,14348.516129,14093.677419,14380.137931,14210.344828,14438.16129,14177.741935,14678.76,14356.84,0.362378,27.405561,90.684940,746.164222
495411,24.06721,39.33807,3237,2024-05-30,EL61,2024,5,0.286225,0.060863,-0.228535,-0.060863,0.226291,0.081376,-0.121595,-0.081376,0.105870,0.065469,0.154644,0.065469,NaN,NaN,0.000000,30,14348.516129,14093.677419,14380.137931,14210.344828,14438.16129,14177.741935,14678.76,14356.84,0.362378,6.439345,90.684940,746.164222
495412,24.06721,39.33807,3237,2024-05-31,EL61,2024,5,0.286225,0.060863,-0.228535,-0.060863,0.226291,0.081376,-0.121595,-0.081376,0.105870,0.065469,0.154644,0.065469,NaN,NaN,0.000000,31,14348.516129,14093.677419,14380.137931,14210.344828,14438.16129,14177.741935,14678.76,14356.84,0.362378,6.232044,90.684940,746.164222
495413,24.06721,39.33807,3237,2024-06-01,EL61,2024,6,0.286225,0.060863,-0.228535,-0.060863,0.226291,0.081376,-0.121595,-0.081376,0.105870,0.065469,0.154644,0.065469,NaN,NaN,0.000000,1,14348.516129,14093.677419,14380.137931,14210.344828,14438.16129,14177.741935,14678.76,14356.84,0.000000,5.019704,90.684940,746.164222

In [66]:
greece_grid = gpd.GeoDataFrame(data, geometry=gpd.points_from_xy(data.x, data.y), crs='EPSG:4326')

greece_grid.head()

,x,y,cell_number,dt_placement,NUTS2_ID,year,month,ndvi,ndmi,ndwi,ndbi,ndvi_mean,ndmi_mean,ndwi_mean,ndbi_mean,ndvi_std,ndmi_std,ndwi_std,ndbi_std,lst_day,lst_night,rainfall,day,lst_day_jan_mean,lst_night_jan_mean,lst_day_feb_mean,lst_night_feb_mean,lst_day_mar_mean,lst_night_mar_mean,lst_day_apr_mean,lst_night_apr_mean,acc_rainfall_1week,acc_rainfall_2week,acc_rainfall_month,acc_rainfall_jan,geometry
0,21.15549,39.67943,0,2024-01-01,EL61,2024,1,0.511748,0.258288,-0.470457,-0.258288,0.428874,0.342719,-0.366368,-0.342719,0.146795,0.096576,0.108932,0.096576,13844.0,13651.0,1.164514,1,13607.903226,13633.967742,13652.862069,13682.965517,13892.0,13649.096774,14751.6,13889.96,1.164514,1.164514,1.164514,1.164514,POINT (21.15549 39.67943)
1,21.15549,39.67943,0,2024-01-02,EL61,2024,1,0.511748,0.258288,-0.470457,-0.258288,0.428874,0.342719,-0.366368,-0.342719,0.146795,0.096576,0.108932,0.096576,13844.0,13651.0,11.846938,2,13607.903226,13633.967742,13652.862069,13682.965517,13892.0,13649.096774,14751.6,13889.96,13.011452,13.011452,13.011452,13.011452,POINT (21.15549 39.67943)
2,21.15549,39.67943,0,2024-01-03,EL61,2024,1,0.511748,0.258288,-0.470457,-0.258288,0.428874,0.342719,-0.366368,-0.342719,0.146795,0.096576,0.108932,0.096576,13844.0,13651.0,0.714449,3,13607.903226,13633.967742,13652.862069,13682.965517,13892.0,13649.096774,14751.6,13889.96,13.725901,13.725901,13.725901,13.725901,POINT (21.15549 39.67943)
3,21.15549,39.67943,0,2024-01-04,EL61,2024,1,0.511748,0.258288,-0.470457,-0.258288,0.428874,0.342719,-0.366368,-0.342719,0.146795,0.096576,0.108932,0.096576,13844.0,13724.0,0.000000,4,13607.903226,13633.967742,13652.862069,13682.965517,13892.0,13649.096774,14751.6,13889.96,13.725901,13.725901,13.725901,13.725901,POINT (21.15549 39.67943)
4,21.15549,39.67943,0,2024-01-05,EL61,2024,1,0.511748,0.258288,-0.470457,-0.258288,0.428874,0.342719,-0.366368,-0.342719,0.146795,0.096576,0.108932,0.096576,13863.0,13643.0,0.250432,5,13607.903226,13633.967742,13652.862069,13682.965517,13892.0,13649.096774,14751.6,13889.96,13.976333,13.976333,13.976333,13.976333,POINT (21.15549 39.67943)

In [67]:
greece_nuts3 = greece_nuts3.to_crs(epsg=4326)
greece_lau1 = greece_lau1.to_crs(epsg=4326)
greece_grid = greece_grid.to_crs(epsg=4326)

In [68]:
greece_lau1.drop(columns=['KWD_YPES'], inplace = True)
greece_lau1.drop(greece_lau1[greece_lau1['NAME'] == 'Άθως'].index, inplace = True)
greece_lau1.rename(columns={"NAME": "LAU1_NAME", "geometry": "lau1_geom"}, inplace = True)
greece_lau1.set_geometry("lau1_geom", inplace = True)
greece_lau1['lau1_centroid'] = greece_lau1['lau1_geom'].centroid
greece_lau1['lau1_rpoint'] = greece_lau1['lau1_geom'].representative_point()
greece_lau1.reset_index(drop=True, inplace=True)

greece_nuts3.rename(columns={"geometry": "nuts3_geom"}, inplace = True)
greece_nuts3.set_geometry("nuts3_geom", inplace = True)

C:\Users\dimit\AppData\Local\Temp\ipykernel_15384\2894926608.py:5: UserWarning: Geometry is in a geographic CRS. Results from 'centroid' are likely incorrect. Use 'GeoSeries.to_crs()' to re-project geometries to a projected CRS before this operation.

  greece_lau1['lau1_centroid'] = greece_lau1['lau1_geom'].centroid

In [69]:
print(f'greece_nuts3 CRS: {greece_nuts3.crs}')
print(f'greece_lau1 CRS: {greece_lau1.crs}')
print(f'greece_grid CRS: {greece_grid.crs}')

greece_nuts3 CRS: EPSG:4326
greece_lau1 CRS: EPSG:4326
greece_grid CRS: EPSG:4326

In [70]:
greece_lau1.set_geometry("lau1_rpoint", inplace = True)
greece_nuts3 = greece_nuts3.to_crs(epsg=4326)
greece_lau1 = greece_lau1.to_crs(epsg=4326)

greece_gdf = greece_lau1.sjoin(greece_nuts3, predicate="within", how = "left")
greece_gdf.head()

,LAU1_NAME,lau1_geom,lau1_centroid,lau1_rpoint,index_right,CNTR_CODE,CNTR_NAME,NUTS1_ID,NUTS1_LATN,NUTS1_NAME,NUTS2_ID,NUTS2_LATN,NUTS2_NAME,NUTS3_ID,NUTS3_LATN,NUTS3_NAME,MOUNT_TYPE,URBN_TYPE,COAST_TYPE
0,Αμυνταίου,"POLYGON ((21.70746 40.85172, 21.70955 40.85119...",POINT (21.63479 40.67528),POINT (21.67171 40.68676),30,EL,Greece,EL5,Voreia Elláda,Βόρεια Ελλάδα,EL53,Dytiki Makedonia,Δυτική Μακεδονία,EL533,Florina,Φλώρινα,3.0,3,3
1,Άκτιου - Βόνιτσας,"MULTIPOLYGON (((20.79456 38.75371, 20.79456 38...",POINT (20.95158 38.82289),POINT (20.93655 38.81891),41,EL,Greece,EL6,Kentriki Elláda,Κεντρική Ελλάδα,EL63,Dytiki Elláda,Δυτική Ελλάδα,EL631,Aitoloakarnania,Αιτωλοακαρνανία,2.0,3,1
2,Άνδρου,"MULTIPOLYGON (((24.95917 37.69039, 24.95897 37...",POINT (24.84814 37.85801),POINT (24.86216 37.84094),11,EL,Greece,EL4,"Nisia Aigaiou, Kriti","Νησιά Αιγαίου, Κρήτη",EL42,Notio Aigaio,Νότιο Αιγαίο,EL422,"Andros, Thira, Kea, Milos, Mykonos, Naxos, Par...","Άνδρος, Θήρα, Κέα, Μήλος, Μύκονος, Νάξος, Πάρο...",2.0,3,1
3,Άργους - Μυκηνών,"POLYGON ((22.52084 37.83857, 22.52111 37.83829...",POINT (22.62532 37.66339),POINT (22.62833 37.65584),49,EL,Greece,EL6,Kentriki Elláda,Κεντρική Ελλάδα,EL65,Peloponnisos,Πελοπόννησος,EL651,"Argolida, Arkadia","Αργολίδα, Αρκαδία",3.0,3,1
4,Έδεσσας,"POLYGON ((21.99535 40.90380, 21.99562 40.90344...",POINT (21.92931 40.79799),POINT (21.93215 40.79303),24,EL,Greece,EL5,Voreia Elláda,Βόρεια Ελλάδα,EL52,Kentriki Makedonia,Κεντρική Μακεδονία,EL524,Pella,Πέλλα,2.0,3,2

In [71]:
greece_gdf.drop(columns = ['lau1_centroid',	'lau1_rpoint', 'index_right', 'CNTR_CODE', 'CNTR_NAME', 'NUTS1_LATN', 'NUTS2_LATN', 'NUTS3_LATN'], inplace = True)

In [72]:
greece_gdf.set_geometry('lau1_geom', inplace = True)
greece_grid.set_geometry('geometry', inplace = True)

In [73]:
greece_gdf = greece_gdf.to_crs(epsg=4326)
greece_grid = greece_grid.to_crs(epsg=4326)

In [74]:
greece_gdf_sub = greece_gdf[greece_gdf['NUTS2_ID'] == NUTS2_ID].copy()
greece_gdf_sub.reset_index(drop=True, inplace=True)

In [75]:
greece_grid.head()

,x,y,cell_number,dt_placement,NUTS2_ID,year,month,ndvi,ndmi,ndwi,ndbi,ndvi_mean,ndmi_mean,ndwi_mean,ndbi_mean,ndvi_std,ndmi_std,ndwi_std,ndbi_std,lst_day,lst_night,rainfall,day,lst_day_jan_mean,lst_night_jan_mean,lst_day_feb_mean,lst_night_feb_mean,lst_day_mar_mean,lst_night_mar_mean,lst_day_apr_mean,lst_night_apr_mean,acc_rainfall_1week,acc_rainfall_2week,acc_rainfall_month,acc_rainfall_jan,geometry
0,21.15549,39.67943,0,2024-01-01,EL61,2024,1,0.511748,0.258288,-0.470457,-0.258288,0.428874,0.342719,-0.366368,-0.342719,0.146795,0.096576,0.108932,0.096576,13844.0,13651.0,1.164514,1,13607.903226,13633.967742,13652.862069,13682.965517,13892.0,13649.096774,14751.6,13889.96,1.164514,1.164514,1.164514,1.164514,POINT (21.15549 39.67943)
1,21.15549,39.67943,0,2024-01-02,EL61,2024,1,0.511748,0.258288,-0.470457,-0.258288,0.428874,0.342719,-0.366368,-0.342719,0.146795,0.096576,0.108932,0.096576,13844.0,13651.0,11.846938,2,13607.903226,13633.967742,13652.862069,13682.965517,13892.0,13649.096774,14751.6,13889.96,13.011452,13.011452,13.011452,13.011452,POINT (21.15549 39.67943)
2,21.15549,39.67943,0,2024-01-03,EL61,2024,1,0.511748,0.258288,-0.470457,-0.258288,0.428874,0.342719,-0.366368,-0.342719,0.146795,0.096576,0.108932,0.096576,13844.0,13651.0,0.714449,3,13607.903226,13633.967742,13652.862069,13682.965517,13892.0,13649.096774,14751.6,13889.96,13.725901,13.725901,13.725901,13.725901,POINT (21.15549 39.67943)
3,21.15549,39.67943,0,2024-01-04,EL61,2024,1,0.511748,0.258288,-0.470457,-0.258288,0.428874,0.342719,-0.366368,-0.342719,0.146795,0.096576,0.108932,0.096576,13844.0,13724.0,0.000000,4,13607.903226,13633.967742,13652.862069,13682.965517,13892.0,13649.096774,14751.6,13889.96,13.725901,13.725901,13.725901,13.725901,POINT (21.15549 39.67943)
4,21.15549,39.67943,0,2024-01-05,EL61,2024,1,0.511748,0.258288,-0.470457,-0.258288,0.428874,0.342719,-0.366368,-0.342719,0.146795,0.096576,0.108932,0.096576,13863.0,13643.0,0.250432,5,13607.903226,13633.967742,13652.862069,13682.965517,13892.0,13649.096774,14751.6,13889.96,13.976333,13.976333,13.976333,13.976333,POINT (21.15549 39.67943)

In [76]:
greece_gdf_sub.head()

,LAU1_NAME,lau1_geom,NUTS1_ID,NUTS1_NAME,NUTS2_ID,NUTS2_NAME,NUTS3_ID,NUTS3_NAME,MOUNT_TYPE,URBN_TYPE,COAST_TYPE
0,Αγιάς,"MULTIPOLYGON (((22.89063 39.67169, 22.89056 39...",EL6,Κεντρική Ελλάδα,EL61,Θεσσαλία,EL612,Λάρισα,2.0,2,1
1,Αλοννήσου,"MULTIPOLYGON (((24.14310 39.34155, 24.14307 39...",EL6,Κεντρική Ελλάδα,EL61,Θεσσαλία,EL613,"Μαγνησία, Σποράδες",2.0,2,1
2,Αλμυρού,"MULTIPOLYGON (((23.06753 39.00526, 23.06740 39...",EL6,Κεντρική Ελλάδα,EL61,Θεσσαλία,EL613,"Μαγνησία, Σποράδες",2.0,2,1
3,Αργιθέας,"POLYGON ((21.43616 39.41522, 21.43830 39.41454...",EL6,Κεντρική Ελλάδα,EL61,Θεσσαλία,EL611,"Καρδίτσα, Τρίκαλα",2.0,3,3
4,Βόλου,"POLYGON ((22.97208 39.45655, 22.97346 39.45643...",EL6,Κεντρική Ελλάδα,EL61,Θεσσαλία,EL613,"Μαγνησία, Σποράδες",2.0,2,1

In [77]:
cm_grid = greece_grid.sjoin_nearest(greece_gdf, how='left', max_distance=0.01, distance_col='dist')

c:\Users\dimit\Python Virtual Environments\noa_eywa\Lib\site-packages\geopandas\array.py:365: UserWarning: Geometry is in a geographic CRS. Results from 'sjoin_nearest' are likely incorrect. Use 'GeoSeries.to_crs()' to re-project geometries to a projected CRS before this operation.

  warnings.warn(

In [78]:
cm_grid.head()

,x,y,cell_number,dt_placement,NUTS2_ID_left,year,month,ndvi,ndmi,ndwi,ndbi,ndvi_mean,ndmi_mean,ndwi_mean,ndbi_mean,ndvi_std,ndmi_std,ndwi_std,ndbi_std,lst_day,lst_night,rainfall,day,lst_day_jan_mean,lst_night_jan_mean,lst_day_feb_mean,lst_night_feb_mean,lst_day_mar_mean,lst_night_mar_mean,lst_day_apr_mean,lst_night_apr_mean,acc_rainfall_1week,acc_rainfall_2week,acc_rainfall_month,acc_rainfall_jan,geometry,index_right,LAU1_NAME,NUTS1_ID,NUTS1_NAME,NUTS2_ID_right,NUTS2_NAME,NUTS3_ID,NUTS3_NAME,MOUNT_TYPE,URBN_TYPE,COAST_TYPE,dist
0,21.15549,39.67943,0,2024-01-01,EL61,2024,1,0.511748,0.258288,-0.470457,-0.258288,0.428874,0.342719,-0.366368,-0.342719,0.146795,0.096576,0.108932,0.096576,13844.0,13651.0,1.164514,1,13607.903226,13633.967742,13652.862069,13682.965517,13892.0,13649.096774,14751.6,13889.96,1.164514,1.164514,1.164514,1.164514,POINT (21.15549 39.67943),137,Καλαμπάκας,EL6,Κεντρική Ελλάδα,EL61,Θεσσαλία,EL611,"Καρδίτσα, Τρίκαλα",2.0,3,3,0.0
1,21.15549,39.67943,0,2024-01-02,EL61,2024,1,0.511748,0.258288,-0.470457,-0.258288,0.428874,0.342719,-0.366368,-0.342719,0.146795,0.096576,0.108932,0.096576,13844.0,13651.0,11.846938,2,13607.903226,13633.967742,13652.862069,13682.965517,13892.0,13649.096774,14751.6,13889.96,13.011452,13.011452,13.011452,13.011452,POINT (21.15549 39.67943),137,Καλαμπάκας,EL6,Κεντρική Ελλάδα,EL61,Θεσσαλία,EL611,"Καρδίτσα, Τρίκαλα",2.0,3,3,0.0
2,21.15549,39.67943,0,2024-01-03,EL61,2024,1,0.511748,0.258288,-0.470457,-0.258288,0.428874,0.342719,-0.366368,-0.342719,0.146795,0.096576,0.108932,0.096576,13844.0,13651.0,0.714449,3,13607.903226,13633.967742,13652.862069,13682.965517,13892.0,13649.096774,14751.6,13889.96,13.725901,13.725901,13.725901,13.725901,POINT (21.15549 39.67943),137,Καλαμπάκας,EL6,Κεντρική Ελλάδα,EL61,Θεσσαλία,EL611,"Καρδίτσα, Τρίκαλα",2.0,3,3,0.0
3,21.15549,39.67943,0,2024-01-04,EL61,2024,1,0.511748,0.258288,-0.470457,-0.258288,0.428874,0.342719,-0.366368,-0.342719,0.146795,0.096576,0.108932,0.096576,13844.0,13724.0,0.000000,4,13607.903226,13633.967742,13652.862069,13682.965517,13892.0,13649.096774,14751.6,13889.96,13.725901,13.725901,13.725901,13.725901,POINT (21.15549 39.67943),137,Καλαμπάκας,EL6,Κεντρική Ελλάδα,EL61,Θεσσαλία,EL611,"Καρδίτσα, Τρίκαλα",2.0,3,3,0.0
4,21.15549,39.67943,0,2024-01-05,EL61,2024,1,0.511748,0.258288,-0.470457,-0.258288,0.428874,0.342719,-0.366368,-0.342719,0.146795,0.096576,0.108932,0.096576,13863.0,13643.0,0.250432,5,13607.903226,13633.967742,13652.862069,13682.965517,13892.0,13649.096774,14751.6,13889.96,13.976333,13.976333,13.976333,13.976333,POINT (21.15549 39.67943),137,Καλαμπάκας,EL6,Κεντρική Ελλάδα,EL61,Θεσσαλία,EL611,"Καρδίτσα, Τρίκαλα",2.0,3,3,0.0

In [79]:
describe_dataframe(cm_grid, remove_zeros=True)

       Column  Missing
7        ndvi   0.0277
8        ndmi   0.0277
9        ndwi   0.0277
10       ndbi   0.0277
11  ndvi_mean   0.0010
12  ndmi_mean   0.0010
13  ndwi_mean   0.0010
14  ndbi_mean   0.0057
15   ndvi_std   0.0010
16   ndmi_std   0.0010
17   ndwi_std   0.0010
18   ndbi_std   0.0057
19    lst_day   5.8824
20  lst_night   5.8828
21   rainfall   1.9608

In [80]:
cm_grid.columns

Index(['x', 'y', 'cell_number', 'dt_placement', 'NUTS2_ID_left', 'year',
       'month', 'ndvi', 'ndmi', 'ndwi', 'ndbi', 'ndvi_mean', 'ndmi_mean',
       'ndwi_mean', 'ndbi_mean', 'ndvi_std', 'ndmi_std', 'ndwi_std',
       'ndbi_std', 'lst_day', 'lst_night', 'rainfall', 'day',
       'lst_day_jan_mean', 'lst_night_jan_mean', 'lst_day_feb_mean',
       'lst_night_feb_mean', 'lst_day_mar_mean', 'lst_night_mar_mean',
       'lst_day_apr_mean', 'lst_night_apr_mean', 'acc_rainfall_1week',
       'acc_rainfall_2week', 'acc_rainfall_month', 'acc_rainfall_jan',
       'geometry', 'index_right', 'LAU1_NAME', 'NUTS1_ID', 'NUTS1_NAME',
       'NUTS2_ID_right', 'NUTS2_NAME', 'NUTS3_ID', 'NUTS3_NAME', 'MOUNT_TYPE',
       'URBN_TYPE', 'COAST_TYPE', 'dist'],
      dtype='object')

In [81]:
cm_grid.rename(columns={'NUTS2_ID_left': 'NUTS2_ID'}, inplace=True)

In [82]:
new_order = ['x', 'y', 'cell_number', 'dt_placement','NUTS1_ID', 'NUTS1_NAME', 'NUTS2_ID', 'NUTS2_NAME', 'NUTS3_ID', 'NUTS3_NAME', 'LAU1_NAME', 'year', 'month',
             'ndvi', 'ndmi', 'ndwi', 'ndbi', 'ndvi_mean', 'ndmi_mean',
             'ndwi_mean', 'ndbi_mean', 'ndvi_std', 'ndmi_std', 'ndwi_std',
             'ndbi_std', 'lst_day', 'lst_night', 'rainfall', 'day',
             'lst_day_jan_mean', 'lst_night_jan_mean', 'lst_day_feb_mean',
             'lst_night_feb_mean', 'lst_day_mar_mean', 'lst_night_mar_mean',
             'lst_day_apr_mean', 'lst_night_apr_mean', 'acc_rainfall_1week',
             'acc_rainfall_2week', 'acc_rainfall_month', 'acc_rainfall_jan',
             'MOUNT_TYPE','URBN_TYPE', 'COAST_TYPE']

In [83]:
cm_grid = cm_grid[new_order]

In [84]:
cm_grid.head()

,x,y,cell_number,dt_placement,NUTS1_ID,NUTS1_NAME,NUTS2_ID,NUTS2_NAME,NUTS3_ID,NUTS3_NAME,LAU1_NAME,year,month,ndvi,ndmi,ndwi,ndbi,ndvi_mean,ndmi_mean,ndwi_mean,ndbi_mean,ndvi_std,ndmi_std,ndwi_std,ndbi_std,lst_day,lst_night,rainfall,day,lst_day_jan_mean,lst_night_jan_mean,lst_day_feb_mean,lst_night_feb_mean,lst_day_mar_mean,lst_night_mar_mean,lst_day_apr_mean,lst_night_apr_mean,acc_rainfall_1week,acc_rainfall_2week,acc_rainfall_month,acc_rainfall_jan,MOUNT_TYPE,URBN_TYPE,COAST_TYPE
0,21.15549,39.67943,0,2024-01-01,EL6,Κεντρική Ελλάδα,EL61,Θεσσαλία,EL611,"Καρδίτσα, Τρίκαλα",Καλαμπάκας,2024,1,0.511748,0.258288,-0.470457,-0.258288,0.428874,0.342719,-0.366368,-0.342719,0.146795,0.096576,0.108932,0.096576,13844.0,13651.0,1.164514,1,13607.903226,13633.967742,13652.862069,13682.965517,13892.0,13649.096774,14751.6,13889.96,1.164514,1.164514,1.164514,1.164514,2.0,3,3
1,21.15549,39.67943,0,2024-01-02,EL6,Κεντρική Ελλάδα,EL61,Θεσσαλία,EL611,"Καρδίτσα, Τρίκαλα",Καλαμπάκας,2024,1,0.511748,0.258288,-0.470457,-0.258288,0.428874,0.342719,-0.366368,-0.342719,0.146795,0.096576,0.108932,0.096576,13844.0,13651.0,11.846938,2,13607.903226,13633.967742,13652.862069,13682.965517,13892.0,13649.096774,14751.6,13889.96,13.011452,13.011452,13.011452,13.011452,2.0,3,3
2,21.15549,39.67943,0,2024-01-03,EL6,Κεντρική Ελλάδα,EL61,Θεσσαλία,EL611,"Καρδίτσα, Τρίκαλα",Καλαμπάκας,2024,1,0.511748,0.258288,-0.470457,-0.258288,0.428874,0.342719,-0.366368,-0.342719,0.146795,0.096576,0.108932,0.096576,13844.0,13651.0,0.714449,3,13607.903226,13633.967742,13652.862069,13682.965517,13892.0,13649.096774,14751.6,13889.96,13.725901,13.725901,13.725901,13.725901,2.0,3,3
3,21.15549,39.67943,0,2024-01-04,EL6,Κεντρική Ελλάδα,EL61,Θεσσαλία,EL611,"Καρδίτσα, Τρίκαλα",Καλαμπάκας,2024,1,0.511748,0.258288,-0.470457,-0.258288,0.428874,0.342719,-0.366368,-0.342719,0.146795,0.096576,0.108932,0.096576,13844.0,13724.0,0.000000,4,13607.903226,13633.967742,13652.862069,13682.965517,13892.0,13649.096774,14751.6,13889.96,13.725901,13.725901,13.725901,13.725901,2.0,3,3
4,21.15549,39.67943,0,2024-01-05,EL6,Κεντρική Ελλάδα,EL61,Θεσσαλία,EL611,"Καρδίτσα, Τρίκαλα",Καλαμπάκας,2024,1,0.511748,0.258288,-0.470457,-0.258288,0.428874,0.342719,-0.366368,-0.342719,0.146795,0.096576,0.108932,0.096576,13863.0,13643.0,0.250432,5,13607.903226,13633.967742,13652.862069,13682.965517,13892.0,13649.096774,14751.6,13889.96,13.976333,13.976333,13.976333,13.976333,2.0,3,3

In [85]:
process_greek(cm_grid, 'NUTS1_NAME')
process_greek(cm_grid, 'NUTS2_NAME')
process_greek(cm_grid, 'NUTS3_NAME')
process_greek(cm_grid, 'LAU1_NAME')

In [86]:
cm_grid.head()

,x,y,cell_number,dt_placement,NUTS1_ID,NUTS1_NAME,NUTS2_ID,NUTS2_NAME,NUTS3_ID,NUTS3_NAME,LAU1_NAME,year,month,ndvi,ndmi,ndwi,ndbi,ndvi_mean,ndmi_mean,ndwi_mean,ndbi_mean,ndvi_std,ndmi_std,ndwi_std,ndbi_std,lst_day,lst_night,rainfall,day,lst_day_jan_mean,lst_night_jan_mean,lst_day_feb_mean,lst_night_feb_mean,lst_day_mar_mean,lst_night_mar_mean,lst_day_apr_mean,lst_night_apr_mean,acc_rainfall_1week,acc_rainfall_2week,acc_rainfall_month,acc_rainfall_jan,MOUNT_TYPE,URBN_TYPE,COAST_TYPE
0,21.15549,39.67943,0,2024-01-01,EL6,κεντρικη ελλαδα,EL61,θεσσαλια,EL611,"καρδιτσα, τρικαλα",καλαμπακας,2024,1,0.511748,0.258288,-0.470457,-0.258288,0.428874,0.342719,-0.366368,-0.342719,0.146795,0.096576,0.108932,0.096576,13844.0,13651.0,1.164514,1,13607.903226,13633.967742,13652.862069,13682.965517,13892.0,13649.096774,14751.6,13889.96,1.164514,1.164514,1.164514,1.164514,2.0,3,3
1,21.15549,39.67943,0,2024-01-02,EL6,κεντρικη ελλαδα,EL61,θεσσαλια,EL611,"καρδιτσα, τρικαλα",καλαμπακας,2024,1,0.511748,0.258288,-0.470457,-0.258288,0.428874,0.342719,-0.366368,-0.342719,0.146795,0.096576,0.108932,0.096576,13844.0,13651.0,11.846938,2,13607.903226,13633.967742,13652.862069,13682.965517,13892.0,13649.096774,14751.6,13889.96,13.011452,13.011452,13.011452,13.011452,2.0,3,3
2,21.15549,39.67943,0,2024-01-03,EL6,κεντρικη ελλαδα,EL61,θεσσαλια,EL611,"καρδιτσα, τρικαλα",καλαμπακας,2024,1,0.511748,0.258288,-0.470457,-0.258288,0.428874,0.342719,-0.366368,-0.342719,0.146795,0.096576,0.108932,0.096576,13844.0,13651.0,0.714449,3,13607.903226,13633.967742,13652.862069,13682.965517,13892.0,13649.096774,14751.6,13889.96,13.725901,13.725901,13.725901,13.725901,2.0,3,3
3,21.15549,39.67943,0,2024-01-04,EL6,κεντρικη ελλαδα,EL61,θεσσαλια,EL611,"καρδιτσα, τρικαλα",καλαμπακας,2024,1,0.511748,0.258288,-0.470457,-0.258288,0.428874,0.342719,-0.366368,-0.342719,0.146795,0.096576,0.108932,0.096576,13844.0,13724.0,0.000000,4,13607.903226,13633.967742,13652.862069,13682.965517,13892.0,13649.096774,14751.6,13889.96,13.725901,13.725901,13.725901,13.725901,2.0,3,3
4,21.15549,39.67943,0,2024-01-05,EL6,κεντρικη ελλαδα,EL61,θεσσαλια,EL611,"καρδιτσα, τρικαλα",καλαμπακας,2024,1,0.511748,0.258288,-0.470457,-0.258288,0.428874,0.342719,-0.366368,-0.342719,0.146795,0.096576,0.108932,0.096576,13863.0,13643.0,0.250432,5,13607.903226,13633.967742,13652.862069,13682.965517,13892.0,13649.096774,14751.6,13889.96,13.976333,13.976333,13.976333,13.976333,2.0,3,3

In [87]:
cm_grid.to_csv(f'{base_folder}/{NUTS2}/GR_{NUTS2}_Timeline_GRID_{YEAR}_filled_mean_rain_shp.csv', encoding=enc, index = False)