In [32]:
import numpy as np
import pandas as pd
import geopandas as gpd
import sys

sys.path.insert(0, r"E:\Drive\NOA\MBD-Prediction\Modules")

from utils import describe_dataframe, process_greek

enc = 'utf-8'

pd.set_option('display.max_columns', None)

In [33]:
base_folder = 'E:/Drive/NOA/MBD-Prediction/Grid Level/data/'

In [34]:
NUTS2 = 'Attica'
NUTS2_ID = 'EL30'
YEAR = 2010

In [35]:
data = pd.read_csv(f'{base_folder}/{NUTS2}/GR_{NUTS2}_Timeline_GRID_{YEAR}_filled_mean_rain.csv', encoding=enc)
greece_nuts3 = gpd.read_file(r"E:\Drive\NOA\MBD-Prediction\Europe NUTS - LAU Shapefiles\Greece\data\EL_Whole.shp",  encoding=enc)
greece_lau1 = gpd.read_file(r"E:\Drive\NOA\MBD-Prediction\Shapefiles\Greece Shapefiles\el_lau1.shp",  encoding=enc)

In [36]:
try:
    data.drop(columns=['Unnamed: 0'], inplace=True)
except Exception:
    print("No column named \'Unnamed: 0\'")

In [37]:
try:
    data.drop(columns=['rainfall.1'], inplace=True)
except Exception:
    print("No column named \'rainfall.1\'")

No column named 'rainfall.1'

In [38]:
data

,x,y,cell_number,dt_placement,NUTS2_ID,year,month,ndvi,ndmi,ndwi,ndbi,ndvi_mean,ndmi_mean,ndwi_mean,ndbi_mean,ndvi_std,ndmi_std,ndwi_std,ndbi_std,lst_day,lst_night,rainfall,day,lst_day_jan_mean,lst_night_jan_mean,lst_day_feb_mean,lst_night_feb_mean,lst_day_mar_mean,lst_night_mar_mean,lst_day_apr_mean,lst_night_apr_mean,acc_rainfall_1week,acc_rainfall_2week,acc_rainfall_month,acc_rainfall_jan
0,22.92536,36.22923,0,2010-01-01,EL30,2010,1,0.309830,0.076474,-0.221980,-0.076474,0.308048,0.100312,-0.172756,-0.100312,0.042085,0.035700,0.062498,0.035700,14531.0,14284.0,0.000000,1,14207.548387,14115.258065,14288.500000,14077.928571,14504.967742,14107.000000,14700.000000,14195.166667,0.000000,0.000000,0.000000,0.000000
1,22.92536,36.22923,0,2010-01-02,EL30,2010,1,0.309830,0.076474,-0.221980,-0.076474,0.308048,0.100312,-0.172756,-0.100312,0.042085,0.035700,0.062498,0.035700,14389.0,14284.0,0.000000,2,14207.548387,14115.258065,14288.500000,14077.928571,14504.967742,14107.000000,14700.000000,14195.166667,0.000000,0.000000,0.000000,0.000000
2,22.92536,36.22923,0,2010-01-03,EL30,2010,1,0.309830,0.076474,-0.221980,-0.076474,0.308048,0.100312,-0.172756,-0.100312,0.042085,0.035700,0.062498,0.035700,14357.0,14284.0,0.000000,3,14207.548387,14115.258065,14288.500000,14077.928571,14504.967742,14107.000000,14700.000000,14195.166667,0.000000,0.000000,0.000000,0.000000
3,22.92536,36.22923,0,2010-01-04,EL30,2010,1,0.309830,0.076474,-0.221980,-0.076474,0.308048,0.100312,-0.172756,-0.100312,0.042085,0.035700,0.062498,0.035700,14177.0,14284.0,0.000000,4,14207.548387,14115.258065,14288.500000,14077.928571,14504.967742,14107.000000,14700.000000,14195.166667,0.000000,0.000000,0.000000,0.000000
4,22.92536,36.22923,0,2010-01-05,EL30,2010,1,0.309830,0.076474,-0.221980,-0.076474,0.308048,0.100312,-0.172756,-0.100312,0.042085,0.035700,0.062498,0.035700,14348.0,14168.0,0.000000,5,14207.548387,14115.258065,14288.500000,14077.928571,14504.967742,14107.000000,14700.000000,14195.166667,0.000000,0.000000,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
269000,24.05547,37.79233,736,2010-12-27,EL30,2010,12,0.115963,0.147067,0.104352,-0.147067,0.130821,0.186959,0.154038,-0.186959,0.020084,0.058858,0.087954,0.058858,14383.0,14298.0,33.033814,27,14290.290323,14125.096774,14355.857143,14034.892857,14624.483871,14170.290323,14890.633333,14231.900000,37.798668,82.315373,95.750807,941.565568
269001,24.05547,37.79233,736,2010-12-28,EL30,2010,12,0.115963,0.147067,0.104352,-0.147067,0.130821,0.186959,0.154038,-0.186959,0.020084,0.058858,0.087954,0.058858,14383.0,14298.0,14.201366,28,14290.290323,14125.096774,14355.857143,14034.892857,14624.483871,14170.290323,14890.633333,14231.900000,51.927618,96.481705,107.564426,955.766935
269002,24.05547,37.79233,736,2010-12-29,EL30,2010,12,0.115963,0.147067,0.104352,-0.147067,0.130821,0.186959,0.154038,-0.186959,0.020084,0.058858,0.087954,0.058858,14383.0,13770.0,0.008233,29,14290.290323,14125.096774,14355.857143,14034.892857,14624.483871,14170.290323,14890.633333,14231.900000,51.935852,88.305435,107.407619,955.775168
269003,24.05547,37.79233,736,2010-12-30,EL30,2010,12,0.115963,0.147067,0.104352,-0.147067,0.130821,0.186959,0.154038,-0.186959,0.020084,0.058858,0.087954,0.058858,14383.0,13770.0,0.000000,30,14290.290323,14125.096774,14355.857143,14034.892857,14624.483871,14170.290323,14890.633333,14231.900000,51.628884,59.422609,106.339525,955.775168
269004,24.05547,37.79233,736,2010-12-31,EL30,2010,12,0.115963,0.147067,0.104352,-0.147067,0.130821,0.186959,0.154038,-0.186959,0.020084,0.058858,0.087954,0.058858,14383.0,13770.0,0.000000,31,14290.290323,14125.096774,14355.857143,14034.892857,14624.483871,14170.290323,14890.633333,14231.900000,51.362086,59.406315,105.293872,955.775168

In [39]:
greece_grid = gpd.GeoDataFrame(data, geometry=gpd.points_from_xy(data.x, data.y), crs='EPSG:4326')

greece_grid.head()

,x,y,cell_number,dt_placement,NUTS2_ID,year,month,ndvi,ndmi,ndwi,ndbi,ndvi_mean,ndmi_mean,ndwi_mean,ndbi_mean,ndvi_std,ndmi_std,ndwi_std,ndbi_std,lst_day,lst_night,rainfall,day,lst_day_jan_mean,lst_night_jan_mean,lst_day_feb_mean,lst_night_feb_mean,lst_day_mar_mean,lst_night_mar_mean,lst_day_apr_mean,lst_night_apr_mean,acc_rainfall_1week,acc_rainfall_2week,acc_rainfall_month,acc_rainfall_jan,geometry
0,22.92536,36.22923,0,2010-01-01,EL30,2010,1,0.30983,0.076474,-0.22198,-0.076474,0.308048,0.100312,-0.172756,-0.100312,0.042085,0.0357,0.062498,0.0357,14531.0,14284.0,0.0,1,14207.548387,14115.258065,14288.5,14077.928571,14504.967742,14107.0,14700.0,14195.166667,0.0,0.0,0.0,0.0,POINT (22.92536 36.22923)
1,22.92536,36.22923,0,2010-01-02,EL30,2010,1,0.30983,0.076474,-0.22198,-0.076474,0.308048,0.100312,-0.172756,-0.100312,0.042085,0.0357,0.062498,0.0357,14389.0,14284.0,0.0,2,14207.548387,14115.258065,14288.5,14077.928571,14504.967742,14107.0,14700.0,14195.166667,0.0,0.0,0.0,0.0,POINT (22.92536 36.22923)
2,22.92536,36.22923,0,2010-01-03,EL30,2010,1,0.30983,0.076474,-0.22198,-0.076474,0.308048,0.100312,-0.172756,-0.100312,0.042085,0.0357,0.062498,0.0357,14357.0,14284.0,0.0,3,14207.548387,14115.258065,14288.5,14077.928571,14504.967742,14107.0,14700.0,14195.166667,0.0,0.0,0.0,0.0,POINT (22.92536 36.22923)
3,22.92536,36.22923,0,2010-01-04,EL30,2010,1,0.30983,0.076474,-0.22198,-0.076474,0.308048,0.100312,-0.172756,-0.100312,0.042085,0.0357,0.062498,0.0357,14177.0,14284.0,0.0,4,14207.548387,14115.258065,14288.5,14077.928571,14504.967742,14107.0,14700.0,14195.166667,0.0,0.0,0.0,0.0,POINT (22.92536 36.22923)
4,22.92536,36.22923,0,2010-01-05,EL30,2010,1,0.30983,0.076474,-0.22198,-0.076474,0.308048,0.100312,-0.172756,-0.100312,0.042085,0.0357,0.062498,0.0357,14348.0,14168.0,0.0,5,14207.548387,14115.258065,14288.5,14077.928571,14504.967742,14107.0,14700.0,14195.166667,0.0,0.0,0.0,0.0,POINT (22.92536 36.22923)

In [40]:
greece_nuts3 = greece_nuts3.to_crs(epsg=4326)
greece_lau1 = greece_lau1.to_crs(epsg=4326)
greece_grid = greece_grid.to_crs(epsg=4326)

In [41]:
greece_lau1.drop(columns=['KWD_YPES'], inplace = True)
greece_lau1.drop(greece_lau1[greece_lau1['NAME'] == 'Άθως'].index, inplace = True)
greece_lau1.rename(columns={"NAME": "LAU1_NAME", "geometry": "lau1_geom"}, inplace = True)
greece_lau1.set_geometry("lau1_geom", inplace = True)
greece_lau1['lau1_centroid'] = greece_lau1['lau1_geom'].centroid
greece_lau1['lau1_rpoint'] = greece_lau1['lau1_geom'].representative_point()
greece_lau1.reset_index(drop=True, inplace=True)

greece_nuts3.rename(columns={"geometry": "nuts3_geom"}, inplace = True)
greece_nuts3.set_geometry("nuts3_geom", inplace = True)

C:\Users\dimit\AppData\Local\Temp\ipykernel_12100\2894926608.py:5: UserWarning: Geometry is in a geographic CRS. Results from 'centroid' are likely incorrect. Use 'GeoSeries.to_crs()' to re-project geometries to a projected CRS before this operation.

  greece_lau1['lau1_centroid'] = greece_lau1['lau1_geom'].centroid

In [42]:
print(f'greece_nuts3 CRS: {greece_nuts3.crs}')
print(f'greece_lau1 CRS: {greece_lau1.crs}')
print(f'greece_grid CRS: {greece_grid.crs}')

greece_nuts3 CRS: EPSG:4326
greece_lau1 CRS: EPSG:4326
greece_grid CRS: EPSG:4326

In [43]:
greece_lau1.set_geometry("lau1_rpoint", inplace = True)
greece_nuts3 = greece_nuts3.to_crs(epsg=4326)
greece_lau1 = greece_lau1.to_crs(epsg=4326)

greece_gdf = greece_lau1.sjoin(greece_nuts3, predicate="within", how = "left")
greece_gdf.head()

,LAU1_NAME,lau1_geom,lau1_centroid,lau1_rpoint,index_right,CNTR_CODE,CNTR_NAME,NUTS1_ID,NUTS1_LATN,NUTS1_NAME,NUTS2_ID,NUTS2_LATN,NUTS2_NAME,NUTS3_ID,NUTS3_LATN,NUTS3_NAME,MOUNT_TYPE,URBN_TYPE,COAST_TYPE
0,Αμυνταίου,"POLYGON ((21.70746 40.85172, 21.70955 40.85119...",POINT (21.63479 40.67528),POINT (21.67171 40.68676),30,EL,Greece,EL5,Voreia Elláda,Βόρεια Ελλάδα,EL53,Dytiki Makedonia,Δυτική Μακεδονία,EL533,Florina,Φλώρινα,3.0,3,3
1,Άκτιου - Βόνιτσας,"MULTIPOLYGON (((20.79456 38.75371, 20.79456 38...",POINT (20.95158 38.82289),POINT (20.93655 38.81891),41,EL,Greece,EL6,Kentriki Elláda,Κεντρική Ελλάδα,EL63,Dytiki Elláda,Δυτική Ελλάδα,EL631,Aitoloakarnania,Αιτωλοακαρνανία,2.0,3,1
2,Άνδρου,"MULTIPOLYGON (((24.95917 37.69039, 24.95897 37...",POINT (24.84814 37.85801),POINT (24.86216 37.84094),11,EL,Greece,EL4,"Nisia Aigaiou, Kriti","Νησιά Αιγαίου, Κρήτη",EL42,Notio Aigaio,Νότιο Αιγαίο,EL422,"Andros, Thira, Kea, Milos, Mykonos, Naxos, Par...","Άνδρος, Θήρα, Κέα, Μήλος, Μύκονος, Νάξος, Πάρο...",2.0,3,1
3,Άργους - Μυκηνών,"POLYGON ((22.52084 37.83857, 22.52111 37.83829...",POINT (22.62532 37.66339),POINT (22.62833 37.65584),49,EL,Greece,EL6,Kentriki Elláda,Κεντρική Ελλάδα,EL65,Peloponnisos,Πελοπόννησος,EL651,"Argolida, Arkadia","Αργολίδα, Αρκαδία",3.0,3,1
4,Έδεσσας,"POLYGON ((21.99535 40.90380, 21.99562 40.90344...",POINT (21.92931 40.79799),POINT (21.93215 40.79303),24,EL,Greece,EL5,Voreia Elláda,Βόρεια Ελλάδα,EL52,Kentriki Makedonia,Κεντρική Μακεδονία,EL524,Pella,Πέλλα,2.0,3,2

In [44]:
greece_gdf.drop(columns = ['lau1_centroid',	'lau1_rpoint', 'index_right', 'CNTR_CODE', 'CNTR_NAME', 'NUTS1_LATN', 'NUTS2_LATN', 'NUTS3_LATN'], inplace = True)

In [45]:
greece_gdf.set_geometry('lau1_geom', inplace = True)
greece_grid.set_geometry('geometry', inplace = True)

In [46]:
greece_gdf = greece_gdf.to_crs(epsg=4326)
greece_grid = greece_grid.to_crs(epsg=4326)

In [47]:
greece_gdf_sub = greece_gdf[greece_gdf['NUTS2_ID'] == NUTS2_ID].copy()
greece_gdf_sub.reset_index(drop=True, inplace=True)

In [48]:
greece_grid.head()

,x,y,cell_number,dt_placement,NUTS2_ID,year,month,ndvi,ndmi,ndwi,ndbi,ndvi_mean,ndmi_mean,ndwi_mean,ndbi_mean,ndvi_std,ndmi_std,ndwi_std,ndbi_std,lst_day,lst_night,rainfall,day,lst_day_jan_mean,lst_night_jan_mean,lst_day_feb_mean,lst_night_feb_mean,lst_day_mar_mean,lst_night_mar_mean,lst_day_apr_mean,lst_night_apr_mean,acc_rainfall_1week,acc_rainfall_2week,acc_rainfall_month,acc_rainfall_jan,geometry
0,22.92536,36.22923,0,2010-01-01,EL30,2010,1,0.30983,0.076474,-0.22198,-0.076474,0.308048,0.100312,-0.172756,-0.100312,0.042085,0.0357,0.062498,0.0357,14531.0,14284.0,0.0,1,14207.548387,14115.258065,14288.5,14077.928571,14504.967742,14107.0,14700.0,14195.166667,0.0,0.0,0.0,0.0,POINT (22.92536 36.22923)
1,22.92536,36.22923,0,2010-01-02,EL30,2010,1,0.30983,0.076474,-0.22198,-0.076474,0.308048,0.100312,-0.172756,-0.100312,0.042085,0.0357,0.062498,0.0357,14389.0,14284.0,0.0,2,14207.548387,14115.258065,14288.5,14077.928571,14504.967742,14107.0,14700.0,14195.166667,0.0,0.0,0.0,0.0,POINT (22.92536 36.22923)
2,22.92536,36.22923,0,2010-01-03,EL30,2010,1,0.30983,0.076474,-0.22198,-0.076474,0.308048,0.100312,-0.172756,-0.100312,0.042085,0.0357,0.062498,0.0357,14357.0,14284.0,0.0,3,14207.548387,14115.258065,14288.5,14077.928571,14504.967742,14107.0,14700.0,14195.166667,0.0,0.0,0.0,0.0,POINT (22.92536 36.22923)
3,22.92536,36.22923,0,2010-01-04,EL30,2010,1,0.30983,0.076474,-0.22198,-0.076474,0.308048,0.100312,-0.172756,-0.100312,0.042085,0.0357,0.062498,0.0357,14177.0,14284.0,0.0,4,14207.548387,14115.258065,14288.5,14077.928571,14504.967742,14107.0,14700.0,14195.166667,0.0,0.0,0.0,0.0,POINT (22.92536 36.22923)
4,22.92536,36.22923,0,2010-01-05,EL30,2010,1,0.30983,0.076474,-0.22198,-0.076474,0.308048,0.100312,-0.172756,-0.100312,0.042085,0.0357,0.062498,0.0357,14348.0,14168.0,0.0,5,14207.548387,14115.258065,14288.5,14077.928571,14504.967742,14107.0,14700.0,14195.166667,0.0,0.0,0.0,0.0,POINT (22.92536 36.22923)

In [49]:
greece_gdf_sub.head()

,LAU1_NAME,lau1_geom,NUTS1_ID,NUTS1_NAME,NUTS2_ID,NUTS2_NAME,NUTS3_ID,NUTS3_NAME,MOUNT_TYPE,URBN_TYPE,COAST_TYPE
0,Ιλίου,"POLYGON ((23.68392 38.06429, 23.68763 38.06131...",EL3,Αττική,EL30,Aττική,EL302,Δυτικός Τομέας Αθηνών,4.0,1,1
1,Ύδρας,"MULTIPOLYGON (((23.40645 37.29497, 23.40642 37...",EL3,Αττική,EL30,Aττική,EL307,"Πειραιάς, Νήσοι",2.0,1,1
2,Αίγινας,"MULTIPOLYGON (((23.31935 37.80028, 23.31914 37...",EL3,Αττική,EL30,Aττική,EL307,"Πειραιάς, Νήσοι",2.0,1,1
3,Αγίας Βαρβάρας,"POLYGON ((23.64394 37.99855, 23.64396 37.99856...",EL3,Αττική,EL30,Aττική,EL302,Δυτικός Τομέας Αθηνών,4.0,1,1
4,Αγίας Παρασκευής,"POLYGON ((23.84009 38.02410, 23.84021 38.02408...",EL3,Αττική,EL30,Aττική,EL301,Βόρειος Τομέας Αθηνών,4.0,1,2

In [50]:
cm_grid = greece_grid.sjoin_nearest(greece_gdf, how='left', max_distance=0.01, distance_col='dist')

c:\Users\dimit\Python Virtual Environments\noa_eywa\Lib\site-packages\geopandas\array.py:365: UserWarning: Geometry is in a geographic CRS. Results from 'sjoin_nearest' are likely incorrect. Use 'GeoSeries.to_crs()' to re-project geometries to a projected CRS before this operation.

  warnings.warn(

In [51]:
cm_grid.head()

,x,y,cell_number,dt_placement,NUTS2_ID_left,year,month,ndvi,ndmi,ndwi,ndbi,ndvi_mean,ndmi_mean,ndwi_mean,ndbi_mean,ndvi_std,ndmi_std,ndwi_std,ndbi_std,lst_day,lst_night,rainfall,day,lst_day_jan_mean,lst_night_jan_mean,lst_day_feb_mean,lst_night_feb_mean,lst_day_mar_mean,lst_night_mar_mean,lst_day_apr_mean,lst_night_apr_mean,acc_rainfall_1week,acc_rainfall_2week,acc_rainfall_month,acc_rainfall_jan,geometry,index_right,LAU1_NAME,NUTS1_ID,NUTS1_NAME,NUTS2_ID_right,NUTS2_NAME,NUTS3_ID,NUTS3_NAME,MOUNT_TYPE,URBN_TYPE,COAST_TYPE,dist
0,22.92536,36.22923,0,2010-01-01,EL30,2010,1,0.30983,0.076474,-0.22198,-0.076474,0.308048,0.100312,-0.172756,-0.100312,0.042085,0.0357,0.062498,0.0357,14531.0,14284.0,0.0,1,14207.548387,14115.258065,14288.5,14077.928571,14504.967742,14107.0,14700.0,14195.166667,0.0,0.0,0.0,0.0,POINT (22.92536 36.22923),161,Κυθήρων,EL3,Αττική,EL30,Aττική,EL307,"Πειραιάς, Νήσοι",2.0,1,1,0.0
1,22.92536,36.22923,0,2010-01-02,EL30,2010,1,0.30983,0.076474,-0.22198,-0.076474,0.308048,0.100312,-0.172756,-0.100312,0.042085,0.0357,0.062498,0.0357,14389.0,14284.0,0.0,2,14207.548387,14115.258065,14288.5,14077.928571,14504.967742,14107.0,14700.0,14195.166667,0.0,0.0,0.0,0.0,POINT (22.92536 36.22923),161,Κυθήρων,EL3,Αττική,EL30,Aττική,EL307,"Πειραιάς, Νήσοι",2.0,1,1,0.0
2,22.92536,36.22923,0,2010-01-03,EL30,2010,1,0.30983,0.076474,-0.22198,-0.076474,0.308048,0.100312,-0.172756,-0.100312,0.042085,0.0357,0.062498,0.0357,14357.0,14284.0,0.0,3,14207.548387,14115.258065,14288.5,14077.928571,14504.967742,14107.0,14700.0,14195.166667,0.0,0.0,0.0,0.0,POINT (22.92536 36.22923),161,Κυθήρων,EL3,Αττική,EL30,Aττική,EL307,"Πειραιάς, Νήσοι",2.0,1,1,0.0
3,22.92536,36.22923,0,2010-01-04,EL30,2010,1,0.30983,0.076474,-0.22198,-0.076474,0.308048,0.100312,-0.172756,-0.100312,0.042085,0.0357,0.062498,0.0357,14177.0,14284.0,0.0,4,14207.548387,14115.258065,14288.5,14077.928571,14504.967742,14107.0,14700.0,14195.166667,0.0,0.0,0.0,0.0,POINT (22.92536 36.22923),161,Κυθήρων,EL3,Αττική,EL30,Aττική,EL307,"Πειραιάς, Νήσοι",2.0,1,1,0.0
4,22.92536,36.22923,0,2010-01-05,EL30,2010,1,0.30983,0.076474,-0.22198,-0.076474,0.308048,0.100312,-0.172756,-0.100312,0.042085,0.0357,0.062498,0.0357,14348.0,14168.0,0.0,5,14207.548387,14115.258065,14288.5,14077.928571,14504.967742,14107.0,14700.0,14195.166667,0.0,0.0,0.0,0.0,POINT (22.92536 36.22923),161,Κυθήρων,EL3,Αττική,EL30,Aττική,EL307,"Πειραιάς, Νήσοι",2.0,1,1,0.0

In [52]:
describe_dataframe(cm_grid, remove_zeros=True)

       Column  Missing
7        ndvi  60.9401
8        ndmi  60.9401
9        ndwi  60.9401
10       ndbi  60.9401
11  ndvi_mean  59.2903
12  ndmi_mean  59.2903
13  ndwi_mean  59.2903
14  ndbi_mean  59.2903
15   ndvi_std  59.2903
16   ndmi_std  59.2903
17   ndwi_std  59.2903
18   ndbi_std  59.2903
19    lst_day   0.0022

In [53]:
cm_grid.columns

Index(['x', 'y', 'cell_number', 'dt_placement', 'NUTS2_ID_left', 'year',
       'month', 'ndvi', 'ndmi', 'ndwi', 'ndbi', 'ndvi_mean', 'ndmi_mean',
       'ndwi_mean', 'ndbi_mean', 'ndvi_std', 'ndmi_std', 'ndwi_std',
       'ndbi_std', 'lst_day', 'lst_night', 'rainfall', 'day',
       'lst_day_jan_mean', 'lst_night_jan_mean', 'lst_day_feb_mean',
       'lst_night_feb_mean', 'lst_day_mar_mean', 'lst_night_mar_mean',
       'lst_day_apr_mean', 'lst_night_apr_mean', 'acc_rainfall_1week',
       'acc_rainfall_2week', 'acc_rainfall_month', 'acc_rainfall_jan',
       'geometry', 'index_right', 'LAU1_NAME', 'NUTS1_ID', 'NUTS1_NAME',
       'NUTS2_ID_right', 'NUTS2_NAME', 'NUTS3_ID', 'NUTS3_NAME', 'MOUNT_TYPE',
       'URBN_TYPE', 'COAST_TYPE', 'dist'],
      dtype='object')

In [54]:
cm_grid.rename(columns={'NUTS2_ID_left': 'NUTS2_ID'}, inplace=True)

In [55]:
new_order = ['x', 'y', 'cell_number', 'dt_placement','NUTS1_ID', 'NUTS1_NAME', 'NUTS2_ID', 'NUTS2_NAME', 'NUTS3_ID', 'NUTS3_NAME', 'LAU1_NAME', 'year', 'month',
             'ndvi', 'ndmi', 'ndwi', 'ndbi', 'ndvi_mean', 'ndmi_mean',
             'ndwi_mean', 'ndbi_mean', 'ndvi_std', 'ndmi_std', 'ndwi_std',
             'ndbi_std', 'lst_day', 'lst_night', 'rainfall', 'day',
             'lst_day_jan_mean', 'lst_night_jan_mean', 'lst_day_feb_mean',
             'lst_night_feb_mean', 'lst_day_mar_mean', 'lst_night_mar_mean',
             'lst_day_apr_mean', 'lst_night_apr_mean', 'acc_rainfall_1week',
             'acc_rainfall_2week', 'acc_rainfall_month', 'acc_rainfall_jan',
             'MOUNT_TYPE','URBN_TYPE', 'COAST_TYPE']

In [56]:
cm_grid = cm_grid[new_order]

In [57]:
cm_grid.head()

,x,y,cell_number,dt_placement,NUTS1_ID,NUTS1_NAME,NUTS2_ID,NUTS2_NAME,NUTS3_ID,NUTS3_NAME,LAU1_NAME,year,month,ndvi,ndmi,ndwi,ndbi,ndvi_mean,ndmi_mean,ndwi_mean,ndbi_mean,ndvi_std,ndmi_std,ndwi_std,ndbi_std,lst_day,lst_night,rainfall,day,lst_day_jan_mean,lst_night_jan_mean,lst_day_feb_mean,lst_night_feb_mean,lst_day_mar_mean,lst_night_mar_mean,lst_day_apr_mean,lst_night_apr_mean,acc_rainfall_1week,acc_rainfall_2week,acc_rainfall_month,acc_rainfall_jan,MOUNT_TYPE,URBN_TYPE,COAST_TYPE
0,22.92536,36.22923,0,2010-01-01,EL3,Αττική,EL30,Aττική,EL307,"Πειραιάς, Νήσοι",Κυθήρων,2010,1,0.30983,0.076474,-0.22198,-0.076474,0.308048,0.100312,-0.172756,-0.100312,0.042085,0.0357,0.062498,0.0357,14531.0,14284.0,0.0,1,14207.548387,14115.258065,14288.5,14077.928571,14504.967742,14107.0,14700.0,14195.166667,0.0,0.0,0.0,0.0,2.0,1,1
1,22.92536,36.22923,0,2010-01-02,EL3,Αττική,EL30,Aττική,EL307,"Πειραιάς, Νήσοι",Κυθήρων,2010,1,0.30983,0.076474,-0.22198,-0.076474,0.308048,0.100312,-0.172756,-0.100312,0.042085,0.0357,0.062498,0.0357,14389.0,14284.0,0.0,2,14207.548387,14115.258065,14288.5,14077.928571,14504.967742,14107.0,14700.0,14195.166667,0.0,0.0,0.0,0.0,2.0,1,1
2,22.92536,36.22923,0,2010-01-03,EL3,Αττική,EL30,Aττική,EL307,"Πειραιάς, Νήσοι",Κυθήρων,2010,1,0.30983,0.076474,-0.22198,-0.076474,0.308048,0.100312,-0.172756,-0.100312,0.042085,0.0357,0.062498,0.0357,14357.0,14284.0,0.0,3,14207.548387,14115.258065,14288.5,14077.928571,14504.967742,14107.0,14700.0,14195.166667,0.0,0.0,0.0,0.0,2.0,1,1
3,22.92536,36.22923,0,2010-01-04,EL3,Αττική,EL30,Aττική,EL307,"Πειραιάς, Νήσοι",Κυθήρων,2010,1,0.30983,0.076474,-0.22198,-0.076474,0.308048,0.100312,-0.172756,-0.100312,0.042085,0.0357,0.062498,0.0357,14177.0,14284.0,0.0,4,14207.548387,14115.258065,14288.5,14077.928571,14504.967742,14107.0,14700.0,14195.166667,0.0,0.0,0.0,0.0,2.0,1,1
4,22.92536,36.22923,0,2010-01-05,EL3,Αττική,EL30,Aττική,EL307,"Πειραιάς, Νήσοι",Κυθήρων,2010,1,0.30983,0.076474,-0.22198,-0.076474,0.308048,0.100312,-0.172756,-0.100312,0.042085,0.0357,0.062498,0.0357,14348.0,14168.0,0.0,5,14207.548387,14115.258065,14288.5,14077.928571,14504.967742,14107.0,14700.0,14195.166667,0.0,0.0,0.0,0.0,2.0,1,1

In [58]:
process_greek(cm_grid, 'NUTS1_NAME')
process_greek(cm_grid, 'NUTS2_NAME')
process_greek(cm_grid, 'NUTS3_NAME')
process_greek(cm_grid, 'LAU1_NAME')

In [59]:
cm_grid.head()

,x,y,cell_number,dt_placement,NUTS1_ID,NUTS1_NAME,NUTS2_ID,NUTS2_NAME,NUTS3_ID,NUTS3_NAME,LAU1_NAME,year,month,ndvi,ndmi,ndwi,ndbi,ndvi_mean,ndmi_mean,ndwi_mean,ndbi_mean,ndvi_std,ndmi_std,ndwi_std,ndbi_std,lst_day,lst_night,rainfall,day,lst_day_jan_mean,lst_night_jan_mean,lst_day_feb_mean,lst_night_feb_mean,lst_day_mar_mean,lst_night_mar_mean,lst_day_apr_mean,lst_night_apr_mean,acc_rainfall_1week,acc_rainfall_2week,acc_rainfall_month,acc_rainfall_jan,MOUNT_TYPE,URBN_TYPE,COAST_TYPE
0,22.92536,36.22923,0,2010-01-01,EL3,αττικη,EL30,αττικη,EL307,"πειραιας, νησοι",κυθηρων,2010,1,0.30983,0.076474,-0.22198,-0.076474,0.308048,0.100312,-0.172756,-0.100312,0.042085,0.0357,0.062498,0.0357,14531.0,14284.0,0.0,1,14207.548387,14115.258065,14288.5,14077.928571,14504.967742,14107.0,14700.0,14195.166667,0.0,0.0,0.0,0.0,2.0,1,1
1,22.92536,36.22923,0,2010-01-02,EL3,αττικη,EL30,αττικη,EL307,"πειραιας, νησοι",κυθηρων,2010,1,0.30983,0.076474,-0.22198,-0.076474,0.308048,0.100312,-0.172756,-0.100312,0.042085,0.0357,0.062498,0.0357,14389.0,14284.0,0.0,2,14207.548387,14115.258065,14288.5,14077.928571,14504.967742,14107.0,14700.0,14195.166667,0.0,0.0,0.0,0.0,2.0,1,1
2,22.92536,36.22923,0,2010-01-03,EL3,αττικη,EL30,αττικη,EL307,"πειραιας, νησοι",κυθηρων,2010,1,0.30983,0.076474,-0.22198,-0.076474,0.308048,0.100312,-0.172756,-0.100312,0.042085,0.0357,0.062498,0.0357,14357.0,14284.0,0.0,3,14207.548387,14115.258065,14288.5,14077.928571,14504.967742,14107.0,14700.0,14195.166667,0.0,0.0,0.0,0.0,2.0,1,1
3,22.92536,36.22923,0,2010-01-04,EL3,αττικη,EL30,αττικη,EL307,"πειραιας, νησοι",κυθηρων,2010,1,0.30983,0.076474,-0.22198,-0.076474,0.308048,0.100312,-0.172756,-0.100312,0.042085,0.0357,0.062498,0.0357,14177.0,14284.0,0.0,4,14207.548387,14115.258065,14288.5,14077.928571,14504.967742,14107.0,14700.0,14195.166667,0.0,0.0,0.0,0.0,2.0,1,1
4,22.92536,36.22923,0,2010-01-05,EL3,αττικη,EL30,αττικη,EL307,"πειραιας, νησοι",κυθηρων,2010,1,0.30983,0.076474,-0.22198,-0.076474,0.308048,0.100312,-0.172756,-0.100312,0.042085,0.0357,0.062498,0.0357,14348.0,14168.0,0.0,5,14207.548387,14115.258065,14288.5,14077.928571,14504.967742,14107.0,14700.0,14195.166667,0.0,0.0,0.0,0.0,2.0,1,1

In [60]:
cm_grid.to_csv(f'{base_folder}/{NUTS2}/GR_{NUTS2}_Timeline_GRID_{YEAR}_filled_mean_rain_shp.csv', encoding=enc, index = False)