In [1]:
import numpy as np
import pandas as pd
pd.set_option('display.max_columns', None)

In [2]:
data = pd.read_csv('GR_Timeline_2009-2022_filled_2.csv', encoding='utf-8')

In [3]:
try:
    data.drop(columns=['Unnamed: 0'], inplace=True)
except Exception:
    print("No column named \'Unnamed: 0\'")

In [4]:
data['dt_placement'] = pd.to_datetime(data['dt_placement'])

# Extract year, month, and day from the 'date' column
data['year'] = data['dt_placement'].dt.year
data['month'] = data['dt_placement'].dt.month
data['day'] = data['dt_placement'].dt.day

In [5]:
data

,x,y,cell_code,dt_placement,NUTS1_ID,NUTS1_NAME,NUTS2_ID,NUTS2_NAME,NUTS3_ID,LAU1_NAME,MOUNT_TYPE,URBN_TYPE,COAST_TYPE,year,month,ndvi,ndmi,ndwi,ndbi,ndvi_mean,ndmi_mean,ndwi_mean,ndbi_mean,ndvi_std,ndmi_std,ndwi_std,ndbi_std,lst_day,lst_night,rainfall,day
0,23.722470,38.078795,OU372,2009-01-01,EL3,αττικη,EL30,αττικη,EL305,αχαρνων,2.0,1.0,1.0,2009,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,14112.0,13780.0,0.000000,1
1,23.722470,38.078795,OU372,2009-01-02,EL3,αττικη,EL30,αττικη,EL305,αχαρνων,2.0,1.0,1.0,2009,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,14112.0,13780.0,2.866936,2
2,23.722470,38.078795,OU372,2009-01-03,EL3,αττικη,EL30,αττικη,EL305,αχαρνων,2.0,1.0,1.0,2009,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,14112.0,13780.0,13.926683,3
3,23.722470,38.078795,OU372,2009-01-04,EL3,αττικη,EL30,αττικη,EL305,αχαρνων,2.0,1.0,1.0,2009,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,14112.0,13780.0,2.439608,4
4,23.722470,38.078795,OU372,2009-01-05,EL3,αττικη,EL30,αττικη,EL305,αχαρνων,2.0,1.0,1.0,2009,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,14112.0,13780.0,10.252046,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22522760,22.205622,38.561047,MR240,2022-12-27,EL6,κεντρικη ελλαδα,EL64,στερεα ελλαδα,EL645,δωριδος,3.0,3.0,1.0,2022,12,0.286783,0.262643,-0.072022,-0.262643,0.355929,0.180265,-0.212274,-0.180265,0.05997,0.098978,0.11779,0.098978,14211.0,13959.0,0.000000,27
22522761,22.205622,38.561047,MR240,2022-12-28,EL6,κεντρικη ελλαδα,EL64,στερεα ελλαδα,EL645,δωριδος,3.0,3.0,1.0,2022,12,0.286783,0.262643,-0.072022,-0.262643,0.355929,0.180265,-0.212274,-0.180265,0.05997,0.098978,0.11779,0.098978,14139.0,13975.0,0.000000,28
22522762,22.205622,38.561047,MR240,2022-12-29,EL6,κεντρικη ελλαδα,EL64,στερεα ελλαδα,EL645,δωριδος,3.0,3.0,1.0,2022,12,0.286783,0.262643,-0.072022,-0.262643,0.355929,0.180265,-0.212274,-0.180265,0.05997,0.098978,0.11779,0.098978,14083.0,13833.0,0.000000,29
22522763,22.205622,38.561047,MR240,2022-12-30,EL6,κεντρικη ελλαδα,EL64,στερεα ελλαδα,EL645,δωριδος,3.0,3.0,1.0,2022,12,0.286783,0.262643,-0.072022,-0.262643,0.355929,0.180265,-0.212274,-0.180265,0.05997,0.098978,0.11779,0.098978,13802.0,13859.0,0.000000,30
22522764,22.205622,38.561047,MR240,2022-12-31,EL6,κεντρικη ελλαδα,EL64,στερεα ελλαδα,EL645,δωριδος,3.0,3.0,1.0,2022,12,0.286783,0.262643,-0.072022,-0.262643,0.355929,0.180265,-0.212274,-0.180265,0.05997,0.098978,0.11779,0.098978,14103.0,13874.0,0.000000,31

In [6]:
data_jan = data.loc[data['month'] == 1]
data_fed = data.loc[data['month'] == 2]
data_mar = data.loc[data['month'] == 3]
data_apr = data.loc[data['month'] == 4]

In [7]:
df_mean_jan = data_jan.groupby(['cell_code', 'year', 'month'], as_index=False)['lst_day', 'lst_night'].mean()
df_mean_feb = data_fed.groupby(['cell_code', 'year', 'month'], as_index=False)['lst_day', 'lst_night'].mean()
df_mean_mar = data_mar.groupby(['cell_code', 'year', 'month'], as_index=False)['lst_day', 'lst_night'].mean()
df_mean_apr = data_apr.groupby(['cell_code', 'year', 'month'], as_index=False)['lst_day', 'lst_night'].mean()

C:\Users\dimit\AppData\Local\Temp/ipykernel_9536/1084894401.py:1: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.
  df_mean_jan = data_jan.groupby(['cell_code', 'year', 'month'], as_index=False)['lst_day', 'lst_night'].mean()
C:\Users\dimit\AppData\Local\Temp/ipykernel_9536/1084894401.py:2: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.
  df_mean_feb = data_fed.groupby(['cell_code', 'year', 'month'], as_index=False)['lst_day', 'lst_night'].mean()
C:\Users\dimit\AppData\Local\Temp/ipykernel_9536/1084894401.py:3: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.
  df_mean_mar = data_mar.groupby(['cell_code', 'year', 'month'], as_index=False)['lst_day', 'lst_night'].mean()
C:\Users\dimit\AppData\Local\Temp/ipykernel_9536/1084894401.py:4: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.
  df_mean_apr = data_apr.groupby(['cell_code', 'year', 'month'], as_index=False)['lst_day', 'lst_night'].mean()

In [13]:
df_mean_jan.rename(columns={'lst_day': 'lst_day_jan_mean', 'lst_night': 'lst_night_jan_mean'}, inplace=True)
df_mean_feb.rename(columns={'lst_day': 'lst_day_feb_mean', 'lst_night': 'lst_night_feb_mean'}, inplace=True)
df_mean_mar.rename(columns={'lst_day': 'lst_day_mar_mean', 'lst_night': 'lst_night_mar_mean'}, inplace=True)
df_mean_apr.rename(columns={'lst_day': 'lst_day_apr_mean', 'lst_night': 'lst_night_apr_mean'}, inplace=True)

In [15]:
df_mean_jan.drop(columns=['month'], inplace = True)
df_mean_feb.drop(columns=['month'], inplace = True)
df_mean_mar.drop(columns=['month'], inplace = True)
df_mean_apr.drop(columns=['month'], inplace = True)

In [19]:
df_mean = pd.merge(df_mean_jan, df_mean_feb, on=['cell_code', 'year']).merge(df_mean_mar, on=['cell_code', 'year']).merge(df_mean_apr, on=['cell_code', 'year'])

In [21]:
df_mean.loc[(df_mean['cell_code'] == 'AAE407') & (df_mean['year'] == 2009)]

,cell_code,year,lst_day_jan_mean,lst_night_jan_mean,lst_day_feb_mean,lst_night_feb_mean,lst_day_mar_mean,lst_night_mar_mean,lst_day_apr_mean,lst_night_apr_mean
0,AAE407,2009,14326.791667,14045.709677,14256.75,14178.642857,14451.903226,14007.677419,14754.466667,14201.666667

In [22]:
data_mean = pd.merge(data, df_mean, on=['cell_code', 'year'])

In [23]:
data_mean

,x,y,cell_code,dt_placement,NUTS1_ID,NUTS1_NAME,NUTS2_ID,NUTS2_NAME,NUTS3_ID,LAU1_NAME,MOUNT_TYPE,URBN_TYPE,COAST_TYPE,year,month,ndvi,ndmi,ndwi,ndbi,ndvi_mean,ndmi_mean,ndwi_mean,ndbi_mean,ndvi_std,ndmi_std,ndwi_std,ndbi_std,lst_day,lst_night,rainfall,day,lst_day_jan_mean,lst_night_jan_mean,lst_day_feb_mean,lst_night_feb_mean,lst_day_mar_mean,lst_night_mar_mean,lst_day_apr_mean,lst_night_apr_mean
0,23.722470,38.078795,OU372,2009-01-01,EL3,αττικη,EL30,αττικη,EL305,αχαρνων,2.0,1.0,1.0,2009,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,14112.0,13780.0,0.000000,1,14272.870968,13947.709677,14304.428571,13893.321429,14593.612903,13974.096774,14909.800000,14193.633333
1,23.722470,38.078795,OU372,2009-01-02,EL3,αττικη,EL30,αττικη,EL305,αχαρνων,2.0,1.0,1.0,2009,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,14112.0,13780.0,2.866936,2,14272.870968,13947.709677,14304.428571,13893.321429,14593.612903,13974.096774,14909.800000,14193.633333
2,23.722470,38.078795,OU372,2009-01-03,EL3,αττικη,EL30,αττικη,EL305,αχαρνων,2.0,1.0,1.0,2009,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,14112.0,13780.0,13.926683,3,14272.870968,13947.709677,14304.428571,13893.321429,14593.612903,13974.096774,14909.800000,14193.633333
3,23.722470,38.078795,OU372,2009-01-04,EL3,αττικη,EL30,αττικη,EL305,αχαρνων,2.0,1.0,1.0,2009,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,14112.0,13780.0,2.439608,4,14272.870968,13947.709677,14304.428571,13893.321429,14593.612903,13974.096774,14909.800000,14193.633333
4,23.722470,38.078795,OU372,2009-01-05,EL3,αττικη,EL30,αττικη,EL305,αχαρνων,2.0,1.0,1.0,2009,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,14112.0,13780.0,10.252046,5,14272.870968,13947.709677,14304.428571,13893.321429,14593.612903,13974.096774,14909.800000,14193.633333
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22522760,22.205622,38.561047,MR240,2022-12-27,EL6,κεντρικη ελλαδα,EL64,στερεα ελλαδα,EL645,δωριδος,3.0,3.0,1.0,2022,12,0.286783,0.262643,-0.072022,-0.262643,0.355929,0.180265,-0.212274,-0.180265,0.05997,0.098978,0.11779,0.098978,14211.0,13959.0,0.000000,27,13975.225806,13688.451613,14069.714286,13731.035714,14104.580645,13616.322581,14506.133333,13992.200000
22522761,22.205622,38.561047,MR240,2022-12-28,EL6,κεντρικη ελλαδα,EL64,στερεα ελλαδα,EL645,δωριδος,3.0,3.0,1.0,2022,12,0.286783,0.262643,-0.072022,-0.262643,0.355929,0.180265,-0.212274,-0.180265,0.05997,0.098978,0.11779,0.098978,14139.0,13975.0,0.000000,28,13975.225806,13688.451613,14069.714286,13731.035714,14104.580645,13616.322581,14506.133333,13992.200000
22522762,22.205622,38.561047,MR240,2022-12-29,EL6,κεντρικη ελλαδα,EL64,στερεα ελλαδα,EL645,δωριδος,3.0,3.0,1.0,2022,12,0.286783,0.262643,-0.072022,-0.262643,0.355929,0.180265,-0.212274,-0.180265,0.05997,0.098978,0.11779,0.098978,14083.0,13833.0,0.000000,29,13975.225806,13688.451613,14069.714286,13731.035714,14104.580645,13616.322581,14506.133333,13992.200000
22522763,22.205622,38.561047,MR240,2022-12-30,EL6,κεντρικη ελλαδα,EL64,στερεα ελλαδα,EL645,δωριδος,3.0,3.0,1.0,2022,12,0.286783,0.262643,-0.072022,-0.262643,0.355929,0.180265,-0.212274,-0.180265,0.05997,0.098978,0.11779,0.098978,13802.0,13859.0,0.000000,30,13975.225806,13688.451613,14069.714286,13731.035714,14104.580645,13616.322581,14506.133333,13992.200000
22522764,22.205622,38.561047,MR240,2022-12-31,EL6,κεντρικη ελλαδα,EL64,στερεα ελλαδα,EL645,δωριδος,3.0,3.0,1.0,2022,12,0.286783,0.262643,-0.072022,-0.262643,0.355929,0.180265,-0.212274,-0.180265,0.05997,0.098978,0.11779,0.098978,14103.0,13874.0,0.000000,31,13975.225806,13688.451613,14069.714286,13731.035714,14104.580645,13616.322581,14506.133333,13992.200000

In [24]:
data_mean.to_csv('GR_Timeline_2009-2022_filled_mean.csv', encoding='utf-8')