In [1]:
import geopandas as gpd
import numpy as np

In [2]:
df = gpd.read_file(r'E:\Drive\NOA\MBD-Prediction\GRID Level\data\CMacedonia\predictions\GR_CMacedonia_GRID_Predictions_May_2024.shp',  encoding='utf-8')

In [3]:
df.head()

,cell_numbe,nuts2_id,nuts3_id,lau1,year,month,x,y,risk_score,geometry
0,0,EL52,EL524,εδεσσας,2024,5,21.7633,40.7981,0.000046,"POLYGON ((21.77505 40.78908, 21.75163 40.78908..."
1,1,EL52,EL524,εδεσσας,2024,5,21.7633,40.8160,0.000010,"POLYGON ((21.77505 40.80705, 21.75163 40.80705..."
2,2,EL52,EL524,εδεσσας,2024,5,21.7633,40.8340,0.000009,"POLYGON ((21.77505 40.82501, 21.75163 40.82501..."
3,3,EL52,EL524,εδεσσας,2024,5,21.7633,40.8520,0.000027,"POLYGON ((21.77505 40.84298, 21.75163 40.84298..."
4,4,EL52,EL524,εδεσσας,2024,5,21.7868,40.7981,0.000332,"POLYGON ((21.79847 40.78908, 21.77505 40.78908..."

In [4]:
df.shape

(4416, 10)

In [5]:
df = df.to_crs(epsg=4326)
df.drop(columns=['cell_numbe','nuts2_id','nuts3_id','lau1','year','month','x','y', 'risk_score'], inplace=True)
df.head()

                                            geometry
0  POLYGON ((21.77505 40.78908, 21.75163 40.78908...
1  POLYGON ((21.77505 40.80705, 21.75163 40.80705...
2  POLYGON ((21.77505 40.82501, 21.75163 40.82501...
3  POLYGON ((21.77505 40.84298, 21.75163 40.84298...
4  POLYGON ((21.79847 40.78908, 21.77505 40.78908...

In [6]:
gdf = df.iloc[:1000].copy()

In [7]:
gdf

                                              geometry
0    POLYGON ((21.77505 40.78908, 21.75163 40.78908...
1    POLYGON ((21.77505 40.80705, 21.75163 40.80705...
2    POLYGON ((21.77505 40.82501, 21.75163 40.82501...
3    POLYGON ((21.77505 40.84298, 21.75163 40.84298...
4    POLYGON ((21.79847 40.78908, 21.77505 40.78908...
..                                                 ...
995  POLYGON ((22.40746 40.57348, 22.38404 40.57348...
996  POLYGON ((22.40746 40.59145, 22.38404 40.59145...
997  POLYGON ((22.40746 40.60941, 22.38404 40.60941...
998  POLYGON ((22.40746 40.62738, 22.38404 40.62738...
999  POLYGON ((22.40746 40.64535, 22.38404 40.64535...

[1000 rows x 1 columns]

In [8]:
num_rows = len(gdf)

In [9]:
gdf['risk_score'] = np.linspace(0, 1, num_rows)

In [10]:
gdf

                                              geometry  risk_score
0    POLYGON ((21.77505 40.78908, 21.75163 40.78908...    0.000000
1    POLYGON ((21.77505 40.80705, 21.75163 40.80705...    0.001001
2    POLYGON ((21.77505 40.82501, 21.75163 40.82501...    0.002002
3    POLYGON ((21.77505 40.84298, 21.75163 40.84298...    0.003003
4    POLYGON ((21.79847 40.78908, 21.77505 40.78908...    0.004004
..                                                 ...         ...
995  POLYGON ((22.40746 40.57348, 22.38404 40.57348...    0.995996
996  POLYGON ((22.40746 40.59145, 22.38404 40.59145...    0.996997
997  POLYGON ((22.40746 40.60941, 22.38404 40.60941...    0.997998
998  POLYGON ((22.40746 40.62738, 22.38404 40.62738...    0.998999
999  POLYGON ((22.40746 40.64535, 22.38404 40.64535...    1.000000

[1000 rows x 2 columns]

In [11]:
gdf.to_file(r'E:\Drive\NOA\MBD-Prediction\GRID Level\data\CMacedonia\predictions\QGIS_Style_GDF.shp', encoding = 'utf-8', index = False)