In [15]:
import pandas as pd
import json

import random
import geopandas as gpd
import numpy as np
import os
from shapely.geometry import Point

enc = 'utf-8'
pd.set_option('display.max_columns', None)
random.seed(0)
np.random.seed(0)

In [16]:
df = pd.read_csv('../data_snipets/GRE_culex_2011_2023.csv', encoding=enc)

C:\Users\dimit\AppData\Local\Temp\ipykernel_1892\2252005050.py:1: DtypeWarning: Columns (64,65,66,67) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('../data_snipets/GRE_culex_2011_2023.csv', encoding=enc)

In [17]:
df.head()

,trap_id,station_id,x,y,dt_placement,week,month,year,country_code,nuts0_code,nuts0_name,nuts1_code,nuts1_name,nuts2_code,nuts2_name,nuts3_code,nuts3_name,lau1_municipality,lau2_settlement,trap_type,culex spp.,region,dt_placement_original,indices_image_date,indices_lat,indices_lon,ndvi,ndmi,ndwi,ndbi,ndvi_mean,ndmi_mean,ndwi_mean,ndbi_mean,ndvi_std,ndmi_std,ndwi_std,ndbi_std,lst_image_date,lst_lat,lst_lon,lst_day,lst_night,monthly_lst_lat,monthly_lst_lon,lst_jan_day_mean,lst_jan_night_mean,lst_feb_day_mean,lst_feb_night_mean,lst_mar_day_mean,lst_mar_night_mean,lst_apr_day_mean,lst_apr_night_mean,indices_image_date.1,indices_lat.1,indices_lon.1,acc_rainfall_jan,dt_placement_minus_7,dt_placement_minus_14,dt_placement_minus_7_avail,dt_placement_minus_14_avail,acc_rainfall_1week,acc_rainfall_2week,id,trapid_region,trapid,unique_code,oldid,culex pipiens
0,AGLTR01_EL52,AGLTR01,22.193720,40.665896,2011-03-29,16.0,3,2011,EL,0,Greece,EL5,NOTHERN GREECE,EL52,CENTRAL MACEDONIA,EL521,IMATHIA,NAOUSA,AGGELOCHORI,Ecodev trap,0.0,Greece,2011-04-13,2011-03-23,40.664487,22.195125,0.593170,0.255064,-0.304578,-0.255064,0.543969,0.190812,-0.313988,-0.190812,0.070675,0.095966,0.032384,0.095966,2011-03-29,40.664487,22.195125,14816.0,14021.0,40.664487,22.195125,14158.500000,13584.142857,14253.076923,13615.300000,14613.285714,13815.583333,14896.083333,14066.500000,2011-03-29,40.650186,22.150101,203.793588,2011-03-22,2011-03-15,2011-03-22,2011-03-15,11.032128,37.117337,NaN,NaN,NaN,NaN,NaN,NaN
1,PRLTR01_EL52,PRLTR01,22.447874,40.753947,2011-03-28,16.0,3,2011,EL,0,Greece,EL5,NOTHERN GREECE,EL52,CENTRAL MACEDONIA,EL524,PELLA,PELLA,PARALIMNI,Ecodev trap,32.0,Greece,2011-04-12,2011-03-23,40.754319,22.446653,0.246762,0.071254,-0.191696,-0.071254,0.264659,0.033256,-0.243740,-0.033256,0.077019,0.067968,0.059814,0.067968,2011-03-28,40.754319,22.446653,14913.0,14140.0,40.754319,22.446653,14177.909091,13640.846154,14365.230769,13658.300000,14661.125000,13869.166667,15057.733333,14094.333333,2011-03-28,40.750186,22.450103,180.220247,2011-03-21,2011-03-14,2011-03-21,2011-03-14,0.072116,37.919265,NaN,NaN,NaN,NaN,NaN,NaN
2,ADETR01_EL52,ADETR01,22.615797,40.664160,2011-04-05,17.0,4,2011,EL,0,Greece,EL5,NOTHERN GREECE,EL52,CENTRAL MACEDONIA,EL522,THESSALONIKI,CHALKIDONA,ADENDRO,Ecodev trap,8.0,Greece,2011-04-20,2011-03-30,40.664487,22.617333,0.188915,-0.021250,-0.206622,0.021250,0.179760,-0.054716,-0.234824,0.054716,0.023055,0.028899,0.021619,0.028899,2011-04-05,40.664487,22.617333,15084.0,13990.0,40.664487,22.617333,14097.363636,13634.545455,14292.909091,13634.300000,14588.714286,13838.769231,15064.066667,14057.937500,2011-04-05,40.650186,22.650104,231.269478,2011-03-29,2011-03-22,2011-03-29,2011-03-22,3.360479,18.171441,NaN,NaN,NaN,NaN,NaN,NaN
3,AIGTR01_EL52,AIGTR01,22.547799,40.509188,2011-04-13,18.0,4,2011,EL,0,Greece,EL5,NOTHERN GREECE,EL52,CENTRAL MACEDONIA,EL525,PIERIA,PYDNA-KOLINDROS,AIGINIO,Ecodev trap,21.0,Greece,2011-04-28,2011-04-08,40.507282,22.549959,0.184265,0.061108,-0.126880,-0.061108,0.181648,0.058692,-0.126564,-0.058692,0.011393,0.010442,0.003869,0.010442,2011-04-13,40.507282,22.549959,14988.0,14071.0,40.507282,22.549959,14122.714286,13667.933333,14239.416667,13674.636364,14579.461538,13807.777778,14955.166667,14076.000000,2011-04-13,40.550185,22.550103,224.639889,2011-04-06,2011-03-30,2011-04-06,2011-03-30,9.028140,11.736175,NaN,NaN,NaN,NaN,NaN,NaN
4,ANTTR01_EL52,ANTTR01,22.715266,40.669967,2011-04-05,17.0,4,2011,EL,0,Greece,EL5,NOTHERN GREECE,EL52,CENTRAL MACEDONIA,EL522,THESSALONIKI,DELTA,ANATOLIKO,Ecodev trap,4.0,Greece,2011-04-20,2011-03-30,40.668979,22.716148,0.362673,0.055860,-0.274874,-0.055860,0.276198,-0.002279,-0.268868,0.002279,0.074791,0.064529,0.032009,0.064529,2011-04-05,40.668979,22.716148,14999.0,13942.0,40.668979,22.716148,14125.600000,13647.692308,14265.083333,13662.700000,14567.250000,13821.333333,14980.705882,14050.461538,2011-04-05,40.650186,22.750104,222.349577,2011-03-29,2011-03-22,2011-03-29,2011-03-22,3.512708,14.843995,NaN,NaN,NaN,NaN,NaN,NaN

In [18]:
df_sub = df.loc[df['nuts2_code'] == 'EL52'].copy()
df_sub.reset_index(drop=True, inplace=True)

In [19]:
df_sub.head()

,trap_id,station_id,x,y,dt_placement,week,month,year,country_code,nuts0_code,nuts0_name,nuts1_code,nuts1_name,nuts2_code,nuts2_name,nuts3_code,nuts3_name,lau1_municipality,lau2_settlement,trap_type,culex spp.,region,dt_placement_original,indices_image_date,indices_lat,indices_lon,ndvi,ndmi,ndwi,ndbi,ndvi_mean,ndmi_mean,ndwi_mean,ndbi_mean,ndvi_std,ndmi_std,ndwi_std,ndbi_std,lst_image_date,lst_lat,lst_lon,lst_day,lst_night,monthly_lst_lat,monthly_lst_lon,lst_jan_day_mean,lst_jan_night_mean,lst_feb_day_mean,lst_feb_night_mean,lst_mar_day_mean,lst_mar_night_mean,lst_apr_day_mean,lst_apr_night_mean,indices_image_date.1,indices_lat.1,indices_lon.1,acc_rainfall_jan,dt_placement_minus_7,dt_placement_minus_14,dt_placement_minus_7_avail,dt_placement_minus_14_avail,acc_rainfall_1week,acc_rainfall_2week,id,trapid_region,trapid,unique_code,oldid,culex pipiens
0,AGLTR01_EL52,AGLTR01,22.193720,40.665896,2011-03-29,16.0,3,2011,EL,0,Greece,EL5,NOTHERN GREECE,EL52,CENTRAL MACEDONIA,EL521,IMATHIA,NAOUSA,AGGELOCHORI,Ecodev trap,0.0,Greece,2011-04-13,2011-03-23,40.664487,22.195125,0.593170,0.255064,-0.304578,-0.255064,0.543969,0.190812,-0.313988,-0.190812,0.070675,0.095966,0.032384,0.095966,2011-03-29,40.664487,22.195125,14816.0,14021.0,40.664487,22.195125,14158.500000,13584.142857,14253.076923,13615.300000,14613.285714,13815.583333,14896.083333,14066.500000,2011-03-29,40.650186,22.150101,203.793588,2011-03-22,2011-03-15,2011-03-22,2011-03-15,11.032128,37.117337,NaN,NaN,NaN,NaN,NaN,NaN
1,PRLTR01_EL52,PRLTR01,22.447874,40.753947,2011-03-28,16.0,3,2011,EL,0,Greece,EL5,NOTHERN GREECE,EL52,CENTRAL MACEDONIA,EL524,PELLA,PELLA,PARALIMNI,Ecodev trap,32.0,Greece,2011-04-12,2011-03-23,40.754319,22.446653,0.246762,0.071254,-0.191696,-0.071254,0.264659,0.033256,-0.243740,-0.033256,0.077019,0.067968,0.059814,0.067968,2011-03-28,40.754319,22.446653,14913.0,14140.0,40.754319,22.446653,14177.909091,13640.846154,14365.230769,13658.300000,14661.125000,13869.166667,15057.733333,14094.333333,2011-03-28,40.750186,22.450103,180.220247,2011-03-21,2011-03-14,2011-03-21,2011-03-14,0.072116,37.919265,NaN,NaN,NaN,NaN,NaN,NaN
2,ADETR01_EL52,ADETR01,22.615797,40.664160,2011-04-05,17.0,4,2011,EL,0,Greece,EL5,NOTHERN GREECE,EL52,CENTRAL MACEDONIA,EL522,THESSALONIKI,CHALKIDONA,ADENDRO,Ecodev trap,8.0,Greece,2011-04-20,2011-03-30,40.664487,22.617333,0.188915,-0.021250,-0.206622,0.021250,0.179760,-0.054716,-0.234824,0.054716,0.023055,0.028899,0.021619,0.028899,2011-04-05,40.664487,22.617333,15084.0,13990.0,40.664487,22.617333,14097.363636,13634.545455,14292.909091,13634.300000,14588.714286,13838.769231,15064.066667,14057.937500,2011-04-05,40.650186,22.650104,231.269478,2011-03-29,2011-03-22,2011-03-29,2011-03-22,3.360479,18.171441,NaN,NaN,NaN,NaN,NaN,NaN
3,AIGTR01_EL52,AIGTR01,22.547799,40.509188,2011-04-13,18.0,4,2011,EL,0,Greece,EL5,NOTHERN GREECE,EL52,CENTRAL MACEDONIA,EL525,PIERIA,PYDNA-KOLINDROS,AIGINIO,Ecodev trap,21.0,Greece,2011-04-28,2011-04-08,40.507282,22.549959,0.184265,0.061108,-0.126880,-0.061108,0.181648,0.058692,-0.126564,-0.058692,0.011393,0.010442,0.003869,0.010442,2011-04-13,40.507282,22.549959,14988.0,14071.0,40.507282,22.549959,14122.714286,13667.933333,14239.416667,13674.636364,14579.461538,13807.777778,14955.166667,14076.000000,2011-04-13,40.550185,22.550103,224.639889,2011-04-06,2011-03-30,2011-04-06,2011-03-30,9.028140,11.736175,NaN,NaN,NaN,NaN,NaN,NaN
4,ANTTR01_EL52,ANTTR01,22.715266,40.669967,2011-04-05,17.0,4,2011,EL,0,Greece,EL5,NOTHERN GREECE,EL52,CENTRAL MACEDONIA,EL522,THESSALONIKI,DELTA,ANATOLIKO,Ecodev trap,4.0,Greece,2011-04-20,2011-03-30,40.668979,22.716148,0.362673,0.055860,-0.274874,-0.055860,0.276198,-0.002279,-0.268868,0.002279,0.074791,0.064529,0.032009,0.064529,2011-04-05,40.668979,22.716148,14999.0,13942.0,40.668979,22.716148,14125.600000,13647.692308,14265.083333,13662.700000,14567.250000,13821.333333,14980.705882,14050.461538,2011-04-05,40.650186,22.750104,222.349577,2011-03-29,2011-03-22,2011-03-29,2011-03-22,3.512708,14.843995,NaN,NaN,NaN,NaN,NaN,NaN

In [20]:
df_locations = df_sub[['x', 'y']].drop_duplicates()
df_locations.reset_index(drop=True, inplace=True)

In [21]:
df_locations

             x          y
0    22.193720  40.665896
1    22.447874  40.753947
2    22.615797  40.664160
3    22.547799  40.509188
4    22.715266  40.669967
..         ...        ...
329  22.386166  40.634090
330  22.105360  40.689983
331  22.466885  40.553780
332  22.400370  40.619469
333  22.509955  40.664059

[334 rows x 2 columns]

In [22]:
geometry = [Point(xy) for xy in zip(df_locations['x'], df_locations['y'])]
gdf = gpd.GeoDataFrame(df_locations, geometry=geometry)
gdf.set_crs(epsg=4326, inplace=True)  # Assuming WGS84 (lat/lon)

             x          y                   geometry
0    22.193720  40.665896  POINT (22.19372 40.66590)
1    22.447874  40.753947  POINT (22.44787 40.75395)
2    22.615797  40.664160  POINT (22.61580 40.66416)
3    22.547799  40.509188  POINT (22.54780 40.50919)
4    22.715266  40.669967  POINT (22.71527 40.66997)
..         ...        ...                        ...
329  22.386166  40.634090  POINT (22.38617 40.63409)
330  22.105360  40.689983  POINT (22.10536 40.68998)
331  22.466885  40.553780  POINT (22.46689 40.55378)
332  22.400370  40.619469  POINT (22.40037 40.61947)
333  22.509955  40.664059  POINT (22.50996 40.66406)

[334 rows x 3 columns]

In [24]:
gdf.to_file('../data_snipets/EL52_mosquito_traps.shp', encoding = enc)