In [1]:
import pandas as pd

import random
import numpy as np
import ast

import sys

sys.path.insert(0, "../utils")

from plots import *
from string_handling import *

enc = 'utf-8' 

random.seed(0)
np.random.seed(0)

pd.set_option('display.max_columns', None)

In [2]:
file_path = "../data/"

In [3]:
cameroon_polygons = pd.read_csv(f"{file_path}CM_WEB_Polygons.csv",  encoding=enc)

In [4]:
cameroon_polygons.head()

   id       gid3       gid2      gid1  gid0
0   1        gor  tchollire  mayo-rey  nord
1   2       kali  tchollire  mayo-rey  nord
2   3  tchollire  tchollire  mayo-rey  nord
3   4      gamba  tchollire  mayo-rey  nord
4   5     sakdje  tchollire  mayo-rey  nord

In [5]:
cameroon_polygons['location'] = list(zip(cameroon_polygons['gid0'], cameroon_polygons['gid2'], cameroon_polygons['gid3']))

In [6]:
cameroon_polygons.drop(['gid0', 'gid1', 'gid2', 'gid3'], axis=1, inplace=True)

In [7]:
cameroon_polygons

      id                            location
0      1              (nord, tchollire, gor)
1      2             (nord, tchollire, kali)
2      3        (nord, tchollire, tchollire)
3      4            (nord, tchollire, gamba)
4      5           (nord, tchollire, sakdje)
..   ...                                 ...
457  458     (extreme nord, mokolo, mouhour)
458  459   (extreme nord, mokolo, ouro tada)
459  460  (extreme nord, bourha, gamboura 2)
460  461      (extreme nord, mokolo, moutaz)
461  462  (extreme nord, maroua 3, dougoi 3)

[462 rows x 2 columns]

In [8]:
location_file_path = "locations_from_shapefile.txt"

with open(location_file_path, "r", encoding="utf-8") as f:
    lines = f.readlines()

locations = [ast.literal_eval(line.strip().rstrip(',')) for line in lines]

df_locations = pd.DataFrame({'location': locations})

In [9]:
df_locations

                            location
0       (extreme nord, bogo, balaza)
1        (extreme nord, bogo, balda)
2         (extreme nord, bogo, bogo)
3        (extreme nord, bogo, borai)
4    (extreme nord, bogo, guinggley)
..                               ...
457          (nord, touboro, mbeing)
458       (nord, touboro, ngai-lara)
459         (nord, touboro, touboro)
460          (nord, touboro, vogzom)
461           (nord, touboro, yanli)

[462 rows x 1 columns]

In [10]:
missing_locations = cameroon_polygons[~cameroon_polygons['location'].isin(df_locations['location'])]
missing_locations.location.sort_values().unique().shape

(0,)

In [11]:
cameroon_polygons.to_csv(f"{file_path}CM_WEB_Polygons_Processed.csv", index=False, encoding=enc)