## Creates the **Timeline** for a specific region by using the Grid File and the required dates ##

In [1]:
import pandas as pd
from datetime import date, timedelta, datetime

import random
import geopandas as gpd
import numpy as np

import sys

sys.path.insert(0, "../../../Modules")

from preprocessing_utils import *

enc = 'utf-8'
dec = 'greek8'
random.seed(0)

c:\Users\dimit\AppData\Local\Programs\Python\Python39\lib\site-packages\geopandas\_compat.py:112: UserWarning: The Shapely GEOS version (3.10.3-CAPI-1.16.1) is incompatible with the GEOS version PyGEOS was compiled with (3.10.4-CAPI-1.16.2). Conversions between both will be slow.
  warnings.warn(

In [2]:
import warnings
warnings.filterwarnings('ignore')

In [3]:
NUTS0 = 'GR'
NUTS2 = 'Attica'
NUTS2_EL = 'αττικης'

In [4]:
YEAR = 2023
MONTH = 'July'
PERIOD = '2nd'

In [5]:
nuts2_grid = pd.read_csv(f'../../data/{NUTS2}/{NUTS0}_{NUTS2}_Grid.csv', encoding = enc)
nuts2_grid.head()

     nuts2                       lau1         x         y
0  αττικης             αγιας βαρβαρας  23.65697  37.99220
1  αττικης           αγιας παρασκευης  23.82642  38.00806
2  αττικης            αγιου δημητριου  23.73031  37.93357
3  αττικης  αγιων αναργυρων καματερου  23.71341  38.04721
4  αττικης                 αγκιστριου  23.34009  37.69503

In [6]:
## start and end date is defined from available epidemiological file

In [7]:
dt = 1 if PERIOD == '1st' else 16
mn = datetime.strptime(MONTH, '%B').month

start = start_dt = date(YEAR, mn, dt)
end = end_dt = date(YEAR, mn, dt)
delta = timedelta(days=1)

In [8]:
dates = []

while start_dt <= end_dt:
    dates.append(start_dt.isoformat())
    start_dt += delta

In [9]:
print('Dates between', start, 'and', end)
print(dates)

Dates between 2023-07-16 and 2023-07-16
['2023-07-16']

In [10]:
len(dates)

1

In [11]:
nuts2_timeline = pd.DataFrame()

In [12]:
data = []
for index, row in nuts2_grid.iterrows():
    for date in dates:
        data.append({'lau1': row['lau1'], 
                     'region': row['nuts2'], 
                     'x': row['x'], 
                     'y': row['y'], 
                     'dt_placement': date})

nuts2_timeline = pd.DataFrame(data)

In [13]:
nuts2_timeline

                          lau1   region         x         y dt_placement
0               αγιας βαρβαρας  αττικης  23.65697  37.99220   2023-07-16
1             αγιας παρασκευης  αττικης  23.82642  38.00806   2023-07-16
2              αγιου δημητριου  αττικης  23.73031  37.93357   2023-07-16
3    αγιων αναργυρων καματερου  αττικης  23.71341  38.04721   2023-07-16
4                   αγκιστριου  αττικης  23.34009  37.69503   2023-07-16
..                         ...      ...       ...       ...          ...
147                     ωρωπου  αττικης  23.84918  38.21351   2023-07-16
148                     ωρωπου  αττικης  23.84918  38.23148   2023-07-16
149                     ωρωπου  αττικης  23.87203  38.23148   2023-07-16
150                     ωρωπου  αττικης  23.89487  38.26741   2023-07-16
151                     ωρωπου  αττικης  23.66640  38.24944   2023-07-16

[152 rows x 5 columns]

In [14]:
nuts2_timeline['dt_placement'] = pd.to_datetime(nuts2_timeline['dt_placement'])

In [15]:
nuts2_timeline.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 152 entries, 0 to 151
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   lau1          152 non-null    object
 1   region        152 non-null    object
 2   x             152 non-null    float64
 3   y             152 non-null    float64
 4   dt_placement  152 non-null    datetime64[ns]
dtypes: datetime64[ns](1), float64(2), object(2)
memory usage: 6.1+ KB

In [16]:
nuts2_timeline.to_csv(f'../../data/{NUTS2}/{NUTS0}_{NUTS2}_Timeline_{YEAR}-{MONTH}-{PERIOD}.csv', index = False)