## Creates the **Timeline** for a specific region by using the Grid File and the required dates ##

In [1]:
import pandas as pd
from datetime import date, timedelta

import random
import geopandas as gpd
import numpy as np

import sys

sys.path.insert(0, "../../../Modules")

from utils import *

pd.options.display.max_columns = None

enc = 'utf-8'
dec = 'greek8'
random.seed(0)

In [2]:
NUTS0 = 'GR'
NUTS2 = 'Thrace'

In [3]:
gr_grid = pd.read_csv(f'../../data/{NUTS2}/{NUTS0}_{NUTS2}_GRID.csv', encoding = enc)
gr_grid

      cell_number NUTS2_ID         x         y
0               0     EL51  23.65882  41.33542
1               1     EL51  23.65882  41.35339
2               2     EL51  23.65882  41.37135
3               3     EL51  23.68241  41.33542
4               4     EL51  23.68241  41.35339
...           ...      ...       ...       ...
3261         3261     EL51  26.58397  41.49712
3262         3262     EL51  26.60756  41.35339
3263         3263     EL51  26.60756  41.37135
3264         3264     EL51  26.60756  41.38932
3265         3265     EL51  26.60756  41.40729

[3266 rows x 4 columns]

In [4]:
## start and end date is defined from available epidemiological file

In [5]:
start = start_dt = date(2024, 1, 1)
end = end_dt = date(2024, 6, 1)
delta = timedelta(days=1)

In [6]:
dates = []

while start_dt <= end_dt:
    dates.append(start_dt.isoformat())
    start_dt += delta

In [7]:
print('Dates between', start, 'and', end)
print(dates)

Dates between 2024-01-01 and 2024-06-01
['2024-01-01', '2024-01-02', '2024-01-03', '2024-01-04', '2024-01-05', '2024-01-06', '2024-01-07', '2024-01-08', '2024-01-09', '2024-01-10', '2024-01-11', '2024-01-12', '2024-01-13', '2024-01-14', '2024-01-15', '2024-01-16', '2024-01-17', '2024-01-18', '2024-01-19', '2024-01-20', '2024-01-21', '2024-01-22', '2024-01-23', '2024-01-24', '2024-01-25', '2024-01-26', '2024-01-27', '2024-01-28', '2024-01-29', '2024-01-30', '2024-01-31', '2024-02-01', '2024-02-02', '2024-02-03', '2024-02-04', '2024-02-05', '2024-02-06', '2024-02-07', '2024-02-08', '2024-02-09', '2024-02-10', '2024-02-11', '2024-02-12', '2024-02-13', '2024-02-14', '2024-02-15', '2024-02-16', '2024-02-17', '2024-02-18', '2024-02-19', '2024-02-20', '2024-02-21', '2024-02-22', '2024-02-23', '2024-02-24', '2024-02-25', '2024-02-26', '2024-02-27', '2024-02-28', '2024-02-29', '2024-03-01', '2024-03-02', '2024-03-03', '2024-03-04', '2024-03-05', '2024-03-06', '2024-03-07', '2024-03-08', '2024-03-09', '2024-03-10', '2024-03-11', '2024-03-12', '2024-03-13', '2024-03-14', '2024-03-15', '2024-03-16', '2024-03-17', '2024-03-18', '2024-03-19', '2024-03-20', '2024-03-21', '2024-03-22', '2024-03-23', '2024-03-24', '2024-03-25', '2024-03-26', '2024-03-27', '2024-03-28', '2024-03-29', '2024-03-30', '2024-03-31', '2024-04-01', '2024-04-02', '2024-04-03', '2024-04-04', '2024-04-05', '2024-04-06', '2024-04-07', '2024-04-08', '2024-04-09', '2024-04-10', '2024-04-11', '2024-04-12', '2024-04-13', '2024-04-14', '2024-04-15', '2024-04-16', '2024-04-17', '2024-04-18', '2024-04-19', '2024-04-20', '2024-04-21', '2024-04-22', '2024-04-23', '2024-04-24', '2024-04-25', '2024-04-26', '2024-04-27', '2024-04-28', '2024-04-29', '2024-04-30', '2024-05-01', '2024-05-02', '2024-05-03', '2024-05-04', '2024-05-05', '2024-05-06', '2024-05-07', '2024-05-08', '2024-05-09', '2024-05-10', '2024-05-11', '2024-05-12', '2024-05-13', '2024-05-14', '2024-05-15', '2024-05-16', '2024-05-17', '2024-05-18', '2024-05-19', '2024-05-20', '2024-05-21', '2024-05-22', '2024-05-23', '2024-05-24', '2024-05-25', '2024-05-26', '2024-05-27', '2024-05-28', '2024-05-29', '2024-05-30', '2024-05-31', '2024-06-01']

In [8]:
len(dates)

153

In [9]:
gr_timeline = pd.DataFrame()

In [10]:
data = []
for index, row in gr_grid.iterrows():
    for date in dates:
        data.append({'x': row['x'], 
                     'y': row['y'], 
                     'cell_number': row['cell_number'],  
                     'dt_placement': date,
                     'NUTS2_ID': row['NUTS2_ID'],
                     })

gr_timeline = pd.DataFrame(data)

In [11]:
gr_timeline

               x         y  cell_number dt_placement NUTS2_ID
0       23.65882  41.33542            0   2024-01-01     EL51
1       23.65882  41.33542            0   2024-01-02     EL51
2       23.65882  41.33542            0   2024-01-03     EL51
3       23.65882  41.33542            0   2024-01-04     EL51
4       23.65882  41.33542            0   2024-01-05     EL51
...          ...       ...          ...          ...      ...
499693  26.60756  41.40729         3265   2024-05-28     EL51
499694  26.60756  41.40729         3265   2024-05-29     EL51
499695  26.60756  41.40729         3265   2024-05-30     EL51
499696  26.60756  41.40729         3265   2024-05-31     EL51
499697  26.60756  41.40729         3265   2024-06-01     EL51

[499698 rows x 5 columns]

In [12]:
gr_timeline['dt_placement'] = pd.to_datetime(gr_timeline['dt_placement'])

In [13]:
gr_timeline['year'] = gr_timeline['dt_placement'].apply(lambda x: x.year)

In [14]:
gr_timeline.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 499698 entries, 0 to 499697
Data columns (total 6 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   x             499698 non-null  float64
 1   y             499698 non-null  float64
 2   cell_number   499698 non-null  int64
 3   dt_placement  499698 non-null  datetime64[ns]
 4   NUTS2_ID      499698 non-null  object
 5   year          499698 non-null  int64
dtypes: datetime64[ns](1), float64(2), int64(2), object(1)
memory usage: 22.9+ MB

In [15]:
years = gr_timeline.year.unique().tolist()

In [16]:
for item in years:
    gr_timeline[gr_timeline.year == item].drop(columns = ['year']).to_csv(f'../../data/{NUTS2}/{NUTS0}_{NUTS2}_Timeline_GRID_{item}.csv', index = False)

In [17]:
gr_timeline

               x         y  cell_number dt_placement NUTS2_ID  year
0       23.65882  41.33542            0   2024-01-01     EL51  2024
1       23.65882  41.33542            0   2024-01-02     EL51  2024
2       23.65882  41.33542            0   2024-01-03     EL51  2024
3       23.65882  41.33542            0   2024-01-04     EL51  2024
4       23.65882  41.33542            0   2024-01-05     EL51  2024
...          ...       ...          ...          ...      ...   ...
499693  26.60756  41.40729         3265   2024-05-28     EL51  2024
499694  26.60756  41.40729         3265   2024-05-29     EL51  2024
499695  26.60756  41.40729         3265   2024-05-30     EL51  2024
499696  26.60756  41.40729         3265   2024-05-31     EL51  2024
499697  26.60756  41.40729         3265   2024-06-01     EL51  2024

[499698 rows x 6 columns]

In [18]:
filled_file = pd.read_csv(f'../../data/{NUTS2}/{NUTS0}_{NUTS2}_Timeline_GRID_2022-2023_filled.csv', encoding = enc)

FileNotFoundError: [Errno 2] No such file or directory: '../../data/Thessaly/GR_Thessaly_Timeline_GRID_2022-2023_filled.csv'

In [ ]:
years = filled_file.year.unique().tolist()

In [ ]:
years

[2022, 2023]

In [ ]:
for item in years:
    filled_file[filled_file.year == item].to_csv(f'../../data/{NUTS2}/{NUTS0}_{NUTS2}_Timeline_GRID_{item}_filled.csv', index = False)