## Creates the **Timeline** for a specific region by using the Grid File and the required dates ##

In [1]:
import pandas as pd
from datetime import date, timedelta

import random
import geopandas as gpd
import numpy as np

import sys

sys.path.insert(0, "../../../Modules")

from utils import *

pd.options.display.max_columns = None

enc = 'utf-8'
dec = 'greek8'
random.seed(0)

In [2]:
NUTS0 = 'GR'
NUTS2 = 'Thrace'

In [3]:
gr_grid = pd.read_csv(f'../../data/{NUTS2}/{NUTS0}_{NUTS2}_GRID.csv', encoding = enc)
gr_grid

      cell_number NUTS2_ID         x         y
0               0     EL51  23.65882  41.33542
1               1     EL51  23.65882  41.35339
2               2     EL51  23.65882  41.37135
3               3     EL51  23.68241  41.33542
4               4     EL51  23.68241  41.35339
...           ...      ...       ...       ...
3261         3261     EL51  26.58397  41.49712
3262         3262     EL51  26.60756  41.35339
3263         3263     EL51  26.60756  41.37135
3264         3264     EL51  26.60756  41.38932
3265         3265     EL51  26.60756  41.40729

[3266 rows x 4 columns]

In [4]:
## start and end date is defined from available epidemiological file

In [5]:
start = start_dt = date(2024, 7, 28)
end = end_dt = date(2024, 12, 31)
delta = timedelta(days=1)

In [6]:
dates = []

while start_dt <= end_dt:
    dates.append(start_dt.isoformat())
    start_dt += delta

In [7]:
print('Dates between', start, 'and', end)
print(dates)

Dates between 2024-07-28 and 2024-12-31
['2024-07-28', '2024-07-29', '2024-07-30', '2024-07-31', '2024-08-01', '2024-08-02', '2024-08-03', '2024-08-04', '2024-08-05', '2024-08-06', '2024-08-07', '2024-08-08', '2024-08-09', '2024-08-10', '2024-08-11', '2024-08-12', '2024-08-13', '2024-08-14', '2024-08-15', '2024-08-16', '2024-08-17', '2024-08-18', '2024-08-19', '2024-08-20', '2024-08-21', '2024-08-22', '2024-08-23', '2024-08-24', '2024-08-25', '2024-08-26', '2024-08-27', '2024-08-28', '2024-08-29', '2024-08-30', '2024-08-31', '2024-09-01', '2024-09-02', '2024-09-03', '2024-09-04', '2024-09-05', '2024-09-06', '2024-09-07', '2024-09-08', '2024-09-09', '2024-09-10', '2024-09-11', '2024-09-12', '2024-09-13', '2024-09-14', '2024-09-15', '2024-09-16', '2024-09-17', '2024-09-18', '2024-09-19', '2024-09-20', '2024-09-21', '2024-09-22', '2024-09-23', '2024-09-24', '2024-09-25', '2024-09-26', '2024-09-27', '2024-09-28', '2024-09-29', '2024-09-30', '2024-10-01', '2024-10-02', '2024-10-03', '2024-10-04', '2024-10-05', '2024-10-06', '2024-10-07', '2024-10-08', '2024-10-09', '2024-10-10', '2024-10-11', '2024-10-12', '2024-10-13', '2024-10-14', '2024-10-15', '2024-10-16', '2024-10-17', '2024-10-18', '2024-10-19', '2024-10-20', '2024-10-21', '2024-10-22', '2024-10-23', '2024-10-24', '2024-10-25', '2024-10-26', '2024-10-27', '2024-10-28', '2024-10-29', '2024-10-30', '2024-10-31', '2024-11-01', '2024-11-02', '2024-11-03', '2024-11-04', '2024-11-05', '2024-11-06', '2024-11-07', '2024-11-08', '2024-11-09', '2024-11-10', '2024-11-11', '2024-11-12', '2024-11-13', '2024-11-14', '2024-11-15', '2024-11-16', '2024-11-17', '2024-11-18', '2024-11-19', '2024-11-20', '2024-11-21', '2024-11-22', '2024-11-23', '2024-11-24', '2024-11-25', '2024-11-26', '2024-11-27', '2024-11-28', '2024-11-29', '2024-11-30', '2024-12-01', '2024-12-02', '2024-12-03', '2024-12-04', '2024-12-05', '2024-12-06', '2024-12-07', '2024-12-08', '2024-12-09', '2024-12-10', '2024-12-11', '2024-12-12', '2024-12-13', '2024-12-14', '2024-12-15', '2024-12-16', '2024-12-17', '2024-12-18', '2024-12-19', '2024-12-20', '2024-12-21', '2024-12-22', '2024-12-23', '2024-12-24', '2024-12-25', '2024-12-26', '2024-12-27', '2024-12-28', '2024-12-29', '2024-12-30', '2024-12-31']

In [8]:
len(dates)

157

In [9]:
gr_timeline = pd.DataFrame()

In [10]:
data = []
for index, row in gr_grid.iterrows():
    for date in dates:
        data.append({'x': row['x'], 
                     'y': row['y'], 
                     'cell_number': row['cell_number'],  
                     'dt_placement': date,
                     'NUTS2_ID': row['NUTS2_ID'],
                     })

gr_timeline = pd.DataFrame(data)

In [11]:
gr_timeline

               x         y  cell_number dt_placement NUTS2_ID
0       23.65882  41.33542            0   2024-07-28     EL51
1       23.65882  41.33542            0   2024-07-29     EL51
2       23.65882  41.33542            0   2024-07-30     EL51
3       23.65882  41.33542            0   2024-07-31     EL51
4       23.65882  41.33542            0   2024-08-01     EL51
...          ...       ...          ...          ...      ...
512757  26.60756  41.40729         3265   2024-12-27     EL51
512758  26.60756  41.40729         3265   2024-12-28     EL51
512759  26.60756  41.40729         3265   2024-12-29     EL51
512760  26.60756  41.40729         3265   2024-12-30     EL51
512761  26.60756  41.40729         3265   2024-12-31     EL51

[512762 rows x 5 columns]

In [12]:
gr_timeline['dt_placement'] = pd.to_datetime(gr_timeline['dt_placement'])

In [13]:
gr_timeline['year'] = gr_timeline['dt_placement'].apply(lambda x: x.year)

In [14]:
gr_timeline.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 512762 entries, 0 to 512761
Data columns (total 6 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   x             512762 non-null  float64
 1   y             512762 non-null  float64
 2   cell_number   512762 non-null  int64
 3   dt_placement  512762 non-null  datetime64[ns]
 4   NUTS2_ID      512762 non-null  object
 5   year          512762 non-null  int64
dtypes: datetime64[ns](1), float64(2), int64(2), object(1)
memory usage: 23.5+ MB

In [15]:
years = gr_timeline.year.unique().tolist()

In [16]:
for item in years:
    gr_timeline[gr_timeline.year == item].drop(columns = ['year']).to_csv(f'../../data/{NUTS2}/{NUTS0}_{NUTS2}_Timeline_GRID_{item}.csv', index = False)

In [17]:
gr_timeline

               x         y  cell_number dt_placement NUTS2_ID  year
0       23.65882  41.33542            0   2024-07-28     EL51  2024
1       23.65882  41.33542            0   2024-07-29     EL51  2024
2       23.65882  41.33542            0   2024-07-30     EL51  2024
3       23.65882  41.33542            0   2024-07-31     EL51  2024
4       23.65882  41.33542            0   2024-08-01     EL51  2024
...          ...       ...          ...          ...      ...   ...
512757  26.60756  41.40729         3265   2024-12-27     EL51  2024
512758  26.60756  41.40729         3265   2024-12-28     EL51  2024
512759  26.60756  41.40729         3265   2024-12-29     EL51  2024
512760  26.60756  41.40729         3265   2024-12-30     EL51  2024
512761  26.60756  41.40729         3265   2024-12-31     EL51  2024

[512762 rows x 6 columns]

In [18]:
# filled_file = pd.read_csv(f'../../data/{NUTS2}/{NUTS0}_{NUTS2}_Timeline_GRID_2022-2023_filled.csv', encoding = enc)

In [19]:
# years = filled_file.year.unique().tolist()

In [20]:
# years

In [21]:
# for item in years:
#     filled_file[filled_file.year == item].to_csv(f'../../data/{NUTS2}/{NUTS0}_{NUTS2}_Timeline_GRID_{item}_filled.csv', index = False)