## Creates the **Timeline** for a specific region by using the Grid File and the required dates ##

In [1]:
import pandas as pd
from datetime import date, timedelta

import random
import geopandas as gpd
import numpy as np

import sys

sys.path.insert(0, "../../../Modules")

from utils import *

pd.options.display.max_columns = None

enc = 'utf-8'
dec = 'greek8'
random.seed(0)

In [2]:
NUTS0 = 'GR'
NUTS2 = 'Thrace'

In [3]:
gr_grid = pd.read_csv(f'../../data/{NUTS2}/{NUTS0}_{NUTS2}_GRID.csv', encoding = enc)
gr_grid

      cell_number NUTS2_ID         x         y
0               0     EL51  23.65882  41.33542
1               1     EL51  23.65882  41.35339
2               2     EL51  23.65882  41.37135
3               3     EL51  23.68241  41.33542
4               4     EL51  23.68241  41.35339
...           ...      ...       ...       ...
3261         3261     EL51  26.58397  41.49712
3262         3262     EL51  26.60756  41.35339
3263         3263     EL51  26.60756  41.37135
3264         3264     EL51  26.60756  41.38932
3265         3265     EL51  26.60756  41.40729

[3266 rows x 4 columns]

In [4]:
## start and end date is defined from available epidemiological file

In [5]:
start = start_dt = date(2025, 1, 1)
end = end_dt = date(2025, 5, 1)
delta = timedelta(days=1)

In [6]:
dates = []

while start_dt <= end_dt:
    dates.append(start_dt.isoformat())
    start_dt += delta

In [7]:
print('Dates between', start, 'and', end)
print(dates)

Dates between 2025-01-01 and 2025-05-01
['2025-01-01', '2025-01-02', '2025-01-03', '2025-01-04', '2025-01-05', '2025-01-06', '2025-01-07', '2025-01-08', '2025-01-09', '2025-01-10', '2025-01-11', '2025-01-12', '2025-01-13', '2025-01-14', '2025-01-15', '2025-01-16', '2025-01-17', '2025-01-18', '2025-01-19', '2025-01-20', '2025-01-21', '2025-01-22', '2025-01-23', '2025-01-24', '2025-01-25', '2025-01-26', '2025-01-27', '2025-01-28', '2025-01-29', '2025-01-30', '2025-01-31', '2025-02-01', '2025-02-02', '2025-02-03', '2025-02-04', '2025-02-05', '2025-02-06', '2025-02-07', '2025-02-08', '2025-02-09', '2025-02-10', '2025-02-11', '2025-02-12', '2025-02-13', '2025-02-14', '2025-02-15', '2025-02-16', '2025-02-17', '2025-02-18', '2025-02-19', '2025-02-20', '2025-02-21', '2025-02-22', '2025-02-23', '2025-02-24', '2025-02-25', '2025-02-26', '2025-02-27', '2025-02-28', '2025-03-01', '2025-03-02', '2025-03-03', '2025-03-04', '2025-03-05', '2025-03-06', '2025-03-07', '2025-03-08', '2025-03-09', '2025-03-10', '2025-03-11', '2025-03-12', '2025-03-13', '2025-03-14', '2025-03-15', '2025-03-16', '2025-03-17', '2025-03-18', '2025-03-19', '2025-03-20', '2025-03-21', '2025-03-22', '2025-03-23', '2025-03-24', '2025-03-25', '2025-03-26', '2025-03-27', '2025-03-28', '2025-03-29', '2025-03-30', '2025-03-31', '2025-04-01', '2025-04-02', '2025-04-03', '2025-04-04', '2025-04-05', '2025-04-06', '2025-04-07', '2025-04-08', '2025-04-09', '2025-04-10', '2025-04-11', '2025-04-12', '2025-04-13', '2025-04-14', '2025-04-15', '2025-04-16', '2025-04-17', '2025-04-18', '2025-04-19', '2025-04-20', '2025-04-21', '2025-04-22', '2025-04-23', '2025-04-24', '2025-04-25', '2025-04-26', '2025-04-27', '2025-04-28', '2025-04-29', '2025-04-30', '2025-05-01']

In [8]:
len(dates)

121

In [9]:
gr_timeline = pd.DataFrame()

In [10]:
data = []
for index, row in gr_grid.iterrows():
    for date in dates:
        data.append({'x': row['x'], 
                     'y': row['y'], 
                     'cell_number': row['cell_number'],  
                     'dt_placement': date,
                     'NUTS2_ID': row['NUTS2_ID'],
                     })

gr_timeline = pd.DataFrame(data)

In [11]:
gr_timeline

               x         y  cell_number dt_placement NUTS2_ID
0       23.65882  41.33542            0   2025-01-01     EL51
1       23.65882  41.33542            0   2025-01-02     EL51
2       23.65882  41.33542            0   2025-01-03     EL51
3       23.65882  41.33542            0   2025-01-04     EL51
4       23.65882  41.33542            0   2025-01-05     EL51
...          ...       ...          ...          ...      ...
395181  26.60756  41.40729         3265   2025-04-27     EL51
395182  26.60756  41.40729         3265   2025-04-28     EL51
395183  26.60756  41.40729         3265   2025-04-29     EL51
395184  26.60756  41.40729         3265   2025-04-30     EL51
395185  26.60756  41.40729         3265   2025-05-01     EL51

[395186 rows x 5 columns]

In [12]:
gr_timeline['dt_placement'] = pd.to_datetime(gr_timeline['dt_placement'])

In [13]:
gr_timeline['year'] = gr_timeline['dt_placement'].apply(lambda x: x.year)

In [14]:
gr_timeline.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 395186 entries, 0 to 395185
Data columns (total 6 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   x             395186 non-null  float64
 1   y             395186 non-null  float64
 2   cell_number   395186 non-null  int64
 3   dt_placement  395186 non-null  datetime64[ns]
 4   NUTS2_ID      395186 non-null  object
 5   year          395186 non-null  int64
dtypes: datetime64[ns](1), float64(2), int64(2), object(1)
memory usage: 18.1+ MB

In [15]:
years = gr_timeline.year.unique().tolist()

In [16]:
for item in years:
    gr_timeline[gr_timeline.year == item].drop(columns = ['year']).to_csv(f'../../data/{NUTS2}/{NUTS0}_{NUTS2}_Timeline_GRID_{item}.csv', index = False)

In [17]:
gr_timeline

               x         y  cell_number dt_placement NUTS2_ID  year
0       23.65882  41.33542            0   2025-01-01     EL51  2025
1       23.65882  41.33542            0   2025-01-02     EL51  2025
2       23.65882  41.33542            0   2025-01-03     EL51  2025
3       23.65882  41.33542            0   2025-01-04     EL51  2025
4       23.65882  41.33542            0   2025-01-05     EL51  2025
...          ...       ...          ...          ...      ...   ...
395181  26.60756  41.40729         3265   2025-04-27     EL51  2025
395182  26.60756  41.40729         3265   2025-04-28     EL51  2025
395183  26.60756  41.40729         3265   2025-04-29     EL51  2025
395184  26.60756  41.40729         3265   2025-04-30     EL51  2025
395185  26.60756  41.40729         3265   2025-05-01     EL51  2025

[395186 rows x 6 columns]

In [18]:
# filled_file = pd.read_csv(f'../../data/{NUTS2}/{NUTS0}_{NUTS2}_Timeline_GRID_2022-2023_filled.csv', encoding = enc)

In [19]:
# years = filled_file.year.unique().tolist()

In [20]:
# years

In [21]:
# for item in years:
#     filled_file[filled_file.year == item].to_csv(f'../../data/{NUTS2}/{NUTS0}_{NUTS2}_Timeline_GRID_{item}_filled.csv', index = False)