## Creates the **Timeline** for a specific region by using the Grid File and the required dates ##

In [1]:
import pandas as pd
from datetime import date, timedelta

import random
import geopandas as gpd
import numpy as np

import sys

sys.path.insert(0, "../../../Modules")

from utils import *

pd.options.display.max_columns = None

enc = 'utf-8'
dec = 'greek8'
random.seed(0)

In [2]:
NUTS0 = 'GR'
NUTS2 = 'Thrace'

In [3]:
gr_grid = pd.read_csv(f'../../data/{NUTS2}/{NUTS0}_{NUTS2}_GRID.csv', encoding = enc)
gr_grid

      cell_number NUTS2_ID         x         y
0               0     EL51  23.65882  41.33542
1               1     EL51  23.65882  41.35339
2               2     EL51  23.65882  41.37135
3               3     EL51  23.68241  41.33542
4               4     EL51  23.68241  41.35339
...           ...      ...       ...       ...
3261         3261     EL51  26.58397  41.49712
3262         3262     EL51  26.60756  41.35339
3263         3263     EL51  26.60756  41.37135
3264         3264     EL51  26.60756  41.38932
3265         3265     EL51  26.60756  41.40729

[3266 rows x 4 columns]

In [4]:
## start and end date is defined from available epidemiological file

In [5]:
start = start_dt = date(2025, 6, 2)
end = end_dt = date(2025, 7, 1)
delta = timedelta(days=1)

In [6]:
dates = []

while start_dt <= end_dt:
    dates.append(start_dt.isoformat())
    start_dt += delta

In [7]:
print('Dates between', start, 'and', end)
print(dates)

Dates between 2025-06-02 and 2025-07-01
['2025-06-02', '2025-06-03', '2025-06-04', '2025-06-05', '2025-06-06', '2025-06-07', '2025-06-08', '2025-06-09', '2025-06-10', '2025-06-11', '2025-06-12', '2025-06-13', '2025-06-14', '2025-06-15', '2025-06-16', '2025-06-17', '2025-06-18', '2025-06-19', '2025-06-20', '2025-06-21', '2025-06-22', '2025-06-23', '2025-06-24', '2025-06-25', '2025-06-26', '2025-06-27', '2025-06-28', '2025-06-29', '2025-06-30', '2025-07-01']

In [8]:
len(dates)

30

In [9]:
gr_timeline = pd.DataFrame()

In [10]:
data = []
for index, row in gr_grid.iterrows():
    for date in dates:
        data.append({'x': row['x'], 
                     'y': row['y'], 
                     'cell_number': row['cell_number'],  
                     'dt_placement': date,
                     'NUTS2_ID': row['NUTS2_ID'],
                     })

gr_timeline = pd.DataFrame(data)

In [11]:
gr_timeline

              x         y  cell_number dt_placement NUTS2_ID
0      23.65882  41.33542            0   2025-06-02     EL51
1      23.65882  41.33542            0   2025-06-03     EL51
2      23.65882  41.33542            0   2025-06-04     EL51
3      23.65882  41.33542            0   2025-06-05     EL51
4      23.65882  41.33542            0   2025-06-06     EL51
...         ...       ...          ...          ...      ...
97975  26.60756  41.40729         3265   2025-06-27     EL51
97976  26.60756  41.40729         3265   2025-06-28     EL51
97977  26.60756  41.40729         3265   2025-06-29     EL51
97978  26.60756  41.40729         3265   2025-06-30     EL51
97979  26.60756  41.40729         3265   2025-07-01     EL51

[97980 rows x 5 columns]

In [12]:
gr_timeline['dt_placement'] = pd.to_datetime(gr_timeline['dt_placement'])

In [13]:
gr_timeline['year'] = gr_timeline['dt_placement'].apply(lambda x: x.year)

In [14]:
gr_timeline.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 97980 entries, 0 to 97979
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   x             97980 non-null  float64
 1   y             97980 non-null  float64
 2   cell_number   97980 non-null  int64
 3   dt_placement  97980 non-null  datetime64[ns]
 4   NUTS2_ID      97980 non-null  object
 5   year          97980 non-null  int64
dtypes: datetime64[ns](1), float64(2), int64(2), object(1)
memory usage: 4.5+ MB

In [15]:
years = gr_timeline.year.unique().tolist()

In [16]:
for item in years:
    gr_timeline[gr_timeline.year == item].drop(columns = ['year']).to_csv(f'../../data/{NUTS2}/{NUTS0}_{NUTS2}_Timeline_GRID_{item}.csv', index = False)

In [17]:
gr_timeline

              x         y  cell_number dt_placement NUTS2_ID  year
0      23.65882  41.33542            0   2025-06-02     EL51  2025
1      23.65882  41.33542            0   2025-06-03     EL51  2025
2      23.65882  41.33542            0   2025-06-04     EL51  2025
3      23.65882  41.33542            0   2025-06-05     EL51  2025
4      23.65882  41.33542            0   2025-06-06     EL51  2025
...         ...       ...          ...          ...      ...   ...
97975  26.60756  41.40729         3265   2025-06-27     EL51  2025
97976  26.60756  41.40729         3265   2025-06-28     EL51  2025
97977  26.60756  41.40729         3265   2025-06-29     EL51  2025
97978  26.60756  41.40729         3265   2025-06-30     EL51  2025
97979  26.60756  41.40729         3265   2025-07-01     EL51  2025

[97980 rows x 6 columns]

In [18]:
# filled_file = pd.read_csv(f'../../data/{NUTS2}/{NUTS0}_{NUTS2}_Timeline_GRID_2022-2023_filled.csv', encoding = enc)

In [19]:
# years = filled_file.year.unique().tolist()

In [20]:
# years

In [21]:
# for item in years:
#     filled_file[filled_file.year == item].to_csv(f'../../data/{NUTS2}/{NUTS0}_{NUTS2}_Timeline_GRID_{item}_filled.csv', index = False)