## Creates the **Timeline** for a specific region by using the Grid File and the required dates ##

In [1]:
import pandas as pd
from datetime import date, timedelta

import random
import geopandas as gpd
import numpy as np

import sys

sys.path.insert(0, "../../../Modules")

from utils import *

pd.options.display.max_columns = None

enc = 'utf-8'
dec = 'greek8'
random.seed(0)

In [2]:
NUTS0 = 'GR'
NUTS2 = 'CMacedonia'

In [3]:
gr_grid = pd.read_csv(f'../../data/{NUTS2}/{NUTS0}_{NUTS2}_GRID.csv', encoding = enc)
gr_grid

      cell_number NUTS2_ID         x         y
0               0     EL52  21.76334  40.79806
1               1     EL52  21.76334  40.81603
2               2     EL52  21.76334  40.83400
3               3     EL52  21.76334  40.85196
4               4     EL52  21.78676  40.79806
...           ...      ...       ...       ...
4411         4411     EL52  24.05875  40.99570
4412         4412     EL52  24.05875  41.01366
4413         4413     EL52  24.08217  40.95976
4414         4414     EL52  24.08217  40.97773
4415         4415     EL52  24.08217  40.99570

[4416 rows x 4 columns]

In [4]:
## start and end date is defined from available epidemiological file

In [5]:
start = start_dt = date(2024, 5, 2)
end = end_dt = date(2024, 6, 1)
delta = timedelta(days=1)

In [6]:
dates = []

while start_dt <= end_dt:
    dates.append(start_dt.isoformat())
    start_dt += delta

In [7]:
print('Dates between', start, 'and', end)
print(dates)

Dates between 2024-05-02 and 2024-06-01
['2024-05-02', '2024-05-03', '2024-05-04', '2024-05-05', '2024-05-06', '2024-05-07', '2024-05-08', '2024-05-09', '2024-05-10', '2024-05-11', '2024-05-12', '2024-05-13', '2024-05-14', '2024-05-15', '2024-05-16', '2024-05-17', '2024-05-18', '2024-05-19', '2024-05-20', '2024-05-21', '2024-05-22', '2024-05-23', '2024-05-24', '2024-05-25', '2024-05-26', '2024-05-27', '2024-05-28', '2024-05-29', '2024-05-30', '2024-05-31', '2024-06-01']

In [8]:
len(dates)

31

In [9]:
gr_timeline = pd.DataFrame()

In [10]:
data = []
for index, row in gr_grid.iterrows():
    for date in dates:
        data.append({'x': row['x'], 
                     'y': row['y'], 
                     'cell_number': row['cell_number'],  
                     'dt_placement': date,
                     'NUTS2_ID': row['NUTS2_ID'],
                     })

gr_timeline = pd.DataFrame(data)

In [11]:
gr_timeline

               x         y  cell_number dt_placement NUTS2_ID
0       21.76334  40.79806            0   2024-05-02     EL52
1       21.76334  40.79806            0   2024-05-03     EL52
2       21.76334  40.79806            0   2024-05-04     EL52
3       21.76334  40.79806            0   2024-05-05     EL52
4       21.76334  40.79806            0   2024-05-06     EL52
...          ...       ...          ...          ...      ...
136891  24.08217  40.99570         4415   2024-05-28     EL52
136892  24.08217  40.99570         4415   2024-05-29     EL52
136893  24.08217  40.99570         4415   2024-05-30     EL52
136894  24.08217  40.99570         4415   2024-05-31     EL52
136895  24.08217  40.99570         4415   2024-06-01     EL52

[136896 rows x 5 columns]

In [12]:
gr_timeline['dt_placement'] = pd.to_datetime(gr_timeline['dt_placement'])

In [13]:
gr_timeline['year'] = gr_timeline['dt_placement'].apply(lambda x: x.year)

In [14]:
gr_timeline.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 136896 entries, 0 to 136895
Data columns (total 6 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   x             136896 non-null  float64
 1   y             136896 non-null  float64
 2   cell_number   136896 non-null  int64
 3   dt_placement  136896 non-null  datetime64[ns]
 4   NUTS2_ID      136896 non-null  object
 5   year          136896 non-null  int64
dtypes: datetime64[ns](1), float64(2), int64(2), object(1)
memory usage: 6.3+ MB

In [15]:
years = gr_timeline.year.unique().tolist()

In [16]:
for item in years:
    gr_timeline[gr_timeline.year == item].drop(columns = ['year']).to_csv(f'../../data/{NUTS2}/{NUTS0}_{NUTS2}_Timeline_GRID_{item}.csv', index = False)

In [17]:
gr_timeline

               x         y  cell_number dt_placement NUTS2_ID  year
0       21.76334  40.79806            0   2024-05-02     EL52  2024
1       21.76334  40.79806            0   2024-05-03     EL52  2024
2       21.76334  40.79806            0   2024-05-04     EL52  2024
3       21.76334  40.79806            0   2024-05-05     EL52  2024
4       21.76334  40.79806            0   2024-05-06     EL52  2024
...          ...       ...          ...          ...      ...   ...
136891  24.08217  40.99570         4415   2024-05-28     EL52  2024
136892  24.08217  40.99570         4415   2024-05-29     EL52  2024
136893  24.08217  40.99570         4415   2024-05-30     EL52  2024
136894  24.08217  40.99570         4415   2024-05-31     EL52  2024
136895  24.08217  40.99570         4415   2024-06-01     EL52  2024

[136896 rows x 6 columns]

In [42]:
filled_file = pd.read_csv(f'../../data/{NUTS2}/{NUTS0}_{NUTS2}_Timeline_GRID_2022-2023_filled.csv', encoding = enc)

In [43]:
years = filled_file.year.unique().tolist()

In [44]:
years

[2022, 2023]

In [45]:
for item in years:
    filled_file[filled_file.year == item].to_csv(f'../../data/{NUTS2}/{NUTS0}_{NUTS2}_Timeline_GRID_{item}_filled.csv', index = False)