In [1]:
import pandas as pd
import sys

sys.path.insert(0, "../../Modules")

from preprocessing_utils import process_greek

enc = 'utf-8'
dec = 'greek8'

In [2]:
df_demograpchics = pd.read_csv('../data/GR_WEB_Demographics_Raw.csv', encoding=enc)
df_demograpchics

,lau1,nuts2,nuts3,area,population_density,population
0,Αβδήρων,Ανατολικής Μακεδονίας και Θράκης,Ξάνθης,352.0,54.0,17860.0
1,Αγαθονησίου,Νοτίου Αιγαίου,Καλύμνου,14.5,12.8,203.0
2,Αγιάς,Θεσσαλίας,Λάρισας,661.8,17.3,10705.0
3,Αγίας Βαρβάρας,Αττικής,Δυτικού Τομέα Αθηνών,2.4,10925.9,26759.0
4,Αγίας Παρασκευής,Αττικής,Βορείου Τομέα Αθηνών,7.9,7557.5,62157.0
...,...,...,...,...,...,...
327,Χανίων,Κρήτης,Χανίων,351.3,309.3,110646.0
328,Χερσονήσου,Κρήτης,Ηρακλείου,272.2,98.2,27229.0
329,Χίου,Βορείου Αιγαίου,Χίου,842.3,61.0,50483.0
330,Ωραιοκάστρου,Κεντρικής Μακεδονίας,Θεσσαλονίκης,217.9,175.8,40114.0
331,Ωρωπού,Αττικής,Ανατολικής Αττικής,338.2,99.8,33977.0

In [3]:
df_demograpchics.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 332 entries, 0 to 331
Data columns (total 6 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   lau1                332 non-null    object
 1   nuts2               332 non-null    object
 2   nuts3               332 non-null    object
 3   area                332 non-null    float64
 4   population_density  332 non-null    float64
 5   population          332 non-null    float64
dtypes: float64(3), object(3)
memory usage: 15.7+ KB

In [4]:
process_greek(df_demograpchics, 'lau1')
process_greek(df_demograpchics, 'nuts2')
process_greek(df_demograpchics, 'nuts3')

In [5]:
df_demograpchics

,lau1,nuts2,nuts3,area,population_density,population
0,αβδηρων,ανατολικης μακεδονιας και θρακης,ξανθης,352.0,54.0,17860.0
1,αγαθονησιου,νοτιου αιγαιου,καλυμνου,14.5,12.8,203.0
2,αγιας,θεσσαλιας,λαρισας,661.8,17.3,10705.0
3,αγιας βαρβαρας,αττικης,δυτικου τομεα αθηνων,2.4,10925.9,26759.0
4,αγιας παρασκευης,αττικης,βορειου τομεα αθηνων,7.9,7557.5,62157.0
...,...,...,...,...,...,...
327,χανιων,κρητης,χανιων,351.3,309.3,110646.0
328,χερσονησου,κρητης,ηρακλειου,272.2,98.2,27229.0
329,χιου,βορειου αιγαιου,χιου,842.3,61.0,50483.0
330,ωραιοκαστρου,κεντρικης μακεδονιας,θεσσαλονικης,217.9,175.8,40114.0
331,ωρωπου,αττικης,ανατολικης αττικης,338.2,99.8,33977.0

In [6]:
demographics_lau1 = df_demograpchics['lau1'].unique().tolist()
demographics_lau1.sort()

demographics_nuts2 = df_demograpchics['nuts2'].unique().tolist()
demographics_nuts2.sort()

demographics_nuts3 = df_demograpchics['nuts3'].unique().tolist()
demographics_nuts3.sort()

with open('../data/GR_WEB_demographics_lau1_processed.txt', 'w', encoding=enc) as f:
    for item in demographics_lau1:
        f.write("%s\n" % item)

with open('../data/GR_WEB_demographics_nuts2_processed.txt', 'w', encoding=enc) as f:
    for item in demographics_nuts2:
        f.write("%s\n" % item)

with open('../data/GR_WEB_demographics_nuts3_processed.txt', 'w', encoding=enc) as f:
    for item in demographics_nuts3:
        f.write("%s\n" % item)

print(f"Number of LAU1 Units in Greece (from demographics file): {len(demographics_lau1)}")

Number of LAU1 Units in Greece (from demographics file): 331

In [7]:
df_demograpchics.to_csv('../data/GR_WEB_Demographics_Processed.csv', index=False)