In [1]:
import pandas as pd
from datetime import date, timedelta

import random
import geopandas as gpd
import numpy as np

import sys

sys.path.insert(0, "../../utils")

from plots import *
from string_handling import *

enc = 'utf-8' 

random.seed(0)
np.random.seed(0)

pd.set_option('display.max_columns', None)

REGION = 'Nord'

In [2]:
cm_nord_grid = pd.read_csv(f'../../data/{REGION}/CM_{REGION}_Grid.csv', encoding=enc)
cm_nord_grid.head()

          x        y  GID0  GID1  GID2      GID3
0  12.29306  8.21972  nord  faro  poli  balkossa
1  12.29306  8.25566  nord  faro  poli  balkossa
2  12.29306  8.29159  nord  faro  poli  balkossa
3  12.29306  8.32752  nord  faro  poli  balkossa
4  12.29306  8.36346  nord  faro  poli  balkossa

In [3]:
start = start_dt = date(2025, 11, 1)
end = end_dt = date(2025, 12, 1)
delta = timedelta(days=1)

In [4]:
dates = []

while start_dt <= end_dt:
    dates.append(start_dt.isoformat())
    start_dt += delta

In [5]:
print('Dates between', start, 'and', end)
print(dates)

Dates between 2025-11-01 and 2025-12-01
['2025-11-01', '2025-11-02', '2025-11-03', '2025-11-04', '2025-11-05', '2025-11-06', '2025-11-07', '2025-11-08', '2025-11-09', '2025-11-10', '2025-11-11', '2025-11-12', '2025-11-13', '2025-11-14', '2025-11-15', '2025-11-16', '2025-11-17', '2025-11-18', '2025-11-19', '2025-11-20', '2025-11-21', '2025-11-22', '2025-11-23', '2025-11-24', '2025-11-25', '2025-11-26', '2025-11-27', '2025-11-28', '2025-11-29', '2025-11-30', '2025-12-01']

In [6]:
len(dates)

31

In [7]:
print(f'Total Rows: {len(dates) * len(cm_nord_grid)}')

Total Rows: 122729

In [8]:
cm_timeline = pd.DataFrame()

In [9]:
data = []
for index, row in cm_nord_grid.iterrows():
    for date in dates:
        data.append({'x': row['x'], 
                     'y': row['y'],
                     'GID0': row['GID0'], 
                     'GID1': row['GID1'],
                     'GID2': row['GID2'], 
                     'GID3': row['GID3'],  
                     'dt_placement': date})

In [10]:
cm_timeline = pd.DataFrame(data)

In [11]:
cm_timeline

               x        y  GID0      GID1     GID2      GID3 dt_placement
0       12.29306  8.21972  nord      faro     poli  balkossa   2025-11-01
1       12.29306  8.21972  nord      faro     poli  balkossa   2025-11-02
2       12.29306  8.21972  nord      faro     poli  balkossa   2025-11-03
3       12.29306  8.21972  nord      faro     poli  balkossa   2025-11-04
4       12.29306  8.21972  nord      faro     poli  balkossa   2025-11-05
...          ...      ...   ...       ...      ...       ...          ...
122724  15.55146  7.75259  nord  mayo-rey  touboro    mafare   2025-11-27
122725  15.55146  7.75259  nord  mayo-rey  touboro    mafare   2025-11-28
122726  15.55146  7.75259  nord  mayo-rey  touboro    mafare   2025-11-29
122727  15.55146  7.75259  nord  mayo-rey  touboro    mafare   2025-11-30
122728  15.55146  7.75259  nord  mayo-rey  touboro    mafare   2025-12-01

[122729 rows x 7 columns]

In [12]:
cm_timeline['dt_placement'] = pd.to_datetime(cm_timeline['dt_placement'])
cm_timeline['year'] = cm_timeline['dt_placement'].apply(lambda x: x.year)

In [13]:
cm_timeline.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 122729 entries, 0 to 122728
Data columns (total 8 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   x             122729 non-null  float64
 1   y             122729 non-null  float64
 2   GID0          122729 non-null  object
 3   GID1          122729 non-null  object
 4   GID2          122729 non-null  object
 5   GID3          122729 non-null  object
 6   dt_placement  122729 non-null  datetime64[ns]
 7   year          122729 non-null  int64
dtypes: datetime64[ns](1), float64(2), int64(1), object(4)
memory usage: 7.5+ MB

In [14]:
years = cm_timeline.year.unique().tolist()

In [15]:
years

[2025]

In [16]:
## change the month here

for item in years:
    cm_towrite = cm_timeline[cm_timeline.year == item].drop(columns = ['year'])
    print(f'Year: {item}, Timeline Shape: {cm_towrite.shape}')
    cm_towrite.to_csv(f'../../data/{REGION}/CM_{REGION}_Timeline_{item}_12.csv', index = False)

Year: 2025, Timeline Shape: (122729, 7)