## Creates the **Epidemiological Timeline** for a specific region by using the available data on WNV Cases ##

In [1]:
import pandas as pd
import numpy as np

enc = 'utf-8'
dec = 'greek8'

pd.options.display.max_columns = None
pd.options.display.max_rows = 10

In [2]:
NUTS0 = 'GR'

In [3]:
data = pd.read_csv(f'../data/{NUTS0}_WNV_cases_GRID_2010-2021_processed.csv', encoding = enc)
data.head(5)

,onset of symptoms,year,month,day,nuts2,nuts3,lau1,lau2,cell_code,cases
0,2010-07-06,2010,7,6,κεντρικης μακεδονιας,σερρων,ηρακλειας,ποντισμενο,BL336,1
1,2010-07-16,2010,7,16,κεντρικης μακεδονιας,κιλκις,κιλκις,μεσοι αποστολοι,CS294,1
2,2010-07-18,2010,7,18,κεντρικης μακεδονιας,πελλας,πελλας,γιαννιτσα,DE262,1
3,2010-07-19,2010,7,19,κεντρικης μακεδονιας,θεσσαλονικης,καλαμαριας,καλαμαρια,EB307,1
4,2010-07-19,2010,7,19,κεντρικης μακεδονιας,θεσσαλονικης,καλαμαριας,καραμπουρνακι,EB308,1

In [4]:
data.shape

(1364, 10)

In [5]:
data.drop(columns = ['onset of symptoms', 'day'], inplace = True)

In [6]:
data

,year,month,nuts2,nuts3,lau1,lau2,cell_code,cases
0,2010,7,κεντρικης μακεδονιας,σερρων,ηρακλειας,ποντισμενο,BL336,1
1,2010,7,κεντρικης μακεδονιας,κιλκις,κιλκις,μεσοι αποστολοι,CS294,1
2,2010,7,κεντρικης μακεδονιας,πελλας,πελλας,γιαννιτσα,DE262,1
3,2010,7,κεντρικης μακεδονιας,θεσσαλονικης,καλαμαριας,καλαμαρια,EB307,1
4,2010,7,κεντρικης μακεδονιας,θεσσαλονικης,καλαμαριας,καραμπουρνακι,EB308,1
...,...,...,...,...,...,...,...,...
1359,2021,9,κεντρικης μακεδονιας,ημαθιας,ηρωικης πολης ναουσας,αγγελοχωρι,DQ244,1
1360,2021,9,αττικης,ανατολικης αττικης,σπατων αρτεμιδος,αρτεμιδα,PG397,1
1361,2021,9,κεντρικης μακεδονιας,ημαθιας,αλεξανδρειας,κλειδι,ED276,1
1362,2021,10,κεντρικης μακεδονιας,θεσσαλονικης,θερμαικου,περαια,EK305,1
1363,2021,10,κεντρικης μακεδονιας,ημαθιας,αλεξανδρειας,αλεξανδρεια,DW264,1

In [7]:
data.cases.sum()

1380

In [8]:
df_grouped = data.groupby(['year', 'month', 'nuts2', 'nuts3', 'lau1', 'lau2', 'cell_code'], as_index = False)
df = df_grouped.sum()

In [9]:
df

,year,month,nuts2,nuts3,lau1,lau2,cell_code,cases
0,2010,7,θεσσαλιας,λαρισας,αγιας,ομολιο,HA280,1
1,2010,7,κεντρικης μακεδονιας,ημαθιας,αλεξανδρειας,αλεξανδρεια,DW265,1
2,2010,7,κεντρικης μακεδονιας,ημαθιας,αλεξανδρειας,σταυρος,EA253,1
3,2010,7,κεντρικης μακεδονιας,ημαθιας,βεροιας,αγιος γεωργιος,DY243,1
4,2010,7,κεντρικης μακεδονιας,ημαθιας,βεροιας,βεροια,EI242,1
...,...,...,...,...,...,...,...,...
1236,2021,9,κεντρικης μακεδονιας,ημαθιας,ηρωικης πολης ναουσας,αγγελοχωρι,DQ244,1
1237,2021,9,κεντρικης μακεδονιας,θεσσαλονικης,αμπελοκηπων μενεμενης,μενεμενη,DT304,1
1238,2021,9,κεντρικης μακεδονιας,θεσσαλονικης,κορδελιου ευοσμου,κορδελιο,DS303,1
1239,2021,10,κεντρικης μακεδονιας,ημαθιας,αλεξανδρειας,αλεξανδρεια,DW264,1
1240,2021,10,κεντρικης μακεδονιας,θεσσαλονικης,θερμαικου,περαια,EK305,1

In [10]:
df.cases.sum()

1380

In [11]:
print(np.sort(df.cases.unique()))

[1 2 3 4 6]

In [53]:
df['date_string'] = df['month'].astype(str) + '-' + df['year'].astype(str)

# Convert 'date_string' column to datetime format
df['dt_placement'] = pd.to_datetime(df['date_string'], format='%m-%Y').dt.to_period('M')
df.drop(columns=['date_string'], inplace = True)

In [54]:
df

,year,month,nuts2,nuts3,lau1,lau2,cell_code,cases,dt_placement
0,2010,7,θεσσαλιας,λαρισας,αγιας,ομολιο,HA280,1,2010-07
1,2010,7,κεντρικης μακεδονιας,ημαθιας,αλεξανδρειας,αλεξανδρεια,DW265,1,2010-07
2,2010,7,κεντρικης μακεδονιας,ημαθιας,αλεξανδρειας,σταυρος,EA253,1,2010-07
3,2010,7,κεντρικης μακεδονιας,ημαθιας,βεροιας,αγιος γεωργιος,DY243,1,2010-07
4,2010,7,κεντρικης μακεδονιας,ημαθιας,βεροιας,βεροια,EI242,1,2010-07
...,...,...,...,...,...,...,...,...,...
1236,2021,9,κεντρικης μακεδονιας,ημαθιας,ηρωικης πολης ναουσας,αγγελοχωρι,DQ244,1,2021-09
1237,2021,9,κεντρικης μακεδονιας,θεσσαλονικης,αμπελοκηπων μενεμενης,μενεμενη,DT304,1,2021-09
1238,2021,9,κεντρικης μακεδονιας,θεσσαλονικης,κορδελιου ευοσμου,κορδελιο,DS303,1,2021-09
1239,2021,10,κεντρικης μακεδονιας,ημαθιας,αλεξανδρειας,αλεξανδρεια,DW264,1,2021-10
1240,2021,10,κεντρικης μακεδονιας,θεσσαλονικης,θερμαικου,περαια,EK305,1,2021-10

In [55]:
df.cases.sum()

1380

In [56]:
cell_codes = df['cell_code'].drop_duplicates().sort_values().tolist()
cell_codes

['AAK447',
 'AAP469',
 'AAY433',
 'AM597',
 'AP595',
 'AQ596',
 'AS606',
 'BC304',
 'BC316',
 'BD337',
 'BE307',
 'BE312',
 'BE320',
 'BF299',
 'BF340',
 'BH333',
 'BH345',
 'BI298',
 'BI345',
 'BI346',
 'BJ320',
 'BK336',
 'BK337',
 'BK338',
 'BK589',
 'BL336',
 'BM297',
 'BM344',
 'BN336',
 'BO339',
 'BO346',
 'BO394',
 'BP335',
 'BQ347',
 'BR341',
 'BR350',
 'BR409',
 'BR475',
 'BS340',
 'BS407',
 'BS408',
 'BS470',
 'BS471',
 'BS472',
 'BS481',
 'BS514',
 'BS588',
 'BT331',
 'BT338',
 'BT414',
 'BT468',
 'BT470',
 'BT471',
 'BT472',
 'BT478',
 'BT484',
 'BT499',
 'BT514',
 'BT515',
 'BU469',
 'BU470',
 'BU473',
 'BU476',
 'BU491',
 'BU505',
 'BU513',
 'BU514',
 'BU515',
 'BV334',
 'BV404',
 'BV473',
 'BV482',
 'BV498',
 'BW334',
 'BW340',
 'BW411',
 'BW472',
 'BX304',
 'BX354',
 'BX358',
 'BX359',
 'BX411',
 'BX416',
 'BX421',
 'BX472',
 'BX493',
 'BX497',
 'BX500',
 'BX504',
 'BX515',
 'BX539',
 'BY358',
 'BY359',
 'BY463',
 'BY477',
 'BY526',
 'BY527',
 'BZ300',
 'BZ305',
 'BZ357',
 'BZ358',
 'BZ359',
 'BZ412',
 'BZ417',
 'BZ463',
 'BZ469',
 'BZ482',
 'BZ535',
 'BZ538',
 'CA290',
 'CA461',
 'CA472',
 'CA474',
 'CA487',
 'CA520',
 'CB348',
 'CB351',
 'CB363',
 'CB477',
 'CB508',
 'CB522',
 'CC359',
 'CC361',
 'CC412',
 'CD277',
 'CD462',
 'CD468',
 'CD539',
 'CE303',
 'CE469',
 'CF243',
 'CF343',
 'CF364',
 'CF410',
 'CF425',
 'CF452',
 'CF468',
 'CF500',
 'CG243',
 'CG295',
 'CG351',
 'CG356',
 'CG421',
 'CG429',
 'CG450',
 'CG472',
 'CH343',
 'CH385',
 'CH421',
 'CH522',
 'CI276',
 'CI293',
 'CI302',
 'CI353',
 'CI450',
 'CI457',
 'CJ369',
 'CJ428',
 'CJ448',
 'CJ454',
 'CJ455',
 'CJ456',
 'CJ462',
 'CJ463',
 'CJ466',
 'CJ476',
 'CK349',
 'CK401',
 'CK455',
 'CK456',
 'CK464',
 'CK476',
 'CL393',
 'CL456',
 'CL482',
 'CL512',
 'CM348',
 'CM427',
 'CM439',
 'CM462',
 'CM464',
 'CM495',
 'CM528',
 'CN266',
 'CN297',
 'CN351',
 'CN434',
 'CN450',
 'CN463',
 'CN470',
 'CN497',
 'CO355',
 'CO430',
 'CO432',
 'CO463',
 'CO470',
 'CO510',
 'CP276',
 'CP348',
 'CP360',
 'CP430',
 'CP432',
 'CP456',
 'CP465',
 'CP466',
 'CQ291',
 'CQ422',
 'CQ429',
 'CQ456',
 'CR301',
 'CR579',
 'CS281',
 'CS294',
 'CS452',
 'CS453',
 'CS456',
 'CT364',
 'CT371',
 'CT426',
 'CT467',
 'CU305',
 'CV282',
 'CV362',
 'CV376',
 'CV377',
 'CW246',
 'CW248',
 'CW277',
 'CX302',
 'CX423',
 'CX456',
 'CX543',
 'CY253',
 'CY367',
 'CZ245',
 'CZ260',
 'CZ283',
 'CZ293',
 'CZ305',
 'DA243',
 'DA249',
 'DA266',
 'DB241',
 'DB257',
 'DB258',
 'DB263',
 'DB283',
 'DB314',
 'DB315',
 'DC232',
 'DC250',
 'DC255',
 'DC288',
 'DC301',
 'DD246',
 'DD247',
 'DD255',
 'DD258',
 'DD262',
 'DD263',
 'DD293',
 'DE241',
 'DE250',
 'DE251',
 'DE262',
 'DE263',
 'DE267',
 'DE301',
 'DF251',
 'DF262',
 'DF263',
 'DF276',
 'DF383',
 'DG238',
 'DG240',
 'DG241',
 'DG247',
 'DG254',
 'DG257',
 'DG276',
 'DG309',
 'DG385',
 'DG456',
 'DH243',
 'DH246',
 'DH249',
 'DH269',
 'DH272',
 'DH287',
 'DH387',
 'DH447',
 'DI249',
 'DI251',
 'DI266',
 'DI272',
 'DI388',
 'DI444',
 'DJ246',
 'DJ251',
 'DJ281',
 'DJ292',
 'DJ318',
 'DJ444',
 'DJ445',
 'DK239',
 'DK300',
 'DK302',
 'DL237',
 'DL278',
 'DL286',
 'DL305',
 'DM241',
 'DM246',
 'DM252',
 'DM304',
 'DM305',
 'DM372',
 'DN249',
 'DN250',
 'DN288',
 'DN289',
 'DN290',
 'DN294',
 'DN316',
 'DN371',
 'DO273',
 'DO315',
 'DO371',
 'DP239',
 'DP250',
 'DP252',
 'DP253',
 'DQ243',
 'DQ244',
 'DQ245',
 'DQ249',
 'DQ250',
 'DQ273',
 'DQ300',
 'DQ370',
 'DR278',
 'DR306',
 'DS265',
 'DS270',
 'DS295',
 'DS302',
 'DS303',
 'DS304',
 'DS305',
 'DS306',
 'DS307',
 'DT237',
 'DT241',
 'DT246',
 'DT247',
 'DT281',
 'DT303',
 'DT304',
 'DT306',
 'DT308',
 'DU238',
 'DU272',
 'DU273',
 'DU304',
 'DU305',
 'DU306',
 'DV233',
 'DV238',
 'DV265',
 'DV270',
 'DV272',
 'DV300',
 'DV306',
 'DV308',
 'DV338',
 'DW264',
 'DW265',
 'DW266',
 'DW289',
 'DW307',
 'DX261',
 'DX264',
 'DX289',
 'DX290',
 'DX308',
 'DX309',
 'DX330',
 'DX349',
 'DX353',
 'DY243',
 'DY244',
 'DY258',
 'DY264',
 'DY286',
 'DY308',
 'DY309',
 'DY310',
 'DZ245',
 'DZ257',
 'DZ274',
 'DZ308',
 'DZ309',
 'DZ310',
 'DZ311',
 'DZ320',
 'EA248',
 'EA253',
 'EA255',
 'EA258',
 'EA261',
 'EA269',
 'EA308',
 'EA309',
 'EA310',
 'EA311',
 'EA352',
 'EB307',
 'EB308',
 'EB309',
 'EB312',
 'EB315',
 'EC256',
 'EC258',
 'EC307',
 'EC308',
 'ED243',
 'ED245',
 'ED250',
 'ED256',
 'ED274',
 'ED276',
 'ED277',
 'ED308',
 'ED309',
 'EE244',
 'EE248',
 'EE249',
 'EE266',
 'EE267',
 'EE269',
 'EF254',
 'EF261',
 'EF265',
 'EF311',
 'EG244',
 'EG313',
 'EH206',
 'EH244',
 'EH245',
 'EH249',
 'EH250',
 'EH313',
 'EI242',
 'EI244',
 'EI245',
 'EI260',
 'EI261',
 'EI316',
 'EJ245',
 'EJ260',
 'EJ263',
 'EK262',
 'EK273',
 'EK305',
 'EL196',
 'EL251',
 'EL273',
 'EL301',
 'EL304',
 'EL311',
 'EL313',
 'EN268',
 'EN308',
 'EN316',
 'EO273',
 'EO300',
 'EO309',
 'EP300',
 'ES319',
 'ET305',
 'ET306',
 'EU278',
 'EU384',
 'EZ349',
 'EZ390',
 'F583',
 'F587',
 'FA273',
 'FC212',
 'FC313',
 'FF276',
 'FF316',
 'FF317',
 'FF389',
 'FG279',
 'FG317',
 'FH251',
 'FH321',
 'FI322',
 'FJ269',
 'FJ270',
 'FJ272',
 'FK269',
 'FK271',
 'FK273',
 'FK277',
 'FL272',
 'FM329',
 'FM371',
 'FN276',
 'FR339',
 'FT274',
 'FT339',
 'FV267',
 'GA345',
 'GE348',
 'GH274',
 'GJ341',
 'GL395',
 'GQ279',
 'GR265',
 'GS283',
 'GT343',
 'GV368',
 'GZ241',
 'HA245',
 'HA280',
 'HB245',
 'HD266',
 'HF227',
 'HG230',
 'HI232',
 'HK235',
 'HK267',
 'HL223',
 'HL24',
 'HN274',
 'HP234',
 'HP275',
 'HQ249',
 'HQ250',
 'HQ256',
 'HQ274',
 'HR249',
 'HR250',
 'HS259',
 'HT259',
 'HT272',
 'HW232',
 'HW284',
 'HX251',
 'HY266',
 'HY285',
 'IA259',
 'IA262',
 'IB260',
 'IB261',
 'IB262',
 'IC259',
 'IC260',
 'IC261',
 'IC262',
 'ID194',
 'ID259',
 'ID260',
 'ID261',
 'ID263',
 'ID268',
 'IE209',
 'IE260',
 'IE261',
 'IE271',
 'IE283',
 'IF261',
 'IF263',
 'IG209',
 'IG230',
 'IJ204',
 'IJ206',
 'IJ276',
 'IK203',
 'IK206',
 'IK264',
 'IK289',
 'IM213',
 'IP199',
 'IQ206',
 'IR245',
 'IS211',
 'IT232',
 'IT58',
 'IU195',
 'IU216',
 'IV207',
 'IW288',
 'JB221',
 'JC231',
 'JE215',
 'JE218',
 'JE245',
 'JG217',
 'JG218',
 'JG222',
 'JI210',
 'JJ232',
 'JJ257',
 'JK212',
 'JK222',
 'JL245',
 'JO216',
 'JO257',
 'JS209',
 'JV225',
 'KK140',
 'KZ116',
 'LR111',
 'LU333',
 'LX111',
 'MD117',
 'MP287',
 'MR164',
 'MU159',
 'MX173',
 'ND361',
 'NK172',
 'NM319',
 'NM364',
 'NO320',
 'NQ351',
 'NR367',
 'NR369',
 'NS337',
 'NS338',
 'NS370',
 'NT202',
 'NT378',
 'NT379',
 'NV203',
 'NV364',
 'NV375',
 'NW387',
 'NX384',
 'NX409',
 'NY360',
 'NY379',
 'NZ230',
 'NZ329',
 'OA228',
 'OA394',
 'OB230',
 'OC328',
 'OE234',
 'OF236',
 'OI394',
 'OL393',
 'OM393',
 'OM397',
 'ON395',
 'ON399',
 'OO396',
 'OO398',
 'OP384',
 'OQ328',
 'OQ395',
 'OR384',
 'OR394',
 'OR395',
 'OS379',
 'OS394',
 'OT167',
 'OT373',
 'OU352',
 'OU359',
 'OU362',
 'OU364',
 'OU369',
 'OU370',
 'OU371',
 'OV359',
 'OW165',
 'OW360',
 'OW361',
 'OW379',
 'OW382',
 'OX165',
 'OX282',
 'OX355',
 'OX356',
 'OX360',
 'OX372',
 'OX375',
 'OX380',
 'OX382',
 'OY356',
 'OY357',
 'OY360',
 'OY372',
 'OY373',
 'OY376',
 'OY377',
 'OY378',
 'OY380',
 'OY382',
 'OY395',
 'OZ356',
 'OZ361',
 'OZ374',
 'OZ377',
 'OZ379',
 'OZ380',
 'OZ381',
 'OZ382',
 'PA347',
 'PA370',
 'PA374',
 'PA377',
 'PA378',
 'PA380',
 'PA382',
 'PA395',
 'PA397',
 'PB345',
 'PB347',
 'PB373',
 'PB375',
 'PB380',
 'PB385',
 'PB389',
 'PC159',
 'PC338',
 'PC346',
 'PC367',
 'PC373',
 'PC374',
 'PC378',
 'PC379',
 'PC380',
 'PC386',
 'PC389',
 'PD338',
 'PD339',
 'PD345',
 'PD351',
 'PD367',
 'PD368',
 'PD369',
 'PD371',
 'PD372',
 'PD374',
 'PD377',
 'PD385',
 'PD391',
 'PE339',
 'PE340',
 'PE352',
 'PE366',
 'PE367',
 'PE374',
 'PE384',
 'PE394',
 'PE397',
 'PF349',
 'PF365',
 'PF366',
 'PF375',
 'PF376',
 'PF378',
 'PF384',
 'PF394',
 'PF397',
 'PG288',
 'PG353',
 'PG364',
 'PG365',
 'PG371',
 'PG372',
 'PG395',
 'PG397',
 'PH346',
 'PH356',
 'PH358',
 'PH359',
 'PH365',
 'PH366',
 'PH367',
 'PH370',
 'PH373',
 'PH374',
 'PH388',
 'PH395',
 'PH396',
 'PI364',
 'PI366',
 'PI368',
 'PI369',
 'PI370',
 'PI372',
 'PI384',
 'PJ295',
 'PJ368',
 'PJ369',
 'PJ370',
 'PJ371',
 'PJ372',
 'PJ373',
 'PJ375',
 'PJ398',
 'PK321',
 'PK370',
 'PK375',
 'PL350',
 'PL369',
 'PL370',
 'PL371',
 'PL372',
 'PM371',
 'PM372',
 'PN373',
 'PN374',
 'PN393',
 'PO374',
 'PO375',
 'PO399',
 'PP375',
 'PP390',
 'PP397',
 'PP398',
 'PQ390',
 'PQ397',
 'PR374',
 'PR390',
 'PS375',
 'PS376',
 'PS398',
 'PU375',
 'PU390',
 'PW400',
 'PX377',
 'PX475',
 'PY387',
 'PZ387',
 'QA387',
 'QA659',
 'QF388',
 'QG652',
 'QH392',
 'QH395',
 'QJ286',
 'QK282',
 'QL281',
 'QL283',
 'QO274',
 'QO290',
 'QQ284',
 'QQ289',
 'QR283',
 'QR284',
 'QR285',
 'QR289',
 'QR291',
 'QR292',
 'QR322',
 'QS287',
 'QS288',
 'QS290',
 'QT290',
 'QV285',
 'QV290',
 'QV339',
 'QW285',
 'QW286',
 'QW338',
 'QW339',
 'QX284',
 'QX291',
 'QY292',
 'QY293',
 'RB296',
 'RD284',
 'RI308',
 'RN287']

In [57]:
case_months = df['month'].drop_duplicates().sort_values().tolist()
case_months

[5, 6, 7, 8, 9, 10]

In [58]:
case_years = df['year'].drop_duplicates().sort_values().tolist()
case_years

[2010, 2011, 2012, 2013, 2014, 2017, 2018, 2019, 2020, 2021]

In [59]:
df.drop(columns=['month', 'year'], inplace = True)

In [60]:
## Creating DataFrame to hold negative examples

df_timeline = pd.DataFrame(columns = ['nuts2', 'nuts3', 'dt_placement', 'cases'])
timeline = []

for cell in cell_codes:
    for year in case_years:
        for month in case_months:
            timeline.append({'cell_code' : cell, 'dt_placement' : f"{year:04}-{month:02}", 'cases' : 0})
            
df_timeline = pd.DataFrame(timeline)

In [61]:
df_timeline

      cell_code dt_placement  cases
0        AAK447      2010-05      0
1        AAK447      2010-06      0
2        AAK447      2010-07      0
3        AAK447      2010-08      0
4        AAK447      2010-09      0
...         ...          ...    ...
52855     RN287      2021-06      0
52856     RN287      2021-07      0
52857     RN287      2021-08      0
52858     RN287      2021-09      0
52859     RN287      2021-10      0

[52860 rows x 3 columns]

In [62]:
df_timeline['dt_placement']= pd.to_datetime(df_timeline['dt_placement'], format='%Y-%m').dt.to_period('M')

In [63]:
df.reset_index(inplace = True, drop=True)
df_timeline.reset_index(inplace = True, drop=True)

In [64]:
df

,nuts2,nuts3,lau1,lau2,cell_code,cases,dt_placement
0,θεσσαλιας,λαρισας,αγιας,ομολιο,HA280,1,2010-07
1,κεντρικης μακεδονιας,ημαθιας,αλεξανδρειας,αλεξανδρεια,DW265,1,2010-07
2,κεντρικης μακεδονιας,ημαθιας,αλεξανδρειας,σταυρος,EA253,1,2010-07
3,κεντρικης μακεδονιας,ημαθιας,βεροιας,αγιος γεωργιος,DY243,1,2010-07
4,κεντρικης μακεδονιας,ημαθιας,βεροιας,βεροια,EI242,1,2010-07
...,...,...,...,...,...,...,...
1236,κεντρικης μακεδονιας,ημαθιας,ηρωικης πολης ναουσας,αγγελοχωρι,DQ244,1,2021-09
1237,κεντρικης μακεδονιας,θεσσαλονικης,αμπελοκηπων μενεμενης,μενεμενη,DT304,1,2021-09
1238,κεντρικης μακεδονιας,θεσσαλονικης,κορδελιου ευοσμου,κορδελιο,DS303,1,2021-09
1239,κεντρικης μακεδονιας,ημαθιας,αλεξανδρειας,αλεξανδρεια,DW264,1,2021-10
1240,κεντρικης μακεδονιας,θεσσαλονικης,θερμαικου,περαια,EK305,1,2021-10

In [65]:
df_timeline

      cell_code dt_placement  cases
0        AAK447      2010-05      0
1        AAK447      2010-06      0
2        AAK447      2010-07      0
3        AAK447      2010-08      0
4        AAK447      2010-09      0
...         ...          ...    ...
52855     RN287      2021-06      0
52856     RN287      2021-07      0
52857     RN287      2021-08      0
52858     RN287      2021-09      0
52859     RN287      2021-10      0

[52860 rows x 3 columns]

In [66]:
merged_timeline = pd.merge(df_timeline, df, how ='left', on=['cell_code', 'dt_placement'])

In [67]:
merged_timeline

      cell_code dt_placement  cases_x nuts2 nuts3 lau1 lau2  cases_y
0        AAK447      2010-05        0   NaN   NaN  NaN  NaN      NaN
1        AAK447      2010-06        0   NaN   NaN  NaN  NaN      NaN
2        AAK447      2010-07        0   NaN   NaN  NaN  NaN      NaN
3        AAK447      2010-08        0   NaN   NaN  NaN  NaN      NaN
4        AAK447      2010-09        0   NaN   NaN  NaN  NaN      NaN
...         ...          ...      ...   ...   ...  ...  ...      ...
52871     RN287      2021-06        0   NaN   NaN  NaN  NaN      NaN
52872     RN287      2021-07        0   NaN   NaN  NaN  NaN      NaN
52873     RN287      2021-08        0   NaN   NaN  NaN  NaN      NaN
52874     RN287      2021-09        0   NaN   NaN  NaN  NaN      NaN
52875     RN287      2021-10        0   NaN   NaN  NaN  NaN      NaN

[52876 rows x 8 columns]

In [68]:
merged_timeline['cases_y'] = merged_timeline['cases_y'].fillna(0)

In [69]:
merged_timeline['cases'] = merged_timeline['cases_x'] + merged_timeline['cases_y']
merged_timeline = merged_timeline.drop(columns=['cases_x', 'cases_y'])
merged_timeline['cases'] = merged_timeline['cases'].astype(int)

In [70]:
merged_timeline

      cell_code dt_placement nuts2 nuts3 lau1 lau2  cases
0        AAK447      2010-05   NaN   NaN  NaN  NaN      0
1        AAK447      2010-06   NaN   NaN  NaN  NaN      0
2        AAK447      2010-07   NaN   NaN  NaN  NaN      0
3        AAK447      2010-08   NaN   NaN  NaN  NaN      0
4        AAK447      2010-09   NaN   NaN  NaN  NaN      0
...         ...          ...   ...   ...  ...  ...    ...
52871     RN287      2021-06   NaN   NaN  NaN  NaN      0
52872     RN287      2021-07   NaN   NaN  NaN  NaN      0
52873     RN287      2021-08   NaN   NaN  NaN  NaN      0
52874     RN287      2021-09   NaN   NaN  NaN  NaN      0
52875     RN287      2021-10   NaN   NaN  NaN  NaN      0

[52876 rows x 7 columns]

In [71]:
merged_timeline['cases'].value_counts().sort_index()

0    51635
1     1135
2       83
3       17
4        4
6        2
Name: cases, dtype: int64

In [72]:
merged_timeline

      cell_code dt_placement nuts2 nuts3 lau1 lau2  cases
0        AAK447      2010-05   NaN   NaN  NaN  NaN      0
1        AAK447      2010-06   NaN   NaN  NaN  NaN      0
2        AAK447      2010-07   NaN   NaN  NaN  NaN      0
3        AAK447      2010-08   NaN   NaN  NaN  NaN      0
4        AAK447      2010-09   NaN   NaN  NaN  NaN      0
...         ...          ...   ...   ...  ...  ...    ...
52871     RN287      2021-06   NaN   NaN  NaN  NaN      0
52872     RN287      2021-07   NaN   NaN  NaN  NaN      0
52873     RN287      2021-08   NaN   NaN  NaN  NaN      0
52874     RN287      2021-09   NaN   NaN  NaN  NaN      0
52875     RN287      2021-10   NaN   NaN  NaN  NaN      0

[52876 rows x 7 columns]

In [77]:
merged_timeline.drop(columns=['nuts2','nuts3','lau1','lau2'], inplace=True)

In [78]:
merged_timeline.cases.sum()

1380

In [79]:
merged_timeline.to_csv(f"../data/{NUTS0}_WNV_cases_GRID_2010-2021.csv", encoding = enc, index = False)