## Creates the **Timeline** for a specific region by using the Grid File and the required dates ##

In [1]:
import pandas as pd
from datetime import date, timedelta

import random
import geopandas as gpd
import numpy as np

import sys

sys.path.insert(0, "../../../Modules")

from utils import *

pd.options.display.max_columns = None

enc = 'utf-8'
dec = 'greek8'
random.seed(0)

In [2]:
NUTS0 = 'GR'
NUTS2 = 'Attica'

In [3]:
gr_grid = pd.read_csv(f'../../data/{NUTS2}/{NUTS0}_{NUTS2}_GRID.csv', encoding = enc)
gr_grid

     cell_number NUTS2_ID         x         y
0              0     EL30  22.92536  36.22923
1              1     EL30  22.92536  36.31906
2              2     EL30  22.92536  36.33703
3              3     EL30  22.94752  36.19329
4              4     EL30  22.94752  36.21126
..           ...      ...       ...       ...
732          732     EL30  24.03331  38.18760
733          733     EL30  24.03331  38.20556
734          734     EL30  24.05547  37.75640
735          735     EL30  24.05547  37.77436
736          736     EL30  24.05547  37.79233

[737 rows x 4 columns]

In [4]:
## start and end date is defined from available epidemiological file

In [5]:
start = start_dt = date(2025, 7, 2)
end = end_dt = date(2025, 8, 1)
delta = timedelta(days=1)

In [6]:
dates = []

while start_dt <= end_dt:
    dates.append(start_dt.isoformat())
    start_dt += delta

In [7]:
print('Dates between', start, 'and', end)
print(dates)

Dates between 2025-07-02 and 2025-08-01
['2025-07-02', '2025-07-03', '2025-07-04', '2025-07-05', '2025-07-06', '2025-07-07', '2025-07-08', '2025-07-09', '2025-07-10', '2025-07-11', '2025-07-12', '2025-07-13', '2025-07-14', '2025-07-15', '2025-07-16', '2025-07-17', '2025-07-18', '2025-07-19', '2025-07-20', '2025-07-21', '2025-07-22', '2025-07-23', '2025-07-24', '2025-07-25', '2025-07-26', '2025-07-27', '2025-07-28', '2025-07-29', '2025-07-30', '2025-07-31', '2025-08-01']

In [8]:
len(dates)

31

In [9]:
gr_timeline = pd.DataFrame()

In [10]:
data = []
for index, row in gr_grid.iterrows():
    for date in dates:
        data.append({'x': row['x'], 
                     'y': row['y'], 
                     'cell_number': row['cell_number'],  
                     'dt_placement': date,
                     'NUTS2_ID': row['NUTS2_ID'],
                     })

gr_timeline = pd.DataFrame(data)

In [11]:
gr_timeline

              x         y  cell_number dt_placement NUTS2_ID
0      22.92536  36.22923            0   2025-07-02     EL30
1      22.92536  36.22923            0   2025-07-03     EL30
2      22.92536  36.22923            0   2025-07-04     EL30
3      22.92536  36.22923            0   2025-07-05     EL30
4      22.92536  36.22923            0   2025-07-06     EL30
...         ...       ...          ...          ...      ...
22842  24.05547  37.79233          736   2025-07-28     EL30
22843  24.05547  37.79233          736   2025-07-29     EL30
22844  24.05547  37.79233          736   2025-07-30     EL30
22845  24.05547  37.79233          736   2025-07-31     EL30
22846  24.05547  37.79233          736   2025-08-01     EL30

[22847 rows x 5 columns]

In [12]:
gr_timeline['dt_placement'] = pd.to_datetime(gr_timeline['dt_placement'])

In [13]:
gr_timeline['year'] = gr_timeline['dt_placement'].apply(lambda x: x.year)

In [14]:
gr_timeline.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22847 entries, 0 to 22846
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   x             22847 non-null  float64
 1   y             22847 non-null  float64
 2   cell_number   22847 non-null  int64
 3   dt_placement  22847 non-null  datetime64[ns]
 4   NUTS2_ID      22847 non-null  object
 5   year          22847 non-null  int64
dtypes: datetime64[ns](1), float64(2), int64(2), object(1)
memory usage: 1.0+ MB

In [15]:
years = gr_timeline.year.unique().tolist()

In [16]:
for item in years:
    gr_timeline[gr_timeline.year == item].drop(columns = ['year']).to_csv(f'../../data/{NUTS2}/{NUTS0}_{NUTS2}_Timeline_GRID_{item}.csv', index = False)

In [17]:
gr_timeline

              x         y  cell_number dt_placement NUTS2_ID  year
0      22.92536  36.22923            0   2025-07-02     EL30  2025
1      22.92536  36.22923            0   2025-07-03     EL30  2025
2      22.92536  36.22923            0   2025-07-04     EL30  2025
3      22.92536  36.22923            0   2025-07-05     EL30  2025
4      22.92536  36.22923            0   2025-07-06     EL30  2025
...         ...       ...          ...          ...      ...   ...
22842  24.05547  37.79233          736   2025-07-28     EL30  2025
22843  24.05547  37.79233          736   2025-07-29     EL30  2025
22844  24.05547  37.79233          736   2025-07-30     EL30  2025
22845  24.05547  37.79233          736   2025-07-31     EL30  2025
22846  24.05547  37.79233          736   2025-08-01     EL30  2025

[22847 rows x 6 columns]

In [18]:
# filled_file = pd.read_csv(f'../../data/{NUTS2}/{NUTS0}_{NUTS2}_Timeline_GRID_2022-2023_filled.csv', encoding = enc)

In [19]:
# years = filled_file.year.unique().tolist()

In [20]:
# years

In [21]:
# for item in years:
#     filled_file[filled_file.year == item].to_csv(f'../../data/{NUTS2}/{NUTS0}_{NUTS2}_Timeline_GRID_{item}_filled.csv', index = False)