## Creates the **Timeline** for a specific region by using the Grid File and the required dates ##

In [1]:
import pandas as pd
from datetime import date, timedelta

import random
import geopandas as gpd
import numpy as np

import sys

sys.path.insert(0, "../../../Modules")

from utils import *

pd.options.display.max_columns = None

enc = 'utf-8'
dec = 'greek8'
random.seed(0)

In [2]:
NUTS0 = 'GR'
NUTS2 = 'Thessaly'

In [3]:
gr_grid = pd.read_csv(f'../../data/{NUTS2}/{NUTS0}_{NUTS2}_GRID.csv', encoding = enc)
gr_grid

      cell_number NUTS2_ID         x         y
0               0     EL61  21.15549  39.67943
1               1     EL61  21.17860  39.62553
2               2     EL61  21.17860  39.64350
3               3     EL61  21.17860  39.66147
4               4     EL61  21.17860  39.67943
...           ...      ...       ...       ...
3233         3233     EL61  23.74369  39.10450
3234         3234     EL61  23.90545  39.19433
3235         3235     EL61  23.90545  39.21230
3236         3236     EL61  23.92856  39.23027
3237         3237     EL61  24.06721  39.33807

[3238 rows x 4 columns]

In [4]:
## start and end date is defined from available epidemiological file

In [6]:
start = start_dt = date(2024, 5, 2)
end = end_dt = date(2024, 6, 1)
delta = timedelta(days=1)

In [7]:
dates = []

while start_dt <= end_dt:
    dates.append(start_dt.isoformat())
    start_dt += delta

In [8]:
print('Dates between', start, 'and', end)
print(dates)

Dates between 2024-05-02 and 2024-06-01
['2024-05-02', '2024-05-03', '2024-05-04', '2024-05-05', '2024-05-06', '2024-05-07', '2024-05-08', '2024-05-09', '2024-05-10', '2024-05-11', '2024-05-12', '2024-05-13', '2024-05-14', '2024-05-15', '2024-05-16', '2024-05-17', '2024-05-18', '2024-05-19', '2024-05-20', '2024-05-21', '2024-05-22', '2024-05-23', '2024-05-24', '2024-05-25', '2024-05-26', '2024-05-27', '2024-05-28', '2024-05-29', '2024-05-30', '2024-05-31', '2024-06-01']

In [9]:
len(dates)

31

In [10]:
gr_timeline = pd.DataFrame()

In [11]:
data = []
for index, row in gr_grid.iterrows():
    for date in dates:
        data.append({'x': row['x'], 
                     'y': row['y'], 
                     'cell_number': row['cell_number'],  
                     'dt_placement': date,
                     'NUTS2_ID': row['NUTS2_ID'],
                     })

gr_timeline = pd.DataFrame(data)

In [12]:
gr_timeline

               x         y  cell_number dt_placement NUTS2_ID
0       21.15549  39.67943            0   2024-05-02     EL61
1       21.15549  39.67943            0   2024-05-03     EL61
2       21.15549  39.67943            0   2024-05-04     EL61
3       21.15549  39.67943            0   2024-05-05     EL61
4       21.15549  39.67943            0   2024-05-06     EL61
...          ...       ...          ...          ...      ...
100373  24.06721  39.33807         3237   2024-05-28     EL61
100374  24.06721  39.33807         3237   2024-05-29     EL61
100375  24.06721  39.33807         3237   2024-05-30     EL61
100376  24.06721  39.33807         3237   2024-05-31     EL61
100377  24.06721  39.33807         3237   2024-06-01     EL61

[100378 rows x 5 columns]

In [13]:
gr_timeline['dt_placement'] = pd.to_datetime(gr_timeline['dt_placement'])

In [14]:
gr_timeline['year'] = gr_timeline['dt_placement'].apply(lambda x: x.year)

In [15]:
gr_timeline.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100378 entries, 0 to 100377
Data columns (total 6 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   x             100378 non-null  float64
 1   y             100378 non-null  float64
 2   cell_number   100378 non-null  int64
 3   dt_placement  100378 non-null  datetime64[ns]
 4   NUTS2_ID      100378 non-null  object
 5   year          100378 non-null  int64
dtypes: datetime64[ns](1), float64(2), int64(2), object(1)
memory usage: 4.6+ MB

In [16]:
years = gr_timeline.year.unique().tolist()

In [17]:
for item in years:
    gr_timeline[gr_timeline.year == item].drop(columns = ['year']).to_csv(f'../../data/{NUTS2}/{NUTS0}_{NUTS2}_Timeline_GRID_{item}.csv', index = False)

In [18]:
gr_timeline

               x         y  cell_number dt_placement NUTS2_ID  year
0       21.15549  39.67943            0   2024-05-02     EL61  2024
1       21.15549  39.67943            0   2024-05-03     EL61  2024
2       21.15549  39.67943            0   2024-05-04     EL61  2024
3       21.15549  39.67943            0   2024-05-05     EL61  2024
4       21.15549  39.67943            0   2024-05-06     EL61  2024
...          ...       ...          ...          ...      ...   ...
100373  24.06721  39.33807         3237   2024-05-28     EL61  2024
100374  24.06721  39.33807         3237   2024-05-29     EL61  2024
100375  24.06721  39.33807         3237   2024-05-30     EL61  2024
100376  24.06721  39.33807         3237   2024-05-31     EL61  2024
100377  24.06721  39.33807         3237   2024-06-01     EL61  2024

[100378 rows x 6 columns]

In [18]:
filled_file = pd.read_csv(f'../../data/{NUTS2}/{NUTS0}_{NUTS2}_Timeline_GRID_2022-2023_filled.csv', encoding = enc)

FileNotFoundError: [Errno 2] No such file or directory: '../../data/Thessaly/GR_Thessaly_Timeline_GRID_2022-2023_filled.csv'

In [ ]:
years = filled_file.year.unique().tolist()

In [ ]:
years

[2022, 2023]

In [ ]:
for item in years:
    filled_file[filled_file.year == item].to_csv(f'../../data/{NUTS2}/{NUTS0}_{NUTS2}_Timeline_GRID_{item}_filled.csv', index = False)