In [25]:
import pandas as pd
import missingno
import geopandas as gpd
import sys
sys.path.insert(0, "../../../../Modules")

from utils import *

enc = 'utf-8'
pd.set_option('display.max_columns', None)

In [2]:
NUTS0 = 'GR'
NUTS2 = 'Attica'
NUTS2_ID = 'EL30'

In [3]:
greece_nuts3_gdf = gpd.read_file(f"../../../../Europe NUTS - LAU/Greece/data/EL_Whole.shp",  encoding=enc)
timeline_filled_mean = pd.read_csv(f'../../data/{NUTS2}/{NUTS0}_{NUTS2}_Timeline_NUTS3_2010-2022_filled_meantemps.csv', encoding=enc)

In [4]:
greece_nuts3_gdf.head()

,CNTR_CODE,CNTR_NAME,NUTS1_ID,NUTS1_LATN,NUTS1_NAME,NUTS2_ID,NUTS2_LATN,NUTS2_NAME,NUTS3_ID,NUTS3_LATN,NUTS3_NAME,MOUNT_TYPE,URBN_TYPE,COAST_TYPE,geometry
0,EL,Greece,EL3,Attiki,Αττική,EL30,Attiki,Aττική,EL301,Voreios Tomeas Athinon,Βόρειος Τομέας Αθηνών,4.0,1,2,"POLYGON ((23.82310 37.97392, 23.80300 37.98545..."
1,EL,Greece,EL3,Attiki,Αττική,EL30,Attiki,Aττική,EL302,Dytikos Tomeas Athinon,Δυτικός Τομέας Αθηνών,4.0,1,1,"MULTIPOLYGON (((23.72005 38.06296, 23.72884 38..."
2,EL,Greece,EL3,Attiki,Αττική,EL30,Attiki,Aττική,EL303,Kentrikos Tomeas Athinon,Κεντρικός Τομέας Αθηνών,4.0,1,2,"POLYGON ((23.82310 37.97392, 23.82185 37.97195..."
3,EL,Greece,EL3,Attiki,Αττική,EL30,Attiki,Aττική,EL304,Notios Tomeas Athinon,Νότιος Τομέας Αθηνών,4.0,1,1,"POLYGON ((23.80679 37.91784, 23.80240 37.91205..."
4,EL,Greece,EL3,Attiki,Αττική,EL30,Attiki,Aττική,EL305,Anatoliki Attiki,Ανατολική Αττική,2.0,1,1,"MULTIPOLYGON (((24.10518 38.18205, 24.10171 38..."

In [5]:
timeline_filled_mean

,nuts3,nuts2,x,y,dt_placement,day,month,year,ndvi,ndmi,ndwi,ndbi,ndvi_mean,ndmi_mean,ndwi_mean,ndbi_mean,ndvi_std,ndmi_std,ndwi_std,ndbi_std,lst_day,lst_night,lst_day_jan_mean,lst_day_feb_mean,lst_day_mar_mean,lst_day_apr_mean,lst_night_jan_mean,lst_night_feb_mean,lst_night_mar_mean,lst_night_apr_mean,rainfall
0,αθηνων,αττικης,23.76093,37.95263,2010-01-01,1,1,2010,0.121077,0.086852,-0.033350,-0.086852,0.123717,0.087819,-0.034276,-0.087819,0.057889,0.038353,0.013501,0.038353,14624.0,14325.0,14624.000000,NaN,NaN,NaN,14325.000000,NaN,NaN,NaN,0.0
1,αθηνων,αττικης,23.76093,37.95263,2010-01-02,2,1,2010,0.121077,0.086852,-0.033350,-0.086852,0.123717,0.087819,-0.034276,-0.087819,0.057889,0.038353,0.013501,0.038353,14049.0,14193.0,14336.500000,NaN,NaN,NaN,14259.000000,NaN,NaN,NaN,0.0
2,αθηνων,αττικης,23.76093,37.95263,2010-01-03,3,1,2010,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,14049.0,14074.0,14240.666667,NaN,NaN,NaN,14197.333333,NaN,NaN,NaN,0.0
3,αθηνων,αττικης,23.76093,37.95263,2010-01-04,4,1,2010,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,14049.0,14074.0,14192.750000,NaN,NaN,NaN,14166.500000,NaN,NaN,NaN,0.0
4,αθηνων,αττικης,23.76093,37.95263,2010-01-05,5,1,2010,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,14049.0,14074.0,14164.000000,NaN,NaN,NaN,14148.000000,NaN,NaN,NaN,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3029219,πειραιως και νησων,αττικης,23.65527,37.96950,2022-12-27,27,12,2022,0.072316,0.012635,-0.083012,-0.012635,0.053833,-0.010063,-0.077402,0.010063,0.011796,0.014127,0.009121,0.014127,14467.0,14238.0,14250.322581,14437.178571,14565.516129,14565.516129,13998.354839,14044.642857,13991.677419,13991.677419,0.0
3029220,πειραιως και νησων,αττικης,23.65527,37.96950,2022-12-28,28,12,2022,0.072316,0.012635,-0.083012,-0.012635,0.053833,-0.010063,-0.077402,0.010063,0.011796,0.014127,0.009121,0.014127,14494.0,14205.0,14250.322581,14437.178571,14565.516129,14565.516129,13998.354839,14044.642857,13991.677419,13991.677419,0.0
3029221,πειραιως και νησων,αττικης,23.65527,37.96950,2022-12-29,29,12,2022,0.072316,0.012635,-0.083012,-0.012635,0.053833,-0.010063,-0.077402,0.010063,0.011796,0.014127,0.009121,0.014127,14494.0,14144.0,14250.322581,14437.178571,14565.516129,14565.516129,13998.354839,14044.642857,13991.677419,13991.677419,0.0
3029222,πειραιως και νησων,αττικης,23.65527,37.96950,2022-12-30,30,12,2022,0.072316,0.012635,-0.083012,-0.012635,0.053833,-0.010063,-0.077402,0.010063,0.011796,0.014127,0.009121,0.014127,14433.0,14246.0,14250.322581,14437.178571,14565.516129,14565.516129,13998.354839,14044.642857,13991.677419,13991.677419,0.0
3029223,πειραιως και νησων,αττικης,23.65527,37.96950,2022-12-31,31,12,2022,0.071806,0.033263,-0.080539,-0.033263,0.055132,0.005726,-0.076924,-0.005726,0.010876,0.015931,0.009444,0.015931,14448.0,14163.0,14250.322581,14437.178571,14565.516129,14565.516129,13998.354839,14044.642857,13991.677419,13991.677419,0.0

In [6]:
attica_gdf = greece_nuts3_gdf.loc[greece_nuts3_gdf['NUTS2_ID'] == f'{NUTS2_ID}'].copy()
attica_gdf.head()

,CNTR_CODE,CNTR_NAME,NUTS1_ID,NUTS1_LATN,NUTS1_NAME,NUTS2_ID,NUTS2_LATN,NUTS2_NAME,NUTS3_ID,NUTS3_LATN,NUTS3_NAME,MOUNT_TYPE,URBN_TYPE,COAST_TYPE,geometry
0,EL,Greece,EL3,Attiki,Αττική,EL30,Attiki,Aττική,EL301,Voreios Tomeas Athinon,Βόρειος Τομέας Αθηνών,4.0,1,2,"POLYGON ((23.82310 37.97392, 23.80300 37.98545..."
1,EL,Greece,EL3,Attiki,Αττική,EL30,Attiki,Aττική,EL302,Dytikos Tomeas Athinon,Δυτικός Τομέας Αθηνών,4.0,1,1,"MULTIPOLYGON (((23.72005 38.06296, 23.72884 38..."
2,EL,Greece,EL3,Attiki,Αττική,EL30,Attiki,Aττική,EL303,Kentrikos Tomeas Athinon,Κεντρικός Τομέας Αθηνών,4.0,1,2,"POLYGON ((23.82310 37.97392, 23.82185 37.97195..."
3,EL,Greece,EL3,Attiki,Αττική,EL30,Attiki,Aττική,EL304,Notios Tomeas Athinon,Νότιος Τομέας Αθηνών,4.0,1,1,"POLYGON ((23.80679 37.91784, 23.80240 37.91205..."
4,EL,Greece,EL3,Attiki,Αττική,EL30,Attiki,Aττική,EL305,Anatoliki Attiki,Ανατολική Αττική,2.0,1,1,"MULTIPOLYGON (((24.10518 38.18205, 24.10171 38..."

In [7]:
print(f'nuts2_gdf CRS: {attica_gdf.crs}')

nuts2_gdf CRS: GEOGCS["WGS 84",DATUM["WGS_1984",SPHEROID["WGS 84",6378137,298.257223563,AUTHORITY["EPSG","7030"]],AUTHORITY["EPSG","6326"]],PRIMEM["Greenwich",0],UNIT["Degree",0.0174532925199433],AXIS["Longitude",EAST],AXIS["Latitude",NORTH]]

In [9]:
attica_gdf = attica_gdf.to_crs(epsg=4326)
print(f'nuts2_gdf CRS: {attica_gdf.crs}')

nuts2_gdf CRS: epsg:4326

In [10]:
timeline_filled_mean_gdf = gpd.GeoDataFrame(timeline_filled_mean, geometry=gpd.points_from_xy(timeline_filled_mean.x, timeline_filled_mean.y), crs='EPSG:4326')

In [11]:
timeline_filled_mean_gdf.head()

,nuts3,nuts2,x,y,dt_placement,day,month,year,ndvi,ndmi,ndwi,ndbi,ndvi_mean,ndmi_mean,ndwi_mean,ndbi_mean,ndvi_std,ndmi_std,ndwi_std,ndbi_std,lst_day,lst_night,lst_day_jan_mean,lst_day_feb_mean,lst_day_mar_mean,lst_day_apr_mean,lst_night_jan_mean,lst_night_feb_mean,lst_night_mar_mean,lst_night_apr_mean,rainfall,geometry
0,αθηνων,αττικης,23.76093,37.95263,2010-01-01,1,1,2010,0.121077,0.086852,-0.03335,-0.086852,0.123717,0.087819,-0.034276,-0.087819,0.057889,0.038353,0.013501,0.038353,14624.0,14325.0,14624.000000,NaN,NaN,NaN,14325.000000,NaN,NaN,NaN,0.0,POINT (23.76093 37.95263)
1,αθηνων,αττικης,23.76093,37.95263,2010-01-02,2,1,2010,0.121077,0.086852,-0.03335,-0.086852,0.123717,0.087819,-0.034276,-0.087819,0.057889,0.038353,0.013501,0.038353,14049.0,14193.0,14336.500000,NaN,NaN,NaN,14259.000000,NaN,NaN,NaN,0.0,POINT (23.76093 37.95263)
2,αθηνων,αττικης,23.76093,37.95263,2010-01-03,3,1,2010,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,14049.0,14074.0,14240.666667,NaN,NaN,NaN,14197.333333,NaN,NaN,NaN,0.0,POINT (23.76093 37.95263)
3,αθηνων,αττικης,23.76093,37.95263,2010-01-04,4,1,2010,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,14049.0,14074.0,14192.750000,NaN,NaN,NaN,14166.500000,NaN,NaN,NaN,0.0,POINT (23.76093 37.95263)
4,αθηνων,αττικης,23.76093,37.95263,2010-01-05,5,1,2010,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,14049.0,14074.0,14164.000000,NaN,NaN,NaN,14148.000000,NaN,NaN,NaN,0.0,POINT (23.76093 37.95263)

In [12]:
attica_gdf.drop(columns=['CNTR_CODE','CNTR_NAME','NUTS1_ID','NUTS1_LATN','NUTS1_NAME','NUTS2_LATN','NUTS3_LATN',
                        'MOUNT_TYPE','URBN_TYPE','COAST_TYPE'], inplace = True)

In [14]:
attica_gdf

,NUTS2_ID,NUTS2_NAME,NUTS3_ID,NUTS3_NAME,geometry
0,EL30,Aττική,EL301,Βόρειος Τομέας Αθηνών,"POLYGON ((23.82310 37.97392, 23.80300 37.98545..."
1,EL30,Aττική,EL302,Δυτικός Τομέας Αθηνών,"MULTIPOLYGON (((23.72005 38.06296, 23.72884 38..."
2,EL30,Aττική,EL303,Κεντρικός Τομέας Αθηνών,"POLYGON ((23.82310 37.97392, 23.82185 37.97195..."
3,EL30,Aττική,EL304,Νότιος Τομέας Αθηνών,"POLYGON ((23.80679 37.91784, 23.80240 37.91205..."
4,EL30,Aττική,EL305,Ανατολική Αττική,"MULTIPOLYGON (((24.10518 38.18205, 24.10171 38..."
5,EL30,Aττική,EL306,Δυτική Αττική,"MULTIPOLYGON (((23.63450 38.21134, 23.63721 38..."
6,EL30,Aττική,EL307,"Πειραιάς, Νήσοι","MULTIPOLYGON (((23.93391 37.47779, 23.94228 37..."

In [15]:
timeline_filled_corrected = timeline_filled_mean_gdf.sjoin(attica_gdf, predicate="within", how = "left")

In [16]:
timeline_filled_corrected.head()

,nuts3,nuts2,x,y,dt_placement,day,month,year,ndvi,ndmi,ndwi,ndbi,ndvi_mean,ndmi_mean,ndwi_mean,ndbi_mean,ndvi_std,ndmi_std,ndwi_std,ndbi_std,lst_day,lst_night,lst_day_jan_mean,lst_day_feb_mean,lst_day_mar_mean,lst_day_apr_mean,lst_night_jan_mean,lst_night_feb_mean,lst_night_mar_mean,lst_night_apr_mean,rainfall,geometry,index_right,NUTS2_ID,NUTS2_NAME,NUTS3_ID,NUTS3_NAME
0,αθηνων,αττικης,23.76093,37.95263,2010-01-01,1,1,2010,0.121077,0.086852,-0.03335,-0.086852,0.123717,0.087819,-0.034276,-0.087819,0.057889,0.038353,0.013501,0.038353,14624.0,14325.0,14624.000000,NaN,NaN,NaN,14325.000000,NaN,NaN,NaN,0.0,POINT (23.76093 37.95263),2,EL30,Aττική,EL303,Κεντρικός Τομέας Αθηνών
1,αθηνων,αττικης,23.76093,37.95263,2010-01-02,2,1,2010,0.121077,0.086852,-0.03335,-0.086852,0.123717,0.087819,-0.034276,-0.087819,0.057889,0.038353,0.013501,0.038353,14049.0,14193.0,14336.500000,NaN,NaN,NaN,14259.000000,NaN,NaN,NaN,0.0,POINT (23.76093 37.95263),2,EL30,Aττική,EL303,Κεντρικός Τομέας Αθηνών
2,αθηνων,αττικης,23.76093,37.95263,2010-01-03,3,1,2010,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,14049.0,14074.0,14240.666667,NaN,NaN,NaN,14197.333333,NaN,NaN,NaN,0.0,POINT (23.76093 37.95263),2,EL30,Aττική,EL303,Κεντρικός Τομέας Αθηνών
3,αθηνων,αττικης,23.76093,37.95263,2010-01-04,4,1,2010,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,14049.0,14074.0,14192.750000,NaN,NaN,NaN,14166.500000,NaN,NaN,NaN,0.0,POINT (23.76093 37.95263),2,EL30,Aττική,EL303,Κεντρικός Τομέας Αθηνών
4,αθηνων,αττικης,23.76093,37.95263,2010-01-05,5,1,2010,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,14049.0,14074.0,14164.000000,NaN,NaN,NaN,14148.000000,NaN,NaN,NaN,0.0,POINT (23.76093 37.95263),2,EL30,Aττική,EL303,Κεντρικός Τομέας Αθηνών

In [19]:
timeline_filled_corrected[['nuts3', 'NUTS3_NAME']].drop_duplicates()

                    nuts3               NUTS3_NAME
0                  αθηνων  Κεντρικός Τομέας Αθηνών
186                αθηνων     Νότιος Τομέας Αθηνών
279                αθηνων    Δυτικός Τομέας Αθηνών
713                αθηνων    Βόρειος Τομέας Αθηνών
1736   ανατολικης αττικης         Ανατολική Αττική
60434     δυτικης αττικης            Δυτική Αττική
82976  πειραιως και νησων          Πειραιάς, Νήσοι

In [20]:
timeline_filled_corrected.drop(columns=['nuts3','nuts2','geometry', 'index_right'], inplace = True)

In [21]:
timeline_filled_corrected.NUTS2_NAME.unique()

array(['Aττική'], dtype=object)

In [22]:
timeline_filled_corrected.NUTS3_NAME.unique()

array(['Κεντρικός Τομέας Αθηνών', 'Νότιος Τομέας Αθηνών',
       'Δυτικός Τομέας Αθηνών', 'Βόρειος Τομέας Αθηνών',
       'Ανατολική Αττική', 'Δυτική Αττική', 'Πειραιάς, Νήσοι'],
      dtype=object)

In [26]:
timeline_filled_corrected

,x,y,dt_placement,day,month,year,ndvi,ndmi,ndwi,ndbi,ndvi_mean,ndmi_mean,ndwi_mean,ndbi_mean,ndvi_std,ndmi_std,ndwi_std,ndbi_std,lst_day,lst_night,lst_day_jan_mean,lst_day_feb_mean,lst_day_mar_mean,lst_day_apr_mean,lst_night_jan_mean,lst_night_feb_mean,lst_night_mar_mean,lst_night_apr_mean,rainfall,NUTS2_ID,NUTS2_NAME,NUTS3_ID,NUTS3_NAME
0,23.76093,37.95263,2010-01-01,1,1,2010,0.121077,0.086852,-0.033350,-0.086852,0.123717,0.087819,-0.034276,-0.087819,0.057889,0.038353,0.013501,0.038353,14624.0,14325.0,14624.000000,NaN,NaN,NaN,14325.000000,NaN,NaN,NaN,0.0,EL30,Aττική,EL303,Κεντρικός Τομέας Αθηνών
1,23.76093,37.95263,2010-01-02,2,1,2010,0.121077,0.086852,-0.033350,-0.086852,0.123717,0.087819,-0.034276,-0.087819,0.057889,0.038353,0.013501,0.038353,14049.0,14193.0,14336.500000,NaN,NaN,NaN,14259.000000,NaN,NaN,NaN,0.0,EL30,Aττική,EL303,Κεντρικός Τομέας Αθηνών
2,23.76093,37.95263,2010-01-03,3,1,2010,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,14049.0,14074.0,14240.666667,NaN,NaN,NaN,14197.333333,NaN,NaN,NaN,0.0,EL30,Aττική,EL303,Κεντρικός Τομέας Αθηνών
3,23.76093,37.95263,2010-01-04,4,1,2010,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,14049.0,14074.0,14192.750000,NaN,NaN,NaN,14166.500000,NaN,NaN,NaN,0.0,EL30,Aττική,EL303,Κεντρικός Τομέας Αθηνών
4,23.76093,37.95263,2010-01-05,5,1,2010,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,14049.0,14074.0,14164.000000,NaN,NaN,NaN,14148.000000,NaN,NaN,NaN,0.0,EL30,Aττική,EL303,Κεντρικός Τομέας Αθηνών
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3029219,23.65527,37.96950,2022-12-27,27,12,2022,0.072316,0.012635,-0.083012,-0.012635,0.053833,-0.010063,-0.077402,0.010063,0.011796,0.014127,0.009121,0.014127,14467.0,14238.0,14250.322581,14437.178571,14565.516129,14565.516129,13998.354839,14044.642857,13991.677419,13991.677419,0.0,EL30,Aττική,EL307,"Πειραιάς, Νήσοι"
3029220,23.65527,37.96950,2022-12-28,28,12,2022,0.072316,0.012635,-0.083012,-0.012635,0.053833,-0.010063,-0.077402,0.010063,0.011796,0.014127,0.009121,0.014127,14494.0,14205.0,14250.322581,14437.178571,14565.516129,14565.516129,13998.354839,14044.642857,13991.677419,13991.677419,0.0,EL30,Aττική,EL307,"Πειραιάς, Νήσοι"
3029221,23.65527,37.96950,2022-12-29,29,12,2022,0.072316,0.012635,-0.083012,-0.012635,0.053833,-0.010063,-0.077402,0.010063,0.011796,0.014127,0.009121,0.014127,14494.0,14144.0,14250.322581,14437.178571,14565.516129,14565.516129,13998.354839,14044.642857,13991.677419,13991.677419,0.0,EL30,Aττική,EL307,"Πειραιάς, Νήσοι"
3029222,23.65527,37.96950,2022-12-30,30,12,2022,0.072316,0.012635,-0.083012,-0.012635,0.053833,-0.010063,-0.077402,0.010063,0.011796,0.014127,0.009121,0.014127,14433.0,14246.0,14250.322581,14437.178571,14565.516129,14565.516129,13998.354839,14044.642857,13991.677419,13991.677419,0.0,EL30,Aττική,EL307,"Πειραιάς, Νήσοι"
3029223,23.65527,37.96950,2022-12-31,31,12,2022,0.071806,0.033263,-0.080539,-0.033263,0.055132,0.005726,-0.076924,-0.005726,0.010876,0.015931,0.009444,0.015931,14448.0,14163.0,14250.322581,14437.178571,14565.516129,14565.516129,13998.354839,14044.642857,13991.677419,13991.677419,0.0,EL30,Aττική,EL307,"Πειραιάς, Νήσοι"

In [36]:
process_greek(timeline_filled_corrected, 'NUTS3_NAME')
process_greek(timeline_filled_corrected, 'NUTS2_NAME')

timeline_filled_corrected['NUTS2_NAME'] = timeline_filled_corrected['NUTS2_NAME'].apply(lambda x : x.replace('a','α'))

In [37]:
cols = timeline_filled_corrected.columns

cols

Index(['NUTS2_ID', 'NUTS2_NAME', 'NUTS3_ID', 'NUTS3_NAME', 'x', 'y',
       'dt_placement', 'day', 'month', 'year', 'ndvi', 'ndmi', 'ndwi', 'ndbi',
       'ndvi_mean', 'ndmi_mean', 'ndwi_mean', 'ndbi_mean', 'ndvi_std',
       'ndmi_std', 'ndwi_std', 'ndbi_std', 'lst_day', 'lst_night',
       'lst_day_jan_mean', 'lst_day_feb_mean', 'lst_day_mar_mean',
       'lst_day_apr_mean', 'lst_night_jan_mean', 'lst_night_feb_mean',
       'lst_night_mar_mean', 'lst_night_apr_mean', 'rainfall'],
      dtype='object')

In [38]:
print(len(cols))

33

In [39]:
new_cols = ['NUTS2_ID', 'NUTS2_NAME', 'NUTS3_ID', 'NUTS3_NAME',
            'x', 'y', 'dt_placement', 'day', 'month', 'year', 'ndvi',
       'ndmi', 'ndwi', 'ndbi', 'ndvi_mean', 'ndmi_mean', 'ndwi_mean',
       'ndbi_mean', 'ndvi_std', 'ndmi_std', 'ndwi_std', 'ndbi_std', 'lst_day',
       'lst_night', 'lst_day_jan_mean', 'lst_day_feb_mean', 'lst_day_mar_mean',
       'lst_day_apr_mean', 'lst_night_jan_mean', 'lst_night_feb_mean',
       'lst_night_mar_mean', 'lst_night_apr_mean', 'rainfall', ]

In [40]:
print(len(new_cols))

33

In [41]:
timeline_filled_corrected = timeline_filled_corrected[new_cols]

In [42]:
timeline_filled_corrected

,NUTS2_ID,NUTS2_NAME,NUTS3_ID,NUTS3_NAME,x,y,dt_placement,day,month,year,ndvi,ndmi,ndwi,ndbi,ndvi_mean,ndmi_mean,ndwi_mean,ndbi_mean,ndvi_std,ndmi_std,ndwi_std,ndbi_std,lst_day,lst_night,lst_day_jan_mean,lst_day_feb_mean,lst_day_mar_mean,lst_day_apr_mean,lst_night_jan_mean,lst_night_feb_mean,lst_night_mar_mean,lst_night_apr_mean,rainfall
0,EL30,αττικη,EL303,κεντρικος τομεας αθηνων,23.76093,37.95263,2010-01-01,1,1,2010,0.121077,0.086852,-0.033350,-0.086852,0.123717,0.087819,-0.034276,-0.087819,0.057889,0.038353,0.013501,0.038353,14624.0,14325.0,14624.000000,NaN,NaN,NaN,14325.000000,NaN,NaN,NaN,0.0
1,EL30,αττικη,EL303,κεντρικος τομεας αθηνων,23.76093,37.95263,2010-01-02,2,1,2010,0.121077,0.086852,-0.033350,-0.086852,0.123717,0.087819,-0.034276,-0.087819,0.057889,0.038353,0.013501,0.038353,14049.0,14193.0,14336.500000,NaN,NaN,NaN,14259.000000,NaN,NaN,NaN,0.0
2,EL30,αττικη,EL303,κεντρικος τομεας αθηνων,23.76093,37.95263,2010-01-03,3,1,2010,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,14049.0,14074.0,14240.666667,NaN,NaN,NaN,14197.333333,NaN,NaN,NaN,0.0
3,EL30,αττικη,EL303,κεντρικος τομεας αθηνων,23.76093,37.95263,2010-01-04,4,1,2010,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,14049.0,14074.0,14192.750000,NaN,NaN,NaN,14166.500000,NaN,NaN,NaN,0.0
4,EL30,αττικη,EL303,κεντρικος τομεας αθηνων,23.76093,37.95263,2010-01-05,5,1,2010,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,14049.0,14074.0,14164.000000,NaN,NaN,NaN,14148.000000,NaN,NaN,NaN,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3029219,EL30,αττικη,EL307,"πειραιας, νησοι",23.65527,37.96950,2022-12-27,27,12,2022,0.072316,0.012635,-0.083012,-0.012635,0.053833,-0.010063,-0.077402,0.010063,0.011796,0.014127,0.009121,0.014127,14467.0,14238.0,14250.322581,14437.178571,14565.516129,14565.516129,13998.354839,14044.642857,13991.677419,13991.677419,0.0
3029220,EL30,αττικη,EL307,"πειραιας, νησοι",23.65527,37.96950,2022-12-28,28,12,2022,0.072316,0.012635,-0.083012,-0.012635,0.053833,-0.010063,-0.077402,0.010063,0.011796,0.014127,0.009121,0.014127,14494.0,14205.0,14250.322581,14437.178571,14565.516129,14565.516129,13998.354839,14044.642857,13991.677419,13991.677419,0.0
3029221,EL30,αττικη,EL307,"πειραιας, νησοι",23.65527,37.96950,2022-12-29,29,12,2022,0.072316,0.012635,-0.083012,-0.012635,0.053833,-0.010063,-0.077402,0.010063,0.011796,0.014127,0.009121,0.014127,14494.0,14144.0,14250.322581,14437.178571,14565.516129,14565.516129,13998.354839,14044.642857,13991.677419,13991.677419,0.0
3029222,EL30,αττικη,EL307,"πειραιας, νησοι",23.65527,37.96950,2022-12-30,30,12,2022,0.072316,0.012635,-0.083012,-0.012635,0.053833,-0.010063,-0.077402,0.010063,0.011796,0.014127,0.009121,0.014127,14433.0,14246.0,14250.322581,14437.178571,14565.516129,14565.516129,13998.354839,14044.642857,13991.677419,13991.677419,0.0
3029223,EL30,αττικη,EL307,"πειραιας, νησοι",23.65527,37.96950,2022-12-31,31,12,2022,0.071806,0.033263,-0.080539,-0.033263,0.055132,0.005726,-0.076924,-0.005726,0.010876,0.015931,0.009444,0.015931,14448.0,14163.0,14250.322581,14437.178571,14565.516129,14565.516129,13998.354839,14044.642857,13991.677419,13991.677419,0.0

In [43]:
timeline_filled_corrected.to_csv(f'../../data/{NUTS2}/{NUTS0}_{NUTS2}_Timeline_NUTS3_2010-2022_filled_meantemps.csv', encoding = enc, index = False)