In [1]:
import pandas as pd
import missingno

enc = 'utf-8'

In [2]:
NUTS0 = 'GR'
NUTS2 = 'CMacedonia'

In [3]:
timeline = pd.read_csv(f'../../data/{NUTS2}/{NUTS0}_{NUTS2}_Timeline_NUTS3_2010-2022.csv', encoding=enc)
timeline_filled_mean = pd.read_csv(f'../../data/{NUTS2}/{NUTS0}_{NUTS2}_Timeline_NUTS3_2010-2022_filled_meantemps.csv', encoding=enc)

In [4]:
timeline

,NUTS2_ID,NUTS2_NAME,NUTS3_ID,NUTS3_NAME,x,y,dt_placement
0,EL52,κεντρικη μακεδονια,EL521,ημαθια,21.96176,40.52441,2010-01-01
1,EL52,κεντρικη μακεδονια,EL521,ημαθια,21.96176,40.52441,2010-01-02
2,EL52,κεντρικη μακεδονια,EL521,ημαθια,21.96176,40.52441,2010-01-03
3,EL52,κεντρικη μακεδονια,EL521,ημαθια,21.96176,40.52441,2010-01-04
4,EL52,κεντρικη μακεδονια,EL521,ημαθια,21.96176,40.52441,2010-01-05
...,...,...,...,...,...,...,...
3071951,EL52,κεντρικη μακεδονια,EL527,χαλκιδικη,23.92642,40.09062,2022-12-27
3071952,EL52,κεντρικη μακεδονια,EL527,χαλκιδικη,23.92642,40.09062,2022-12-28
3071953,EL52,κεντρικη μακεδονια,EL527,χαλκιδικη,23.92642,40.09062,2022-12-29
3071954,EL52,κεντρικη μακεδονια,EL527,χαλκιδικη,23.92642,40.09062,2022-12-30
3071955,EL52,κεντρικη μακεδονια,EL527,χαλκιδικη,23.92642,40.09062,2022-12-31

In [5]:
timeline_filled_mean

,nuts3,nuts2,x,y,dt_placement,day,month,year,ndvi,ndmi,...,lst_night,lst_day_jan_mean,lst_day_feb_mean,lst_day_mar_mean,lst_day_apr_mean,lst_night_jan_mean,lst_night_feb_mean,lst_night_mar_mean,lst_night_apr_mean,rainfall
0,ημαθιας,κεντρικης μακεδονιας,21.96145,40.52252,2010-01-01,1,1,2010,NaN,NaN,...,13669.0,14199.000000,NaN,NaN,NaN,13669.000000,NaN,NaN,NaN,2.030213
1,ημαθιας,κεντρικης μακεδονιας,21.96145,40.52252,2010-01-02,2,1,2010,NaN,NaN,...,13669.0,14199.000000,NaN,NaN,NaN,13669.000000,NaN,NaN,NaN,1.997432
2,ημαθιας,κεντρικης μακεδονιας,21.96145,40.52252,2010-01-03,3,1,2010,NaN,NaN,...,13669.0,14199.000000,NaN,NaN,NaN,13669.000000,NaN,NaN,NaN,0.882009
3,ημαθιας,κεντρικης μακεδονιας,21.96145,40.52252,2010-01-04,4,1,2010,NaN,NaN,...,13669.0,14199.000000,NaN,NaN,NaN,13669.000000,NaN,NaN,NaN,1.242316
4,ημαθιας,κεντρικης μακεδονιας,21.96145,40.52252,2010-01-05,5,1,2010,NaN,NaN,...,13669.0,14199.000000,NaN,NaN,NaN,13669.000000,NaN,NaN,NaN,0.093469
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3067203,χαλκιδικης,κεντρικης μακεδονιας,23.55821,40.41417,2022-12-27,27,12,2022,0.584723,0.370539,...,13997.0,14065.322581,14193.357143,14176.225806,14176.225806,13751.806452,13779.178571,13721.193548,13721.193548,0.000000
3067204,χαλκιδικης,κεντρικης μακεδονιας,23.55821,40.41417,2022-12-28,28,12,2022,NaN,NaN,...,13997.0,14065.322581,14193.357143,14176.225806,14176.225806,13751.806452,13779.178571,13721.193548,13721.193548,0.000000
3067205,χαλκιδικης,κεντρικης μακεδονιας,23.55821,40.41417,2022-12-29,29,12,2022,0.584723,0.370539,...,13914.0,14065.322581,14193.357143,14176.225806,14176.225806,13751.806452,13779.178571,13721.193548,13721.193548,0.000000
3067206,χαλκιδικης,κεντρικης μακεδονιας,23.55821,40.41417,2022-12-30,30,12,2022,0.584723,0.370539,...,13923.0,14065.322581,14193.357143,14176.225806,14176.225806,13751.806452,13779.178571,13721.193548,13721.193548,0.000000
3067207,χαλκιδικης,κεντρικης μακεδονιας,23.55821,40.41417,2022-12-31,31,12,2022,0.584723,0.370539,...,13919.0,14065.322581,14193.357143,14176.225806,14176.225806,13751.806452,13779.178571,13721.193548,13721.193548,0.000000

In [6]:
timeline_filled_mean.drop(columns=['nuts2'], inplace = True)
timeline_filled_mean.rename(columns={"nuts3": "NUTS3_NAME"}, inplace=True)

In [17]:
timeline.NUTS2_NAME.unique()

array(['κεντρικη μακεδονια'], dtype=object)

In [8]:
timeline_filled_mean.NUTS3_NAME.unique()

array(['ημαθιας', 'θεσσαλονικης', 'κιλκις', 'πελλας', 'πιεριας', 'σερρων',
       'χαλκιδικης'], dtype=object)

In [9]:
timeline_filled_mean['NUTS3_NAME'] = timeline_filled_mean['NUTS3_NAME'].apply(lambda x : x.replace('ημαθιας','ημαθια'))
timeline_filled_mean['NUTS3_NAME'] = timeline_filled_mean['NUTS3_NAME'].apply(lambda x : x.replace('θεσσαλονικης','θεσσαλονικη'))
timeline_filled_mean['NUTS3_NAME'] = timeline_filled_mean['NUTS3_NAME'].apply(lambda x : x.replace('πελλας','πελλα'))
timeline_filled_mean['NUTS3_NAME'] = timeline_filled_mean['NUTS3_NAME'].apply(lambda x : x.replace('πιεριας','πιερια'))
timeline_filled_mean['NUTS3_NAME'] = timeline_filled_mean['NUTS3_NAME'].apply(lambda x : x.replace('σερρων','σερρες'))
timeline_filled_mean['NUTS3_NAME'] = timeline_filled_mean['NUTS3_NAME'].apply(lambda x : x.replace('χαλκιδικης','χαλκιδικη'))

In [10]:
timeline_filled_mean

,NUTS3_NAME,x,y,dt_placement,day,month,year,ndvi,ndmi,ndwi,...,lst_night,lst_day_jan_mean,lst_day_feb_mean,lst_day_mar_mean,lst_day_apr_mean,lst_night_jan_mean,lst_night_feb_mean,lst_night_mar_mean,lst_night_apr_mean,rainfall
0,ημαθια,21.96145,40.52252,2010-01-01,1,1,2010,NaN,NaN,NaN,...,13669.0,14199.000000,NaN,NaN,NaN,13669.000000,NaN,NaN,NaN,2.030213
1,ημαθια,21.96145,40.52252,2010-01-02,2,1,2010,NaN,NaN,NaN,...,13669.0,14199.000000,NaN,NaN,NaN,13669.000000,NaN,NaN,NaN,1.997432
2,ημαθια,21.96145,40.52252,2010-01-03,3,1,2010,NaN,NaN,NaN,...,13669.0,14199.000000,NaN,NaN,NaN,13669.000000,NaN,NaN,NaN,0.882009
3,ημαθια,21.96145,40.52252,2010-01-04,4,1,2010,NaN,NaN,NaN,...,13669.0,14199.000000,NaN,NaN,NaN,13669.000000,NaN,NaN,NaN,1.242316
4,ημαθια,21.96145,40.52252,2010-01-05,5,1,2010,NaN,NaN,NaN,...,13669.0,14199.000000,NaN,NaN,NaN,13669.000000,NaN,NaN,NaN,0.093469
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3067203,χαλκιδικη,23.55821,40.41417,2022-12-27,27,12,2022,0.584723,0.370539,-0.435388,...,13997.0,14065.322581,14193.357143,14176.225806,14176.225806,13751.806452,13779.178571,13721.193548,13721.193548,0.000000
3067204,χαλκιδικη,23.55821,40.41417,2022-12-28,28,12,2022,NaN,NaN,NaN,...,13997.0,14065.322581,14193.357143,14176.225806,14176.225806,13751.806452,13779.178571,13721.193548,13721.193548,0.000000
3067205,χαλκιδικη,23.55821,40.41417,2022-12-29,29,12,2022,0.584723,0.370539,-0.435388,...,13914.0,14065.322581,14193.357143,14176.225806,14176.225806,13751.806452,13779.178571,13721.193548,13721.193548,0.000000
3067206,χαλκιδικη,23.55821,40.41417,2022-12-30,30,12,2022,0.584723,0.370539,-0.435388,...,13923.0,14065.322581,14193.357143,14176.225806,14176.225806,13751.806452,13779.178571,13721.193548,13721.193548,0.000000
3067207,χαλκιδικη,23.55821,40.41417,2022-12-31,31,12,2022,0.584723,0.370539,-0.435388,...,13919.0,14065.322581,14193.357143,14176.225806,14176.225806,13751.806452,13779.178571,13721.193548,13721.193548,0.000000

In [14]:
nuts3_id = {'ημαθια': 'EL521', 
            'θεσσαλονικη': 'EL522', 
            'κιλκις': 'EL523', 
            'πελλα': 'EL524', 
            'πιερια': 'EL525',
            'σερρες': 'EL526',
            'χαλκιδικη': 'EL527'}

In [18]:
timeline_filled_mean['NUTS3_ID'] = timeline_filled_mean['NUTS3_NAME'].map(nuts3_id)
timeline_filled_mean['NUTS2_ID'] = 'EL52'
timeline_filled_mean['NUTS2_NAME'] = 'κεντρικη μακεδονια'

In [20]:
cols = timeline_filled_mean.columns

cols

Index(['NUTS3_NAME', 'x', 'y', 'dt_placement', 'day', 'month', 'year', 'ndvi',
       'ndmi', 'ndwi', 'ndbi', 'ndvi_mean', 'ndmi_mean', 'ndwi_mean',
       'ndbi_mean', 'ndvi_std', 'ndmi_std', 'ndwi_std', 'ndbi_std', 'lst_day',
       'lst_night', 'lst_day_jan_mean', 'lst_day_feb_mean', 'lst_day_mar_mean',
       'lst_day_apr_mean', 'lst_night_jan_mean', 'lst_night_feb_mean',
       'lst_night_mar_mean', 'lst_night_apr_mean', 'rainfall', 'NUTS3_ID',
       'NUTS2_ID', 'NUTS2_NAME'],
      dtype='object')

In [21]:
print(len(cols))

33

In [22]:
new_cols = ['NUTS2_ID', 'NUTS2_NAME', 'NUTS3_ID', 'NUTS3_NAME',
            'x', 'y', 'dt_placement', 'day', 'month', 'year', 'ndvi',
       'ndmi', 'ndwi', 'ndbi', 'ndvi_mean', 'ndmi_mean', 'ndwi_mean',
       'ndbi_mean', 'ndvi_std', 'ndmi_std', 'ndwi_std', 'ndbi_std', 'lst_day',
       'lst_night', 'lst_day_jan_mean', 'lst_day_feb_mean', 'lst_day_mar_mean',
       'lst_day_apr_mean', 'lst_night_jan_mean', 'lst_night_feb_mean',
       'lst_night_mar_mean', 'lst_night_apr_mean', 'rainfall', ]

In [23]:
print(len(new_cols))

33

In [25]:
timeline_filled_mean = timeline_filled_mean[new_cols]

In [26]:
timeline_filled_mean

,NUTS2_ID,NUTS2_NAME,NUTS3_ID,NUTS3_NAME,x,y,dt_placement,day,month,year,...,lst_night,lst_day_jan_mean,lst_day_feb_mean,lst_day_mar_mean,lst_day_apr_mean,lst_night_jan_mean,lst_night_feb_mean,lst_night_mar_mean,lst_night_apr_mean,rainfall
0,EL52,κεντρικη μακεδονια,EL521,ημαθια,21.96145,40.52252,2010-01-01,1,1,2010,...,13669.0,14199.000000,NaN,NaN,NaN,13669.000000,NaN,NaN,NaN,2.030213
1,EL52,κεντρικη μακεδονια,EL521,ημαθια,21.96145,40.52252,2010-01-02,2,1,2010,...,13669.0,14199.000000,NaN,NaN,NaN,13669.000000,NaN,NaN,NaN,1.997432
2,EL52,κεντρικη μακεδονια,EL521,ημαθια,21.96145,40.52252,2010-01-03,3,1,2010,...,13669.0,14199.000000,NaN,NaN,NaN,13669.000000,NaN,NaN,NaN,0.882009
3,EL52,κεντρικη μακεδονια,EL521,ημαθια,21.96145,40.52252,2010-01-04,4,1,2010,...,13669.0,14199.000000,NaN,NaN,NaN,13669.000000,NaN,NaN,NaN,1.242316
4,EL52,κεντρικη μακεδονια,EL521,ημαθια,21.96145,40.52252,2010-01-05,5,1,2010,...,13669.0,14199.000000,NaN,NaN,NaN,13669.000000,NaN,NaN,NaN,0.093469
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3067203,EL52,κεντρικη μακεδονια,EL527,χαλκιδικη,23.55821,40.41417,2022-12-27,27,12,2022,...,13997.0,14065.322581,14193.357143,14176.225806,14176.225806,13751.806452,13779.178571,13721.193548,13721.193548,0.000000
3067204,EL52,κεντρικη μακεδονια,EL527,χαλκιδικη,23.55821,40.41417,2022-12-28,28,12,2022,...,13997.0,14065.322581,14193.357143,14176.225806,14176.225806,13751.806452,13779.178571,13721.193548,13721.193548,0.000000
3067205,EL52,κεντρικη μακεδονια,EL527,χαλκιδικη,23.55821,40.41417,2022-12-29,29,12,2022,...,13914.0,14065.322581,14193.357143,14176.225806,14176.225806,13751.806452,13779.178571,13721.193548,13721.193548,0.000000
3067206,EL52,κεντρικη μακεδονια,EL527,χαλκιδικη,23.55821,40.41417,2022-12-30,30,12,2022,...,13923.0,14065.322581,14193.357143,14176.225806,14176.225806,13751.806452,13779.178571,13721.193548,13721.193548,0.000000
3067207,EL52,κεντρικη μακεδονια,EL527,χαλκιδικη,23.55821,40.41417,2022-12-31,31,12,2022,...,13919.0,14065.322581,14193.357143,14176.225806,14176.225806,13751.806452,13779.178571,13721.193548,13721.193548,0.000000

In [28]:
timeline_filled_mean.to_csv(f'../../data/{NUTS2}/{NUTS0}_{NUTS2}_Timeline_NUTS3_2010-2022_filled_meantemps.csv', encoding = enc, index = False)