## Creates the **Epidemiological Timeline** for a specific region by using the available data on WNV Cases ##

In [1]:
import pandas as pd
import numpy as np

enc = 'utf-8'
dec = 'greek8'

pd.options.display.max_columns = None
pd.options.display.max_rows = 10

In [2]:
NUTS0 = 'GR'
NUTS2 = 'CMacedonia'
NUTS2_EL = 'κεντρικης μακεδονιας'

In [3]:
data = pd.read_csv(f'../../data/{NUTS0}_WNV_cases_2010-2022_processed.csv', encoding = enc)
data.head(5)

,onset of symptoms,year,month,day,nuts2,nuts3,cases
0,2010-07-06,2010,7,6,κεντρικης μακεδονιας,σερρων,1
1,2010-07-16,2010,7,16,κεντρικης μακεδονιας,κιλκις,1
2,2010-07-18,2010,7,18,κεντρικης μακεδονιας,πελλας,1
3,2010-07-19,2010,7,19,κεντρικης μακεδονιας,θεσσαλονικης,2
4,2010-07-20,2010,7,20,κεντρικης μακεδονιας,ημαθιας,1

In [4]:
data.shape

(1306, 7)

In [5]:
df = data[data['nuts2'].isin([NUTS2_EL])].copy()

In [6]:
df.reset_index(drop = True, inplace = True)

In [7]:
df.drop(columns = ['onset of symptoms', 'day'], inplace = True)

In [8]:
df

     year  month                 nuts2         nuts3  cases
0    2010      7  κεντρικης μακεδονιας        σερρων      1
1    2010      7  κεντρικης μακεδονιας        κιλκις      1
2    2010      7  κεντρικης μακεδονιας        πελλας      1
3    2010      7  κεντρικης μακεδονιας  θεσσαλονικης      2
4    2010      7  κεντρικης μακεδονιας       ημαθιας      1
..    ...    ...                   ...           ...    ...
639  2022     10  κεντρικης μακεδονιας        πελλας      1
640  2022     10  κεντρικης μακεδονιας       ημαθιας      1
641  2022     10  κεντρικης μακεδονιας  θεσσαλονικης      1
642  2022     10  κεντρικης μακεδονιας  θεσσαλονικης      1
643  2022     11  κεντρικης μακεδονιας  θεσσαλονικης      1

[644 rows x 5 columns]

In [9]:
df.cases.sum()

863

In [10]:
df_grouped = df.groupby(['year', 'month', 'nuts2', 'nuts3'], as_index = False)
df = df_grouped.sum()

In [11]:
df

     year  month                 nuts2         nuts3  cases
0    2010      7  κεντρικης μακεδονιας       ημαθιας      6
1    2010      7  κεντρικης μακεδονιας  θεσσαλονικης     11
2    2010      7  κεντρικης μακεδονιας        κιλκις      6
3    2010      7  κεντρικης μακεδονιας        πελλας      3
4    2010      7  κεντρικης μακεδονιας       πιεριας      1
..    ...    ...                   ...           ...    ...
133  2022     10  κεντρικης μακεδονιας  θεσσαλονικης     11
134  2022     10  κεντρικης μακεδονιας        πελλας      2
135  2022     10  κεντρικης μακεδονιας        σερρων      1
136  2022     10  κεντρικης μακεδονιας    χαλκιδικης      1
137  2022     11  κεντρικης μακεδονιας  θεσσαλονικης      1

[138 rows x 5 columns]

In [12]:
df.cases.sum()

863

In [13]:
print(np.sort(df.cases.unique()))

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 16 17 20 27 34 36 40 41 49 50]

In [14]:
wnv_lau1_list = df['nuts3'].drop_duplicates().sort_values().tolist()

with open(f'../../data/{NUTS2}/{NUTS0}_{NUTS2}_WNV_2010-2022_NUTS3_Units_Processed.txt', 'w', encoding=enc) as f:
    for item in wnv_lau1_list:
        f.write("%s\n" % item)
  
print(f"Number of NUTS3 Units in {NUTS2} (from cases): {len(wnv_lau1_list)}")

Number of NUTS3 Units in CMacedonia (from cases): 7

In [15]:
df['date_string'] = df['month'].astype(str) + '-' + df['year'].astype(str)

# Convert 'date_string' column to datetime format
df['dt_placement'] = pd.to_datetime(df['date_string'], format='%m-%Y').dt.to_period('M')
df.drop(columns=['date_string'], inplace = True)

In [16]:
df

     year  month                 nuts2         nuts3  cases dt_placement
0    2010      7  κεντρικης μακεδονιας       ημαθιας      6      2010-07
1    2010      7  κεντρικης μακεδονιας  θεσσαλονικης     11      2010-07
2    2010      7  κεντρικης μακεδονιας        κιλκις      6      2010-07
3    2010      7  κεντρικης μακεδονιας        πελλας      3      2010-07
4    2010      7  κεντρικης μακεδονιας       πιεριας      1      2010-07
..    ...    ...                   ...           ...    ...          ...
133  2022     10  κεντρικης μακεδονιας  θεσσαλονικης     11      2022-10
134  2022     10  κεντρικης μακεδονιας        πελλας      2      2022-10
135  2022     10  κεντρικης μακεδονιας        σερρων      1      2022-10
136  2022     10  κεντρικης μακεδονιας    χαλκιδικης      1      2022-10
137  2022     11  κεντρικης μακεδονιας  θεσσαλονικης      1      2022-11

[138 rows x 6 columns]

In [17]:
df.cases.sum()

863

In [18]:
case_months = df['month'].drop_duplicates().sort_values().tolist()
case_months

[6, 7, 8, 9, 10, 11]

In [19]:
case_years = df['year'].drop_duplicates().sort_values().tolist()
case_years

[2010, 2011, 2012, 2013, 2018, 2019, 2020, 2021, 2022]

In [20]:
with open(f'../../data/{NUTS2}/{NUTS0}_{NUTS2}_WNV_2010-2022_NUTS3_Cases_Dates.txt', 'w', encoding=enc) as f:

    f.write("%s: " % 'months')
    for item in case_months:
        f.write("%s, " % item)

    f.write("\n")

    f.write("%s: " % 'years')
    for item in case_years:
        f.write("%s, " % item)

In [21]:
df.drop(columns=['month', 'year'], inplace = True)

In [22]:
## Creating DataFrame to hold negative examples

df_timeline = pd.DataFrame(columns = ['nuts2', 'nuts3', 'dt_placement', 'cases'])
timeline = []

for nuts3 in df['nuts3'].drop_duplicates().sort_values():
    for year in case_years:
        for month in case_months:
            timeline.append({'nuts2' : NUTS2_EL, 'nuts3' : nuts3, 'dt_placement' : f"{year:04}-{month:02}", 'cases' : 0})
            
df_timeline = pd.DataFrame(timeline)

In [23]:
df_timeline

                    nuts2       nuts3 dt_placement  cases
0    κεντρικης μακεδονιας     ημαθιας      2010-06      0
1    κεντρικης μακεδονιας     ημαθιας      2010-07      0
2    κεντρικης μακεδονιας     ημαθιας      2010-08      0
3    κεντρικης μακεδονιας     ημαθιας      2010-09      0
4    κεντρικης μακεδονιας     ημαθιας      2010-10      0
..                    ...         ...          ...    ...
373  κεντρικης μακεδονιας  χαλκιδικης      2022-07      0
374  κεντρικης μακεδονιας  χαλκιδικης      2022-08      0
375  κεντρικης μακεδονιας  χαλκιδικης      2022-09      0
376  κεντρικης μακεδονιας  χαλκιδικης      2022-10      0
377  κεντρικης μακεδονιας  χαλκιδικης      2022-11      0

[378 rows x 4 columns]

In [24]:
df_timeline['dt_placement']= pd.to_datetime(df_timeline['dt_placement'], format='%Y-%m').dt.to_period('M')

In [25]:
df.reset_index(inplace = True, drop=True)
df_timeline.reset_index(inplace = True, drop=True)

In [26]:
rearranged_cols = ['nuts2',	'nuts3', 'dt_placement', 'cases']

# Reindex the DataFrame with the desired column order
df = df.reindex(columns=rearranged_cols)

In [27]:
df

                    nuts2         nuts3 dt_placement  cases
0    κεντρικης μακεδονιας       ημαθιας      2010-07      6
1    κεντρικης μακεδονιας  θεσσαλονικης      2010-07     11
2    κεντρικης μακεδονιας        κιλκις      2010-07      6
3    κεντρικης μακεδονιας        πελλας      2010-07      3
4    κεντρικης μακεδονιας       πιεριας      2010-07      1
..                    ...           ...          ...    ...
133  κεντρικης μακεδονιας  θεσσαλονικης      2022-10     11
134  κεντρικης μακεδονιας        πελλας      2022-10      2
135  κεντρικης μακεδονιας        σερρων      2022-10      1
136  κεντρικης μακεδονιας    χαλκιδικης      2022-10      1
137  κεντρικης μακεδονιας  θεσσαλονικης      2022-11      1

[138 rows x 4 columns]

In [28]:
df_timeline

                    nuts2       nuts3 dt_placement  cases
0    κεντρικης μακεδονιας     ημαθιας      2010-06      0
1    κεντρικης μακεδονιας     ημαθιας      2010-07      0
2    κεντρικης μακεδονιας     ημαθιας      2010-08      0
3    κεντρικης μακεδονιας     ημαθιας      2010-09      0
4    κεντρικης μακεδονιας     ημαθιας      2010-10      0
..                    ...         ...          ...    ...
373  κεντρικης μακεδονιας  χαλκιδικης      2022-07      0
374  κεντρικης μακεδονιας  χαλκιδικης      2022-08      0
375  κεντρικης μακεδονιας  χαλκιδικης      2022-09      0
376  κεντρικης μακεδονιας  χαλκιδικης      2022-10      0
377  κεντρικης μακεδονιας  χαλκιδικης      2022-11      0

[378 rows x 4 columns]

In [29]:
merged_timeline = pd.merge(df_timeline, df, how ='left', on=['nuts2','nuts3','dt_placement'])

In [30]:
merged_timeline

                    nuts2       nuts3 dt_placement  cases_x  cases_y
0    κεντρικης μακεδονιας     ημαθιας      2010-06        0      NaN
1    κεντρικης μακεδονιας     ημαθιας      2010-07        0      6.0
2    κεντρικης μακεδονιας     ημαθιας      2010-08        0     36.0
3    κεντρικης μακεδονιας     ημαθιας      2010-09        0      7.0
4    κεντρικης μακεδονιας     ημαθιας      2010-10        0      NaN
..                    ...         ...          ...      ...      ...
373  κεντρικης μακεδονιας  χαλκιδικης      2022-07        0      NaN
374  κεντρικης μακεδονιας  χαλκιδικης      2022-08        0     12.0
375  κεντρικης μακεδονιας  χαλκιδικης      2022-09        0     10.0
376  κεντρικης μακεδονιας  χαλκιδικης      2022-10        0      1.0
377  κεντρικης μακεδονιας  χαλκιδικης      2022-11        0      NaN

[378 rows x 5 columns]

In [31]:
merged_timeline['cases_y'] = merged_timeline['cases_y'].fillna(0)

In [32]:
merged_timeline['cases'] = merged_timeline['cases_x'] + merged_timeline['cases_y']
merged_timeline = merged_timeline.drop(columns=['cases_x', 'cases_y'])
merged_timeline['cases'] = merged_timeline['cases'].astype(int)

In [33]:
merged_timeline

                    nuts2       nuts3 dt_placement  cases
0    κεντρικης μακεδονιας     ημαθιας      2010-06      0
1    κεντρικης μακεδονιας     ημαθιας      2010-07      6
2    κεντρικης μακεδονιας     ημαθιας      2010-08     36
3    κεντρικης μακεδονιας     ημαθιας      2010-09      7
4    κεντρικης μακεδονιας     ημαθιας      2010-10      0
..                    ...         ...          ...    ...
373  κεντρικης μακεδονιας  χαλκιδικης      2022-07      0
374  κεντρικης μακεδονιας  χαλκιδικης      2022-08     12
375  κεντρικης μακεδονιας  χαλκιδικης      2022-09     10
376  κεντρικης μακεδονιας  χαλκιδικης      2022-10      1
377  κεντρικης μακεδονιας  χαλκιδικης      2022-11      0

[378 rows x 4 columns]

In [34]:
merged_timeline['cases'].value_counts().sort_index()

0     240
1      39
2      22
3      17
4      10
     ...
36      1
40      1
41      1
49      1
50      1
Name: cases, Length: 24, dtype: int64

In [35]:
merged_timeline

                    nuts2       nuts3 dt_placement  cases
0    κεντρικης μακεδονιας     ημαθιας      2010-06      0
1    κεντρικης μακεδονιας     ημαθιας      2010-07      6
2    κεντρικης μακεδονιας     ημαθιας      2010-08     36
3    κεντρικης μακεδονιας     ημαθιας      2010-09      7
4    κεντρικης μακεδονιας     ημαθιας      2010-10      0
..                    ...         ...          ...    ...
373  κεντρικης μακεδονιας  χαλκιδικης      2022-07      0
374  κεντρικης μακεδονιας  χαλκιδικης      2022-08     12
375  κεντρικης μακεδονιας  χαλκιδικης      2022-09     10
376  κεντρικης μακεδονιας  χαλκιδικης      2022-10      1
377  κεντρικης μακεδονιας  χαλκιδικης      2022-11      0

[378 rows x 4 columns]

In [36]:
merged_timeline.cases.sum()

863

In [37]:
merged_timeline.nuts2.unique()

array(['κεντρικης μακεδονιας'], dtype=object)

In [38]:
merged_timeline.drop(columns=['nuts2'], inplace = True)
merged_timeline.rename(columns={'nuts3': 'NUTS3_NAME'}, inplace= True)

In [39]:
merged_timeline['NUTS3_NAME'] = merged_timeline['NUTS3_NAME'].apply(lambda x : x.replace('ημαθιας','ημαθια'))
merged_timeline['NUTS3_NAME'] = merged_timeline['NUTS3_NAME'].apply(lambda x : x.replace('θεσσαλονικης','θεσσαλονικη'))
merged_timeline['NUTS3_NAME'] = merged_timeline['NUTS3_NAME'].apply(lambda x : x.replace('πελλας','πελλα'))
merged_timeline['NUTS3_NAME'] = merged_timeline['NUTS3_NAME'].apply(lambda x : x.replace('πιεριας','πιερια'))
merged_timeline['NUTS3_NAME'] = merged_timeline['NUTS3_NAME'].apply(lambda x : x.replace('σερρων','σερρες'))
merged_timeline['NUTS3_NAME'] = merged_timeline['NUTS3_NAME'].apply(lambda x : x.replace('χαλκιδικης','χαλκιδικη'))

In [40]:
merged_timeline['NUTS2_NAME'] = 'κεντρικη μακεδονια'

In [43]:
merged_timeline = merged_timeline[['NUTS2_NAME', 'NUTS3_NAME', 'dt_placement', 'cases']]
merged_timeline

             NUTS2_NAME NUTS3_NAME dt_placement  cases
0    κεντρικη μακεδονια     ημαθια      2010-06      0
1    κεντρικη μακεδονια     ημαθια      2010-07      6
2    κεντρικη μακεδονια     ημαθια      2010-08     36
3    κεντρικη μακεδονια     ημαθια      2010-09      7
4    κεντρικη μακεδονια     ημαθια      2010-10      0
..                  ...        ...          ...    ...
373  κεντρικη μακεδονια  χαλκιδικη      2022-07      0
374  κεντρικη μακεδονια  χαλκιδικη      2022-08     12
375  κεντρικη μακεδονια  χαλκιδικη      2022-09     10
376  κεντρικη μακεδονια  χαλκιδικη      2022-10      1
377  κεντρικη μακεδονια  χαλκιδικη      2022-11      0

[378 rows x 4 columns]

In [44]:
merged_timeline.to_csv(f"../../data/{NUTS2}/{NUTS0}_{NUTS2}_WNV_Cases_NUTS3_2010-2022.csv", encoding = enc, index = False)