In [10]:
import pandas as pd

enc = 'utf-8'
dec = 'greek8'

pd.options.display.max_columns = None
pd.options.display.max_rows = 10

In [11]:
data = pd.read_csv('data/GR_WNV_cases_2010-2021_processed.csv', encoding = enc)
data.head(5)

,onset of symptoms,year,month,day,nuts2,nuts3,lau1,lau2,age,sex
0,2010-07-28,2010,7,28,κεντρικης μακεδονιας,θεσσαλονικης,θεσσαλονικης,"παπαφη, θεσσαλονικη",75,f
1,2010-07-22,2010,7,22,κεντρικης μακεδονιας,ημαθιας,βεροιας,βεροια,78,m
2,2010-07-24,2010,7,24,κεντρικης μακεδονιας,κιλκις,κιλκις,λεβεντοχωρι,70,f
3,2010-07-30,2010,7,30,κεντρικης μακεδονιας,κιλκις,κιλκις,καμπανη,74,m
4,2010-07-06,2010,7,6,κεντρικης μακεδονιας,σερρων,ηρακλειας,ποντισμενο,19,f

In [12]:
df_cmacedonia = data[data['nuts2'].isin(['κεντρικης μακεδονιας'])].copy()

In [13]:
df_cmacedonia.reset_index(drop = True, inplace = True)

In [14]:
df_cmacedonia

,onset of symptoms,year,month,day,nuts2,nuts3,lau1,lau2,age,sex
0,2010-07-28,2010,7,28,κεντρικης μακεδονιας,θεσσαλονικης,θεσσαλονικης,"παπαφη, θεσσαλονικη",75,f
1,2010-07-22,2010,7,22,κεντρικης μακεδονιας,ημαθιας,βεροιας,βεροια,78,m
2,2010-07-24,2010,7,24,κεντρικης μακεδονιας,κιλκις,κιλκις,λεβεντοχωρι,70,f
3,2010-07-30,2010,7,30,κεντρικης μακεδονιας,κιλκις,κιλκις,καμπανη,74,m
4,2010-07-06,2010,7,6,κεντρικης μακεδονιας,σερρων,ηρακλειας,ποντισμενο,19,f
...,...,...,...,...,...,...,...,...,...,...
627,2021-09-17,2021,9,17,κεντρικης μακεδονιας,ημαθιας,αλεξανδρειας,κλειδι,51,f
628,2021-09-13,2021,9,13,κεντρικης μακεδονιας,ημαθιας,ηρωικης πολης ναουσας,αγγελοχωρι,85,m
629,2021-09-03,2021,9,3,κεντρικης μακεδονιας,ημαθιας,αλεξανδρειας,πλατυ,52,f
630,2021-10-04,2021,10,4,κεντρικης μακεδονιας,θεσσαλονικης,θερμαϊκου,περαια,65,m
631,2021-10-25,2021,10,25,κεντρικης μακεδονιας,ημαθιας,αλεξανδρειας,αλεξανδρεια,65,m

In [15]:
cmacedonia_lau1 = df_cmacedonia['lau1'].drop_duplicates().sort_values().tolist()

with open('data/GR_WNV_CMacedonia_lau1_processed.txt', 'w', encoding=enc) as f:
    for item in cmacedonia_lau1:
        f.write("%s\n" % item)
  
print(f"Number of LAU1 Units in Central Macedonia (from cases): {len(cmacedonia_lau1)}")

Number of LAU1 Units in Central Macedonia (from cases): 37

In [16]:
df_cmacedonia['period'] = df_cmacedonia.apply(lambda row: 1 if (row['day']>=1 and row['day']<=15) else 2, axis = 1)
df_cmacedonia['dt_placement'] = df_cmacedonia.apply(lambda row: f"{row['year']:04}-{row['month']:02}-{1 if row['period'] == 1 else 16:02}", axis = 1)

df_cmacedonia['dt_placement']= pd.to_datetime(df_cmacedonia['dt_placement'])
df_cmacedonia['case'] = 1

In [17]:
df_cmacedonia

,onset of symptoms,year,month,day,nuts2,nuts3,lau1,lau2,age,sex,period,dt_placement,case
0,2010-07-28,2010,7,28,κεντρικης μακεδονιας,θεσσαλονικης,θεσσαλονικης,"παπαφη, θεσσαλονικη",75,f,2,2010-07-16,1
1,2010-07-22,2010,7,22,κεντρικης μακεδονιας,ημαθιας,βεροιας,βεροια,78,m,2,2010-07-16,1
2,2010-07-24,2010,7,24,κεντρικης μακεδονιας,κιλκις,κιλκις,λεβεντοχωρι,70,f,2,2010-07-16,1
3,2010-07-30,2010,7,30,κεντρικης μακεδονιας,κιλκις,κιλκις,καμπανη,74,m,2,2010-07-16,1
4,2010-07-06,2010,7,6,κεντρικης μακεδονιας,σερρων,ηρακλειας,ποντισμενο,19,f,1,2010-07-01,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
627,2021-09-17,2021,9,17,κεντρικης μακεδονιας,ημαθιας,αλεξανδρειας,κλειδι,51,f,2,2021-09-16,1
628,2021-09-13,2021,9,13,κεντρικης μακεδονιας,ημαθιας,ηρωικης πολης ναουσας,αγγελοχωρι,85,m,1,2021-09-01,1
629,2021-09-03,2021,9,3,κεντρικης μακεδονιας,ημαθιας,αλεξανδρειας,πλατυ,52,f,1,2021-09-01,1
630,2021-10-04,2021,10,4,κεντρικης μακεδονιας,θεσσαλονικης,θερμαϊκου,περαια,65,m,1,2021-10-01,1
631,2021-10-25,2021,10,25,κεντρικης μακεδονιας,ημαθιας,αλεξανδρειας,αλεξανδρεια,65,m,2,2021-10-16,1

In [18]:
df_cmacedonia.drop(columns = ['onset of symptoms', 'day', 'nuts3', 'lau2', 'age', 'sex', 'period'], inplace = True)

In [19]:
df_cmacedonia = df_cmacedonia[['month', 'year', 'lau1', 'nuts2', 'dt_placement', 'case']]

In [20]:
df_cmacedonia

,month,year,lau1,nuts2,dt_placement,case
0,7,2010,θεσσαλονικης,κεντρικης μακεδονιας,2010-07-16,1
1,7,2010,βεροιας,κεντρικης μακεδονιας,2010-07-16,1
2,7,2010,κιλκις,κεντρικης μακεδονιας,2010-07-16,1
3,7,2010,κιλκις,κεντρικης μακεδονιας,2010-07-16,1
4,7,2010,ηρακλειας,κεντρικης μακεδονιας,2010-07-01,1
...,...,...,...,...,...,...
627,9,2021,αλεξανδρειας,κεντρικης μακεδονιας,2021-09-16,1
628,9,2021,ηρωικης πολης ναουσας,κεντρικης μακεδονιας,2021-09-01,1
629,9,2021,αλεξανδρειας,κεντρικης μακεδονιας,2021-09-01,1
630,10,2021,θερμαϊκου,κεντρικης μακεδονιας,2021-10-01,1
631,10,2021,αλεξανδρειας,κεντρικης μακεδονιας,2021-10-16,1

In [21]:
df_cmacedonia['month'].drop_duplicates().sort_values().tolist()

[6, 7, 8, 9, 10]

In [22]:
df_cmacedonia['year'].drop_duplicates().sort_values().tolist()

[2010, 2011, 2012, 2013, 2018, 2019, 2020, 2021]

In [23]:
## Creating DataFrame to hold negative examples

df_timeline = pd.DataFrame(columns = ['lau1', 'nuts2', 'dt_placement', 'case'])

for municipality in df_cmacedonia['lau1'].drop_duplicates().sort_values():
    for year in range(2010, 2022):
        for month in range (6,11):
            df_timeline = df_timeline.append({'lau1' : municipality, 'nuts2' : 'κεντρικης μακεδονιας', 'dt_placement' : f"{year:04}-{month:02}-{1:02}", 'case' : 0}, ignore_index = True)
            df_timeline = df_timeline.append({'lau1' : municipality, 'nuts2' : 'κεντρικης μακεδονιας', 'dt_placement' : f"{year:04}-{month:02}-{16:02}", 'case' : 0}, ignore_index = True)
            
df_timeline

              lau1                 nuts2 dt_placement case
0     αλεξανδρειας  κεντρικης μακεδονιας   2010-06-01    0
1     αλεξανδρειας  κεντρικης μακεδονιας   2010-06-16    0
2     αλεξανδρειας  κεντρικης μακεδονιας   2010-07-01    0
3     αλεξανδρειας  κεντρικης μακεδονιας   2010-07-16    0
4     αλεξανδρειας  κεντρικης μακεδονιας   2010-08-01    0
...            ...                   ...          ...  ...
4435  ωραιοκαστρου  κεντρικης μακεδονιας   2021-08-16    0
4436  ωραιοκαστρου  κεντρικης μακεδονιας   2021-09-01    0
4437  ωραιοκαστρου  κεντρικης μακεδονιας   2021-09-16    0
4438  ωραιοκαστρου  κεντρικης μακεδονιας   2021-10-01    0
4439  ωραιοκαστρου  κεντρικης μακεδονιας   2021-10-16    0

[4440 rows x 4 columns]

In [24]:
df_timeline['dt_placement']= pd.to_datetime(df_timeline['dt_placement'])

In [25]:
df_cmacedonia.reset_index(inplace = True, drop=True)
df_timeline.reset_index(inplace = True, drop=True)

In [26]:
## Add cases to negative examples DataFrame

#iterrate DataFrame with cases by row
for index, row in df_cmacedonia.iterrows():
    #find index at DataFrame with negative examples where location and date matches the DataFrame with cases
    idx = df_timeline.index[(df_timeline['lau1']==row['lau1']) & (df_timeline['dt_placement']==row['dt_placement'])]
    #get the previous case number using index
    previous_case = df_timeline._get_value(idx.values[0], 'case')
    #add 1 (one) to column case
    df_timeline.at[idx.values[0],'case'] = previous_case+1

In [27]:
df_timeline['case'].value_counts().sort_index()

0     4104
1      212
2       61
3       23
4       20
      ...
8        3
9        1
11       1
12       1
18       1
Name: case, Length: 13, dtype: int64

In [28]:
df_timeline

              lau1                 nuts2 dt_placement case
0     αλεξανδρειας  κεντρικης μακεδονιας   2010-06-01    0
1     αλεξανδρειας  κεντρικης μακεδονιας   2010-06-16    0
2     αλεξανδρειας  κεντρικης μακεδονιας   2010-07-01    0
3     αλεξανδρειας  κεντρικης μακεδονιας   2010-07-16    2
4     αλεξανδρειας  κεντρικης μακεδονιας   2010-08-01   11
...            ...                   ...          ...  ...
4435  ωραιοκαστρου  κεντρικης μακεδονιας   2021-08-16    0
4436  ωραιοκαστρου  κεντρικης μακεδονιας   2021-09-01    0
4437  ωραιοκαστρου  κεντρικης μακεδονιας   2021-09-16    0
4438  ωραιοκαστρου  κεντρικης μακεδονιας   2021-10-01    0
4439  ωραιοκαστρου  κεντρικης μακεδονιας   2021-10-16    0

[4440 rows x 4 columns]

In [29]:
df_timeline.to_csv("data/GR_CMacedonia_Epidemiological_Timeline_2010-2021.csv", encoding = enc, index = False)