In [1]:
import pandas as pd

enc = 'utf-8'
dec = 'greek8'

pd.options.display.max_columns = None
pd.options.display.max_rows = 10

In [2]:
data = pd.read_csv('data/GR_WNV_cases_2010-2021_processed.csv', encoding = enc)
data.head(5)

,onset of symptoms,year,month,day,nuts2,nuts3,lau1,lau2,age,sex
0,2010-07-28,2010,7,28,κεντρικης μακεδονιας,θεσσαλονικης,θεσσαλονικης,"παπαφη, θεσσαλονικη",75,f
1,2010-07-22,2010,7,22,κεντρικης μακεδονιας,ημαθιας,βεροιας,βεροια,78,m
2,2010-07-24,2010,7,24,κεντρικης μακεδονιας,κιλκις,κιλκις,λεβεντοχωρι,70,f
3,2010-07-30,2010,7,30,κεντρικης μακεδονιας,κιλκις,κιλκις,καμπανη,74,m
4,2010-07-06,2010,7,6,κεντρικης μακεδονιας,σερρων,ηρακλειας,ποντισμενο,19,f

In [3]:
df_thrace = data[data['nuts2'].isin(['ανατολικης μακεδονιας & θρακης'])].copy()

In [4]:
df_thrace.reset_index(drop = True, inplace = True)

In [5]:
df_thrace

,onset of symptoms,year,month,day,nuts2,nuts3,lau1,lau2,age,sex
0,2010-10-05,2010,10,5,ανατολικης μακεδονιας & θρακης,καβαλας,νεστου,πηγη,70,m
1,2012-07-30,2012,7,30,ανατολικης μακεδονιας & θρακης,ξανθης,ξανθης,χρυσα,76,m
2,2012-08-04,2012,8,4,ανατολικης μακεδονιας & θρακης,ξανθης,τοπειρου,αγιος αθανασιος,68,m
3,2012-08-05,2012,8,5,ανατολικης μακεδονιας & θρακης,καβαλας,καβαλας,φιλιπποι,76,m
4,2012-08-04,2012,8,4,ανατολικης μακεδονιας & θρακης,ξανθης,αβδηρων,πετεινος,75,m
...,...,...,...,...,...,...,...,...,...,...
254,2020-10-08,2020,10,8,ανατολικης μακεδονιας & θρακης,καβαλας,καβαλας,κρηνιδες,76,m
255,2021-08-12,2021,8,12,ανατολικης μακεδονιας & θρακης,καβαλας,παγγαιου,παραλια οφρυνιου (τουζλα),42,f
256,2021-07-19,2021,7,19,ανατολικης μακεδονιας & θρακης,δραμας,δραμας,μικροχωρι,72,f
257,2021-08-31,2021,8,31,ανατολικης μακεδονιας & θρακης,καβαλας,καβαλας,καβαλα,55,m
258,2021-08-31,2021,8,31,ανατολικης μακεδονιας & θρακης,καβαλας,παγγαιου,παραλια οφρυνιου (τουζλα),46,m

In [6]:
thrace_lau1 = df_thrace['lau1'].drop_duplicates().sort_values().tolist()

with open('data/GR_WNV_Thrace_lau1_processed.txt', 'w', encoding=enc) as f:
    for item in thrace_lau1:
        f.write("%s\n" % item)
  
print(f"Number of LAU1 Units in Thrace (from cases): {len(thrace_lau1)}")

Number of LAU1 Units in Thrace (from cases): 18

In [7]:
df_thrace['period'] = df_thrace.apply(lambda row: 1 if (row['day']>=1 and row['day']<=15) else 2, axis = 1)
df_thrace['dt_placement'] = df_thrace.apply(lambda row: f"{row['year']:04}-{row['month']:02}-{1 if row['period'] == 1 else 16:02}", axis = 1)

df_thrace['dt_placement']= pd.to_datetime(df_thrace['dt_placement'])
df_thrace['case'] = 1

In [8]:
df_thrace

,onset of symptoms,year,month,day,nuts2,nuts3,lau1,lau2,age,sex,period,dt_placement,case
0,2010-10-05,2010,10,5,ανατολικης μακεδονιας & θρακης,καβαλας,νεστου,πηγη,70,m,1,2010-10-01,1
1,2012-07-30,2012,7,30,ανατολικης μακεδονιας & θρακης,ξανθης,ξανθης,χρυσα,76,m,2,2012-07-16,1
2,2012-08-04,2012,8,4,ανατολικης μακεδονιας & θρακης,ξανθης,τοπειρου,αγιος αθανασιος,68,m,1,2012-08-01,1
3,2012-08-05,2012,8,5,ανατολικης μακεδονιας & θρακης,καβαλας,καβαλας,φιλιπποι,76,m,1,2012-08-01,1
4,2012-08-04,2012,8,4,ανατολικης μακεδονιας & θρακης,ξανθης,αβδηρων,πετεινος,75,m,1,2012-08-01,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
254,2020-10-08,2020,10,8,ανατολικης μακεδονιας & θρακης,καβαλας,καβαλας,κρηνιδες,76,m,1,2020-10-01,1
255,2021-08-12,2021,8,12,ανατολικης μακεδονιας & θρακης,καβαλας,παγγαιου,παραλια οφρυνιου (τουζλα),42,f,1,2021-08-01,1
256,2021-07-19,2021,7,19,ανατολικης μακεδονιας & θρακης,δραμας,δραμας,μικροχωρι,72,f,2,2021-07-16,1
257,2021-08-31,2021,8,31,ανατολικης μακεδονιας & θρακης,καβαλας,καβαλας,καβαλα,55,m,2,2021-08-16,1
258,2021-08-31,2021,8,31,ανατολικης μακεδονιας & θρακης,καβαλας,παγγαιου,παραλια οφρυνιου (τουζλα),46,m,2,2021-08-16,1

In [9]:
df_thrace.drop(columns = ['onset of symptoms', 'day', 'nuts3', 'lau2', 'age', 'sex', 'period'], inplace = True)

In [10]:
df_thrace = df_thrace[['month', 'year', 'lau1', 'nuts2', 'dt_placement', 'case']]

In [11]:
df_thrace

     month  year      lau1                           nuts2 dt_placement  case
0       10  2010    νεστου  ανατολικης μακεδονιας & θρακης   2010-10-01     1
1        7  2012    ξανθης  ανατολικης μακεδονιας & θρακης   2012-07-16     1
2        8  2012  τοπειρου  ανατολικης μακεδονιας & θρακης   2012-08-01     1
3        8  2012   καβαλας  ανατολικης μακεδονιας & θρακης   2012-08-01     1
4        8  2012   αβδηρων  ανατολικης μακεδονιας & θρακης   2012-08-01     1
..     ...   ...       ...                             ...          ...   ...
254     10  2020   καβαλας  ανατολικης μακεδονιας & θρακης   2020-10-01     1
255      8  2021  παγγαιου  ανατολικης μακεδονιας & θρακης   2021-08-01     1
256      7  2021    δραμας  ανατολικης μακεδονιας & θρακης   2021-07-16     1
257      8  2021   καβαλας  ανατολικης μακεδονιας & θρακης   2021-08-16     1
258      8  2021  παγγαιου  ανατολικης μακεδονιας & θρακης   2021-08-16     1

[259 rows x 6 columns]

In [12]:
df_thrace['month'].drop_duplicates().sort_values().tolist()

[6, 7, 8, 9, 10]

In [13]:
df_thrace['year'].drop_duplicates().sort_values().tolist()

[2010, 2012, 2013, 2014, 2018, 2019, 2020, 2021]

In [14]:
## Creating DataFrame to hold negative examples

df_timeline = pd.DataFrame(columns = ['lau1', 'nuts2', 'dt_placement', 'case'])

for municipality in df_thrace['lau1'].drop_duplicates().sort_values():
    for year in range(2010, 2022):
        for month in range (6,11):
            df_timeline = df_timeline.append({'lau1' : municipality, 'nuts2' : 'ανατολικης μακεδονιας και θρακης', 'dt_placement' : f"{year:04}-{month:02}-{1:02}", 'case' : 0}, ignore_index = True)
            df_timeline = df_timeline.append({'lau1' : municipality, 'nuts2' : 'ανατολικης μακεδονιας και θρακης', 'dt_placement' : f"{year:04}-{month:02}-{16:02}", 'case' : 0}, ignore_index = True)
            
df_timeline

          lau1                             nuts2 dt_placement case
0      αβδηρων  ανατολικης μακεδονιας και θρακης   2010-06-01    0
1      αβδηρων  ανατολικης μακεδονιας και θρακης   2010-06-16    0
2      αβδηρων  ανατολικης μακεδονιας και θρακης   2010-07-01    0
3      αβδηρων  ανατολικης μακεδονιας και θρακης   2010-07-16    0
4      αβδηρων  ανατολικης μακεδονιας και θρακης   2010-08-01    0
...        ...                               ...          ...  ...
2155  τοπειρου  ανατολικης μακεδονιας και θρακης   2021-08-16    0
2156  τοπειρου  ανατολικης μακεδονιας και θρακης   2021-09-01    0
2157  τοπειρου  ανατολικης μακεδονιας και θρακης   2021-09-16    0
2158  τοπειρου  ανατολικης μακεδονιας και θρακης   2021-10-01    0
2159  τοπειρου  ανατολικης μακεδονιας και θρακης   2021-10-16    0

[2160 rows x 4 columns]

In [15]:
df_timeline['dt_placement']= pd.to_datetime(df_timeline['dt_placement'])

In [16]:
df_thrace.reset_index(inplace = True, drop=True)
df_timeline.reset_index(inplace = True, drop=True)

In [17]:
## Add cases to negative examples DataFrame

#iterrate DataFrame with cases by row
for index, row in df_thrace.iterrows():
    #find index at DataFrame with negative examples where location and date matches the DataFrame with cases
    idx = df_timeline.index[(df_timeline['lau1']==row['lau1']) & (df_timeline['dt_placement']==row['dt_placement'])]
    #get the previous case number using index
    previous_case = df_timeline._get_value(idx.values[0], 'case')
    #add 1 (one) to column case
    df_timeline.at[idx.values[0],'case'] = previous_case+1

In [18]:
df_timeline['case'].value_counts().sort_index()

0     2029
1       78
2       25
3       12
4        7
5        3
7        3
9        1
10       1
12       1
Name: case, dtype: int64

In [19]:
df_timeline

          lau1                             nuts2 dt_placement case
0      αβδηρων  ανατολικης μακεδονιας και θρακης   2010-06-01    0
1      αβδηρων  ανατολικης μακεδονιας και θρακης   2010-06-16    0
2      αβδηρων  ανατολικης μακεδονιας και θρακης   2010-07-01    0
3      αβδηρων  ανατολικης μακεδονιας και θρακης   2010-07-16    0
4      αβδηρων  ανατολικης μακεδονιας και θρακης   2010-08-01    0
...        ...                               ...          ...  ...
2155  τοπειρου  ανατολικης μακεδονιας και θρακης   2021-08-16    0
2156  τοπειρου  ανατολικης μακεδονιας και θρακης   2021-09-01    0
2157  τοπειρου  ανατολικης μακεδονιας και θρακης   2021-09-16    0
2158  τοπειρου  ανατολικης μακεδονιας και θρακης   2021-10-01    0
2159  τοπειρου  ανατολικης μακεδονιας και θρακης   2021-10-16    0

[2160 rows x 4 columns]

In [20]:
df_timeline.to_csv("data/GR_Thrace_Epidemiological_Timeline_2010-2021.csv", encoding = enc, index = False)