In [1]:
import pandas as pd

enc = 'utf-8'
dec = 'greek8'

pd.options.display.max_columns = None
pd.options.display.max_rows = 10

In [2]:
NUTS0 = 'GR'
NUTS2 = 'Thessaly'
NUTS2_EL = 'θεσσαλιας'

In [3]:
data = pd.read_csv(f'data/{NUTS0}_WNV_cases_2010-2021_processed.csv', encoding = enc)
data.head(5)

,onset of symptoms,year,month,day,nuts2,nuts3,lau1,lau2,age,sex
0,2010-07-28,2010,7,28,κεντρικης μακεδονιας,θεσσαλονικης,θεσσαλονικης,"παπαφη, θεσσαλονικη",75,f
1,2010-07-22,2010,7,22,κεντρικης μακεδονιας,ημαθιας,βεροιας,βεροια,78,m
2,2010-07-24,2010,7,24,κεντρικης μακεδονιας,κιλκις,κιλκις,λεβεντοχωρι,70,f
3,2010-07-30,2010,7,30,κεντρικης μακεδονιας,κιλκις,κιλκις,καμπανη,74,m
4,2010-07-06,2010,7,6,κεντρικης μακεδονιας,σερρων,ηρακλειας,ποντισμενο,19,f

In [4]:
df = data[data['nuts2'].isin([NUTS2_EL])].copy()

In [5]:
df.reset_index(drop = True, inplace = True)

In [6]:
df

,onset of symptoms,year,month,day,nuts2,nuts3,lau1,lau2,age,sex
0,2010-07-28,2010,7,28,θεσσαλιας,λαρισας,αγιας,ομολιο,59,m
1,2010-08-11,2010,8,11,θεσσαλιας,λαρισας,ελασσονας,τσαριτσανη,58,f
2,2010-08-21,2010,8,21,θεσσαλιας,λαρισας,λαρισαιων,λαρισα,72,f
3,2010-08-27,2010,8,27,θεσσαλιας,λαρισας,ελασσονας,μεσοχωρι,77,f
4,2010-09-02,2010,9,2,θεσσαλιας,λαρισας,ελασσονας,ελασσονα,80,f
...,...,...,...,...,...,...,...,...,...,...
104,2020-08-03,2020,8,3,θεσσαλιας,λαρισας,λαρισαιων,λαρισα,87,f
105,2020-08-10,2020,8,10,θεσσαλιας,καρδιτσας,καρδιτσας,πτελοπουλα,28,f
106,2020-08-20,2020,8,20,θεσσαλιας,καρδιτσας,καρδιτσας,μυρινα (η μυρινη),70,m
107,2020-09-05,2020,9,5,θεσσαλιας,τρικαλων,πυλης,παλαιομοναστηρο,71,m
108,2020-09-10,2020,9,10,θεσσαλιας,τρικαλων,τρικκαιων,πατουλια,81,m

In [7]:
wnv_lau1_list = df['lau1'].drop_duplicates().sort_values().tolist()

with open(f'data/{NUTS0}_WNV_{NUTS2}_lau1_processed.txt', 'w', encoding=enc) as f:
    for item in wnv_lau1_list:
        f.write("%s\n" % item)
  
print(f"Number of LAU1 Units in {NUTS2} (from cases): {len(wnv_lau1_list)}")

Number of LAU1 Units in Thessaly (from cases): 15

In [8]:
df['period'] = df.apply(lambda row: 1 if (row['day']>=1 and row['day']<=15) else 2, axis = 1)
df['dt_placement'] = df.apply(lambda row: f"{row['year']:04}-{row['month']:02}-{1 if row['period'] == 1 else 16:02}", axis = 1)

df['dt_placement']= pd.to_datetime(df['dt_placement'])
df['case'] = 1

In [9]:
df

,onset of symptoms,year,month,day,nuts2,nuts3,lau1,lau2,age,sex,period,dt_placement,case
0,2010-07-28,2010,7,28,θεσσαλιας,λαρισας,αγιας,ομολιο,59,m,2,2010-07-16,1
1,2010-08-11,2010,8,11,θεσσαλιας,λαρισας,ελασσονας,τσαριτσανη,58,f,1,2010-08-01,1
2,2010-08-21,2010,8,21,θεσσαλιας,λαρισας,λαρισαιων,λαρισα,72,f,2,2010-08-16,1
3,2010-08-27,2010,8,27,θεσσαλιας,λαρισας,ελασσονας,μεσοχωρι,77,f,2,2010-08-16,1
4,2010-09-02,2010,9,2,θεσσαλιας,λαρισας,ελασσονας,ελασσονα,80,f,1,2010-09-01,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
104,2020-08-03,2020,8,3,θεσσαλιας,λαρισας,λαρισαιων,λαρισα,87,f,1,2020-08-01,1
105,2020-08-10,2020,8,10,θεσσαλιας,καρδιτσας,καρδιτσας,πτελοπουλα,28,f,1,2020-08-01,1
106,2020-08-20,2020,8,20,θεσσαλιας,καρδιτσας,καρδιτσας,μυρινα (η μυρινη),70,m,2,2020-08-16,1
107,2020-09-05,2020,9,5,θεσσαλιας,τρικαλων,πυλης,παλαιομοναστηρο,71,m,1,2020-09-01,1
108,2020-09-10,2020,9,10,θεσσαλιας,τρικαλων,τρικκαιων,πατουλια,81,m,1,2020-09-01,1

In [10]:
df.drop(columns = ['onset of symptoms', 'day', 'nuts3', 'lau2', 'age', 'sex', 'period'], inplace = True)

In [11]:
df = df[['month', 'year', 'lau1', 'nuts2', 'dt_placement', 'case']]

In [12]:
df

     month  year       lau1      nuts2 dt_placement  case
0        7  2010      αγιας  θεσσαλιας   2010-07-16     1
1        8  2010  ελασσονας  θεσσαλιας   2010-08-01     1
2        8  2010  λαρισαιων  θεσσαλιας   2010-08-16     1
3        8  2010  ελασσονας  θεσσαλιας   2010-08-16     1
4        9  2010  ελασσονας  θεσσαλιας   2010-09-01     1
..     ...   ...        ...        ...          ...   ...
104      8  2020  λαρισαιων  θεσσαλιας   2020-08-01     1
105      8  2020  καρδιτσας  θεσσαλιας   2020-08-01     1
106      8  2020  καρδιτσας  θεσσαλιας   2020-08-16     1
107      9  2020      πυλης  θεσσαλιας   2020-09-01     1
108      9  2020  τρικκαιων  θεσσαλιας   2020-09-01     1

[109 rows x 6 columns]

In [23]:
case_months = df['month'].drop_duplicates().sort_values().tolist()
case_months

[7, 8, 9, 10]

In [24]:
case_years = df['year'].drop_duplicates().sort_values().tolist()
case_years

[2010, 2011, 2018, 2019, 2020]

In [26]:
with open(f'data/{NUTS0}_WNV_{NUTS2}_cases_dates.txt', 'w', encoding=enc) as f:

    f.write("%s: " % 'months')
    for item in case_months:
        f.write("%s, " % item)

    f.write("\n")

    f.write("%s: " % 'years')
    for item in case_years:
        f.write("%s, " % item)

In [15]:
## Creating DataFrame to hold negative examples

df_timeline = pd.DataFrame(columns = ['lau1', 'nuts2', 'dt_placement', 'case'])

for municipality in df['lau1'].drop_duplicates().sort_values():
    for year in range(2010, 2022):
        for month in range (6,11):
            df_timeline = df_timeline.append({'lau1' : municipality, 'nuts2' : NUTS2_EL, 'dt_placement' : f"{year:04}-{month:02}-{1:02}", 'case' : 0}, ignore_index = True)
            df_timeline = df_timeline.append({'lau1' : municipality, 'nuts2' : NUTS2_EL, 'dt_placement' : f"{year:04}-{month:02}-{16:02}", 'case' : 0}, ignore_index = True)
            
df_timeline

          lau1      nuts2 dt_placement case
0        αγιας  θεσσαλιας   2010-06-01    0
1        αγιας  θεσσαλιας   2010-06-16    0
2        αγιας  θεσσαλιας   2010-07-01    0
3        αγιας  θεσσαλιας   2010-07-16    0
4        αγιας  θεσσαλιας   2010-08-01    0
...        ...        ...          ...  ...
1795  φαρσαλων  θεσσαλιας   2021-08-16    0
1796  φαρσαλων  θεσσαλιας   2021-09-01    0
1797  φαρσαλων  θεσσαλιας   2021-09-16    0
1798  φαρσαλων  θεσσαλιας   2021-10-01    0
1799  φαρσαλων  θεσσαλιας   2021-10-16    0

[1800 rows x 4 columns]

In [16]:
df_timeline['dt_placement']= pd.to_datetime(df_timeline['dt_placement'])

In [17]:
df.reset_index(inplace = True, drop=True)
df_timeline.reset_index(inplace = True, drop=True)

In [18]:
## Add cases to negative examples DataFrame

#iterrate DataFrame with cases by row
for index, row in df.iterrows():
    #find index at DataFrame with negative examples where location and date matches the DataFrame with cases
    idx = df_timeline.index[(df_timeline['lau1']==row['lau1']) & (df_timeline['dt_placement']==row['dt_placement'])]
    #get the previous case number using index
    previous_case = df_timeline._get_value(idx.values[0], 'case')
    #add 1 (one) to column case
    df_timeline.at[idx.values[0],'case'] = previous_case+1

In [19]:
df_timeline['case'].value_counts().sort_index()

0    1727
1      47
2      20
3       5
7       1
Name: case, dtype: int64

In [20]:
df_timeline

          lau1      nuts2 dt_placement case
0        αγιας  θεσσαλιας   2010-06-01    0
1        αγιας  θεσσαλιας   2010-06-16    0
2        αγιας  θεσσαλιας   2010-07-01    0
3        αγιας  θεσσαλιας   2010-07-16    1
4        αγιας  θεσσαλιας   2010-08-01    0
...        ...        ...          ...  ...
1795  φαρσαλων  θεσσαλιας   2021-08-16    0
1796  φαρσαλων  θεσσαλιας   2021-09-01    0
1797  φαρσαλων  θεσσαλιας   2021-09-16    0
1798  φαρσαλων  θεσσαλιας   2021-10-01    0
1799  φαρσαλων  θεσσαλιας   2021-10-16    0

[1800 rows x 4 columns]

In [21]:
df_timeline.to_csv(f"data/{NUTS0}_{NUTS2}_Epidemiological_Timeline_2010-2021.csv", encoding = enc, index = False)