## Creates the **Epidemiological Timeline** for a specific region by using the available data on WNV Cases ##

In [1]:
import pandas as pd
import numpy as np

enc = 'utf-8'
dec = 'greek8'

pd.options.display.max_columns = None
pd.options.display.max_rows = 10

In [2]:
NUTS0 = 'GR'
NUTS2 = 'Thrace'
NUTS2_EL = 'ανατολικης μακεδονιας και θρακης'

In [3]:
data = pd.read_csv(f'../../data/{NUTS0}_WNV_cases_2010-2023_processed.csv', encoding = enc)
data.head(5)

,onset of symptoms,year,month,day,nuts2,nuts3,cases
0,2010-07-06,2010,7,6,κεντρικης μακεδονιας,σερρων,1
1,2010-07-16,2010,7,16,κεντρικης μακεδονιας,κιλκις,1
2,2010-07-18,2010,7,18,κεντρικης μακεδονιας,πελλας,1
3,2010-07-19,2010,7,19,κεντρικης μακεδονιας,θεσσαλονικης,2
4,2010-07-20,2010,7,20,κεντρικης μακεδονιας,ημαθιας,1

In [4]:
data.shape

(1431, 7)

In [5]:
df = data[data['nuts2'].isin([NUTS2_EL])].copy()

In [6]:
df.reset_index(drop = True, inplace = True)

In [7]:
df.drop(columns = ['onset of symptoms', 'day'], inplace = True)

In [8]:
df

     year  month                             nuts2    nuts3  cases
0    2010     10  ανατολικης μακεδονιας και θρακης  καβαλας      1
1    2012      7  ανατολικης μακεδονιας και θρακης   ξανθης      1
2    2012      8  ανατολικης μακεδονιας και θρακης   ξανθης      2
3    2012      8  ανατολικης μακεδονιας και θρακης   ξανθης      3
4    2012      8  ανατολικης μακεδονιας και θρακης  καβαλας      2
..    ...    ...                               ...      ...    ...
225  2023      9  ανατολικης μακεδονιας και θρακης  καβαλας      1
226  2023      9  ανατολικης μακεδονιας και θρακης  καβαλας      1
227  2023      9  ανατολικης μακεδονιας και θρακης  καβαλας      1
228  2023      9  ανατολικης μακεδονιας και θρακης    εβρου      1
229  2023     10  ανατολικης μακεδονιας και θρακης   δραμας      1

[230 rows x 5 columns]

In [9]:
df.cases.sum()

282

In [10]:
df_grouped = df.groupby(['year', 'month', 'nuts2', 'nuts3'], as_index = False)
df = df_grouped.sum()

In [11]:
df

    year  month                             nuts2    nuts3  cases
0   2010     10  ανατολικης μακεδονιας και θρακης  καβαλας      1
1   2012      7  ανατολικης μακεδονιας και θρακης   ξανθης      1
2   2012      8  ανατολικης μακεδονιας και θρακης   δραμας      1
3   2012      8  ανατολικης μακεδονιας και θρακης  καβαλας     16
4   2012      8  ανατολικης μακεδονιας και θρακης   ξανθης     38
..   ...    ...                               ...      ...    ...
58  2023      9  ανατολικης μακεδονιας και θρακης   δραμας      2
59  2023      9  ανατολικης μακεδονιας και θρακης    εβρου      1
60  2023      9  ανατολικης μακεδονιας και θρακης  καβαλας      4
61  2023      9  ανατολικης μακεδονιας και θρακης   ξανθης      1
62  2023     10  ανατολικης μακεδονιας και θρακης   δραμας      1

[63 rows x 5 columns]

In [12]:
df.cases.sum()

282

In [13]:
print(np.sort(df.cases.unique()))

[ 1  2  3  4  5  6  7  9 10 11 16 21 23 38]

In [14]:
wnv_lau1_list = df['nuts3'].drop_duplicates().sort_values().tolist()

with open(f'../../data/{NUTS2}/{NUTS0}_{NUTS2}_WNV_2010-2023_NUTS3_Units_Processed.txt', 'w', encoding=enc) as f:
    for item in wnv_lau1_list:
        f.write("%s\n" % item)
  
print(f"Number of NUTS3 Units in {NUTS2} (from cases): {len(wnv_lau1_list)}")

Number of NUTS3 Units in Thrace (from cases): 5

In [15]:
df['date_string'] = df['month'].astype(str) + '-' + df['year'].astype(str)

# Convert 'date_string' column to datetime format
df['dt_placement'] = pd.to_datetime(df['date_string'], format='%m-%Y').dt.to_period('M')
df.drop(columns=['date_string'], inplace = True)

In [16]:
df

    year  month                             nuts2    nuts3  cases dt_placement
0   2010     10  ανατολικης μακεδονιας και θρακης  καβαλας      1      2010-10
1   2012      7  ανατολικης μακεδονιας και θρακης   ξανθης      1      2012-07
2   2012      8  ανατολικης μακεδονιας και θρακης   δραμας      1      2012-08
3   2012      8  ανατολικης μακεδονιας και θρακης  καβαλας     16      2012-08
4   2012      8  ανατολικης μακεδονιας και θρακης   ξανθης     38      2012-08
..   ...    ...                               ...      ...    ...          ...
58  2023      9  ανατολικης μακεδονιας και θρακης   δραμας      2      2023-09
59  2023      9  ανατολικης μακεδονιας και θρακης    εβρου      1      2023-09
60  2023      9  ανατολικης μακεδονιας και θρακης  καβαλας      4      2023-09
61  2023      9  ανατολικης μακεδονιας και θρακης   ξανθης      1      2023-09
62  2023     10  ανατολικης μακεδονιας και θρακης   δραμας      1      2023-10

[63 rows x 6 columns]

In [17]:
df.cases.sum()

282

In [18]:
case_months = df['month'].drop_duplicates().sort_values().tolist()
case_months

[6, 7, 8, 9, 10]

In [19]:
case_years = df['year'].drop_duplicates().sort_values().tolist()
case_years

[2010, 2012, 2013, 2014, 2018, 2019, 2020, 2021, 2022, 2023]

In [20]:
with open(f'../../data/{NUTS2}/{NUTS0}_{NUTS2}_WNV_2010-2023_NUTS3_Cases_Dates.txt', 'w', encoding=enc) as f:

    f.write("%s: " % 'months')
    for item in case_months:
        f.write("%s, " % item)

    f.write("\n")

    f.write("%s: " % 'years')
    for item in case_years:
        f.write("%s, " % item)

In [21]:
df.drop(columns=['month', 'year'], inplace = True)

In [22]:
## Creating DataFrame to hold negative examples

df_timeline = pd.DataFrame(columns = ['nuts2', 'nuts3', 'dt_placement', 'cases'])
timeline = []

for nuts3 in df['nuts3'].drop_duplicates().sort_values():
    for year in case_years:
        for month in case_months:
            timeline.append({'nuts2' : NUTS2_EL, 'nuts3' : nuts3, 'dt_placement' : f"{year:04}-{month:02}", 'cases' : 0})
            
df_timeline = pd.DataFrame(timeline)

In [23]:
df_timeline

                                nuts2    nuts3 dt_placement  cases
0    ανατολικης μακεδονιας και θρακης   δραμας      2010-06      0
1    ανατολικης μακεδονιας και θρακης   δραμας      2010-07      0
2    ανατολικης μακεδονιας και θρακης   δραμας      2010-08      0
3    ανατολικης μακεδονιας και θρακης   δραμας      2010-09      0
4    ανατολικης μακεδονιας και θρακης   δραμας      2010-10      0
..                                ...      ...          ...    ...
245  ανατολικης μακεδονιας και θρακης  ροδοπης      2023-06      0
246  ανατολικης μακεδονιας και θρακης  ροδοπης      2023-07      0
247  ανατολικης μακεδονιας και θρακης  ροδοπης      2023-08      0
248  ανατολικης μακεδονιας και θρακης  ροδοπης      2023-09      0
249  ανατολικης μακεδονιας και θρακης  ροδοπης      2023-10      0

[250 rows x 4 columns]

In [24]:
df_timeline['dt_placement']= pd.to_datetime(df_timeline['dt_placement'], format='%Y-%m').dt.to_period('M')

In [25]:
df.reset_index(inplace = True, drop=True)
df_timeline.reset_index(inplace = True, drop=True)

In [26]:
rearranged_cols = ['nuts2',	'nuts3', 'dt_placement', 'cases']

# Reindex the DataFrame with the desired column order
df = df.reindex(columns=rearranged_cols)

In [27]:
df

                               nuts2    nuts3 dt_placement  cases
0   ανατολικης μακεδονιας και θρακης  καβαλας      2010-10      1
1   ανατολικης μακεδονιας και θρακης   ξανθης      2012-07      1
2   ανατολικης μακεδονιας και θρακης   δραμας      2012-08      1
3   ανατολικης μακεδονιας και θρακης  καβαλας      2012-08     16
4   ανατολικης μακεδονιας και θρακης   ξανθης      2012-08     38
..                               ...      ...          ...    ...
58  ανατολικης μακεδονιας και θρακης   δραμας      2023-09      2
59  ανατολικης μακεδονιας και θρακης    εβρου      2023-09      1
60  ανατολικης μακεδονιας και θρακης  καβαλας      2023-09      4
61  ανατολικης μακεδονιας και θρακης   ξανθης      2023-09      1
62  ανατολικης μακεδονιας και θρακης   δραμας      2023-10      1

[63 rows x 4 columns]

In [28]:
df_timeline

                                nuts2    nuts3 dt_placement  cases
0    ανατολικης μακεδονιας και θρακης   δραμας      2010-06      0
1    ανατολικης μακεδονιας και θρακης   δραμας      2010-07      0
2    ανατολικης μακεδονιας και θρακης   δραμας      2010-08      0
3    ανατολικης μακεδονιας και θρακης   δραμας      2010-09      0
4    ανατολικης μακεδονιας και θρακης   δραμας      2010-10      0
..                                ...      ...          ...    ...
245  ανατολικης μακεδονιας και θρακης  ροδοπης      2023-06      0
246  ανατολικης μακεδονιας και θρακης  ροδοπης      2023-07      0
247  ανατολικης μακεδονιας και θρακης  ροδοπης      2023-08      0
248  ανατολικης μακεδονιας και θρακης  ροδοπης      2023-09      0
249  ανατολικης μακεδονιας και θρακης  ροδοπης      2023-10      0

[250 rows x 4 columns]

In [29]:
merged_timeline = pd.merge(df_timeline, df, how ='left', on=['nuts2','nuts3','dt_placement'])

In [30]:
merged_timeline

                                nuts2    nuts3 dt_placement  cases_x  cases_y
0    ανατολικης μακεδονιας και θρακης   δραμας      2010-06        0      NaN
1    ανατολικης μακεδονιας και θρακης   δραμας      2010-07        0      NaN
2    ανατολικης μακεδονιας και θρακης   δραμας      2010-08        0      NaN
3    ανατολικης μακεδονιας και θρακης   δραμας      2010-09        0      NaN
4    ανατολικης μακεδονιας και θρακης   δραμας      2010-10        0      NaN
..                                ...      ...          ...      ...      ...
245  ανατολικης μακεδονιας και θρακης  ροδοπης      2023-06        0      NaN
246  ανατολικης μακεδονιας και θρακης  ροδοπης      2023-07        0      NaN
247  ανατολικης μακεδονιας και θρακης  ροδοπης      2023-08        0      1.0
248  ανατολικης μακεδονιας και θρακης  ροδοπης      2023-09        0      NaN
249  ανατολικης μακεδονιας και θρακης  ροδοπης      2023-10        0      NaN

[250 rows x 5 columns]

In [31]:
merged_timeline['cases_y'] = merged_timeline['cases_y'].fillna(0)

In [32]:
merged_timeline['cases'] = merged_timeline['cases_x'] + merged_timeline['cases_y']
merged_timeline = merged_timeline.drop(columns=['cases_x', 'cases_y'])
merged_timeline['cases'] = merged_timeline['cases'].astype(int)

In [33]:
merged_timeline

                                nuts2    nuts3 dt_placement  cases
0    ανατολικης μακεδονιας και θρακης   δραμας      2010-06      0
1    ανατολικης μακεδονιας και θρακης   δραμας      2010-07      0
2    ανατολικης μακεδονιας και θρακης   δραμας      2010-08      0
3    ανατολικης μακεδονιας και θρακης   δραμας      2010-09      0
4    ανατολικης μακεδονιας και θρακης   δραμας      2010-10      0
..                                ...      ...          ...    ...
245  ανατολικης μακεδονιας και θρακης  ροδοπης      2023-06      0
246  ανατολικης μακεδονιας και θρακης  ροδοπης      2023-07      0
247  ανατολικης μακεδονιας και θρακης  ροδοπης      2023-08      1
248  ανατολικης μακεδονιας και θρακης  ροδοπης      2023-09      0
249  ανατολικης μακεδονιας και θρακης  ροδοπης      2023-10      0

[250 rows x 4 columns]

In [34]:
merged_timeline['cases'].value_counts().sort_index()

0     187
1      22
2      10
3      11
4       2
     ...
11      1
16      1
21      1
23      1
38      1
Name: cases, Length: 15, dtype: int64

In [35]:
merged_timeline

                                nuts2    nuts3 dt_placement  cases
0    ανατολικης μακεδονιας και θρακης   δραμας      2010-06      0
1    ανατολικης μακεδονιας και θρακης   δραμας      2010-07      0
2    ανατολικης μακεδονιας και θρακης   δραμας      2010-08      0
3    ανατολικης μακεδονιας και θρακης   δραμας      2010-09      0
4    ανατολικης μακεδονιας και θρακης   δραμας      2010-10      0
..                                ...      ...          ...    ...
245  ανατολικης μακεδονιας και θρακης  ροδοπης      2023-06      0
246  ανατολικης μακεδονιας και θρακης  ροδοπης      2023-07      0
247  ανατολικης μακεδονιας και θρακης  ροδοπης      2023-08      1
248  ανατολικης μακεδονιας και θρακης  ροδοπης      2023-09      0
249  ανατολικης μακεδονιας και θρακης  ροδοπης      2023-10      0

[250 rows x 4 columns]

In [36]:
merged_timeline.cases.sum()

282

In [37]:
merged_timeline.nuts2.unique()

array(['ανατολικης μακεδονιας και θρακης'], dtype=object)

In [38]:
merged_timeline.drop(columns=['nuts2'], inplace = True)
merged_timeline.rename(columns={'nuts3': 'NUTS3_NAME'}, inplace= True)

In [39]:
merged_timeline.NUTS3_NAME.unique()

array(['δραμας', 'εβρου', 'καβαλας', 'ξανθης', 'ροδοπης'], dtype=object)

In [40]:
merged_timeline['NUTS3_NAME'] = merged_timeline['NUTS3_NAME'].apply(lambda x : x.replace('δραμας','δραμα'))
merged_timeline['NUTS3_NAME'] = merged_timeline['NUTS3_NAME'].apply(lambda x : x.replace('εβρου','εβρος'))
merged_timeline['NUTS3_NAME'] = merged_timeline['NUTS3_NAME'].apply(lambda x : x.replace('καβαλας','θασος, καβαλα'))
merged_timeline['NUTS3_NAME'] = merged_timeline['NUTS3_NAME'].apply(lambda x : x.replace('ξανθης','ξανθη'))
merged_timeline['NUTS3_NAME'] = merged_timeline['NUTS3_NAME'].apply(lambda x : x.replace('ροδοπης','ροδοπη'))

In [41]:
merged_timeline['NUTS2_NAME'] = 'ανατολικη μακεδονια, θρακη'

In [42]:
merged_timeline = merged_timeline[['NUTS2_NAME', 'NUTS3_NAME', 'dt_placement', 'cases']]
merged_timeline

                     NUTS2_NAME NUTS3_NAME dt_placement  cases
0    ανατολικη μακεδονια, θρακη      δραμα      2010-06      0
1    ανατολικη μακεδονια, θρακη      δραμα      2010-07      0
2    ανατολικη μακεδονια, θρακη      δραμα      2010-08      0
3    ανατολικη μακεδονια, θρακη      δραμα      2010-09      0
4    ανατολικη μακεδονια, θρακη      δραμα      2010-10      0
..                          ...        ...          ...    ...
245  ανατολικη μακεδονια, θρακη     ροδοπη      2023-06      0
246  ανατολικη μακεδονια, θρακη     ροδοπη      2023-07      0
247  ανατολικη μακεδονια, θρακη     ροδοπη      2023-08      1
248  ανατολικη μακεδονια, θρακη     ροδοπη      2023-09      0
249  ανατολικη μακεδονια, θρακη     ροδοπη      2023-10      0

[250 rows x 4 columns]

In [43]:
merged_timeline.to_csv(f"../../data/{NUTS2}/{NUTS0}_{NUTS2}_WNV_Cases_NUTS3_2010-2023.csv", encoding = enc, index = False)