## Creates the **Timeline** for a specific region by using the Grid File and the required dates ##

In [1]:
import pandas as pd
from datetime import date, timedelta

import random
import geopandas as gpd
import numpy as np

import sys

sys.path.insert(0, "../../../Modules")

from preprocessing_utils import *

enc = 'utf-8'

random.seed(0)

c:\Users\dimit\AppData\Local\Programs\Python\Python39\lib\site-packages\geopandas\_compat.py:112: UserWarning: The Shapely GEOS version (3.10.3-CAPI-1.16.1) is incompatible with the GEOS version PyGEOS was compiled with (3.10.4-CAPI-1.16.2). Conversions between both will be slow.
  warnings.warn(

In [2]:
import warnings
warnings.filterwarnings('ignore')

In [3]:
NUTS0 = 'IT'
NUTS2 = 'Veneto'
NUTS2_LOWER = 'veneto'

In [4]:
nuts2_grid = pd.read_csv(f'../../data/{NUTS2}/{NUTS0}_{NUTS2}_Grid.csv', encoding = enc)
nuts2_grid.head()

    nuts2         lau1         x         y
0  veneto  abano terme  11.79539  45.35783
1  veneto        adria  12.03247  45.07647
2  veneto        adria  12.05787  45.05851
3  veneto        adria  12.05787  45.07647
4  veneto         affi  10.77673  45.55680

In [4]:
## start and end date is defined from available epidemiological file

In [5]:
start = start_dt = date(2023, 5, 1)
end = end_dt = date(2023, 5, 1)
delta = timedelta(days=1)

In [6]:
dates = []

while start_dt <= end_dt:
    dates.append(start_dt.isoformat())
    start_dt += delta

In [7]:
print('Dates between', start, 'and', end)
print(dates)

Dates between 2023-05-01 and 2023-05-01
['2023-05-01']

In [8]:
len(dates)

1

In [9]:
nuts2_timeline = pd.DataFrame()

In [10]:
for index, row in nuts2_grid.iterrows():
    for date in dates:
        nuts2_timeline = nuts2_timeline.append({'lau1' : row['lau1'], 
                                                  'region' : row['nuts2'], 
                                                  'x' : row['x'],
                                                  'y' : row['y'],
                                                  'dt_placement': date}, 
                                                  ignore_index = True)

In [11]:
nuts2_timeline

                lau1  region         x         y dt_placement
0        abano terme  veneto  11.79539  45.35783   2023-05-01
1              adria  veneto  12.03247  45.07647   2023-05-01
2              adria  veneto  12.05787  45.05851   2023-05-01
3              adria  veneto  12.05787  45.07647   2023-05-01
4               affi  veneto  10.77673  45.55680   2023-05-01
..               ...     ...       ...       ...          ...
799            zevio  veneto  11.10178  45.35397   2023-05-01
800          zimella  veneto  11.35805  45.34777   2023-05-01
801  zoppe da cadore  veneto  12.17878  46.38835   2023-05-01
802        zovencedo  veneto  11.49430  45.43798   2023-05-01
803         zugliano  veneto  11.50206  45.73042   2023-05-01

[804 rows x 5 columns]

In [12]:
nuts2_timeline['dt_placement'] = pd.to_datetime(nuts2_timeline['dt_placement'])

In [13]:
nuts2_timeline.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 804 entries, 0 to 803
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   lau1          804 non-null    object
 1   region        804 non-null    object
 2   x             804 non-null    float64
 3   y             804 non-null    float64
 4   dt_placement  804 non-null    datetime64[ns]
dtypes: datetime64[ns](1), float64(2), object(2)
memory usage: 31.5+ KB

In [23]:
nuts2_timeline.to_csv(f'../../data/{NUTS2}/{NUTS0}_{NUTS2}_Timeline_2023-May-1st.csv', index = False)

In [17]:
# nuts2_timeline

In [18]:
# nuts2_timeline['dt_placement'].iloc[15].day

In [19]:
# nuts2_timeline_biweekly = nuts2_timeline.copy()
# remove = []

# for index, row in nuts2_timeline.iterrows():
#     if row['dt_placement'].day == 1 or row['dt_placement'].day == 16:
#         pass
#     else:
#         remove.append(index)


# nuts2_timeline_biweekly.drop(index = remove, axis = 1, inplace = True)
# nuts2_timeline_biweekly.reset_index(inplace = True, drop = True)

In [20]:
# nuts2_timeline_biweekly.info()

In [21]:
# nuts2_timeline_biweekly.to_csv(f'../../data/{NUTS2}/{NUTS0}_{NUTS2}_Timeline_Biweekly_2008-2019.csv', index = False)