## Creates the **Timeline** for a specific region by using the Grid File and the required dates ##

In [1]:
import pandas as pd
from datetime import date, timedelta

import random
import geopandas as gpd
import numpy as np

import sys

sys.path.insert(0, "../../../Modules")

from utils import *

enc = 'utf-8'

random.seed(0)

c:\Users\dimit\AppData\Local\Programs\Python\Python39\lib\site-packages\geopandas\_compat.py:112: UserWarning: The Shapely GEOS version (3.10.3-CAPI-1.16.1) is incompatible with the GEOS version PyGEOS was compiled with (3.10.4-CAPI-1.16.2). Conversions between both will be slow.
  warnings.warn(

In [2]:
NUTS0 = 'IT'
NUTS2 = 'Veneto'
NUTS2_LOWER = 'veneto'

In [3]:
nuts2_grid = pd.read_csv(f'../../data/{NUTS2}/{NUTS0}_{NUTS2}_Grid.csv', encoding = enc)
nuts2_grid.head()

    nuts2         lau1         x         y
0  veneto  abano terme  11.79324  45.35865
1  veneto        adria  12.05470  45.07423
2  veneto        adria  12.05470  45.05177
3  veneto        adria  12.02294  45.07423
4  veneto        adria  11.99118  45.07423

In [4]:
## start and end date is defined from available epidemiological file

In [5]:
start = start_dt = date(2008, 1, 1)
end = end_dt = date(2019, 12, 31)
delta = timedelta(days=1)

In [6]:
dates = []

while start_dt <= end_dt:
    dates.append(start_dt.isoformat())
    start_dt += delta

In [7]:
print('Dates between', start, 'and', end)
print(dates)

Dates between 2008-01-01 and 2019-12-31

In [8]:
len(dates)

4383

In [9]:
nuts2_timeline = pd.DataFrame()

In [10]:
data = []
for index, row in nuts2_grid.iterrows():
    for date in dates:
        data.append({'lau1': row['lau1'], 
                     'region': row['nuts2'], 
                     'x': row['x'], 
                     'y': row['y'], 
                     'dt_placement': date})

nuts2_timeline = pd.DataFrame(data)

In [11]:
nuts2_timeline

                lau1  region         x         y dt_placement
0        abano terme  veneto  11.79324  45.35865   2008-01-01
1        abano terme  veneto  11.79324  45.35865   2008-01-02
2        abano terme  veneto  11.79324  45.35865   2008-01-03
3        abano terme  veneto  11.79324  45.35865   2008-01-04
4        abano terme  veneto  11.79324  45.35865   2008-01-05
...              ...     ...       ...       ...          ...
3957844     zugliano  veneto  11.50206  45.73042   2019-12-27
3957845     zugliano  veneto  11.50206  45.73042   2019-12-28
3957846     zugliano  veneto  11.50206  45.73042   2019-12-29
3957847     zugliano  veneto  11.50206  45.73042   2019-12-30
3957848     zugliano  veneto  11.50206  45.73042   2019-12-31

[3957849 rows x 5 columns]

In [12]:
nuts2_timeline['dt_placement'] = pd.to_datetime(nuts2_timeline['dt_placement'])

In [13]:
nuts2_timeline.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3957849 entries, 0 to 3957848
Data columns (total 5 columns):
 #   Column        Dtype
---  ------        -----
 0   lau1          object
 1   region        object
 2   x             float64
 3   y             float64
 4   dt_placement  datetime64[ns]
dtypes: datetime64[ns](1), float64(2), object(2)
memory usage: 151.0+ MB

In [14]:
nuts2_timeline.to_csv(f'../../data/{NUTS2}/{NUTS0}_{NUTS2}_Timeline_2008-2019.csv', index = False)

In [15]:
nuts2_timeline

                lau1  region         x         y dt_placement
0        abano terme  veneto  11.79324  45.35865   2008-01-01
1        abano terme  veneto  11.79324  45.35865   2008-01-02
2        abano terme  veneto  11.79324  45.35865   2008-01-03
3        abano terme  veneto  11.79324  45.35865   2008-01-04
4        abano terme  veneto  11.79324  45.35865   2008-01-05
...              ...     ...       ...       ...          ...
3957844     zugliano  veneto  11.50206  45.73042   2019-12-27
3957845     zugliano  veneto  11.50206  45.73042   2019-12-28
3957846     zugliano  veneto  11.50206  45.73042   2019-12-29
3957847     zugliano  veneto  11.50206  45.73042   2019-12-30
3957848     zugliano  veneto  11.50206  45.73042   2019-12-31

[3957849 rows x 5 columns]

In [16]:
nuts2_timeline['dt_placement'].iloc[15].day

16

In [17]:
nuts2_timeline_biweekly = nuts2_timeline.copy()
remove = []

for index, row in nuts2_timeline.iterrows():
    if row['dt_placement'].day == 1 or row['dt_placement'].day == 16:
        pass
    else:
        remove.append(index)


nuts2_timeline_biweekly.drop(index = remove, axis = 1, inplace = True)
nuts2_timeline_biweekly.reset_index(inplace = True, drop = True)

In [18]:
nuts2_timeline_biweekly.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 260064 entries, 0 to 260063
Data columns (total 5 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   lau1          260064 non-null  object
 1   region        260064 non-null  object
 2   x             260064 non-null  float64
 3   y             260064 non-null  float64
 4   dt_placement  260064 non-null  datetime64[ns]
dtypes: datetime64[ns](1), float64(2), object(2)
memory usage: 9.9+ MB

In [19]:
nuts2_timeline_biweekly.to_csv(f'../../data/{NUTS2}/{NUTS0}_{NUTS2}_Timeline_Biweekly_2008-2019.csv', index = False)