## Creates the **Timeline** for a specific region by using the Grid File and the required dates ##

In [113]:
import pandas as pd
from datetime import date, timedelta, datetime

import random
import geopandas as gpd
import numpy as np

import sys

sys.path.insert(0, "../../../Modules")

from utils import *

enc = 'utf-8'

random.seed(0)

In [114]:
import warnings
warnings.filterwarnings('ignore')

In [115]:
NUTS0 = 'IT'
NUTS2 = 'Veneto'
NUTS2_LOWER = 'veneto'

In [116]:
YEAR = 2023
MONTH = 'August'
PERIOD = '1st'

In [117]:
nuts2_grid = pd.read_csv(f'../../data/{NUTS2}/{NUTS0}_{NUTS2}_Grid.csv', encoding = enc)
nuts2_grid.head()

    nuts2         lau1         x         y
0  veneto  abano terme  11.79324  45.35865
1  veneto        adria  12.05470  45.07423
2  veneto        adria  12.05470  45.05177
3  veneto        adria  12.02294  45.07423
4  veneto        adria  11.99118  45.07423

In [118]:
## start and end date is defined from available epidemiological file

In [119]:
dt = 1 if PERIOD == '1st' else 16
mn = datetime.strptime(MONTH, '%B').month

start = start_dt = date(YEAR, mn, dt)
end = end_dt = date(YEAR, mn, dt)
delta = timedelta(days=1)

In [120]:
dates = []

while start_dt <= end_dt:
    dates.append(start_dt.isoformat())
    start_dt += delta

In [121]:
print('Dates between', start, 'and', end)
print(dates)

Dates between 2023-08-01 and 2023-08-01
['2023-08-01']

In [122]:
len(dates)

1

In [123]:
nuts2_timeline = pd.DataFrame()

In [124]:
data = []
for index, row in nuts2_grid.iterrows():
    for date in dates:
        data.append({'lau1': row['lau1'], 
                     'region': row['nuts2'], 
                     'x': row['x'], 
                     'y': row['y'], 
                     'dt_placement': date})

nuts2_timeline = pd.DataFrame(data)

In [125]:
nuts2_timeline

                lau1  region         x         y dt_placement
0        abano terme  veneto  11.79324  45.35865   2023-08-01
1              adria  veneto  12.05470  45.07423   2023-08-01
2              adria  veneto  12.05470  45.05177   2023-08-01
3              adria  veneto  12.02294  45.07423   2023-08-01
4              adria  veneto  11.99118  45.07423   2023-08-01
..               ...     ...       ...       ...          ...
898            zevio  veneto  11.14969  45.36071   2023-08-01
899          zimella  veneto  11.35805  45.34777   2023-08-01
900  zoppe da cadore  veneto  12.17878  46.38835   2023-08-01
901        zovencedo  veneto  11.49430  45.43798   2023-08-01
902         zugliano  veneto  11.50206  45.73042   2023-08-01

[903 rows x 5 columns]

In [126]:
nuts2_timeline['dt_placement'] = pd.to_datetime(nuts2_timeline['dt_placement'])

In [127]:
nuts2_timeline.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 903 entries, 0 to 902
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   lau1          903 non-null    object
 1   region        903 non-null    object
 2   x             903 non-null    float64
 3   y             903 non-null    float64
 4   dt_placement  903 non-null    datetime64[ns]
dtypes: datetime64[ns](1), float64(2), object(2)
memory usage: 35.4+ KB

In [128]:
nuts2_timeline.to_csv(f'../../data/{NUTS2}/{NUTS0}_{NUTS2}_Timeline_{YEAR}-{MONTH}-{PERIOD}.csv', index = False)