## Creates the **Epidemiological Timeline** for a specific region by using the available data on WNV Cases ##

In [1]:
import pandas as pd

enc = 'utf-8'
dec = 'greek8'

pd.options.display.max_columns = None
pd.options.display.max_rows = 10

In [2]:
NUTS0 = 'GR'
NUTS2 = 'CMacedonia'
NUTS2_EL = 'κεντρικης μακεδονιας'

## 2010 - 2021 ##

In [3]:
data_2021 = pd.read_csv(f'../../data/{NUTS0}_WNV_cases_2010-2021_processed.csv', encoding = enc)
data_2021.head(5)

,onset of symptoms,year,month,day,nuts2,nuts3,lau1,lau2,age,sex
0,2010-07-28,2010,7,28,κεντρικης μακεδονιας,θεσσαλονικης,θεσσαλονικης,"παπαφη, θεσσαλονικη",75,f
1,2010-07-22,2010,7,22,κεντρικης μακεδονιας,ημαθιας,βεροιας,βεροια,78,m
2,2010-07-24,2010,7,24,κεντρικης μακεδονιας,κιλκις,κιλκις,λεβεντοχωρι,70,f
3,2010-07-30,2010,7,30,κεντρικης μακεδονιας,κιλκις,κιλκις,καμπανη,74,m
4,2010-07-06,2010,7,6,κεντρικης μακεδονιας,σερρων,ηρακλειας,ποντισμενο,19,f

In [4]:
df_21 = data_2021[data_2021['nuts2'].isin([NUTS2_EL])].copy()

In [5]:
df_21.reset_index(drop = True, inplace = True)

In [6]:
df_21

,onset of symptoms,year,month,day,nuts2,nuts3,lau1,lau2,age,sex
0,2010-07-28,2010,7,28,κεντρικης μακεδονιας,θεσσαλονικης,θεσσαλονικης,"παπαφη, θεσσαλονικη",75,f
1,2010-07-22,2010,7,22,κεντρικης μακεδονιας,ημαθιας,βεροιας,βεροια,78,m
2,2010-07-24,2010,7,24,κεντρικης μακεδονιας,κιλκις,κιλκις,λεβεντοχωρι,70,f
3,2010-07-30,2010,7,30,κεντρικης μακεδονιας,κιλκις,κιλκις,καμπανη,74,m
4,2010-07-06,2010,7,6,κεντρικης μακεδονιας,σερρων,ηρακλειας,ποντισμενο,19,f
...,...,...,...,...,...,...,...,...,...,...
627,2021-09-17,2021,9,17,κεντρικης μακεδονιας,ημαθιας,αλεξανδρειας,κλειδι,51,f
628,2021-09-13,2021,9,13,κεντρικης μακεδονιας,ημαθιας,ηρωικης πολης ναουσας,αγγελοχωρι,85,m
629,2021-09-03,2021,9,3,κεντρικης μακεδονιας,ημαθιας,αλεξανδρειας,πλατυ,52,f
630,2021-10-04,2021,10,4,κεντρικης μακεδονιας,θεσσαλονικης,θερμαϊκου,περαια,65,m
631,2021-10-25,2021,10,25,κεντρικης μακεδονιας,ημαθιας,αλεξανδρειας,αλεξανδρεια,65,m

In [7]:
wnv_lau1_list_21 = df_21['lau1'].drop_duplicates().sort_values().tolist()

with open(f'../../data/{NUTS2}/{NUTS0}_{NUTS2}_WNV_2010-2021_LAU1_Units_Processed.txt', 'w', encoding=enc) as f:
    for item in wnv_lau1_list_21:
        f.write("%s\n" % item)
  
print(f"Number of LAU1 Units in {NUTS2} (from cases): {len(wnv_lau1_list_21)}")

Number of LAU1 Units in CMacedonia (from cases): 37

In [8]:
df_21['period'] = df_21.apply(lambda row: 1 if (row['day']>=1 and row['day']<=15) else 2, axis = 1)
df_21['dt_placement'] = df_21.apply(lambda row: f"{row['year']:04}-{row['month']:02}-{1 if row['period'] == 1 else 16:02}", axis = 1)

df_21['dt_placement']= pd.to_datetime(df_21['dt_placement'])
df_21['case'] = 1

In [9]:
df_21

,onset of symptoms,year,month,day,nuts2,nuts3,lau1,lau2,age,sex,period,dt_placement,case
0,2010-07-28,2010,7,28,κεντρικης μακεδονιας,θεσσαλονικης,θεσσαλονικης,"παπαφη, θεσσαλονικη",75,f,2,2010-07-16,1
1,2010-07-22,2010,7,22,κεντρικης μακεδονιας,ημαθιας,βεροιας,βεροια,78,m,2,2010-07-16,1
2,2010-07-24,2010,7,24,κεντρικης μακεδονιας,κιλκις,κιλκις,λεβεντοχωρι,70,f,2,2010-07-16,1
3,2010-07-30,2010,7,30,κεντρικης μακεδονιας,κιλκις,κιλκις,καμπανη,74,m,2,2010-07-16,1
4,2010-07-06,2010,7,6,κεντρικης μακεδονιας,σερρων,ηρακλειας,ποντισμενο,19,f,1,2010-07-01,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
627,2021-09-17,2021,9,17,κεντρικης μακεδονιας,ημαθιας,αλεξανδρειας,κλειδι,51,f,2,2021-09-16,1
628,2021-09-13,2021,9,13,κεντρικης μακεδονιας,ημαθιας,ηρωικης πολης ναουσας,αγγελοχωρι,85,m,1,2021-09-01,1
629,2021-09-03,2021,9,3,κεντρικης μακεδονιας,ημαθιας,αλεξανδρειας,πλατυ,52,f,1,2021-09-01,1
630,2021-10-04,2021,10,4,κεντρικης μακεδονιας,θεσσαλονικης,θερμαϊκου,περαια,65,m,1,2021-10-01,1
631,2021-10-25,2021,10,25,κεντρικης μακεδονιας,ημαθιας,αλεξανδρειας,αλεξανδρεια,65,m,2,2021-10-16,1

In [10]:
df_21.drop(columns = ['onset of symptoms', 'day', 'nuts3', 'lau2', 'age', 'sex', 'period'], inplace = True)

In [11]:
df_21 = df_21[['month', 'year', 'lau1', 'nuts2', 'dt_placement', 'case']]

In [12]:
df_21

,month,year,lau1,nuts2,dt_placement,case
0,7,2010,θεσσαλονικης,κεντρικης μακεδονιας,2010-07-16,1
1,7,2010,βεροιας,κεντρικης μακεδονιας,2010-07-16,1
2,7,2010,κιλκις,κεντρικης μακεδονιας,2010-07-16,1
3,7,2010,κιλκις,κεντρικης μακεδονιας,2010-07-16,1
4,7,2010,ηρακλειας,κεντρικης μακεδονιας,2010-07-01,1
...,...,...,...,...,...,...
627,9,2021,αλεξανδρειας,κεντρικης μακεδονιας,2021-09-16,1
628,9,2021,ηρωικης πολης ναουσας,κεντρικης μακεδονιας,2021-09-01,1
629,9,2021,αλεξανδρειας,κεντρικης μακεδονιας,2021-09-01,1
630,10,2021,θερμαϊκου,κεντρικης μακεδονιας,2021-10-01,1
631,10,2021,αλεξανδρειας,κεντρικης μακεδονιας,2021-10-16,1

In [13]:
case_months = df_21['month'].drop_duplicates().sort_values().tolist()
case_months

[6, 7, 8, 9, 10]

In [14]:
case_years = df_21['year'].drop_duplicates().sort_values().tolist()
case_years

[2010, 2011, 2012, 2013, 2018, 2019, 2020, 2021]

In [15]:
with open(f'../../data/{NUTS2}/{NUTS0}_{NUTS2}_WNV_2010-2021_Cases_Dates.txt', 'w', encoding=enc) as f:

    f.write("%s: " % 'months')
    for item in case_months:
        f.write("%s, " % item)

    f.write("\n")

    f.write("%s: " % 'years')
    for item in case_years:
        f.write("%s, " % item)

In [16]:
df_21.reset_index(inplace = True, drop=True)

## 2022 ##

In [17]:
data_2022 = pd.read_csv(f'../../data/{NUTS0}_WNV_cases_2022_processed.csv', encoding = enc)
data_2022.head(5)

,onset of symptoms,year,month,day,nuts2,nuts3,lau1,cases
0,2022-07-12,2022,7,12,κεντρικης μακεδονιας,θεσσαλονικης,αμπελοκηπων μενεμενης,1
1,2022-07-19,2022,7,19,κεντρικης μακεδονιας,θεσσαλονικης,δελτα,2
2,2022-07-19,2022,7,19,κεντρικης μακεδονιας,θεσσαλονικης,χαλκηδονος,1
3,2022-07-16,2022,7,16,κεντρικης μακεδονιας,θεσσαλονικης,δελτα,1
4,2022-07-16,2022,7,16,κεντρικης μακεδονιας,θεσσαλονικης,θερμης,1

In [18]:
data_2022.shape

(177, 8)

In [19]:
df_22 = data_2022[data_2022['nuts2'].isin([NUTS2_EL])].copy()
df_22.reset_index(drop = True, inplace = True)
df_22

,onset of symptoms,year,month,day,nuts2,nuts3,lau1,cases
0,2022-07-12,2022,7,12,κεντρικης μακεδονιας,θεσσαλονικης,αμπελοκηπων μενεμενης,1
1,2022-07-19,2022,7,19,κεντρικης μακεδονιας,θεσσαλονικης,δελτα,2
2,2022-07-19,2022,7,19,κεντρικης μακεδονιας,θεσσαλονικης,χαλκηδονος,1
3,2022-07-16,2022,7,16,κεντρικης μακεδονιας,θεσσαλονικης,δελτα,1
4,2022-07-16,2022,7,16,κεντρικης μακεδονιας,θεσσαλονικης,θερμης,1
...,...,...,...,...,...,...,...,...
143,2022-10-11,2022,10,11,κεντρικης μακεδονιας,πελλας,πελλας,1
144,2022-10-11,2022,10,11,κεντρικης μακεδονιας,ημαθιας,βεροιας,1
145,2022-10-18,2022,10,18,κεντρικης μακεδονιας,θεσσαλονικης,θεσσαλονικης,1
146,2022-10-25,2022,10,25,κεντρικης μακεδονιας,θεσσαλονικης,κορδελιου ευοσμου,1
147,2022-11-22,2022,11,22,κεντρικης μακεδονιας,θεσσαλονικης,καλαμαριας,1

In [20]:
wnv_lau1_list_22 = df_22['lau1'].drop_duplicates().sort_values().tolist()

with open(f'../../data/{NUTS2}/{NUTS0}_{NUTS2}_WNV_2022_LAU1_Units_Processed.txt', 'w', encoding=enc) as f:
    for item in wnv_lau1_list_22:
        f.write("%s\n" % item)
  
print(f"Number of LAU1 Units in {NUTS2} (from cases): {len(wnv_lau1_list_22)}")

Number of LAU1 Units in CMacedonia (from cases): 34

In [21]:
df_22['period'] = df_22.apply(lambda row: 1 if (row['day']>=1 and row['day']<=15) else 2, axis = 1)
df_22['dt_placement'] = df_22.apply(lambda row: f"{row['year']:04}-{row['month']:02}-{1 if row['period'] == 1 else 16:02}", axis = 1)

df_22['dt_placement']= pd.to_datetime(df_22['dt_placement'])
df_22

,onset of symptoms,year,month,day,nuts2,nuts3,lau1,cases,period,dt_placement
0,2022-07-12,2022,7,12,κεντρικης μακεδονιας,θεσσαλονικης,αμπελοκηπων μενεμενης,1,1,2022-07-01
1,2022-07-19,2022,7,19,κεντρικης μακεδονιας,θεσσαλονικης,δελτα,2,2,2022-07-16
2,2022-07-19,2022,7,19,κεντρικης μακεδονιας,θεσσαλονικης,χαλκηδονος,1,2,2022-07-16
3,2022-07-16,2022,7,16,κεντρικης μακεδονιας,θεσσαλονικης,δελτα,1,2,2022-07-16
4,2022-07-16,2022,7,16,κεντρικης μακεδονιας,θεσσαλονικης,θερμης,1,2,2022-07-16
...,...,...,...,...,...,...,...,...,...,...
143,2022-10-11,2022,10,11,κεντρικης μακεδονιας,πελλας,πελλας,1,1,2022-10-01
144,2022-10-11,2022,10,11,κεντρικης μακεδονιας,ημαθιας,βεροιας,1,1,2022-10-01
145,2022-10-18,2022,10,18,κεντρικης μακεδονιας,θεσσαλονικης,θεσσαλονικης,1,2,2022-10-16
146,2022-10-25,2022,10,25,κεντρικης μακεδονιας,θεσσαλονικης,κορδελιου ευοσμου,1,2,2022-10-16
147,2022-11-22,2022,11,22,κεντρικης μακεδονιας,θεσσαλονικης,καλαμαριας,1,2,2022-11-16

In [22]:
df_22.drop(columns = ['onset of symptoms', 'day', 'nuts3', 'period'], inplace = True)
df_22 = df_22[['month', 'year', 'lau1', 'nuts2', 'dt_placement', 'cases']]
df_22

,month,year,lau1,nuts2,dt_placement,cases
0,7,2022,αμπελοκηπων μενεμενης,κεντρικης μακεδονιας,2022-07-01,1
1,7,2022,δελτα,κεντρικης μακεδονιας,2022-07-16,2
2,7,2022,χαλκηδονος,κεντρικης μακεδονιας,2022-07-16,1
3,7,2022,δελτα,κεντρικης μακεδονιας,2022-07-16,1
4,7,2022,θερμης,κεντρικης μακεδονιας,2022-07-16,1
...,...,...,...,...,...,...
143,10,2022,πελλας,κεντρικης μακεδονιας,2022-10-01,1
144,10,2022,βεροιας,κεντρικης μακεδονιας,2022-10-01,1
145,10,2022,θεσσαλονικης,κεντρικης μακεδονιας,2022-10-16,1
146,10,2022,κορδελιου ευοσμου,κεντρικης μακεδονιας,2022-10-16,1
147,11,2022,καλαμαριας,κεντρικης μακεδονιας,2022-11-16,1

In [23]:
df_22.cases.sum()

231

In [24]:
case_months = df_22['month'].drop_duplicates().sort_values().tolist()
case_months

[7, 8, 9, 10, 11]

In [25]:
case_years = df_22['year'].drop_duplicates().sort_values().tolist()
case_years

[2022]

In [26]:
with open(f'../../data/{NUTS2}/{NUTS0}_{NUTS2}_WNV_2022_Cases_Dates.txt', 'w', encoding=enc) as f:

    f.write("%s: " % 'months')
    for item in case_months:
        f.write("%s, " % item)

    f.write("\n")

    f.write("%s: " % 'years')
    for item in case_years:
        f.write("%s, " % item)

In [27]:
df_22.reset_index(inplace = True, drop=True)

In [28]:
## Creating DataFrame to hold negative examples
municipalities = wnv_lau1_list_21 + wnv_lau1_list_22
municipalities_set = set(municipalities)
municipalities_sorted = sorted(municipalities_set)


df_timeline = pd.DataFrame(columns = ['lau1', 'nuts2', 'dt_placement', 'case'])

for municipality in municipalities_sorted:
    for year in range(2010, 2023):
        for month in range (6,12):
            df_timeline = df_timeline.append({'lau1' : municipality, 'nuts2' : NUTS2_EL, 'dt_placement' : f"{year:04}-{month:02}-{1:02}", 'case' : 0}, ignore_index = True)
            df_timeline = df_timeline.append({'lau1' : municipality, 'nuts2' : NUTS2_EL, 'dt_placement' : f"{year:04}-{month:02}-{16:02}", 'case' : 0}, ignore_index = True)
            
df_timeline

              lau1                 nuts2 dt_placement case
0     αλεξανδρειας  κεντρικης μακεδονιας   2010-06-01    0
1     αλεξανδρειας  κεντρικης μακεδονιας   2010-06-16    0
2     αλεξανδρειας  κεντρικης μακεδονιας   2010-07-01    0
3     αλεξανδρειας  κεντρικης μακεδονιας   2010-07-16    0
4     αλεξανδρειας  κεντρικης μακεδονιας   2010-08-01    0
...            ...                   ...          ...  ...
6079  ωραιοκαστρου  κεντρικης μακεδονιας   2022-09-16    0
6080  ωραιοκαστρου  κεντρικης μακεδονιας   2022-10-01    0
6081  ωραιοκαστρου  κεντρικης μακεδονιας   2022-10-16    0
6082  ωραιοκαστρου  κεντρικης μακεδονιας   2022-11-01    0
6083  ωραιοκαστρου  κεντρικης μακεδονιας   2022-11-16    0

[6084 rows x 4 columns]

In [29]:
df_timeline['dt_placement']= pd.to_datetime(df_timeline['dt_placement'])
df_timeline.reset_index(inplace = True, drop=True)

In [31]:
## Add cases to negative examples DataFrame

#iterrate DataFrame with cases by row
for index, row in df_21.iterrows():
    #find index at DataFrame with negative examples where location and date matches the DataFrame with cases
    idx = df_timeline.index[(df_timeline['lau1']==row['lau1']) & (df_timeline['dt_placement']==row['dt_placement'])]
    #get the previous case number using index
    previous_case = df_timeline._get_value(idx.values[0], 'case')
    #add 1 (one) to column case
    df_timeline.at[idx.values[0],'case'] = previous_case+1

In [34]:
df_timeline.case.sum()

632

In [35]:
## Add cases to negative examples DataFrame

#iterrate DataFrame with cases by row
for index, row in df_22.iterrows():
    #find index at DataFrame with negative examples where location and date matches the DataFrame with cases
    idx = df_timeline.index[(df_timeline['lau1']==row['lau1']) & (df_timeline['dt_placement']==row['dt_placement'])]
    #get the previous case number using index
    try:
        previous_case = df_timeline._get_value(idx.values[0], 'case')
    except IndexError:
        print(index)
        print(idx)
    current_case = row['cases']
    #add 1 (one) to column case
    df_timeline.at[idx.values[0],'case'] = previous_case+current_case

In [37]:
df_timeline.case.sum()

863

In [38]:
df_timeline.to_csv(f"../../data/{NUTS2}/{NUTS0}_{NUTS2}_WNV_Cases_2010-2022.csv", encoding = enc, index = False)