## Creates the **Timeline** for a specific region by using the Grid File and the required dates ##

In [1]:
import pandas as pd
from datetime import date, timedelta

import random
import geopandas as gpd
import numpy as np

import sys

sys.path.insert(0, "../../../Modules")

from preprocessing_utils import *

enc = 'utf-8'
dec = 'greek8'
random.seed(0)

c:\Users\dimit\AppData\Local\Programs\Python\Python39\lib\site-packages\geopandas\_compat.py:112: UserWarning: The Shapely GEOS version (3.10.3-CAPI-1.16.1) is incompatible with the GEOS version PyGEOS was compiled with (3.10.4-CAPI-1.16.2). Conversions between both will be slow.
  warnings.warn(

In [2]:
import warnings
warnings.filterwarnings('ignore')

In [3]:
NUTS0 = 'GR'
NUTS2 = 'CMacedonia'
NUTS2_EL = 'κεντρικης μακεδονιας'

In [4]:
MONTH = 'June'
PERIOD = '2nd'

In [5]:
nuts2_grid = pd.read_csv(f'../../data/{NUTS2}/{NUTS0}_{NUTS2}_Grid.csv', encoding = enc)
nuts2_grid.head()

                  nuts2          lau1         x         y
0  κεντρικης μακεδονιας  αλεξανδρειας  22.39544  40.65816
1  κεντρικης μακεδονιας  αλεξανδρειας  22.46627  40.67612
2  κεντρικης μακεδονιας  αλεξανδρειας  22.48988  40.62222
3  κεντρικης μακεδονιας  αλεξανδρειας  22.58432  40.62222
4  κεντρικης μακεδονιας      αλμωπιας  22.06171  40.94926

In [6]:
## start and end date is defined from available epidemiological file

In [7]:
start = start_dt = date(2023, 6, 16)
end = end_dt = date(2023, 6, 16)
delta = timedelta(days=1)

In [8]:
dates = []

while start_dt <= end_dt:
    dates.append(start_dt.isoformat())
    start_dt += delta

In [9]:
print('Dates between', start, 'and', end)
print(dates)

Dates between 2023-06-16 and 2023-06-16
['2023-06-16']

In [10]:
len(dates)

1

In [11]:
nuts2_timeline = pd.DataFrame()

In [12]:
data = []
for index, row in nuts2_grid.iterrows():
    for date in dates:
        data.append({'lau1': row['lau1'], 
                     'region': row['nuts2'], 
                     'x': row['x'], 
                     'y': row['y'], 
                     'dt_placement': date})

nuts2_timeline = pd.DataFrame(data)

In [13]:
nuts2_timeline

             lau1                region         x         y dt_placement
0    αλεξανδρειας  κεντρικης μακεδονιας  22.39544  40.65816   2023-06-16
1    αλεξανδρειας  κεντρικης μακεδονιας  22.46627  40.67612   2023-06-16
2    αλεξανδρειας  κεντρικης μακεδονιας  22.48988  40.62222   2023-06-16
3    αλεξανδρειας  κεντρικης μακεδονιας  22.58432  40.62222   2023-06-16
4        αλμωπιας  κεντρικης μακεδονιας  22.06171  40.94926   2023-06-16
..            ...                   ...       ...       ...          ...
175    χαλκηδονος  κεντρικης μακεδονιας  22.71513  40.75357   2023-06-16
176    χαλκηδονος  κεντρικης μακεδονιας  22.71513  40.77153   2023-06-16
177    χαλκηδονος  κεντρικης μακεδονιας  22.73880  40.73560   2023-06-16
178  ωραιοκαστρου  κεντρικης μακεδονιας  22.94073  40.74476   2023-06-16
179  ωραιοκαστρου  κεντρικης μακεδονιας  22.94073  40.79866   2023-06-16

[180 rows x 5 columns]

In [14]:
nuts2_timeline['dt_placement'] = pd.to_datetime(nuts2_timeline['dt_placement'])

In [15]:
nuts2_timeline.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 180 entries, 0 to 179
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   lau1          180 non-null    object
 1   region        180 non-null    object
 2   x             180 non-null    float64
 3   y             180 non-null    float64
 4   dt_placement  180 non-null    datetime64[ns]
dtypes: datetime64[ns](1), float64(2), object(2)
memory usage: 7.2+ KB

In [16]:
nuts2_timeline.to_csv(f'../../data/{NUTS2}/{NUTS0}_{NUTS2}_Timeline_2023-{MONTH}-{PERIOD}.csv', index = False)

In [16]:
#nuts2_timeline

In [17]:
#nuts2_timeline['dt_placement'].iloc[15].day

In [18]:
# nuts2_timeline_biweekly = nuts2_timeline.copy()
# remove = []

# for index, row in nuts2_timeline.iterrows():
#     if row['dt_placement'].day == 1 or row['dt_placement'].day == 16:
#         pass
#     else:
#         remove.append(index)


# nuts2_timeline_biweekly.drop(index = remove, axis = 1, inplace = True)
# nuts2_timeline_biweekly.reset_index(inplace = True, drop = True)

In [19]:
# nuts2_timeline_biweekly.info()

In [20]:
# nuts2_timeline_biweekly

In [21]:
# nuts2_timeline_biweekly.to_csv(f'../../data/{NUTS2}/{NUTS0}_{NUTS2}_Timeline_Biweekly_2023-June.csv', index = False)