## Creates the **Timeline** for a specific region by using the Grid File and the required dates ##

In [33]:
import pandas as pd
from datetime import date, timedelta

import random
import geopandas as gpd
import numpy as np

import sys

sys.path.insert(0, "../../../Modules")

from preprocessing_utils import *

enc = 'utf-8'
dec = 'greek8'
random.seed(0)

In [34]:
import warnings
warnings.filterwarnings('ignore')

In [35]:
NUTS0 = 'GR'
NUTS2 = 'CMacedonia'
NUTS2_EL = 'κεντρικης μακεδονιας'

In [36]:
nuts2_grid = pd.read_csv(f'../../data/{NUTS2}/{NUTS0}_{NUTS2}_Grid.csv', encoding = enc)
nuts2_grid.head()

                  nuts2          lau1         x         y
0  κεντρικης μακεδονιας  αλεξανδρειας  22.39544  40.65816
1  κεντρικης μακεδονιας  αλεξανδρειας  22.46627  40.67612
2  κεντρικης μακεδονιας  αλεξανδρειας  22.48988  40.62222
3  κεντρικης μακεδονιας  αλεξανδρειας  22.58432  40.62222
4  κεντρικης μακεδονιας      αλμωπιας  22.06171  40.94926

In [37]:
## start and end date is defined from available epidemiological file

In [38]:
start = start_dt = date(2023, 5, 1)
end = end_dt = date(2023, 5, 31)
delta = timedelta(days=1)

In [39]:
dates = []

while start_dt <= end_dt:
    dates.append(start_dt.isoformat())
    start_dt += delta

In [40]:
print('Dates between', start, 'and', end)
print(dates)

Dates between 2023-05-01 and 2023-05-31
['2023-05-01', '2023-05-02', '2023-05-03', '2023-05-04', '2023-05-05', '2023-05-06', '2023-05-07', '2023-05-08', '2023-05-09', '2023-05-10', '2023-05-11', '2023-05-12', '2023-05-13', '2023-05-14', '2023-05-15', '2023-05-16', '2023-05-17', '2023-05-18', '2023-05-19', '2023-05-20', '2023-05-21', '2023-05-22', '2023-05-23', '2023-05-24', '2023-05-25', '2023-05-26', '2023-05-27', '2023-05-28', '2023-05-29', '2023-05-30', '2023-05-31']

In [41]:
len(dates)

31

In [42]:
nuts2_timeline = pd.DataFrame()

In [43]:
for index, row in nuts2_grid.iterrows():
    for date in dates:
        nuts2_timeline = nuts2_timeline.append({'lau1' : row['lau1'], 
                                                  'region' : row['nuts2'], 
                                                  'x' : row['x'],
                                                  'y' : row['y'],
                                                  'dt_placement': date}, 
                                                  ignore_index = True)

In [44]:
nuts2_timeline

              lau1                region         x         y dt_placement
0     αλεξανδρειας  κεντρικης μακεδονιας  22.39544  40.65816   2023-05-01
1     αλεξανδρειας  κεντρικης μακεδονιας  22.39544  40.65816   2023-05-02
2     αλεξανδρειας  κεντρικης μακεδονιας  22.39544  40.65816   2023-05-03
3     αλεξανδρειας  κεντρικης μακεδονιας  22.39544  40.65816   2023-05-04
4     αλεξανδρειας  κεντρικης μακεδονιας  22.39544  40.65816   2023-05-05
...            ...                   ...       ...       ...          ...
5575  ωραιοκαστρου  κεντρικης μακεδονιας  22.94073  40.79866   2023-05-27
5576  ωραιοκαστρου  κεντρικης μακεδονιας  22.94073  40.79866   2023-05-28
5577  ωραιοκαστρου  κεντρικης μακεδονιας  22.94073  40.79866   2023-05-29
5578  ωραιοκαστρου  κεντρικης μακεδονιας  22.94073  40.79866   2023-05-30
5579  ωραιοκαστρου  κεντρικης μακεδονιας  22.94073  40.79866   2023-05-31

[5580 rows x 5 columns]

In [45]:
nuts2_timeline['dt_placement'] = pd.to_datetime(nuts2_timeline['dt_placement'])

In [46]:
nuts2_timeline.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5580 entries, 0 to 5579
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   lau1          5580 non-null   object
 1   region        5580 non-null   object
 2   x             5580 non-null   float64
 3   y             5580 non-null   float64
 4   dt_placement  5580 non-null   datetime64[ns]
dtypes: datetime64[ns](1), float64(2), object(2)
memory usage: 218.1+ KB

In [47]:
nuts2_timeline.to_csv(f'../../data/{NUTS2}/{NUTS0}_{NUTS2}_Timeline_2023-May.csv', index = False)

In [48]:
nuts2_timeline

              lau1                region         x         y dt_placement
0     αλεξανδρειας  κεντρικης μακεδονιας  22.39544  40.65816   2023-05-01
1     αλεξανδρειας  κεντρικης μακεδονιας  22.39544  40.65816   2023-05-02
2     αλεξανδρειας  κεντρικης μακεδονιας  22.39544  40.65816   2023-05-03
3     αλεξανδρειας  κεντρικης μακεδονιας  22.39544  40.65816   2023-05-04
4     αλεξανδρειας  κεντρικης μακεδονιας  22.39544  40.65816   2023-05-05
...            ...                   ...       ...       ...          ...
5575  ωραιοκαστρου  κεντρικης μακεδονιας  22.94073  40.79866   2023-05-27
5576  ωραιοκαστρου  κεντρικης μακεδονιας  22.94073  40.79866   2023-05-28
5577  ωραιοκαστρου  κεντρικης μακεδονιας  22.94073  40.79866   2023-05-29
5578  ωραιοκαστρου  κεντρικης μακεδονιας  22.94073  40.79866   2023-05-30
5579  ωραιοκαστρου  κεντρικης μακεδονιας  22.94073  40.79866   2023-05-31

[5580 rows x 5 columns]

In [50]:
nuts2_timeline['dt_placement'].iloc[15].day

16

In [51]:
nuts2_timeline_biweekly = nuts2_timeline.copy()
remove = []

for index, row in nuts2_timeline.iterrows():
    if row['dt_placement'].day == 1 or row['dt_placement'].day == 16:
        pass
    else:
        remove.append(index)


nuts2_timeline_biweekly.drop(index = remove, axis = 1, inplace = True)
nuts2_timeline_biweekly.reset_index(inplace = True, drop = True)

In [52]:
nuts2_timeline_biweekly.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 360 entries, 0 to 359
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   lau1          360 non-null    object
 1   region        360 non-null    object
 2   x             360 non-null    float64
 3   y             360 non-null    float64
 4   dt_placement  360 non-null    datetime64[ns]
dtypes: datetime64[ns](1), float64(2), object(2)
memory usage: 14.2+ KB

In [53]:
nuts2_timeline_biweekly

             lau1                region         x         y dt_placement
0    αλεξανδρειας  κεντρικης μακεδονιας  22.39544  40.65816   2023-05-01
1    αλεξανδρειας  κεντρικης μακεδονιας  22.39544  40.65816   2023-05-16
2    αλεξανδρειας  κεντρικης μακεδονιας  22.46627  40.67612   2023-05-01
3    αλεξανδρειας  κεντρικης μακεδονιας  22.46627  40.67612   2023-05-16
4    αλεξανδρειας  κεντρικης μακεδονιας  22.48988  40.62222   2023-05-01
..            ...                   ...       ...       ...          ...
355    χαλκηδονος  κεντρικης μακεδονιας  22.73880  40.73560   2023-05-16
356  ωραιοκαστρου  κεντρικης μακεδονιας  22.94073  40.74476   2023-05-01
357  ωραιοκαστρου  κεντρικης μακεδονιας  22.94073  40.74476   2023-05-16
358  ωραιοκαστρου  κεντρικης μακεδονιας  22.94073  40.79866   2023-05-01
359  ωραιοκαστρου  κεντρικης μακεδονιας  22.94073  40.79866   2023-05-16

[360 rows x 5 columns]

In [54]:
nuts2_timeline_biweekly.to_csv(f'../../data/{NUTS2}/{NUTS0}_{NUTS2}_Timeline_Biweekly_2023-May.csv', index = False)