In [31]:
import numpy as np
import pandas as pd
import csv
import random
from sklearn.linear_model import LogisticRegression
import sys
import os

sys.path.insert(0, "../../../Modules")

pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', 10)
random.seed(0)
np.random.seed(0)

from utils import *

enc = 'utf-8'

In [32]:
import warnings
warnings.filterwarnings("ignore")

In [33]:
NUTS0 = 'GR'
NUTS2 = 'CMacedonia'

In [34]:
YEAR = 2023

In [35]:
base_path = f'../../data/{NUTS2}/results/'

In [36]:
file_list = os.listdir(base_path)
file_list.sort()
file_list

['GR_CMacedonia_Results_2010-2022.csv',
 'GR_CMacedonia_Results_2023-July-1st.csv',
 'GR_CMacedonia_Results_2023-July-2nd.csv',
 'GR_CMacedonia_Results_2023-June-1st.csv',
 'GR_CMacedonia_Results_2023-June-2nd.csv',
 'GR_CMacedonia_Results_2023-May-1st.csv',
 'GR_CMacedonia_Results_2023-May-2nd.csv']

In [37]:
result_files = []

for file in file_list:
    data = pd.read_csv(f'{base_path}/{file}', encoding='utf-8')
    data.drop(columns=['x', 'y'], inplace=True)
    data.rename(columns={"probability": "score", "municipality": "lau1"}, inplace=True)
    result_files.append(data)

In [38]:
result_files[0] = result_files[0].loc[(result_files[0]['year'] == 2022)]

In [39]:
result_files[0].drop(columns = ['case'], inplace = True)

In [40]:
result_files[1].drop(columns = ['risk_class'], inplace = True)

In [41]:
result_files[2].drop(columns = ['risk_class'], inplace = True)

In [42]:
result_files[3].drop(columns = ['Class Number - (Relative Risk Level)', 'Class Number - (Risk Level)'], inplace = True)

In [43]:
result_files[4].drop(columns = ['Class Number - (Relative Risk Level)', 'Class Number - (Risk Level)'], inplace = True)

In [44]:
result_files[5].drop(columns = ['Class Number - (Relative Risk Level)', 'Class Number - (Risk Level)'], inplace = True)

In [45]:
result_files[6].drop(columns = ['Class Number - (Relative Risk Level)', 'Class Number - (Risk Level)'], inplace = True)

In [46]:
concated = pd.concat(result_files, ignore_index=True, axis = 0)

In [47]:
concated.month.unique()

array([ 8,  9,  7, 10,  6, 11,  5], dtype=int64)

In [48]:
zero_score = {'lau1': 'αγνωστη', 'day': 0, 'month': 0, 'year': 0, 'score': 0}
one_score = {'lau1': 'αγνωστη', 'day': 0, 'month': 0, 'year': 0, 'score': 1}

In [49]:
concated

                 lau1  day  month  year     score
0             βεροιας    1      8  2022  0.976101
1           κατερινης    1      8  2022  0.973144
2             σκυδρας    1      8  2022  0.973015
3        θεσσαλονικης   16      8  2022  0.972536
4             βεροιας   16      8  2022  0.968615
..                ...  ...    ...   ...       ...
679  πυδνας κολινδρου   16      5  2023  0.001364
680   νεαπολης συκεων   16      5  2023  0.001020
681         πολυγυρου   16      5  2023  0.000984
682        αριστοτελη   16      5  2023  0.000667
683          σιθωνιας   16      5  2023  0.000658

[684 rows x 5 columns]

In [50]:
concated_og = concated.copy()

In [51]:
concated = concated.append(zero_score, ignore_index = True)
concated = concated.append(one_score, ignore_index = True)

In [52]:
concated

             lau1  day  month  year     score
0         βεροιας    1      8  2022  0.976101
1       κατερινης    1      8  2022  0.973144
2         σκυδρας    1      8  2022  0.973015
3    θεσσαλονικης   16      8  2022  0.972536
4         βεροιας   16      8  2022  0.968615
..            ...  ...    ...   ...       ...
681     πολυγυρου   16      5  2023  0.000984
682    αριστοτελη   16      5  2023  0.000667
683      σιθωνιας   16      5  2023  0.000658
684       αγνωστη    0      0     0  0.000000
685       αγνωστη    0      0     0  1.000000

[686 rows x 5 columns]

In [53]:
concated_sorted = concated.sort_values(by='score', ascending=True)

In [54]:
concated_sorted.reset_index(drop = True, inplace = True)

In [55]:
concated_sorted

             lau1  day  month  year     score
0         αγνωστη    0      0     0  0.000000
1        σιθωνιας   16     11  2022  0.000041
2    διου ολυμπου   16     11  2022  0.000059
3        σιθωνιας    1      5  2023  0.000114
4      αριστοτελη    1      5  2023  0.000120
..            ...  ...    ...   ...       ...
681       σκυδρας   16      7  2023  0.981870
682        κιλκις   16      7  2023  0.982481
683  αλεξανδρειας   16      7  2023  0.983765
684        πελλας   16      7  2023  0.988813
685       αγνωστη    0      0     0  1.000000

[686 rows x 5 columns]

In [56]:
a_list = [124.3636364, 111.9272727, 99.49090909, 87.05454545, 74.61818182, 62.18181818, 49.74545455, 37.30909091, 24.87272727, 12.43636364]

In [57]:
import math
indices = []

# Loop through the elements in the float_list and get the floor of each element
for num in a_list:
    floor_value = math.floor(num)
    indices.append(floor_value)

In [68]:
indices

[124, 111, 99, 87, 74, 62, 49, 37, 24, 12]

In [78]:
bins = []
sum = 0
for index in indices:
    sum = sum + index
    bin_lim = concated_sorted.loc[sum, 'score']
    bins.append(bin_lim)

bins.append(1)

In [79]:
bins[0] = 0

In [80]:
bins

[0,
 0.0519532459065283,
 0.1816893663993899,
 0.4462301109659787,
 0.6961146735067791,
 0.828467446658036,
 0.9010964813559036,
 0.9460397591581712,
 0.96861457695728,
 0.9794766839193912,
 1]

In [81]:
concated_og['risk_class'] = pd.cut(concated_og['score'], bins=bins, labels=False, include_lowest=True)

In [82]:
concated_og.risk_class.value_counts().sort_index()

0    235
1     99
2     87
3     74
4     62
5     49
6     37
7     24
8     12
9      5
Name: risk_class, dtype: int64

In [83]:
bins_formatted = [ '%.4f' % elem for elem in bins]
print(bins_formatted)

['0.0000', '0.0520', '0.1817', '0.4462', '0.6961', '0.8285', '0.9011', '0.9460', '0.9686', '0.9795', '1.0000']

In [84]:
scores = concated['score'].tolist()

In [85]:
#bins = bins.tolist()

AttributeError: 'list' object has no attribute 'tolist'

In [86]:
scores_path = f'../../data/{NUTS2}/{NUTS0}_{NUTS2}_Scores_{YEAR}_(10).csv'

with open(scores_path, mode='w', newline='') as file:
    writer = csv.writer(file)
    writer.writerow(scores)

In [87]:
bins_path = f'../../data/{NUTS2}/{NUTS0}_{NUTS2}_Bins_{YEAR}_(10).csv'

with open(bins_path, mode='w', newline='') as file:
    writer = csv.writer(file)
    writer.writerow(bins)