## Creates the **Timeline** for a specific region by using the Grid File and the required dates ##

In [1]:
import pandas as pd
from datetime import date, timedelta

import random
import geopandas as gpd
import numpy as np

import sys

sys.path.insert(0, "../../../Modules")

from preprocessing_utils import *

enc = 'utf-8'
dec = 'greek8'
random.seed(0)

c:\Users\dimit\AppData\Local\Programs\Python\Python39\lib\site-packages\fuzzywuzzy\fuzz.py:11: UserWarning: Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning
  warnings.warn('Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning')

In [2]:
import warnings
warnings.filterwarnings('ignore')

In [3]:
NUTS0 = 'GR'
NUTS2 = 'Thessaly'
NUTS2_EL = 'θεσσαλιας'

In [17]:
MONTH = 'July'
PERIOD = '1st'

In [6]:
nuts2_grid = pd.read_csv(f'../../data/{NUTS2}/{NUTS0}_{NUTS2}_Grid.csv', encoding = enc)
nuts2_grid.head()

       nuts2   lau1         x         y
0  θεσσαλιας  αγιας  22.63715  39.66477
1  θεσσαλιας  αγιας  22.70702  39.75460
2  θεσσαλιας  αγιας  22.73031  39.79054
3  θεσσαλιας  αγιας  22.77688  39.66477
4  θεσσαλιας  αγιας  22.77688  39.70070

In [7]:
## start and end date is defined from available epidemiological file

In [8]:
start = start_dt = date(2023, 7, 1)
end = end_dt = date(2023, 7, 1)
delta = timedelta(days=1)

In [9]:
dates = []

while start_dt <= end_dt:
    dates.append(start_dt.isoformat())
    start_dt += delta

In [10]:
print('Dates between', start, 'and', end)
print(dates)

Dates between 2023-07-01 and 2023-07-01
['2023-07-01']

In [11]:
len(dates)

1

In [12]:
nuts2_timeline = pd.DataFrame()

In [13]:
data = []
for index, row in nuts2_grid.iterrows():
    for date in dates:
        data.append({'lau1': row['lau1'], 
                     'region': row['nuts2'], 
                     'x': row['x'], 
                     'y': row['y'], 
                     'dt_placement': date})

nuts2_timeline = pd.DataFrame(data)

In [14]:
nuts2_timeline

         lau1     region         x         y dt_placement
0       αγιας  θεσσαλιας  22.63715  39.66477   2023-07-01
1       αγιας  θεσσαλιας  22.70702  39.75460   2023-07-01
2       αγιας  θεσσαλιας  22.73031  39.79054   2023-07-01
3       αγιας  θεσσαλιας  22.77688  39.66477   2023-07-01
4       αγιας  θεσσαλιας  22.77688  39.70070   2023-07-01
..        ...        ...       ...       ...          ...
121  φαρσαλων  θεσσαλιας  22.43281  39.24713   2023-07-01
122  φαρσαλων  θεσσαλιας  22.45598  39.30103   2023-07-01
123  φαρσαλων  θεσσαλιας  22.45598  39.35493   2023-07-01
124  φαρσαλων  θεσσαλιας  22.45598  39.39086   2023-07-01
125  φαρσαλων  θεσσαλιας  22.59495  39.30103   2023-07-01

[126 rows x 5 columns]

In [15]:
nuts2_timeline['dt_placement'] = pd.to_datetime(nuts2_timeline['dt_placement'])

In [16]:
nuts2_timeline.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 126 entries, 0 to 125
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   lau1          126 non-null    object
 1   region        126 non-null    object
 2   x             126 non-null    float64
 3   y             126 non-null    float64
 4   dt_placement  126 non-null    datetime64[ns]
dtypes: datetime64[ns](1), float64(2), object(2)
memory usage: 5.0+ KB

In [18]:
nuts2_timeline.to_csv(f'../../data/{NUTS2}/{NUTS0}_{NUTS2}_Timeline_2023-{MONTH}-{PERIOD}.csv', index = False)

In [16]:
#nuts2_timeline

In [17]:
#nuts2_timeline['dt_placement'].iloc[15].day

In [18]:
# nuts2_timeline_biweekly = nuts2_timeline.copy()
# remove = []

# for index, row in nuts2_timeline.iterrows():
#     if row['dt_placement'].day == 1 or row['dt_placement'].day == 16:
#         pass
#     else:
#         remove.append(index)


# nuts2_timeline_biweekly.drop(index = remove, axis = 1, inplace = True)
# nuts2_timeline_biweekly.reset_index(inplace = True, drop = True)

In [19]:
# nuts2_timeline_biweekly.info()

In [20]:
# nuts2_timeline_biweekly

In [21]:
# nuts2_timeline_biweekly.to_csv(f'../../data/{NUTS2}/{NUTS0}_{NUTS2}_Timeline_Biweekly_2023-June.csv', index = False)