## Creates the **Timeline** for a specific region by using the Grid File and the required dates ##

In [1]:
import pandas as pd
from datetime import date, timedelta

import random
import geopandas as gpd
import numpy as np

import sys

sys.path.insert(0, "../../../Modules")

from preprocessing_utils import *

enc = 'utf-8'
dec = 'greek8'
random.seed(0)

In [2]:
import warnings
warnings.filterwarnings('ignore')

In [3]:
NUTS0 = 'GR'
NUTS2 = 'Thessaly'
NUTS2_EL = 'θεσσαλιας'

In [4]:
nuts2_grid = pd.read_csv(f'../../data/{NUTS2}/{NUTS0}_{NUTS2}_Grid.csv', encoding = enc)
nuts2_grid.head()

       nuts2   lau1         x         y
0  θεσσαλιας  αγιας  22.63715  39.66477
1  θεσσαλιας  αγιας  22.70702  39.75460
2  θεσσαλιας  αγιας  22.73031  39.79054
3  θεσσαλιας  αγιας  22.77688  39.66477
4  θεσσαλιας  αγιας  22.77688  39.70070

In [5]:
## start and end date is defined from available epidemiological file

In [6]:
start = start_dt = date(2023, 5, 1)
end = end_dt = date(2023, 5, 31)
delta = timedelta(days=1)

In [7]:
dates = []

while start_dt <= end_dt:
    dates.append(start_dt.isoformat())
    start_dt += delta

In [8]:
print('Dates between', start, 'and', end)
print(dates)

Dates between 2023-05-01 and 2023-05-31
['2023-05-01', '2023-05-02', '2023-05-03', '2023-05-04', '2023-05-05', '2023-05-06', '2023-05-07', '2023-05-08', '2023-05-09', '2023-05-10', '2023-05-11', '2023-05-12', '2023-05-13', '2023-05-14', '2023-05-15', '2023-05-16', '2023-05-17', '2023-05-18', '2023-05-19', '2023-05-20', '2023-05-21', '2023-05-22', '2023-05-23', '2023-05-24', '2023-05-25', '2023-05-26', '2023-05-27', '2023-05-28', '2023-05-29', '2023-05-30', '2023-05-31']

In [9]:
len(dates)

31

In [10]:
nuts2_timeline = pd.DataFrame()

In [11]:
for index, row in nuts2_grid.iterrows():
    for date in dates:
        nuts2_timeline = nuts2_timeline.append({'lau1' : row['lau1'], 
                                                  'region' : row['nuts2'], 
                                                  'x' : row['x'],
                                                  'y' : row['y'],
                                                  'dt_placement': date}, 
                                                  ignore_index = True)

In [12]:
nuts2_timeline

          lau1     region         x         y dt_placement
0        αγιας  θεσσαλιας  22.63715  39.66477   2023-05-01
1        αγιας  θεσσαλιας  22.63715  39.66477   2023-05-02
2        αγιας  θεσσαλιας  22.63715  39.66477   2023-05-03
3        αγιας  θεσσαλιας  22.63715  39.66477   2023-05-04
4        αγιας  θεσσαλιας  22.63715  39.66477   2023-05-05
...        ...        ...       ...       ...          ...
3901  φαρσαλων  θεσσαλιας  22.59495  39.30103   2023-05-27
3902  φαρσαλων  θεσσαλιας  22.59495  39.30103   2023-05-28
3903  φαρσαλων  θεσσαλιας  22.59495  39.30103   2023-05-29
3904  φαρσαλων  θεσσαλιας  22.59495  39.30103   2023-05-30
3905  φαρσαλων  θεσσαλιας  22.59495  39.30103   2023-05-31

[3906 rows x 5 columns]

In [13]:
nuts2_timeline['dt_placement'] = pd.to_datetime(nuts2_timeline['dt_placement'])

In [14]:
nuts2_timeline.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3906 entries, 0 to 3905
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   lau1          3906 non-null   object
 1   region        3906 non-null   object
 2   x             3906 non-null   float64
 3   y             3906 non-null   float64
 4   dt_placement  3906 non-null   datetime64[ns]
dtypes: datetime64[ns](1), float64(2), object(2)
memory usage: 152.7+ KB

In [15]:
nuts2_timeline.to_csv(f'../../data/{NUTS2}/{NUTS0}_{NUTS2}_Timeline_2023-May.csv', index = False)

In [16]:
nuts2_timeline

          lau1     region         x         y dt_placement
0        αγιας  θεσσαλιας  22.63715  39.66477   2023-05-01
1        αγιας  θεσσαλιας  22.63715  39.66477   2023-05-02
2        αγιας  θεσσαλιας  22.63715  39.66477   2023-05-03
3        αγιας  θεσσαλιας  22.63715  39.66477   2023-05-04
4        αγιας  θεσσαλιας  22.63715  39.66477   2023-05-05
...        ...        ...       ...       ...          ...
3901  φαρσαλων  θεσσαλιας  22.59495  39.30103   2023-05-27
3902  φαρσαλων  θεσσαλιας  22.59495  39.30103   2023-05-28
3903  φαρσαλων  θεσσαλιας  22.59495  39.30103   2023-05-29
3904  φαρσαλων  θεσσαλιας  22.59495  39.30103   2023-05-30
3905  φαρσαλων  θεσσαλιας  22.59495  39.30103   2023-05-31

[3906 rows x 5 columns]

In [17]:
nuts2_timeline['dt_placement'].iloc[15].day

16

In [18]:
nuts2_timeline_biweekly = nuts2_timeline.copy()
remove = []

for index, row in nuts2_timeline.iterrows():
    if row['dt_placement'].day == 1 or row['dt_placement'].day == 16:
        pass
    else:
        remove.append(index)


nuts2_timeline_biweekly.drop(index = remove, axis = 1, inplace = True)
nuts2_timeline_biweekly.reset_index(inplace = True, drop = True)

In [19]:
nuts2_timeline_biweekly.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 252 entries, 0 to 251
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   lau1          252 non-null    object
 1   region        252 non-null    object
 2   x             252 non-null    float64
 3   y             252 non-null    float64
 4   dt_placement  252 non-null    datetime64[ns]
dtypes: datetime64[ns](1), float64(2), object(2)
memory usage: 10.0+ KB

In [20]:
nuts2_timeline_biweekly

         lau1     region         x         y dt_placement
0       αγιας  θεσσαλιας  22.63715  39.66477   2023-05-01
1       αγιας  θεσσαλιας  22.63715  39.66477   2023-05-16
2       αγιας  θεσσαλιας  22.70702  39.75460   2023-05-01
3       αγιας  θεσσαλιας  22.70702  39.75460   2023-05-16
4       αγιας  θεσσαλιας  22.73031  39.79054   2023-05-01
..        ...        ...       ...       ...          ...
247  φαρσαλων  θεσσαλιας  22.45598  39.35493   2023-05-16
248  φαρσαλων  θεσσαλιας  22.45598  39.39086   2023-05-01
249  φαρσαλων  θεσσαλιας  22.45598  39.39086   2023-05-16
250  φαρσαλων  θεσσαλιας  22.59495  39.30103   2023-05-01
251  φαρσαλων  θεσσαλιας  22.59495  39.30103   2023-05-16

[252 rows x 5 columns]

In [21]:
nuts2_timeline_biweekly.to_csv(f'../../data/{NUTS2}/{NUTS0}_{NUTS2}_Timeline_Biweekly_2023-May.csv', index = False)